### ISSUE TITLE
Access to UI elements.

### ISSUE THREAD

**Issue by dasoga** [ResearchKit/ResearchKit#1002]
Hi everyone, I want to get access to the UI elements for example:

In this view I want to center the text of the answers.
![simulator screen shot aug 1 2017 10 46 49 am](https://user-images.githubusercontent.com/11412369/28834006-bc4bb802-76a6-11e7-90cb-018298e0826b.png)

I want to move to the next question after selecting one without pressing 'next', but I couldn't.
I tried to follow the stack views, but I didn't find a way to do it.

<img width="1251" alt="screen shot 2017-08-01 at 10 49 31 am" src="https://user-images.githubusercontent.com/11412369/28834249-5ba673ba-76a7-11e7-9704-ba543e97dfeb.png">

Does somebody knows how can I do this?
Thank you in advance...

**Comment by Pariecemckinney-apple** [comment]
@dasoga - If you want to access the ui element presented it would be best to navigate to the file within the framework that presents the view and modify ui elements directly.

**Comment by dasoga** [comment]
Hi @Pariecemckinney-apple, thanks for your answer, I'll have to do that
