### ISSUE TITLE
Property restorationData get-only 

### ISSUE THREAD

**Issue by acegreen** [ResearchKit/ResearchKit#1005]
Hello, I'm trying to restore my data but am running into an issue. I'm already breaking norms by subclassing ORKTaskViewController and instantiating it from a storyboard directly. This all works well and as expected except for when I try to restore data since its a get-only property.

Is there any way to restore data without using the convenience init?

```
    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        self.task = ResearchKit.ResearchKitHelper.sharedInstance.surveyTaskV1
        self.restorationData = [HERE I WOULD LIKE TO ADD MY DATA]
        self.delegate = self
   }
```

**Comment by Pariecemckinney-apple** [comment]
@acegreen Just to make sure, are you referring to data that was saved after a user exits a task early?

**Comment by acegreen** [comment]
@Pariecemckinney-apple no, the restorationData when they completed the survey. With my in-line implementation of ORKTaskViewController, I would like to check if I have a survey saved, retrieve its restorationData and feed it to the VC so it acts as if the survey was already completed (shows the last step with the conclusion/summary)

**Comment by Pariecemckinney-apple** [comment]
@acegreen Have you tried using the other provided init `ORKTaskViewController(task: ORKTask?, restorationData: Data?, delegate: ORKTaskViewControllerDelegate?)`? if I'm understanding correctly, you wish to store the data of a previously completed task locally (restoration data). Then if a user comes back to this task you will load the restoration data and go directly to the end of the task where there will be some sort of summary/analytics? 

If this is correct, you should only have to have to provide a if statement to check if you have restoration data saved and if you do, use the init function shown above. If not, you would just use the standard init function to start a new ORKTaskViewController. I hope this helps and please let me know if I'm not understanding correctly. I'll be looking out for your response!

**Comment by Pariecemckinney-apple** [comment]
https://github.com/ResearchKit/ResearchKit/issues/1017
