### ISSUE TITLE
Multiple rules for an ORKNavigatableOrderedTask

### ISSUE THREAD

**Issue by InfiniteZenith** [ResearchKit/ResearchKit#1006]
I've got a quick question. In the ResearchKit documentation, I've come across the note that "The rule will be used to obtain a new destination step when the participant goes forward from the trigger step. You cannot add two different navigation rules to the same trigger step identifier; only the most recently added rule is kept." If I am understanding this correctly, every step is only allowed one rule. This would preclude the following use-case from happening:

Suppose I have five questions 1, 2, 3, 4, and 5, that question one has three choices A, B and C so that choosing A goes to question 2, choosing B goes to 3 and choosing C goes to 4. Each of 2, 3, 4 then go to question 5 when completed.

Are there any plans to allow for adding multiple rules to ResearchKit in the future to accommodate this multiple branching behaviour, or is there another way of making use of the navigation rules to approximate this functionality? Thanks!

**Comment by swaffoja** [comment]
I think you want to check out `ORKPredicateStepNavigationRule`. One rule may have multiple result predicates and destinations. It would probably look something like this:

    let checkA = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "A" as NSCoding & NSCopying & NSObjectProtocol)     
    let checkB = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "B" as NSCoding & NSCopying & NSObjectProtocol)
    let checkC = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "C" as NSCoding & NSCopying & NSObjectProtocol)     
    let rule = ORKPredicateStepNavigationRule(resultPredicates: [checkA, checkB, checkC], destinationStepIdentifiers: ["questionStep2","questionStep3","questionStep4"], defaultStepIdentifier: nil, validateArrays: false) 
    task.setNavigationRule(rule, forTriggerStepIdentifier:"questionStep1")

You'd need to set a `ORKDirectStepNavigationRule` rule to jump to question 5. http://blog.shazino.com/articles/dev/researchkit-survey-navigation/

-------

I wrote an alternative to `ORKNavigableOrderedTask` that I call [BranchingOrderedTask](https://gist.github.com/swaffoja/11932f6bb563f5ea26d2c77afe822e3e). Your logic would look like:

    let checkA = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "A" as NSCoding & NSCopying & NSObjectProtocol)
    task.setVisibleStep("questionStep2", when: [checkA])

    let checkB = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "B" as NSCoding & NSCopying & NSObjectProtocol)
    task.setVisibleStep("questionStep3", when: [checkB])

    let checkC = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector(taskIdentifier: "myTask", resultIdentifier: "questionStep1"), expectedAnswerValue: "C" as NSCoding & NSCopying & NSObjectProtocol)
    task.setVisibleStep("questionStep4", when: [checkC])

You would not need to jump to question 5. Note that BranchingOrderedTask only allows linear progression whereas ORKNavigableOrderedTask lets you have loops.

**Comment by InfiniteZenith** [comment]
That's perfect, then. Thanks!
