### ISSUE TITLE
Pre-populate and answer on ORKTextAwnser

### ISSUE THREAD

**Issue by joelcorporan** [ResearchKit/ResearchKit#1007]
Can I pre-populate and answer on ORKTextAwnser?

**Comment by ninoguba** [comment]
Simple answer is yes.

**Comment by joelcorporan** [comment]
How? I was looking into that and there is no method that allows you insert a string... Or maybe I'm wrong...

**Comment by ninoguba** [comment]
http://researchkit.org/docs/Classes/ORKTaskViewController.html#//api/name/defaultResultSource

**Comment by joelcorporan** [comment]
I'm really new on ResearchKit. I'm still trying to pre-populate the answer, This is my code:

    case .informationStep:
            let informationTitle = NSLocalizedString("User Information", comment: "")
            let informationFirstName = NSLocalizedString("First Name", comment: "")
            let informationLastName = NSLocalizedString("Last Name", comment: "")
            let informationEmail = NSLocalizedString("Email", comment: "") 
           
            // Create Information Form
            var items = [ORKFormItem]()
            let informationForm = ORKFormStep(identifier: String(describing: Identifier.informationStep), title: informationTitle, text: "Enter your name and last name")
            
            // First Name Entry
            let nameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
            nameAnswerFormat.multipleLines = false
            
            let nameItem = ORKFormItem(identifier: String(describing: Identifier.informationName), text: informationFirstName, answerFormat: nameAnswerFormat)
            nameItem.isOptional = false
            
            items.append(nameItem)
            
            // Last Name Entry
            let lastNameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
            lastNameAnswerFormat.multipleLines = false
            
            let lastNameItem = ORKFormItem(identifier: String(describing: Identifier.informationLastName), text: informationLastName, answerFormat: nameAnswerFormat)
            lastNameItem.isOptional = false
            
            items.append(lastNameItem)
            
            // Email Entry
            let emailAnswerFormat = ORKEmailAnswerFormat()
            
            let emailItem = ORKFormItem(identifier: String(describing: Identifier.informationEmail), text: informationEmail, answerFormat: emailAnswerFormat)
            emailItem.isOptional = false
            
            items.append(emailItem)
            
            informationForm.formItems = items
            informationForm.isOptional = optional

            return informationForm
            
and trying to access the ORKTaskViewController through:
 


func taskViewController(_ taskViewController: ORKTaskViewController, stepViewControllerWillAppear stepViewController: ORKStepViewController) {

       if let identifier = stepViewController.step?.identifier {
            if identifier == String(describing: Identifier.informationStep) {
                taskViewController.defaultResultSource
            }
        }
    } 


But I still don't know what to do...

**Comment by ninoguba** [comment]
I understand.  I've gone through the same head scratching experience before. =)  The API documentation is not very clear on this and is very sparse on examples.  Let me whip up an example for you in a bit...

**Comment by ninoguba** [comment]
Ok hope this helps...

Sample code to declare your step:

```        
        let informationTitle = NSLocalizedString("User Information", comment: "")
        let informationFirstName = NSLocalizedString("First Name", comment: "")
        let informationLastName = NSLocalizedString("Last Name", comment: "")
        let informationEmail = NSLocalizedString("Email", comment: "")
        
        // Create Information Form
        var items = [ORKFormItem]()
        let informationForm = ORKFormStep(identifier: "informationStep", title: informationTitle, text: "Enter your name and last name")
        
        // First Name Entry
        let nameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
        nameAnswerFormat.multipleLines = false
        
        let nameItem = ORKFormItem(identifier: "informationName", text: informationFirstName, answerFormat: nameAnswerFormat)
        nameItem.isOptional = false
        
        items.append(nameItem)
        
        // Last Name Entry
        let lastNameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
        lastNameAnswerFormat.multipleLines = false
        
        let lastNameItem = ORKFormItem(identifier: "informationLastName", text: informationLastName, answerFormat: nameAnswerFormat)
        lastNameItem.isOptional = false
        
        items.append(lastNameItem)
        
        // Email Entry
        let emailAnswerFormat = ORKEmailAnswerFormat()
        
        let emailItem = ORKFormItem(identifier: "informationEmail", text: informationEmail, answerFormat: emailAnswerFormat)
        emailItem.isOptional = false
        
        items.append(emailItem)
        
        informationForm.formItems = items
        informationForm.isOptional = false
```

Code to declare your task and task view controller:

```
let task = ORKOrderedTask(identifier: "informationTask", steps: [informationForm])
let taskViewController = ORKTaskViewController(task: task, taskRun: nil)
taskViewController.defaultResultSource = self
```

Then extend your class to define your defaults:

```
extension Sample : ORKTaskResultSource {
    
    func stepResult(forStepIdentifier stepIdentifier: String) -> ORKStepResult? {
        if (stepIdentifier == "informationStep") {
            var results = [ORKTextQuestionResult]()

            let result1 = ORKTextQuestionResult(identifier: "informationName")
            result1.questionType = ORKQuestionType.text
            result1.textAnswer = "Johnny"
            results += [result1]

            let result2 = ORKTextQuestionResult(identifier: "informationLastName")
            result2.questionType = ORKQuestionType.text
            result2.textAnswer = "Appleseed"
            results += [result2]

            let result3 = ORKTextQuestionResult(identifier: "informationEmail")
            result3.questionType = ORKQuestionType.text
            result3.textAnswer = "jappleseed@apple.com"
            results += [result3]
            
            let stepResult = ORKStepResult(stepIdentifier: "informationStep", results: results)
            return stepResult
        }
    }
    
}
```

**Comment by joelcorporan** [comment]
Dude, thanks! It is working correctly!
