### ISSUE TITLE
Determining results during a task?

### ISSUE THREAD

**Issue by Br35Ba56** [ResearchKit/ResearchKit#1009]
Good day ResearchKit team,
     
I am fairly new to Swift and Objective-C so please forgive me if this is a simple question.  I am trying to build a task that asks the participant for a start date and time, and a stop date and time to get the duration they completed a specific task during the day.  The task is built from two question steps that ask the user for a date and time via ORKDateAnswerStyle.dateAndTime, first being the start date and time and second being the stop date and time.  I would like to have the stop date and time limited to only one hour after the first date and time therefore ensuring the user cannot enter a date that has a negative duration compared to the first date and time or greater than an hour after the start date and time.

My question is, how can I get the result from the first step in the task, to determine the min/max date and time for the second step in the task?
     
Any help with this is greatly appreciated.

**Comment by ninoguba** [comment]
Similar question to #689

**Comment by Br35Ba56** [comment]
Thanks for directing me to that issue.  I was able to come up with a solution extending ORKOrderedTask and overriding stepAfterStep.
