### ISSUE TITLE
Navigating through steps via an external API Call

### ISSUE THREAD

**Issue by raheelsayeed** [ResearchKit/ResearchKit#1011]
I am trying to build a ResearchKit app where the survey questions are defined, however, their values and order isn't. I'm required to make a `URLRequest` as a Question is responded to _during_ the survey with the id and value of the Step. 

Is there possible given the current state of ResearchKit? 
I probably will subclass `ORKTask` and `ORKQuestionStep` and see if this works out.

**Comment by rsanchezsaez** [comment]
Hi, thanks for submitting the issue.

Why do you need to submit the response to a server to get the next step? Couldn't you have all the question and navigation logic contained on the app and use an `ORKNavigableOrderedTask`? Could you provide more details of your use case? I'm sure we'll be able to figure something out.

**Comment by raheelsayeed** [comment]
Hey,

Well, we've got a use case, to have an app deployed as an assessment tool for the patients. 
Heres what I know and not know:

- A complete set of questions. So, I could create the `ORKSteps` before the survey begins. 
- Theres an elaborate processing based on few algorithms and Scores and Standarerrors which determent the next step (question) based on the earliar answers (not just the immediate preceding Result value. 
-  `ORKNavigableOrderedTask` may not be enough in the above case, perhaps until I implement the actual statistical algorithm. 

I was hoping to find a way and make an api call during the survey, which can give me an ID for the step thats already in the `ORKOrderedTask`. Would this make sense? Im pushing to use ResearchKit for this.

**Comment by Pariecemckinney-apple** [comment]
Hello @raheelsayeed ,

Just wanted to check in to see if you were able to come up with a solution or is the issue still unsolved?

**Comment by raheelsayeed** [comment]
Hi @Pariecemckinney-apple ,

I did manage to hack my way through, with certain limitations.

I mainly use `override  func step(after step: ORKStep?, with result: ORKTaskResult) -> ORKStep?` to make the API Call and figure out which `step` to show next with a few `booleans`.
