### ISSUE TITLE
Height response Issue

### ISSUE THREAD

**Issue by arun14999** [ResearchKit/ResearchKit#1012]
**Description**:-

**Steps to replicate**:-
In height QuestionStep, enter your height as 5'2" OR 4'3" in response to a question that uses the standard RK height response type
tap next to go to the next question
tap back to go back to the height question

**Actual result**:-

height has been reduced by 1 inch
If 5'2" was entered - height shown is now 5'1" 
If 4'3" was entered - height shown is now 4'2"

**Expected result**:-
Heights entered should not change unless changed by the user

**Comment by ninoguba** [comment]
The fix to this is a minor change to the ORKInchesToFeetAndInches() function in ORKHelpers_Internal.h

```
ORK_INLINE void ORKInchesToFeetAndInches(double inches, double *outFeet, double *outInches) {
    if (outFeet == NULL || outInches == NULL) {
        return;
    }
    *outFeet = floor(inches / 12);
    *outInches = round(fmod(inches, 12));
}
```
Just need to round the inches @rsanchezsaez

**Comment by ninoguba** [comment]
Submitted PR #1013 to fix this

**Comment by arun14999** [comment]
Thanks a lot.

**Comment by Pariecemckinney-apple** [comment]
@arun14999 Thanks for posting the issue and thanks @ninoguba for the quick fix and PR. Will merge it now! Closing
