### ISSUE TITLE
[ORKKeychainWrapper objectForKey: error: ] does not conform to NS_ASSUME_NONNULL contract

### ISSUE THREAD

**Issue by phyrworks** [ResearchKit/ResearchKit#1014]
The ORKKeychainWrapper @interface is surrounded by `NS_ASSUME_NONNULL_BEGIN`/`NS_ASSUME_NONNULL_END` #pragmas.  This suggests a contract that all objects will be assumed `nonnull`.  This assumption does not hold true for the case of `[ORKKeychainWrapper objectForKey: error: ]`.  Specifically, the implementation shows that `nil` can indeed be returned.  This does not cause a problem when using the code in Objective-C, but can cause a crash condition in Swift.  Swift will translate the method into the following signature:
`ORKKeychainWrapper.object(forKey: String, error: NSErrorPointer) -> NSSecureCoding`. Note, the assumed return type is `nonnull`, and the error condition is not being converted to a `throws` specification.  
This has an additional problem in that if `nil` is returned by the function, a call to cast the returned object can cause an `EXC_BAD_ACCESS` exception when one attempts to optionally convert the returned value.  Since Swift makes the assumption that an object exists, the object does not come back as nil, but rather a junk pointer.  For instance, to call the function in Swift as currently implemented, one must do something like:
```swift
var error: NSError?
// Note, the lack of throws requires checking error
let value = ORKKeychainWrapper.object(forKey: "Some Key", error: &error)
// The following will cause an EXC_BAD_ACCESS exception and crash the program
let data = value as? Data
```

The correct Swift signature for the method should be:
```swift
static func object(forKey: String) throws -> NSSecureCoding
```

To achieve this, the Objective-C declaration should be the following:
```objective-c
+ (nullable id<NSSecureCoding>)objectForKey:(nonnull NSString *)key error: (NSError * __autoreleasing _Nullable * _Nullable)error;
```

It would also be worthwhile if the use of `NS_ASSUME_NONNULL_BEGIN`/`NS_ASSUME_NONNULL_END` be reviewed for this file, and the entire project, to ensure that the contract is being upheld.  It is clearer and less error prone to set nullability specifiers for each method and property directly, rather than using the NS_ASSUME... pragmas.

The 'Error Handling' section of the following link may be of some assistance: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID6

**Comment by kelseydedoshka-apple** [comment]
@phyrworks - great catch, and I agree with your suggestion to take a close look at this for the entirety of the project. As we track this on our side, have you seen other instances of this that has caused issues for you?

**Comment by srinathtm-apple** [comment]
Closing this issue as the fix has been merged into master.
