### ISSUE TITLE
ORKConsentSectionType Study Tasks broken UI in iPhone X Simulator

### ISSUE THREAD

**Issue by Aleic27** [ResearchKit/ResearchKit#1019]
Hi, I run our company mobile app in Xcode 9 using iPhone X simulator and this appeared on the Study Tasks screen:
![researchkit-xcode9-layout_error](https://user-images.githubusercontent.com/20060747/31065220-43b0ef42-a776-11e7-9339-71aba60912f7.png)

The Next button is not tappable anymore as it positioned closer to the Home Indicator.

**Comment by kelseydedoshka-apple** [comment]
@Aleic27 - great catch. Stay tuned for fixes on our side. In the meantime if you update the views to conform to SafeAreaLayoutGuide (bottom for the case you mentioned above) this should help you get around this if it is currently blocking you.

**Comment by hershman** [comment]
I'm very eager for your fix here. I've gotten emails from two MyHeart Counts users about iPhone X problems with the "Getting Started" page and also surveys.

**Comment by hershman** [comment]
Thank you. We were able to pull in these changes and will provide iPhone X support in MyHeart Counts version 2.0.4

**Comment by akshay-yadav-apple** [comment]
@Aleic27 Closing the issue now. Feel free to reopen if the problem persists.

**Comment by mmertsock** [comment]
Another iPhone X layout issue I've encountered is the UIToolbar with the Agree/Disagree buttons in the consent review step (see screen shot below). Are fixes already in progress for this? If not, I can contribute a pull request.

<img width="553" alt="screen shot 2018-02-09 at 1 14 48 pm" src="https://user-images.githubusercontent.com/2637734/36043412-43ddbbac-0d9d-11e8-85aa-2e4489084c4c.png">

**Comment by srinathtm-apple** [comment]
Hey @mmertsock , I don't think we are working on a fix for this right now. 

PRs are always welcome!

**Comment by pmkowal** [comment]
Hi @mmertsock, thanks for sharing the issue. We've already fixed the issue in our project. You can check the following pull request #1080.

**Comment by srinathtm-apple** [comment]
Closing this issue since the fix has been merged into master.
