### ISSUE TITLE
ORKPredicateStepNavigationRule is getting failed in Xcode 8.3.3

### ISSUE THREAD

**Issue by nageshkumarmishra** [ResearchKit/ResearchKit#1020]
ORKPredicateStepNavigationRule working fine in XCode 8.2.1 getting failed in Xcode 8.3.3

Please find the sample code below, let me know if I am doing any mistake.

Thanks in advance.

 let predicateInstance: NSPredicate = ORKResultPredicate.predicateForChoiceQuestionResult(with:  ORKResultSelector(resultIdentifier: choiceQuestionSourceIdentifier), expectedAnswerValue: currentResultItem as NSCoding & NSCopying & NSObjectProtocol)
                                PredSkipToOne =   (ruleDict.value(forKey: "skipTo") as AnyObject) as! String
                                singleChoicePredicateDict.setObject(PredSkipToOne, forKey: "Destination" as NSCopying)
                                singleChoicePredicateDict.setObject(predicateInstance, forKey: "predicateInstance" as NSCopying)
                                singleChoicePredicateRulesArray.add(singleChoicePredicateDict)
                            }
                            var stuff:[(predicate: NSPredicate, destinationString: String)] = [(predicate: NSPredicate, destinationString: String)]()
                            for (index, PredicateDict) in singleChoicePredicateRulesArray.enumerated()
                            {
                                print(index)
                                let PredicateDic:NSMutableDictionary = PredicateDict as! NSMutableDictionary
                                
                                stuff += [(predicate: PredicateDic.value(forKey: "predicateInstance") as! NSPredicate, destinationString: PredicateDic.value(forKey: "Destination") as! String)]
                            }
                            let singleChoicePredicate = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: stuff as! [(resultPredicate: NSPredicate, destinationStepIdentifier: String)])

Out Put:-

Could not cast value of type '(predicate: __ObjC.NSPredicate, destinationString: Swift.String)' (0x103a75f48) to '(resultPredicate: __ObjC.NSPredicate, destinationStepIdentifier: Swift.String)' (0x103a778b8).
2017-10-08 20:44:39.805615+0530 Turbo[5171:1582542] Could not cast value of type '(predicate: __ObjC.NSPredicate, destinationString: Swift.String)' (0x103a75f48) to '(resultPredicate: __ObjC.NSPredicate, destinationStepIdentifier: Swift.String)' (0x103a778b8)

**Comment by kelseydedoshka-apple** [comment]
@nageshkumarmishra - apologies for the delay getting back to you here. Would you mind verifying for me if you are still seeing this issue with Xcode 9?

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
