### ISSUE TITLE
ORKImageCaptureStep camera viewport does not fill the width of the view frame

### ISSUE THREAD

**Issue by obianachebe** [ResearchKit/ResearchKit#1021]
When I create an ORKImageCaptureStep and display the ORKStep, the viewport is very tiny and does not fill the width of the view frame. Currently testing on an iPhone 6s+ running iOS 11.0.2

**What did you do?**

I created an ORKImageCaptureStep, then an ORKOrderedTask, and finally presented a taskViewController with the task as shown below:

```
let imageStep = ORKImageCaptureStep(identifier: "imageCapture")
imageStep.title = "Image Capture"

let task = ORKOrderedTask(identifier: "SurveyTask", steps: [imageStep])
let taskVC = ORKTaskViewController(task: task, taskRun: nil)

present(taskVC, animated: true, completion: nil)
```

**What did you expect to happen?**

I expected for the viewport to take up most of the frame

**What did you see instead?**

The viewport is very small

![img_3501](https://user-images.githubusercontent.com/13955058/31510933-f0a779f2-af3a-11e7-8f29-2905fd94f080.PNG)

Any help is much appreciated!

**Comment by ninoguba** [comment]
You'll want to set your imageStep's templateImage and templateImageInsets to control the size of the camera viewport.  I know the API documentation says setting this is optional but I learned this is necessary to size the viewport to expectations.

**Comment by obianachebe** [comment]
@ninoguba thanks for the reply. I've set the templateImageInsets as so:

`imageStep.templateImageInsets = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)`

This allows the viewport to better fill the frame, but the capture button is no longer visible (see below). Am I missing something?

![img_3503](https://user-images.githubusercontent.com/13955058/31514242-cf648694-af45-11e7-94b3-9dabb135c629.PNG)

**Comment by ninoguba** [comment]
Try setting a templateImage that is transparent and sized to the frame size and aspect ratio you desire.

**Comment by obianachebe** [comment]
@ninoguba I've set a templateImage and set the templateImageInsets as shown:

`imageStep.templateImageInsets = UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10)`

The viewport now takes up the full width of the frame and the capture button shows, which is great! The bad news is that my templateImage is not showing, and it seems that any alteration of those insets will make the viewport tiny again. Also, if I use a templateImage of a different size, I have to "guess" which UIEdgeInsets will allow the viewport to be displayed properly. Seems a bit finicky to me.

**Comment by ninoguba** [comment]
Yes not the most predictable aspect of ResearchKit.  You're welcome to fix it and contribute it back if you can.

**Comment by kelseydedoshka-apple** [comment]
@obianachebe - great catch, as @ninoguba has pointed out something we will work to clear up moving forward. @ninoguba - thanks for the help on this one.

**Comment by kelseydedoshka-apple** [comment]
@obianachebe - just wanted to check back in here and see if the suggestions were able to help unblock you from this and ok to close out? Otherwise please let me know where else you are stuck so we can help identify a solution

**Comment by obianachebe** [comment]
Yes we were able find a solution after following the suggested advice. Thanks for all the help!

**Comment by kelseydedoshka-apple** [comment]
@obianachebe - great, glad to hear this helped unlock you!
