### ISSUE TITLE
Enabling Next button for Radio Questions

### ISSUE THREAD

**Issue by majeedyaseen** [ResearchKit/ResearchKit#1023]
Help Needed,

How can I enable Next Button for Radio type survey Questions (Non-Optional)?  
As currently, a user Just click on option and advance to next questions for Radio type questions.  I want to add the Next button for such questions, so user can't fill the questions randomly by just clicking continuously on options because if surveys are filled quickly then sometimes the device gets hanged and the user can't move further to other questions. 

Thanks

**Comment by kelseydedoshka-apple** [comment]
@majeedyaseen - are you using the BooleanChoice answer format? Do you mind sharing a snippet of the code that creates these questions so I can better understand your issue?

**Comment by majeedyaseen** [comment]
@kelseydedoshka-apple I managed to solve the issue as I override the library for the BooleanChoice question where next question won't come just by clicking on the answer choice rather user has to click NEXT to forward to other questions. I was expecting an earlier response but anyways thanks for the reply back that means a lot :)

**Comment by kelseydedoshka-apple** [comment]
@majeedyaseen - apologies we didn't get a response to you sooner and great to hear you were able to solve your issue. In the future you could also try using just a standard TextChoice answer format and creating your own options for Yes/No which may help you get around this as well.

**Comment by kelseydedoshka-apple** [comment]
@majeedyaseen - closing as you have resolved this issue, but please feel free to reach back out if you run across this again.
