### ISSUE TITLE
HealthKit information not preselected when allowed to read

### ISSUE THREAD

**Issue by tobiasjungnickel** [ResearchKit/ResearchKit#1024]
When presenting a question step for HealthKit information - e. g. gender - that information is not preselected even if access to read information is granted. It is only visible for the user, because the "Next" button is enabled while this isn't obvious.
For me it should be preselected to let the user know that the information is used to send in the survey while he can still skip the question if it's optional.

`let genderStep = ORKQuestionStep(identifier: "kGenderItem", title: "Gender", answer: ORKHealthKit CharacteristicTypeAnswerFormat(characteristicType: HKCharacteristicType.characteristicType(forIdentifier: .biologicalSex)!))`
<img width="545" alt="screen shot 2017-10-30 at 12 32 07" src="https://user-images.githubusercontent.com/2171646/32168838-62e74466-bd6e-11e7-9bab-da8498457351.png">

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel - just so I understand you correctly, are you seeing the gender from HK populate properly in the result object for the corresponding step behind the scenes, it just isn't being reflected properly to the user in view controller?

**Comment by tobiasjungnickel** [comment]
@kelseydedoshka-apple yes, i got the HK result after the step, but it is just not selected

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel - I have started looking into this a bit.  From my side it looks like if you navigate back to a previous step, then forward again, I see the default selection. That along with the result object being populated properly leads me to think we just aren't refreshing the UI at the right time once the answer is fetched. 

I am curious if you are seeing similar behavior on your side? Still investigating further on my side as well.

**Comment by tobiasjungnickel** [comment]
@kelseydedoshka-apple yes, i can confirm that when navigating back and forth the checkmark appears on the correct selection on the device itself, but not in the Simulator.

**Comment by srinathtm-apple** [comment]
Hey @tobiasjungnickel I have a potential fix for this issue, can you please take a look at #1041 to see if it looks good? 

Essentially, we were being overly cautious and creating new cells only if they were previously nil and this was throwing off the case where we were calling reloadData after creating the cell.

**Comment by srinathtm-apple** [comment]
Closing this issue as the fix has been merged to master.
