### ISSUE TITLE
Add custom key value pair in serialized JSON using ORKESerializer class

### ISSUE THREAD

**Issue by nasim-ahmed** [ResearchKit/ResearchKit#1033]
Hello,  
I collected the results from ORKTaskViewController results and serialized the results into JSON.  I want to send it to the server. But before sending,I want to add extra key and value in the dictionary returned from the class. How can I have this custom JSON?

**Comment by kelseydedoshka-apple** [comment]
@nasim-ahmed - are you trying to add additional values the ORKResult object before you serialize the results to JSON or do you want to add values to the dictionary after you have converted to JSON?

**Comment by nasim-ahmed** [comment]
@kelseydedoshka-apple - This is the JSON which I am getting from the server 
![returnedjson](https://user-images.githubusercontent.com/14360799/33108816-5c1bfa76-cf68-11e7-9df5-ac91f74b6e5b.png) for displaying the questions. And this is the generated JSON  using ORKESerializer class
<img width="483" alt="screen shot 2017-11-22 at 9 26 40 am" src="https://user-images.githubusercontent.com/14360799/33108850-8ecb32de-cf68-11e7-97af-aff54a61e7da.png">
Below the end Date, i want to add moduleId, taskId in the generated JSON. How can i solve this?
Thanks

**Comment by kelseydedoshka-apple** [comment]
@nasim-ahmed - are you using JSONObjectForObject method of ORKESerializer? This returns an NSDictionary, so you could then create a mutable copy of that dictionary and add values to that dictionary (like the moduleId and taskId) as needed. Let me know if this works out for you.

**Comment by nasim-ahmed** [comment]
I tried using JSONObjectForObject  method, but I can't work this out. Can you please show an example code or give me a link for the problem?.

**Comment by kelseydedoshka-apple** [comment]
@nasim-ahmed - what issues are you seeing with this? Can you provide the code snippet you tried that wasn't working so I can see if I can help out with that?

For some sample code you could try something like:

NSDictionary *dictionary = [ORKESerializer JSONObjectForObject:task error:nil];
NSMutableDictionary *mutableDictionary = [dictionary mutableCopy];
[mutableDictionary setValue:@"valueToSet" forKey:@"keyToSet"];

Let me know if this helps at all.

**Comment by nasim-ahmed** [comment]
Thank you.. It worked.
