### ISSUE TITLE
Change the UITableView of ORKAnswerFormat to UIViews or UICollectionView like below ?

### ISSUE THREAD

**Issue by kkadapa** [ResearchKit/ResearchKit#1037]
I am trying hard to change the layout of ORKAnswerFormat from regular TabeFormat to Image/UIViews like below. Can someone help me with this ? I also posted the same on stackoverflow. I want to reuse the same View attached below for taking a Survey with different questions and choices.

https://stackoverflow.com/q/47270603/3512137?sem=2

![fgwcwm](https://user-images.githubusercontent.com/6679852/33412115-767bfdd6-d557-11e7-8de7-0ac612aec578.png)

**Comment by ninoguba** [comment]
In my opinion, for this sample use case/question you provided, the builtin ORKTextChoiceAnswerFormat is what I would use instead.

**Comment by kelseydedoshka-apple** [comment]
@kkadapa - Similar to @ninoguba 's suggestion I might look at using other answer formats that may get you closer to what you are looking for. Have you tried using the TextChoiceAnswerFormat and just setting the background colors? Or is the layout you have above crucial here? The ImageChoiceAnswerFormat would allow you to repeatedly use colored square images and you could extend the module to add labels over the images for what you are looking for.

Based on the layout you display, it looks like it best fits a UICollectionView layout, unfortunately that isn't something we currently support. You could consider creating a new module using that approach if none of the others pan out for you. If you do would love to see what you come up with.

**Comment by kkadapa** [comment]
@kelseydedoshka-apple how can i add background color ? Can you help me with the below code 

and also how can i use ImageChoiceAnswerFormat for me i am getting an exception like below 
![img](https://user-images.githubusercontent.com/6679852/33468788-d0edac1c-d62c-11e7-94dc-48acf0a42847.png)

**Comment by kelseydedoshka-apple** [comment]
@kkadapa - for setting that background color - are you looking for that to be modular? In that case you would need to extend the framework which I can go a bit deeper into if this is the case. Otherwise if the colors are always static you could just go into the framework code itself and set background colors on the table cells.

For the image choice answer format take a look at the ORKImageChoiceAnswerFormat example code in the ORKTest app in TaskFactory+TaskReview.m. Let me know if this helps you unblock you.

**Comment by kkadapa** [comment]
@kelseydedoshka-apple My colors are static and UILabel is dynamic. Thanks for the ORKTest app suggestion : Moreover, can i add another button below the **Next** button (basically a tip) and redirect to a different ViewController while the Survey is still in the progress and then revert back and continue the survey  ?

Here it is perfect with three color squares (I'll add a UILabel programmatically)
![yellow](<img src="https://user-images.githubusercontent.com/6679852/33522527-f5f015e0-d7bc-11e7-8b2c-40e97dcda359.png" width="50%" height="50%" />)

Can i make two more color squares below the three ? I tried doing and it just adjusts in the same row as below...
![blue](<img src="https://user-images.githubusercontent.com/6679852/33522528-fad75596-d7bc-11e7-9ec9-b5ee3570fe23.png" width="50%" height="50%" />)

**Comment by kelseydedoshka-apple** [comment]
@kkadapa - just for my understanding what is your concern with the blue being added to the same row? Does that make the squares too small? If that is the case you could set the vertical flag to YES and have the squares layout vertically instead of horizontally.

**Comment by kkadapa** [comment]
@kelseydedoshka-apple That helps but i want three in 1st row and the other two in the second row. Not sure if that's doable.  On the other hand can i add a button below the colors before Next button ? I want to redirect to a different ViewController and bring back to the Survey after the user reviews a tip...

**Comment by kelseydedoshka-apple** [comment]
@kkadapa - Unfortunately for the functionality you are looking for in the second row you would have to build that out yourself. Either by adding a second row of images in the view or using something like a collection view in a new view controller to get this layout.

Adding an additional button would also require customization. You could add a basic property to the steps for button name and/or action on click which will fire a call back when selected and you could perform the necessary action from there.

**Comment by kkadapa** [comment]
Thank you very much @kelseydedoshka-apple Makes sense thanks. you may close this issue.
