### ISSUE TITLE
Researchkit: Skip/Branching in daily survey questions, not supporting for imageChoice questions

### ISSUE THREAD

**Issue by hemanthkorada** [ResearchKit/ResearchKit#1042]
Hi , I am able to navigate/Skip  to the specific question for (Boolean and Single choice question). I want to navigate to specific question based on the Image choice predicate defined. How can achieve this??

**Comment by Pariecemckinney-apple** [comment]
Hello @hemanthkorada, 

When working with image choice questions the answer format is still a "choiceAnswerFormat" which means you don't need a defined image choice predicate. If you're familiar at all with using predicates the code below should look familiar. 

`

       let navigableTask = ORKNavigableOrderedTask(identifier: "navigable_task", steps: steps)
        let predicateRoundShape: NSPredicate = ORKResultPredicate.predicateForChoiceQuestionResult(with: ORKResultSelector.init(resultIdentifier: "ImageChoiceQuestion"), matchingPattern: "Round Shape")
    
        let predicateNotRoundShape: NSPredicate = NSCompoundPredicate.init(notPredicateWithSubpredicate: predicateRoundShape)
        let predicateRule: ORKPredicateStepNavigationRule = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateNotRoundShape, "IdentifierOfStepToNavigateTo")])
      
        navigableTask.setNavigationRule(predicateRule, forTriggerStepIdentifier: "ImageChoiceQuestion")
        
        let taskViewController = ORKTaskViewController(task: navigableTask, taskRun: nil)
        taskViewController.delegate = self
        present(taskViewController, animated: true, completion: nil)

`

In the code above we're assuming that we have two image choices (Round Shape vs Square Shape). If we select "Round Shape" you will navigate to the very next step after the imageChoice step, so the identifier isn't needed anywhere in the code shown above. However, if we select anything other than "Round Shape" (there is only Square Shape in this case) we will skip the next question and navigate to whichever step you like based on the identifier you pass to the "predicateRule" variable.

Hope this helps and please feel free to reach out if you need anything else or still have questions!

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
