### ISSUE TITLE
swift documentation

### ISSUE THREAD

**Issue by titopalito** [ResearchKit/ResearchKit#1045]
Hey there.
Here is a link with some swift documentation, i noticed that your documentation lacks of it.
[Chinese documentation.](
http://chinaresearchkit.github.io/docs/docs/Survey/CreatingSurveys.html)

This is the same link but through google translate:
[Translated documentation.](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=es&ie=UTF-8&u=http%3A%2F%2Fchinaresearchkit.github.io%2Fdocs%2Fdocs%2FSurvey%2FCreatingSurveys.html&edit-text=)

Best regards.

**Comment by srinathtm-apple** [comment]
@titopalito - thank you for pointing us to this amazing resource! 

We will add this link to the README section.

**Comment by titopalito** [comment]
Thanks for being nice xD
I wanted to contribute with something 🙃

**Comment by srinathtm-apple** [comment]
This link has been added under a separate page in the ResearchKit wiki tab.

https://github.com/ResearchKit/ResearchKit/wiki/Chinese-documentation-for-ResearchKit

**Comment by titopalito** [comment]
Thank you so much @srinathtm-apple
