### ISSUE TITLE
Can we Put links in ORKQuestionStep title ?

### ISSUE THREAD

**Issue by majeedyaseen** [ResearchKit/ResearchKit#1047]
I want to include a link inside the question title of ORKQuestionStep, which on clicking opens a respective web-view and show the contents accordingly. If possible please let me know how to achieve that?

Thank you

**Comment by kelseydedoshka-apple** [comment]
@majeedyaseen - currently the framework does not support links in the ORKQuestionStep title. You could extend the framework if you like, to take in an attributed string or button instead which when clicked can open a web view like you mentioned. Is it required that the link be in the title or could it appear anywhere in the step to select?

**Comment by majeedyaseen** [comment]
@kelseydedoshka-apple Thankyou but if I add a button for ORKQuestionStep like you suggested, will that come with all the questions ?. As I have the link to very questions.

**Comment by kelseydedoshka-apple** [comment]
@majeedyaseen - depends on if that is the functionality you are looking for. You could add a boolean property to the step and if it is set to true then display the button, otherwise hide it for those steps that you don't want it displayed.
