### ISSUE TITLE
htmlReviewContent for consent form does not show images

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1049]
I am trying to add a custom consent form using htmlReviewContent.

The consent form will load, however, the images are not showing up when the consent form is displaying. Images show up as a question mark placeholder. 
Both the html file and the image contents were copied to the project in a folder called "consent". The images are .png format and are placed in a subfolder in the "consent" folder. 

Any idea why this is the case? 

This is how the png file is refered in html.
```
<p class=MsoNormal align=center style='text-align:center;background:white'><img
width=152 height=38 src="ParticipantConsentForm.fld/image001.png" align=left
hspace=9 alt=UA-1C-SOLID-LH-LG.png><b><span lang=EN-CA style='color:black'>PARTICIPANT
CONSENT FORM</span></b></p>
```

This is how the html file was loaded to the htmlReviewContent
```
        if let filepath = Bundle.main.path(forResource: "ParticipantConsentForm", ofType: "html",inDirectory:"consent") {
            do {
                let contents = try String(contentsOfFile: filepath)
                //print(contents)
                consentDocument.htmlReviewContent = contents
            } catch {
                print(" contents could not be loaded")
            }
        } else {
            print(" file not found!")
        }
```

**Comment by windenchanter** [comment]
I think it is probably related to the xcode setup, probably not related to the researchkit per se. I haven't solved this issue yet. 

> Demo [7856:693004] TIC TCP Conn Failed [1:0x60000016dd40]: 12:8 Err(-65554)
> 2017-12-28 19:53:24.830228-0700 Demo[7856:693001] Task <105048A3-2FED-40A5-9AA3-5FA3EBD7F965>.<0> HTTP load failed (error code: -1003 [12:8])
> 2017-12-28 19:53:24.830426-0700 tDemo[7856:693001] NSURLConnection finished with error - code -1003

**Comment by windenchanter** [comment]
I have solved this:
The template app used ORKHelpers.m. In ORKHelpers.m a placeholder baseURL were assigned to http://researchkit. plus a  UUID. 
This is used to set the baseURL when making the pdf file and showing the html conent form. This need to be changed depending on where the image files are located. I have to change this path and it now works. 

I wonder what is the purpose of having this function to generate random base URL? 

```
NSURL *ORKCreateRandomBaseURL() {
    
    //return [NSURL URLWithString:[NSString stringWithFormat:@"http://researchkit.%@/", [NSUUID UUID].UUIDString]];
    //
    return [NSURL URLWithString:@""];

}
```

**Comment by kelseydedoshka-apple** [comment]
@windenchanter - glad you were able to get this resolved. Just so I can understand the problem better - were you adding your images assets to ResearchKit directly or in your project asset folder?

**Comment by windenchanter** [comment]
@kelseydedoshka-apple  The html file and images are in the project's folder. Not added to the ResearchKit.

**Comment by kelseydedoshka-apple** [comment]
@windenchanter - you shouldn't need to change the baseURL string, but need to make sure you are referencing your images properly. Here is an example of referencing the image path and using it in the html.

NSString *imagePath = [[NSBundle mainBundle] pathForResource:@"coffee" ofType:@"jpg"];
    [html appendString:[NSString stringWithFormat:@"<p><img src=\"file://%@\" /><p>", imagePath]];

Let me know if this works for you, or if you are happy with your solution go ahead and close this out?

**Comment by windenchanter** [comment]
@kelseydedoshka-apple 
Thank you for providing the code. I was using swift 4 and did a similar string replacement for the image file location inside the html file, so the absolute path was there. I think that worked (but I think it only worked after I changed the base URL, so not sure if changing baseURL is necessary). I will close this issue and if others have a problem later they can open new issues.

**Comment by kelseydedoshka-apple** [comment]
@windenchanter - great, don't hesitate to reach back out if you continue to have issues here.
