### ISSUE TITLE
App freeze when attempting to access taskViewController.restorationData

### ISSUE THREAD

**Issue by swaffoja** [ResearchKit/ResearchKit#1050]
Steps to reproduce:

1. Clone ResearchKit master branch
2. Edit samples\ORKCatalog\ORKCatalog\Tasks\TaskListViewController.swift
```
func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {

        // Attempting to access restorationData results in freeze on physical device
        if let data = taskViewController.restorationData {
            print(data)
        }
        
        taskResultFinishedCompletionHandler?(taskViewController.result)

        taskViewController.dismiss(animated: true, completion: nil)
    }
```
3. Use Xcode 9.2 (9C40b). Run ORKCatalog on physical device. Model: MN8L2LL/A. iOS version: 11.2.1 (15C153). Reproduced on 2nd physical device: Model: ME307LL/A. Version 11.2.1 (15C153)
4. Complete the Simple Survey Example. Press the "Done" button on the "Thanks, Thank you for participating in this sample survey" completion step.
5. The app will freeze (not crash) when it attempts to access the `restorationData` property. If the app does not freeze for you, complete the Simple Survey Example a 2nd time and it should.
6. Pause the debugger to see the thread state. `ORKBookmarkDataFromURL` results in `lib system_kernel.dylib semaphore_wait_trap`
7. Retry using Simulator. Note that app does not freeze, but instead throws error `Could not create a bookmark: Error Doamin=NSCocoaErrorDomain Code=4097...`

Note that the freeze occurs on ResearchKit 1.2.1 as well. 

Might be related to #1038, #1048

<img width="1709" alt="screen shot 2017-12-29 at 8 42 20 am" src="https://user-images.githubusercontent.com/887384/34440001-cf9f9184-ec77-11e7-8de9-8bf9429a6f2b.png">
<img width="1704" alt="screen shot 2017-12-29 at 8 43 56 am" src="https://user-images.githubusercontent.com/887384/34440047-1d5fadfa-ec78-11e7-925a-379fc4728057.png">

**Comment by cmetts** [comment]
I can confirm this bug. This appears to be related 11.2 iOS release, not ResearchKit per se. It is still there with 11.2.2 released today. Everything was working great until I installed 11.2.1 earlier today.

**Comment by cmetts** [comment]
Anyone who updates their iOS will break the study app I have produced.

**Comment by cmetts** [comment]
If I reboot my iPad, the app will work once, not breaking when accessing restorationData. It breaks the very next time.

**Comment by swaffoja** [comment]
Agreed, it does appear to be 11.2+ specific. A device running 11.0.3 (15A432) had no problems. I upgraded to 11.2.2 (15C202) and the freeze occurs. I pressed the home button, reopened ORKCatalog, and a crash occurred. See: [crash log.txt](https://github.com/ResearchKit/ResearchKit/files/1615781/crash.log.txt)

I'm unsure what to do at this point aside from disable the save/restore task feature in my app.

**Comment by cmetts** [comment]
This one is getting even stranger for me. My prior report was on iPad. I finally updated my iPhone today to 11.2.2, and all my apps work correctly. Same code on iPad with 11.2.2, crashes same place.

swaffoja, have you only been testing on simulator?

**Comment by swaffoja** [comment]
@cmetts The tricky thing is that it issue isn't 100% consistent. As you noted "the app will work once [but] it breaks the very next time."

I've been testing on physical iPhone, iPad, and simulators.

**Comment by cmetts** [comment]
Yes it seems this would really be causing problems for people. I can't imagine many people not supporting that feature.

**Comment by swaffoja** [comment]
Just an update on my current knowledge of the issue:

`semaphore_wait_trap` is a low-level locking function. A thread that is blocked in semaphore_wait_trap is waiting for something to become available. `restorationData` is being called on the main thread, is waiting to create a bookmark via `createBookmarkWithURLAtDepth`, never gets access, and thus freezes the UI. Here is a nice site that covers semaphores: https://medium.com/swiftly-swift/a-quick-look-at-semaphores-6b7b85233ddb

**Comment by swaffoja** [comment]
@cmetts Could you try these steps:

1. Download [my ResearchKit fork](https://github.com/swaffoja/ResearchKit). The only file I altered is shown is shown [in this commit](https://github.com/swaffoja/ResearchKit/commit/55dbd425c3a20e1b1a59e3121727c7a64c2e1d7c).
2. Reboot your iOS device running version 11.2+. You need to do this to ensure you are in a clean state.
3. Open `RKWorkspace.xcworkspace` in Xcode
4. Set your target to `ORKCatalog` > `[YOURPHYSICALDEVICE]`
5. Build and run the project
6. Complete the Simple Survey Example
7. Verify that you see `Got restoration data` in the Xcode debugging console

Next:

1. Edit `ORKCatalog > Presenting Tasks > TaskListViewController.swift` in Xcode
2. Comment out line 110. `outputDirectory.appendPathComponent("example_app_subdirectory", isDirectory: true)`
3. Build and run the project
4. Complete the Simple Survey Example
5. Verify that the app freezes

Theory:

`ORKTaskViewController` has a property called `outputDirectory` that specifies where [generated files](https://github.com/ResearchKit/ResearchKit/blob/e4918e28bd484f5110f01dc1d1b4babe0f098477/ResearchKit/Common/ORKTaskViewController.h#L413) should be stored. ResearchKit examples simply specify the [main Documents directory](https://github.com/ResearchKit/ResearchKit/blob/5a05aed6eee6a27158054d587bfc17b5f08775e7/samples/ORKCatalog/ORKCatalog/Tasks/TaskListViewController.swift#L109). ResearchKit uses the `outputDirectory` to [create bookmarks](https://github.com/ResearchKit/ResearchKit/blob/4f3d0f33df3ca96764ccac72a2dda729a567ac33/ResearchKit/Common/ORKHelpers.m#L439). Prior to iOS 11.2+ it was perfectly fine to create a bookmark of the root Documents directory. Starting in iOS 11.2 this started generating an error and causing a deadlock.

**Comment by swaffoja** [comment]
I worked with Apple DTS on this issue. Don't set ORKTaskViewController.outputDirectory to the main documents directory and you should be fine. DTS engineer asked me to file a bug report: https://bugreport.apple.com/web/?problemID=36831113

Summary:
The ORKTaskViewController.outputDirectory attribute is used to store task-generated documents, such as audio files. Only some of the active tasks use the outputDirectory. If your ResearchKit app uses active tasks and your outputDirectory is set to the main documents directory then your app would freeze. All other cases your app would be fine.

**Comment by swaffoja** [comment]
Closing as this is a Framework bug, not a ResearchKit bug.

**Comment by swaffoja** [comment]
This bug was fixed in iOS 12 beta 3
