### ISSUE TITLE
ORKTextScaleAnswerFormat.textAnswerFormat() Custom numerical label

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1051]
Hi, I am having trouble to find a way of setting minimum value. The scale is currently starting from 1, I'd like to have it start from 0. I know you can set this from the ORKTextScaleAnswerFormat, but I also want to keep the text component. Where should I look to make this work? 

<img width="358" alt="example" src="https://user-images.githubusercontent.com/22673319/34698703-ba237c2c-f496-11e7-91da-a5d9469b7148.png">

**Comment by windenchanter** [comment]
I think I found where it was implemented. It was hardcoded to be 1.
```
- (NSNumber *)minimumNumber {
    return @(1);
}
- (NSNumber *)maximumNumber {
    return @(_textChoices.count);
}
```
I am new to programming and don't really understand objective C. Is there a way of modifying this function to achieve what I needed? I can, of course, duplicate the code here and make one answer format class specifically start with a minimum of 0 and maximum of _textChoices.count -1. But I suspect there might be a better way?

**Comment by windenchanter** [comment]
I find changing the minimum and maximum number will make the label appear correctly. But If I click on the first tick of the slider it will crash. 

The error is located in ORKScaleSlider.m
```

- (NSString *)accessibilityValue {
    // If thumb is hidden it means that the slider hasn't been touched yet. That is, there's currently
    // no value (nor a default value), hence we shouldn't return one to VO.
    if (!self.showThumb) {
        return nil;
    } else if (self.textChoices) {
        ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value -1]; 
        return textChoice.text;
    }
    return [self _axFormattedValue:self.value];
}
```


If I change ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value -1] to
ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value]

The slider will run with the scales showing correctly, but the values are all shifted. If I select the first tick, it will show no text. If I select the second tick it will show "Not at all", which should be the text associated with tick 1. They all got shifted. 

Also, I found that changing those parameters in ORKScaleSliderView.m does not change the label.
All I need is to change the numerical label from 0 to 1 and 11 to 10. 

```
_leftRangeDescriptionLabel.textColor
_rightRangeDescriptionLabel.textColor 
_leftRangeLabel.text 
_rightRangeLabel.text 
```

**Comment by Pariecemckinney-apple** [comment]
Hello @windenchanter, 

Just for clarity, are you saying that if I change my minimum value to -3 and click that tick (first tick) the app will crash? If so, which version of ResearchKit and Xcode are you using? Also, is this using the simulator or an actual device? Looking forward to your response.

**Comment by windenchanter** [comment]
@Pariecemckinney-apple 
Hi, 
The minimum and maximum number on the slider is not available to change directly from ORKTextScaleAnswerFormat.textScale(). I am looking for a way to set the minimum to 0 instead of 1.

If I change the hardcoded 1 to 0 only, and then click on the first tick, it will crash.
If I change the hardcoded 1 to 0 and also ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value -1] to ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value], the crashing will not happen, but the text and index relationship seems to be shifted. 

I downloaded the research kit 2 months ago. I am not sure how to check the version number. But it is somewhat recent. 
I was using a simulator.

**Comment by Pariecemckinney-apple** [comment]
Hey @windenchanter, I think I understand the problem now. They're four steps to remove the index offset causing your problem. 

1. Change the hardcoded 1 to 0 which is inside the minimumNumber function you mentioned earlier in this thread 
2.  Inside of the "maximumNumber" function which is directly below the minimumNumber function change the return line to "return @(_textChoices.count - 1)"
3. Then inside of the "accessibilityValue" function you mentioned earlier change the textChoice variable to "ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value];"
4. Then inside of the currentTextChoiceIndex function which is inside of the "ORKSliderView.m" file change the return line to "return _currentNumberValue.unsignedIntegerValue" 

This should fix your problem. Unfortunately, the framework doesn't have built in functionality to support this. The current structure was put into place because its far more common for users to see a scale starting from 1 rather than 0 when the index is mapped to a text result. Hope this helps and please let me know if you need anything else!

**Comment by windenchanter** [comment]
@Pariecemckinney-apple 
Thank you! This did fix the problem for the particular text slider that I wanted to display ticks starting at 0. However, this also changes the behaviour of all text sliders, where sometimes I want them to start at 1. I am still looking into this. I may have to use the value picker answer format as an alternative.

**Comment by Pariecemckinney-apple** [comment]
No problem! Yes, unfortunately you will have to pick one way of the other at the moment unless you go in the framework and add the customization. If you ever decide to add the functionality at any point please let us know how it goes. I am sure somebody else in the community will benefit from it one day!

**Comment by windenchanter** [comment]
@Pariecemckinney-apple 
I have solved my issue. 
First I have copied contents of ORKTextScaleAnswerFormat, and made a new class ORKTextScaleAnswerFormat2.
The only difference between the original and the new one is that the default minimum number is set to 0, maximum is set to maximum -1. I have searched for ORKTextScaleAnswerFormat declarations across different files and whenever there's a reference, I made a duplicate and call it ORKTextScaleAnswerFormat2.

```
+ (ORKTextScaleAnswerFormat *)textScaleAnswerFormatWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                      defaultIndex:(NSInteger)defaultIndex
                                                          vertical:(BOOL)vertical {
    return [[ORKTextScaleAnswerFormat alloc] initWithTextChoices:textChoices
                                                    defaultIndex:defaultIndex
                                                        vertical:vertical];
}

//I don't really understand what is going on here. I don't know objective C and the compiler gave an error about duplicate declaration if I don't change textScaleAnswerFormatWithTextChoices to textScaleAnswerFormat2WithTextChoices

+ (ORKTextScaleAnswerFormat2 *)textScaleAnswerFormat2WithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                      defaultIndex:(NSInteger)defaultIndex
                                                          vertical:(BOOL)vertical {
    return [[ORKTextScaleAnswerFormat2 alloc] initWithTextChoices:textChoices
                                                    defaultIndex:defaultIndex
                                                        vertical:vertical];
}
```

I also had to edit ORKChoiceNumberFormatHelper.m to add
```
        } else if ([answerFormat isKindOfClass:[ORKTextScaleAnswerFormat2 class]]) {
            ORKTextScaleAnswerFormat2 *textScaleAnswerFormat2 = (ORKTextScaleAnswerFormat2 *)answerFormat;
            _choices = textScaleAnswerFormat2.textChoices;
```

At this point, I was able to call the two different answering format separately. 

> Then inside of the "accessibilityValue" function you mentioned earlier change the textChoice variable to "ORKTextChoice *textChoice = self.textChoices[(NSInteger)self.value];"
> Then inside of the currentTextChoiceIndex function which is inside of the "ORKSliderView.m" file change the return line to "return _currentNumberValue.unsignedIntegerValue"
> 

Both classes somehow call the same functions. 
Because the required number of ticks differ between the task I needed to start the scale at 0 and the task I needed to start the scale at 1, I inserted an if statement to check how many number of items are needed in the slider. I simply looked for a property that contains the text items and used .count. 

I think one way to implement this is to create a new answerformat class, but instead of my hack of using if statement based on the number of items contained in the text array it should be based on something else. e.g. an offset value provided to the function. 

Or use the current answer format but allow a function input to change the min-max offsets to shift value labels. Then if the offset differs from 0, we adjust the "accessibilityValue" function and currentTextChoiceIndex function accordingly. 

I can't help much on implementation this properly. If someone knows objectiveC it would probably be easy to implement.

**Comment by ninoguba** [comment]
@windenchanter I suggest adding another initializer to specify your desired min/max slider values would be more appropriate, rather than simply duplicating the function or the class.  Something like this:

```
+ (ORKTextScaleAnswerFormat *)textScaleAnswerFormatWithTextChoices:(NSArray <ORKTextChoice *> *)textChoices
                                                 minimumIndexValue:(nullable NSNumber *)minimumIndexValue
                                                 maximumIndexValue:(nullable NSNumber *)maximumIndexValue
                                                      defaultIndex:(NSInteger)defaultIndex;

```

Then in your implementation class, you'll do something like this:


```
- (NSNumber *)minimumNumber {
    if (_minimumIndexValue == nil) {
        return @(1);
    } else {
        return _minimumIndexValue;
    }
}
- (NSNumber *)maximumNumber {
    if (_maximumIndexValue == nil) {
        return @(_textChoices.count);
    } else {
       return _maximumIndexValue;
    }
}
```

You'll still need to modify the other affected functions.  Hope this helps a bit...

**Comment by windenchanter** [comment]
@ninoguba Thank you! This is very helpful!
I will give this a try.

**Comment by windenchanter** [comment]
@ninoguba 
In ORKScaleSliderView.m I have to specify:
```
- (NSUInteger)currentTextChoiceIndex {
        return _currentNumberValue.unsignedIntegerValue;
}
```
Instead of return _currentNumberValue.unsignedIntegerValue - 1. 

The issue is that sometimes I need it to be -1, and sometimes not. I wonder how can I make this function aware whether the minimum number to display is 0 or 1. 

I can access _slider.textChoices here, but I cannot retrieve the text value of _slider.textChoices[0]. 

`(lldb) po _slider.textChoices[0]
<ORKTextChoice: 0x600000a5c050>`

Is there a way to expose the _slider.textChoices[0]'s value? Then I can use an if statement to decide whether to -1 or not.

**Comment by simon-apple** [comment]
Closing since this has been resolved. We recommend upgrading to the latest release, which includes many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
