### ISSUE TITLE
Code signing error

### ISSUE THREAD

**Issue by vkoushik** [ResearchKit/ResearchKit#1053]
Hi,

I am trying to run the sample code but both orksample and orkcatalog are throwing error stating code signing error.

Failed to create provisioning profile.
The app ID "com.example.researchkit-samplecode.ORKCatalog" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

No profiles for 'com.example.researchkit-samplecode.ORKCatalog' were found
Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.researchkit-samplecode.ORKCatalog'.

Similar to orksample. Can someone please help me with this issue? Thank you

**Comment by srinathtm-apple** [comment]
Hey @vkoushik can you please try changing the bundleID if you are running it on a hardware or you could just try deploying to the simulator.

**Comment by vkoushik** [comment]
It works on simulator. I changed the id from com.example.apple-samplecode.Sample to com.example.apple-samplecode.ORKSample but still doesn't work on device

**Comment by srinathtm-apple** [comment]
Hey @vkoushik, this doesn't sound like an issue with the framework. My guess is your development team and provisioning profiles aren't setup correctly.

**Comment by vkoushik** [comment]
Other day i downloaded coreML sample app, it had similar id except for the app name "com.example.apple-samplecode.MarsHabitatPricePredictorNA67PTC25X"  and installed on my phone, it worked fine without any issues but it happened with Researchkit. This is just FYI. I changed id to com.example.ORKSample with apple-samplecode removed and it's working now.

**Comment by vkoushik** [comment]
Thank you
