### ISSUE TITLE
iPad white margin not scrollable

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1055]
The's margin on both sides of the tableview when I am presenting a formStep on an iPad. The scrolling (vertical direction) works fine if the touch gesture is inside the tableview, but does not work on the margin. 
I am wondering if there's a way to make the scrolling work besides reducing the margin size.
If not, where should I look to set the margin size?

**Comment by ninoguba** [comment]
In ORKSkin.m, line 284 you will find this switch statement:

```
    switch (ORKGetHorizontalScreenTypeForWindow(window)) {
        case ORKScreenTypeiPhone4:
        case ORKScreenTypeiPhone5:
        case ORKScreenTypeiPhone6:
        case ORKScreenTypeiPhone6Plus:
        default:
            margin = ORKStandardLeftTableViewCellMarginForWindow(window);
            break;
        case ORKScreenTypeiPad:{
            margin = ORKStandardHorizontalAdaptiveSizeMarginForiPadWidth(ORKiPadScreenSize.width, window);
            break;
        }
        case ORKScreenTypeiPad12_9:{
            margin = ORKStandardHorizontalAdaptiveSizeMarginForiPadWidth(ORKiPad12_9ScreenSize.width, window);
            break;
        }
    }
```

Slightly modify it to the following to get rid of the extra margins on the iPad:

```
    switch (ORKGetHorizontalScreenTypeForWindow(window)) {
        case ORKScreenTypeiPhone4:
        case ORKScreenTypeiPhone5:
        case ORKScreenTypeiPhone6:
        case ORKScreenTypeiPhone6Plus:
        case ORKScreenTypeiPad:
        case ORKScreenTypeiPad12_9:
        default:
            margin = ORKStandardLeftTableViewCellMarginForWindow(window);
            break;
    }
```

**Comment by windenchanter** [comment]
@ninoguba This works on getting rid of the margin, but now it looks too wide. I wonder how can I adjust this margin to be less wide?
Is there any value I can enter for ORKiPadScreenSize.width to make this less wide?
`margin = ORKStandardHorizontalAdaptiveSizeMarginForiPadWidth(ORKiPadScreenSize.width, window);`

**Comment by ninoguba** [comment]
Yes you can adjust the margins if that is what you want.  All you need to do is follow the code.

**Comment by ninoguba** [comment]
@windenchanter what I mean by "follow the code" is command-click on ORKiPadScreenSize.width in Xcode to jump to its definition in code and just adjust according to your needs.

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. We recommended upgrading to the latest release, and if you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
