### ISSUE TITLE
Picker Views doesnt support Dynamic Type fonts

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#1056]
I found that question types that use the UIPickerView doesnt support Dynamic Type fonts, unlike the rest.

In iOS Settings > General > Accessibility > Larger Text, one can change the size of the font based on their preference, i.e for the vision impaired.

<img width="551" alt="screen shot 2018-01-29 at 3 40 51 pm" src="https://user-images.githubusercontent.com/4361804/35540594-77f9a81e-050b-11e8-88a9-030fae3a8b2d.png">

This is how it looks when using larger text.

<img width="551" alt="screen shot 2018-01-29 at 3 40 27 pm" src="https://user-images.githubusercontent.com/4361804/35540715-172ac4d6-050c-11e8-87ea-d1b7e1f4fee8.png">

This is how it looks when using the normal text size.

<img width="551" alt="screen shot 2018-01-29 at 3 46 20 pm" src="https://user-images.githubusercontent.com/4361804/35540734-33ea2cce-050c-11e8-9ae2-3fab58bfdd40.png">

As you can tell, the text of the UIPickerView didnt change size at all.  I expect it to be similar to the adjusted size of the ORKTextChoices below:

<img width="551" alt="screen shot 2018-01-29 at 3 40 09 pm" src="https://user-images.githubusercontent.com/4361804/35541064-c8d1585c-050d-11e8-9a0f-808476bc3e67.png">

Anyone have dealt with this issue before?

**Comment by ninoguba** [comment]
This is a start for the solution.  In ORKValuePicker.m, I had to implement viewForRow of the UIPickerViewDelegate like below:

```
- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view
{
    UILabel* valueLabel = (UILabel*)view;
    if (!valueLabel)
    {
        valueLabel = [[UILabel alloc] init];
        [valueLabel setFont:[self defaultFont]];
        [valueLabel setTextAlignment:NSTextAlignmentCenter];
    }
    // Fill the label text here
    valueLabel.text = [self pickerView:pickerView titleForRow:row forComponent:component];
    return valueLabel;
}

- (UIFont *)defaultFont {
    UIFontDescriptor *descriptor = [UIFontDescriptor preferredFontDescriptorWithTextStyle:UIFontTextStyleBody];
    return [UIFont systemFontOfSize:((NSNumber *)[descriptor objectForKey:UIFontDescriptorSizeAttribute]).doubleValue + 2.0];
}
```

This makes it use of the Dynamic Type fonts.  Now I just need to adjust the cell heights to fit the bigger fonts accordingly...

**Comment by ninoguba** [comment]
Did something like this for the dynamic row height:

```
- (CGFloat)pickerView:(UIPickerView *)pickerView rowHeightForComponent:(NSInteger)component {
    UIFont *font = [self defaultFont];
    CGFloat height =  font.pointSize + 15.0;
    if (height < 34) {
        return 34;
    } else {
        return height;
    }
}
```

15.0 is just for spacing.  34.0 is the height when the text size is normal so I made this the minimum for the row height.  Now this is how it looks with support for Dynamic Types.

<img width="551" alt="screen shot 2018-01-30 at 4 20 10 pm" src="https://user-images.githubusercontent.com/4361804/35598651-94ec6122-05d9-11e8-9625-2e9859c109e3.png">

Same fix should be applied to ORKHeightPicker, ORKWeightPicker and other components that use the UIPickerView.

I'm open to submit this as a PR if the community thinks this is a necessary fix.  Leaving this open for a chance to be discussed.

**Comment by srinathtm-apple** [comment]
Hey @ninoguba , I think this is extremely useful. Please go ahead a create a PR so that we can have folks review the code changes. Thank you!

**Comment by ninoguba** [comment]
Ok @srinathtm-apple will start working on the PR.

**Comment by ninoguba** [comment]
PR #1062 is now ready for review
