### ISSUE TITLE
Need fixed ORKScaleSliderView length on all iPad devices

### ISSUE THREAD

**Issue by majidsaleem105** [ResearchKit/ResearchKit#1057]
Hello friends,

We're creating a specific survey and we need to display a fixed length [ of 10CM ] of slider in it on all iPad including retina and non-retina devices.

We're currently hard-coding values in ORKScaleSliderView class but this solution doesn't work for iPad devices. It displays correct length for the devices we applied changes so we're looking for some good suggestions to draw exact 10CM slider length all iPad devices.

Thanks in advance for your help!

**Comment by dukemike** [comment]
For VAS, we use the scale answer format and remove the scale and tic marks. Our interpretation has been that measuring the distance on the 10cm VAS to get 0 - 100 mm is equivalent to getting 0 - 100 on the slider. I’m not sure if any formal research has been done on this though.

— Mike

On Jan 30, 2018, at 5:23 AM, majidsaleem105 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello friends,

We're creating a specific survey and we need to display a fixed length of 10CM of slider in it on all iPad devices including retina and non-retina.

We're currently hard-coding values in ORKScaleSliderView class but this solution doesn't work for iPad devices. It displays correct length for the devices we applied changes so we're looking for some good suggestions to draw exact 10CM slider length all iPad devices.

Thanks in advance for your help!

**Comment by ninoguba** [comment]
@majidsaleem105 you may want to share your code that works on iPhones so that others can see what modifications to your code will be needed to make it work for the iPads.

**Comment by majidsaleem105** [comment]
@ninoguba Here is the code. 

       CGFloat screenWidth = floor( [UIScreen mainScreen].bounds.size.width );
        NSInteger screenWidthInt = (NSInteger) screenWidth;
        CGFloat kMargin = 17.0;
        switch( screenWidthInt )
        {
            case 768 : kMargin =  64.0; break;
            case 1024: kMargin = 128.0; break;
            case 1366: kMargin = 214.0; break;
            case 1536: kMargin = 222.0; break; // expected value
            case 2048: kMargin = 242.0; break; // expected value
            case 2732: kMargin = 534.0; break; // expected value
        }

This way, it works for 768, 1024 and 1366 resolutions. Now I need to know what could be possible values of 1536, 2048 & 2732 [retina devices] resolutions?

**Comment by ninoguba** [comment]
@majidsaleem105 how did you come up with your margins for 768, 1024, 1366? you can just apply it to the other widths.

**Comment by majidsaleem105** [comment]
@ninoguba I used iPad simulators for these resolutions. I'm unable to download Retina iPad simulator, it says "Incompatible Device". ![retina ipad](https://user-images.githubusercontent.com/1611600/35914933-e94d5d9a-0c26-11e8-948a-03dc9dfca0fd.png)

**Comment by ninoguba** [comment]
On your screenshot I see you have the iPad Pro simulators already.  Those are Retina displays.

Also you can just refer to this reference for this information:

https://developer.apple.com/library/content/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html

**Comment by simon-apple** [comment]
Closing since this has been resolved.
