### ISSUE TITLE
Navigable Ordered Tasks in Swift

### ISSUE THREAD

**Issue by SarahUCD** [ResearchKit/ResearchKit#1058]
I am having trouble with the navigable ordered tasks. I want the survey to only ask where if the person taking the survey answers "yes" to the location question. The code is compiling, but it is asking where even when the user says, "no" to the location question.

Another question I have is: 
When looking online I notice people using two types of identifiers both of which are shown here. Which one is correct? (identifier: String(describing:Identifier.whereAt) or identifier: "location") 

import ResearchKit

private enum Identifier {
    // Location where task specific indentifiers.
    case StepNabigationTaskIdentifier
    case formStep
    case generalFormStep
    case location
    case whereAt
    case season
    case locationWhereTask
    case noLocationStep
    case noLocationResult
}

public var SurveyTask: ORKTask {
    var steps = [ORKStep]()
    
    // Instructions:
    let instructionStep = ORKInstructionStep(identifier: "IntroStep")
    instructionStep.title = "Example Title"
    instructionStep.text = "Example Text"
    steps += [instructionStep]
    
    // Choices for Answers
    let textChoices = [
        ORKTextChoice(text: "Yes", value: "Yes" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "No", value: "No" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "Not Sure", value: "NS" as NSCoding & NSCopying & NSObjectProtocol),
    ]
    let choiceAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)
    //  Input Answers
    let inputAnswerFormat = ORKTextAnswerFormat(maximumLength: 60)
    inputAnswerFormat.multipleLines = false
    
    // Questions:
    let locationQuestionStep = ORKQuestionStep(identifier: "location", title: "Do you have a favorite place?", answer: choiceAnswerFormat)
    steps += [locationQuestionStep]
    let whereQuestionStep = ORKQuestionStep(identifier: String(describing:Identifier.whereAt), title: "Where?", answer: inputAnswerFormat) 
    steps += [whereQuestionStep]
    let seasonQuestionStep = ORKQuestionStep(identifier: "season", title: "Do you have a favorite season? ", answer: choiceAnswerFormat)
    steps += [seasonQuestionStep]
    
    
    // Form a task
    var task = ORKNavigableOrderedTask(identifier: "StepNavigationTaskIdentifier", steps: steps)
    var predicateRule: ORKPredicateStepNavigationRule? = nil
    
    // Navigation rules:
    //  Expected answer - (usually No) - Skips to the next question
    let resultSelector: ORKResultSelector
    let directRule: ORKDirectStepNavigationRule
    resultSelector = ORKResultSelector(resultIdentifier: "location")
     let predicateAnswerType = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "No" as NSCoding & NSCopying & NSObjectProtocol)
    // Destination step - the next question
    predicateRule = ORKPredicateStepNavigationRule(resultPredicates: [predicateAnswerType], destinationStepIdentifiers: [("No" as NSCoding & NSCopying & NSObjectProtocol) as! String], defaultStepIdentifier: "season", validateArrays: true)
    // Trigger Step - first question which triggers the navigation rule
    task.setNavigationRule(predicateRule!, forTriggerStepIdentifier: locationQuestionStep.identifier)
    
    let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
    summaryStep.title = "Done!"
    summaryStep.text = "The survey has finished!"
    steps += [summaryStep]
    
    return ORKOrderedTask(identifier: String(describing:Identifier.locationWhereTask), steps: steps)
}

**Comment by kelseydedoshka-apple** [comment]
@SarahUCD - it looks like you are creating your ORKNavigableOrderedTask right under the // Form a task comment, however retuning a different task at the end of the file. I believe the task you create first which are you setting the predicate rules on is the task you want to return.

**Comment by SarahUCD** [comment]
@kelseydedoshka-apple  - even after making those changes it is still not navigating through the ordered tasks as I hoped it would. Here is the updated code:

import ResearchKit


public var SurveyTask: ORKTask {
    var steps = [ORKStep]()
    
    // Instructions:
    let instructionStep = ORKInstructionStep(identifier: "IntroStep")
    instructionStep.title = "Example Title"
    instructionStep.text = "Example Text"
    steps += [instructionStep]
    
    // Choices for Answers
    let textChoices = [
        ORKTextChoice(text: "Yes", value: "Yes" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "No", value: "No" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "Not Sure", value: "NS" as NSCoding & NSCopying & NSObjectProtocol),
        ]
    let choiceAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)
    //  Input Answers
    let inputAnswerFormat = ORKTextAnswerFormat(maximumLength: 60)
    inputAnswerFormat.multipleLines = false
    
    // Questions:
    let locationQuestionStep = ORKQuestionStep(identifier: "location", title: "Do you have a favorite place?", answer: choiceAnswerFormat)
    steps += [locationQuestionStep]
    let whereQuestionStep = ORKQuestionStep(identifier:"where", title: "Where?", answer: inputAnswerFormat)
    steps += [whereQuestionStep]
    let seasonQuestionStep = ORKQuestionStep(identifier: "season", title: "Do you have a favorite season? ", answer: choiceAnswerFormat)
    steps += [seasonQuestionStep]
    
    
    // Form a task
    var task = ORKNavigableOrderedTask(identifier: "StepNavigationTaskIdentifier", steps: steps)
    var predicateRule: ORKPredicateStepNavigationRule? = nil
    
    // Navigation rules:
    //  Expected answer - (usually No) - Skips to the next question
    let resultSelector: ORKResultSelector
    //let directRule: ORKDirectStepNavigationRule
    resultSelector = ORKResultSelector(resultIdentifier: "location")
    
    let predicateAnswerType = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "No" as NSCoding & NSCopying & NSObjectProtocol)
    
    // Destination step - the next question
    predicateRule = ORKPredicateStepNavigationRule(resultPredicates: [predicateAnswerType], destinationStepIdentifiers: [("No" as NSCoding & NSCopying & NSObjectProtocol) as! String], defaultStepIdentifier: "season", validateArrays: true)
    
    // Trigger Step - first question which triggers the navigation rule
    task.setNavigationRule(predicateRule!, forTriggerStepIdentifier: "location")
    
    let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
    summaryStep.title = "Done!"
    summaryStep.text = "The survey has finished!"
    steps += [summaryStep]
    
    return ORKOrderedTask(identifier: "StepNavigationTaskIdentifier" , steps: steps)
}

**Comment by dukemike** [comment]
@SarahUCD, I've updated your example to use a skip rule.

```swift
    static let surveyTask: ORKOrderedTask = {
        var steps = [ORKStep]()
        
        // Instruction step
        let instructionStep = ORKInstructionStep(identifier: "IntroStep")
        instructionStep.title = "Example Title"
        instructionStep.text = "Example Text"
        steps += [instructionStep]

        // Choices for Answers
        let textChoices = [
            ORKTextChoice(text: "Yes", value: "Yes" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: "No", value: "No" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: "Not Sure", value: "NS" as NSCoding & NSCopying & NSObjectProtocol),
            ]
        let choiceAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)

        //  Input Answers
        let inputAnswerFormat = ORKTextAnswerFormat(maximumLength: 60)
        inputAnswerFormat.multipleLines = false

        // Questions:
        let locationQuestionStep = ORKQuestionStep(identifier: "location", title: "Do you have a favorite place?", answer: choiceAnswerFormat)
        steps += [locationQuestionStep]
        let whereQuestionStep = ORKQuestionStep(identifier:"where", title: "Where?", answer: inputAnswerFormat)
        steps += [whereQuestionStep]
        let seasonQuestionStep = ORKQuestionStep(identifier: "season", title: "Do you have a favorite season? ", answer: choiceAnswerFormat)
        steps += [seasonQuestionStep]

        let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
        summaryStep.title = "Done!"
        summaryStep.text = "The survey has finished!"
        steps += [summaryStep]

        // Form a task
        var task = ORKNavigableOrderedTask(identifier: "StepNavigationTaskIdentifier", steps: steps)

        //  Expected answer - (usually No) - Skips to the next question
        let resultSelector: ORKResultSelector = ORKResultSelector(resultIdentifier: "location")
        let askLocation = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, matchingPattern: "No")
        let locationNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askLocation)

        task.setSkip(locationNavigationRule, forStepIdentifier: "where")

        return task
    }()
```

**Comment by SarahUCD** [comment]
@dukemike - Thanks for the help!
Although, the code you provided has a couple errors: Use of undeclared type 'ORKOrderedTask' and Static properties may only be declared on a type.

**Comment by SarahUCD** [comment]
@dukemike - Now I am having troubles adding another navigable task. Are you able to help me? This is what the code looks like:

import ResearchKit

public var surveyTask: ORKOrderedTask = {
    var steps = [ORKStep]()
    
    // Instruction step
    let instructionStep = ORKInstructionStep(identifier: "IntroStep")
    instructionStep.title = "Example Title"
    instructionStep.text = "Example Text"
    steps += [instructionStep]
    
    // Choices for Answers
    let textChoices = [
        ORKTextChoice(text: "Yes", value: "Yes" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "No", value: "No" as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "Not Sure", value: "NS" as NSCoding & NSCopying & NSObjectProtocol),
        ]
    let choiceAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)
    
    //  Input Answers
    let inputAnswerFormat = ORKTextAnswerFormat(maximumLength: 60)
    inputAnswerFormat.multipleLines = false
    
    // Questions:
    let locationQuestionStep = ORKQuestionStep(identifier: "location", title: "Do you have a favorite place?", answer: choiceAnswerFormat)
    steps += [locationQuestionStep]
    let whereQuestionStep = ORKQuestionStep(identifier:"where", title: "Where?", answer: inputAnswerFormat)
    steps += [whereQuestionStep]
    let seasonQuestionStep = ORKQuestionStep(identifier: "season", title: "Do you have a favorite season? ", answer: choiceAnswerFormat)
    steps += [seasonQuestionStep]
    let whichSeasonQuestionStep = ORKQuestionStep(identifier: "whichSeason", title: "Which Season is your favorite?", answer: inputAnswerFormat)
    steps += [whichSeasonQuestionStep]
    let animalQuestionStep = ORKQuestionStep(identifier: "animal", title: "What is your favorite animal?", answer: inputAnswerFormat)
    steps += [animalQuestionStep]
    
    let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
    summaryStep.title = "Done!"
    summaryStep.text = "The survey has finished!"
    steps += [summaryStep]
    
    // Form a task
    var task = ORKNavigableOrderedTask(identifier: "StepNavigationTaskIdentifier", steps: steps)
    
    //  Expected answer - (usually No) - Skips to the next question
    let resultSelector: ORKResultSelector = ORKResultSelector(resultIdentifier: "location")
    let askLocation = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, matchingPattern: "No")
    let locationNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askLocation)
    
    task.setSkip(locationNavigationRule, forStepIdentifier: "where")
    
    return task
    
    // Form another task
    var whichSeasonTask = ORKNavigableOrderedTask(identifier: "whichSeasonTask", steps: steps)
    let seasonResultSelector = ORKResultSelector(resultIdentifier: "season")
    let askSeason = ORKResultPredicate.predicateForChoiceQuestionResult(with: seasonResultSelector, matchingPattern: "No")
    let seasonNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askSeason)
    whichSeasonTask.setSkip(seasonNavigationRule, forStepIdentifier: "whichSeason")
    return whichSeasonTask
    
    
}()

**Comment by srinathtm-apple** [comment]
The code will exit once it hits "return task", it will never reach "return whichSeasonTask"

**Comment by SarahUCD** [comment]
I have tried changing my code to only have one task to return and it only preforms one task (the which season task) when I change the code to look like this:
let resultSelector: ORKResultSelector = ORKResultSelector(resultIdentifier: "location")
    let askLocation = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, matchingPattern: "No")
    let locationNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askLocation)
    
    task.setSkip(locationNavigationRule, forStepIdentifier: "where")
    
    task = ORKNavigableOrderedTask(identifier: "whichSeasonTask", steps: steps)
    let seasonResultSelector = ORKResultSelector(resultIdentifier: "season")
    let askSeason = ORKResultPredicate.predicateForChoiceQuestionResult(with: seasonResultSelector, matchingPattern: "No")
    let seasonNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askSeason)
    task.setSkip(seasonNavigationRule, forStepIdentifier: "whichSeason")
    
    return task


What am I doing wrong?

**Comment by dukemike** [comment]
@SarahUCD You are redefining `task` in your `//Second Navigable Task` block. You should remove `task = ORKNavigableOrderedTask(identifier: "whichSeasonTask", steps: steps)`.


```swift
        var task = ORKNavigableOrderedTask(identifier: "StepNavigationTaskIdentifier", steps: steps)

        let locationSelector: ORKResultSelector = ORKResultSelector(resultIdentifier: "location")
        let askLocation = ORKResultPredicate.predicateForChoiceQuestionResult(with: locationSelector, matchingPattern: "No")
        let locationNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askLocation)

        let seasonSelector: ORKResultSelector = ORKResultSelector(resultIdentifier: "season")
        let askSeason = ORKResultPredicate.predicateForChoiceQuestionResult(with: seasonSelector, matchingPattern: "No")
        let seasonNavigationRule = ORKPredicateSkipStepNavigationRule(resultPredicate: askSeason)

        task.setSkip(locationNavigationRule, forStepIdentifier: "where")
        task.setSkip(seasonNavigationRule, forStepIdentifier: "whichSeason")

        return task
```

**Comment by SarahUCD** [comment]
@dukemike  - Thanks for your help!

I am still having some minor issues. I have written the code so there are multiple choice answers including "other". If the user selects "other" I want it to go to a page where they can input using text. I have correctly coded the answer format, but I'm having issues with the navigable tasks. It seems they are set up to go through the survey unless prompted to skip steps. This is an issue because if someone selects another answer and other (using the multiple choice format) it skips to the next question instead of letting the user type in their "other" answer. Any ideas on how to achieve this?

**Comment by SarahUCD** [comment]
@dukemike or anyone else who can help:

Is it possible to make the "no" and "not sure" skip steps using navigable ordered tasks?

When I use the code below it requires both no and not sure to be selected which isn't actually possible with the single choice format and not desired regardless. 
let askLocation = ORKResultPredicate.predicateForChoiceQuestionResult(with: locationSelector, matchingPatterns: ["No", "NS]) 

When I try to make two different navigation rules and result predicates it only acts correctly for one and not the other. From reading up on the topic I believe this is because you can only assign one skip rule per question step.

Any help is appreciated!

**Comment by ninoguba** [comment]
You have to make separate predicates out of your available choices and then use NSCompoundPredicate and use orPredicateWithSubpredicates to build the condition you desire.

https://developer.apple.com/documentation/foundation/nscompoundpredicate/1417873-orpredicatewithsubpredicates

**Comment by SarahUCD** [comment]
Thank you @ninoguba! That works for most of the questions on my survey. 

However, there are some questions where this won't work. For example, when asked if they own any pets they will be presented with a list of pets and and it will ask them different questions based off of the answer cat, dog or others on the list. The way I would code it using NSCompoundPredicates it would state if they select dog skip the questions for cat, ferret, etc. but what if they have a dog and cat? This is why I think the NSCompoundPredicates isn't the solution for this specific problem. Any ideas?

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
