### ISSUE TITLE
Skip Steps at beginning ORKNavigableOrderedTask

### ISSUE THREAD

**Issue by AH24** [ResearchKit/ResearchKit#1059]
I have a survey that has some introduction steps at the beginning and I want to skip past these if certain conditions are met before the survey. Is there a way to have say the first 2 steps skip.

So I want the survey to start at step 3 of 5 before they have taken any. Currently I only see a way to skip after a certain question like this
`let rule = ORKDirectStepNavigationRule(destinationStepIdentifier: introductionStep3.identifier)
task.setNavigationRule(rule, forTriggerStepIdentifier: introductionStep.identifier)`

Is there a way to skip the first two without having a trigger step? I am trying to use ORKSkipStepNavigationRule, but I can't seem to figure out the correct implementaion. I am writing in Swift

**Comment by ninoguba** [comment]
You can make your ORKTask dynamic.  Depending on your conditions, you can set the task with 5 steps or just 3.

**Comment by HEIDEMAN** [comment]
But I want it to start at step 3 of 5 as oppossed to step 1 of 3. 
If certain conditions are met they would have done 2 steps already in a different survey and I would like to have them to start at 3 to avoid confusion for user

**Comment by ninoguba** [comment]
Have you tried programmatically setting the answers to the first two steps and see if this triggers your navigation rules?

**Comment by ninoguba** [comment]
Also with ORKNavigableOrderedTasks, the progress title "Step 1 of 3" won't show anyway right?

**Comment by fansaien** [comment]
@ninoguba There is a property shouldReportProgress to show the progress title.

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
