### ISSUE TITLE
Customizing location of the Done button

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1061]
I am wondering if the location of the done button at the end of each survey can be moved? It looks ok on an iPhone, but on an iPad it is at the top right corner and is difficult to notice. There is a big white checkmark enclosed in a blue circle at the centre of the screen that looks like a button and I got people pressing that all the time. 
One way is just to tell them to locate the button at the top right corner, but I wonder if anything else can be done? Can the button size be adjusted to a bigger size? Or is there a way to remove this big check mark enclosed in a circle? It looks too much like a button. 
![image](https://user-images.githubusercontent.com/22673319/35891259-97d30fc6-0b60-11e8-8d67-6fdab0f2c1a0.png)

**Comment by mmertsock** [comment]
ORKCompletionStepViewController has a [`shouldShowContinueButton`](http://researchkit.org/docs/Classes/ORKCompletionStepViewController.html#//api/name/shouldShowContinueButton) property, which you can use to have the view controller display a Done button below the checkmark.

**Comment by windenchanter** [comment]
@mmertsock Thank you! I found this property, but I don't know where I can set this property. Could you please advice on how to set it?

I have my completion step set:
`let completionStep = ORKCompletionStep(identifier: "CompletionStep")`
Then this completion step is added to a ORKNavigableOrderedTask.

**Comment by ninoguba** [comment]
```
let completionStep = ORKCompletionStep(identifier: "CompletionStep")
completionStep.shouldShowContinueButton = true
```

**Comment by windenchanter** [comment]
@ninoguba 
Hi, I have tried that, but with the following error.
Value of type 'ORKCompletionStep' has no member 'shouldShowContinueButton'
The shouldShowContinueButton property is only accessible for the ORKCompletionStepViewController class.
How do I set this value for the ORKCompletionStepViewController class?

**Comment by mmertsock** [comment]
The simplest way is to implement the [`taskViewController:stepViewControllerWillAppear:`](http://researchkit.org/docs/Protocols/ORKTaskViewControllerDelegate.html#//api/name/taskViewController:stepViewControllerWillAppear:) method of `ORKTaskViewControllerDelegate`. You can check whether check whether the step view controller passed to that method is an ORKCompletionStepViewController, and if so cast it to an ORKCompletionStepViewController and set the shouldShowContinueButton property:

```swift
func taskViewController(_ taskViewController: ORKTaskViewController, stepViewControllerWillAppear stepViewController: ORKStepViewController) {
    if let completionViewController = stepViewController as? ORKCompletionStepViewController {
        completionViewController.shouldShowContinueButton = true
    }
}
```

**Comment by ninoguba** [comment]
Sorry my mistake. Just realized @mmertsock referred to ORKCompletionStepViewController instead of ORKCompletionStep.  Please follow @mmertsock's suggestion above for the correct approach.

**Comment by windenchanter** [comment]
Great! This works beautifully. Thanks a lot @mmertsock @ninoguba
