### ISSUE TITLE
ORKRegistrationStep expansion for Phone Number

### ISSUE THREAD

**Issue by Br35Ba56** [ResearchKit/ResearchKit#1068]
Hi,

I'm using AWS Cognito for participant sign up and sign in.  There are two options for account verification, email or phone number via SMS.  If I am trying to prevent malicious users of my application from skewing research data by having multiple accounts, SMS is the logical way to verify a user.  However, ORKRegistrationStep does not provide an option to add a phone number field.  Therefore, instead of trying to extend classes, I modified the code base of ResearchKit to add the field.  For my purpose, the field needs to be their so I added it to the initializer of ORKRegistrationStep.m just below the Email item initialization.  If this is something the community could use, I will write it up so its an optional field and submit a pull request.

Let me know

<img width="374" alt="screen shot 2018-02-13 at 5 43 56 pm" src="https://user-images.githubusercontent.com/21034740/36180336-8e665cc4-10e5-11e8-91c9-13a366790ffd.png">

**Comment by srinathtm-apple** [comment]
Hey @Br35Ba56 , this sounds like a great addition, please feel free to file a PR!

Also, I think it might be better to add it as a new option in the ORKRegistrationStepOption enum, that way the UI to enter phone number won't show up unless a developer explicitly requests it in options.

**Comment by srinathtm-apple** [comment]
@Br35Ba56 absolutely! You could add 2 new properties called phoneNumberValidationRegularExpression and phoneNumberInvalidMessage (similar to passcode) and maybe also create a custom initializer for this, although I don't think it is strictly necessary.

**Comment by srinathtm-apple** [comment]
Closing this issue since the PR referencing this has been merged.
