### ISSUE TITLE
Default value for multiple choice?

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1070]
A default value is available to set for a slider. Is it possible to add a default value for multiple choice? I am trying to add a default value for multiple choice but I have no clue where to look. I appreciate any advice. 

I am particularly interested in multiple choices that allow selection of more than one choices. 
For example: [None, Apple, Banana, Car]. I would like the None to be a default choice. Apple, Banana, Car can all be selected or not. But if any non-None choices are selected, e.g., Apple is selected, "None" should be disabled. In other words, you can still select Banana and Car when Apple is selected, but you should not be able to select None.

**Comment by ninoguba** [comment]
Look here for setting default answers:
http://researchkit.org/docs/Classes/ORKTaskViewController.html#//api/name/defaultResultSource

Look here for setting choices as mutually exclusive:
http://researchkit.org/docs/Classes/ORKTextChoice.html#//api/name/exclusive

**Comment by windenchanter** [comment]
@ninoguba Thank you. When I look at the documentation, it says "The source can provide default answers, perhaps based on previous runs of the same task, which will be used to prefill question and form items. For example, an ORKTaskResult object from a previous run of the task can function as an ORKTaskResultSource object, because ORKTaskResult implements the protocol."

I wonder how can I deliberatively construct this ORKTaskResult object. Let's say the second question in my questionnaire needs a default value of 1, but the first and third question does not need a default value, how can this be set?

**Comment by ninoguba** [comment]
Check my previous response here #1007.

**Comment by windenchanter** [comment]
@ninoguba 
Thank you! I got it to work now. I got stuck on specifying the answer first, then I realized that the answer for multiple choice cannot be specified by = 0 (assuming default answer is 0), it has to be set to = [0]

**Comment by ninoguba** [comment]
@windenchanter glad I can help.  if you have further questions let us know, otherwise you can close the issue now.
