### ISSUE TITLE
ORK Catalog app: 'Range of Motion' active tasks do not display properly

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1073]
Hi All,

The titles and instructions for the two 'Range of Motion' active tasks (Knee and Shoulder) do not display properly (at any stage) when run within the sample app, ORKCatalog (screenshots attached).

I've not been able to get this working, so would love some input from somebody more experienced.

Thanks

![img-4271](https://user-images.githubusercontent.com/35876659/36380181-3fc86b46-1579-11e8-8dec-13da8d2b215c.JPG)
![img-4272](https://user-images.githubusercontent.com/35876659/36380182-3fe3c5da-1579-11e8-8945-b6e12b5bac33.JPG)
![img-4273](https://user-images.githubusercontent.com/35876659/36380183-4007c5d4-1579-11e8-96a6-aae6ae6a4d91.JPG)
![img-4274](https://user-images.githubusercontent.com/35876659/36380184-402effc8-1579-11e8-9e86-8f2c283a1af8.JPG)

**Comment by srinathtm-apple** [comment]
Hey @davwillev , thanks for pointing this out. Looks like a PR which we merged in a while back introduced this issue. We will roll out a fix for this soon.

**Comment by srinathtm-apple** [comment]
#1074

**Comment by davwillev** [comment]
That's great - thanks @srinathtm-apple 
I tried re-inserting the code from your fix, but errors were being flagged. I'll wait until you tell me that the fix is completed

**Comment by srinathtm-apple** [comment]
@davwillev - what errors are you seeing ? I believe the fix is complete and only thing remaining is to merge the changes into master.

**Comment by davwillev** [comment]
@srinathtm-apple - I've got it working now - no further errors. Thanks!
