### ISSUE TITLE
ORKCatalog app CMDeviceMotion results file format

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1079]
Hi All,

Would it be possible to modify the format of the resulting output file from ORKCatalog.

My colleagues and I are interested in extending the utility of the range of motion tasks, and having the full CMDeviceMotion data is excellent for this. However, the results are currently formatted as a unattributed file (see attached), which we can open in a text viewer but can't easily analyse to assess our results.

By contrast, if these data were formatted on a CSV file, with each row ordered by timestamp, we could easily check the data and then make our adjustments to the module accordingly. I would love some help with this, and I'm sure the other active tasks would benefit from this modification too.

Many thanks

**Comment by srinathtm-apple** [comment]
Hey @davwillev , the results are currently formatted in a NSDictionary/JSON format which is super easy to serialize and upload. Our intention I believe was to help the app developer access this data and upload it to a server for further processing. 

Now, there are a few tools available online which let you convert JSON to CSV that you can leverage. There are also websites that do this conversion online and allow you to download the resulting csv file. 

I hope that was helpful. Please let me know if you have any further questions.

**Comment by davwillev** [comment]
Great - I got that converted already. Thanks so much for the advice.

Can I just ask, are the attitude data on the JSON file already processed to account for gravitational acceleration? See: https://developer.apple.com/documentation/coremotion/getting_processed_device_motion_data

**Comment by srinathtm-apple** [comment]
@davwillev  , as per our API documentation -

"Device motion data is the processed motion data provided by CoreMotion and obtained
 from a `CMMotionManager` object. The data can include measures of the overall device orientation
 obtained from combining accelerometer, magnetometer, and gyroscope data."

Also looking at the code, the attitude values we are providing is relative to the initial position. 

Please let me know if that answered your question, if not, I can dig deeper and get back to you!

**Comment by davwillev** [comment]
Thanks for getting back to me, @srinathtm-apple 
The first ('flexion') result produced by the attitude values is not always zero, so these results seem to be using another reference frame. I've opened up another 'issue' to improve the overall results from these tasks

**Comment by srinathtm-apple** [comment]
Closing this issue as the overall improvement efforts are being tracked by separate issues and PRs.
