### ISSUE TITLE
ImageCapture behavior understanding

### ISSUE THREAD

**Issue by AndriiDoroshko** [ResearchKit/ResearchKit#1083]
Alright guys))) I’ve got in next issues with imageCaptureStep (see screenshots): 

1. `ImageCaotureView` is very small, and I did find a single way to make it bigger, i simple add an      empty .png(1011x1245) as `templateImage` and got next size: 
	Is there another way to change the size of this view?
	When I go to landscape mode I and back in portrait
 Your browser does not support the video tag. mode the `CaptureImageButtons` are 		disappeared. Any ideas whats going on here?
<img src="https://user-images.githubusercontent.com/32369717/36600866-26fafe3a-18bc-11e8-943b-b461fa65f148.gif" width="400">

2. `ImageCapturedView`. The image is captured, ResearchKit provides the beautiful view with the image, `doneButton` and `recaptureButton`. But in portrait mode, `recaptureButton` goes all the way down, out of screen.   
	In landscape mode, `recaptureButton` are visible, but its right in the middle of screen. And 		what the transparented view under the buttons?
<img src="https://user-images.githubusercontent.com/32369717/36601189-2930aba4-18bd-11e8-95a5-31e48c418c30.gif" width="400">

<img src="https://user-images.githubusercontent.com/32369717/36601514-f59b68fa-18bd-11e8-9919-f08c051ba52c.png" width="400"><img src="https://user-images.githubusercontent.com/32369717/36601564-14042fa2-18be-11e8-9858-95808d83e712.png" width="200">

3. How can i change size of `imageCapturedView`?

**Comment by ninoguba** [comment]
The fix for this has already been merged to master. Refer to #1064

**Comment by AndriiDoroshko** [comment]
@ninoguba Only for first issue))) 
When could master be merged to stable?

**Comment by AndriiDoroshko** [comment]
@ninoguba `recaptureButton` are invisible in stable) Is it fixed in master?

**Comment by ninoguba** [comment]
@AndriiDoroshko the position of the recaptureButton is fixed on the PR as well.

**Comment by AndriiDoroshko** [comment]
@ninoguba Thank you very much for your answer)
Why i can't modify `imageCapturedView`  in a way i want? It's would be great feature, cause i realised, ResearchKit doesn't provide customisation)

**Comment by ninoguba** [comment]
You're always free to make any customizations you want.  Some methods and properties of the framework components are exposed making it easy to configure according to your needs.  However in some more complicated use cases, you'll just have to customize the framework itself to fit your exact requirements.

**Comment by AndriiDoroshko** [comment]
I don't want to touch framework, because if it update, my code will be broken (
I couldn't find how to customize 'imageCaptureCameraPreviewStep'. May you please give me a quick example?
Let's say, I need to move 'recapturebutton' all the way up, next to "backButton", or make 'imageCaptureView' 20% smaller of it's original size

**Comment by srinathtm-apple** [comment]
@AndriiDoroshko ResearchKit is a UI framework and if you want to customize the UI to suit your needs, you will have to make some changes in the framework.

For example, if you want to make imageCaptureView 20% smaller, you can try modifying the constraints in ORKImageCaptureStepViewController.m - setUpConstraints()

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
