### ISSUE TITLE
Knee and shoulder range of motion tasks: suggested adjustments to angle calculations

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1084]
I've been testing the range of motion tasks, and noticed that the resulting results for the knee task was the inverse of what it should be (a vertical position for the phone was displaying as 90 degrees, and the 'extended'/'maximum' angle was displaying as 0 degrees).

Also, both the shoulder and the knee tests were sensitive to yaw, which would change the resulting angles if the phone was held upside down, for example (also try spinning a phone 180 degrees while flat on a table surface to see this for the current version).

The following changes to ORKRangeOfMotionStepViewController seemed to sort these problems:

Knee (original):

    ORKRangeOfMotionResult *result = [[ORKRangeOfMotionResult alloc] initWithIdentifier:self.step.identifier];
    result.start = _startAngle;
    result.finish = result.start - _rangeOfMotionAngle;

Knee (modified):

    ORKRangeOfMotionResult *result = [[ORKRangeOfMotionResult alloc] initWithIdentifier:self.step.identifier];
    result.start = 90.0 - _startAngle;
    result.finish = _rangeOfMotionAngle - result.start;

This change should also be applicable to the shoulder task, rendering the current ORKShoulderRangeOfMotionStepViewController as unnecessary:

Shoulder (original):

    ORKRangeOfMotionResult *result = [[ORKRangeOfMotionResult alloc] initWithIdentifier:self.step.identifier];
    result.start = 90.0 - _startAngle;
    result.finish = result.start + _rangeOfMotionAngle;

Shoulder (modified):

    ORKRangeOfMotionResult *result = [[ORKRangeOfMotionResult alloc] initWithIdentifier:self.step.identifier];
    result.start = 90.0 - _startAngle;
    result.finish = _rangeOfMotionAngle - result.start;

**Comment by davwillev** [comment]
Hi All,

In addition to the above modifications, I am trying to modify the Range of Motion tasks so they will work whether the phone is in portrait or landscape orientation. To do so, I added the quartenion definitions for roll and yaw to ORKRangeOfMotionStepViewController.m (as only the definition for pitch was currently written). Please check these are correct:

#define radiansToDegrees(radians) ((radians) * 180.0 / M_PI)
#define allOrientationsForPitch(x, w, y, z) (atan2(2.0 * (x*w + y*z), 1.0 - 2.0 * (x*x + z*z)))

//Added definition for roll (y-axis rotation)
#define allOrientationsForYaw(x, w, y, z) (atan2(2.0 * (y*w + x*z), 1.0 - 2.0 * (y*y + z*z)))

//Added definition for yaw (z-axis rotation)
#define allOrientationsForRoll(x, w, y, z) (asin(2.0 * (x*y + w*z)))


Once the above definitions were added, I tried to modify the existing coding that appears to account for a landscape orientation, by replacing attitude.roll by the quarternion conversion for roll:

/*
 When the device is in Portrait mode, we need to get the attitude's pitch
 to determine the device's angle. attitude.pitch doesn't return all
 orientations, so we use the attitude's quaternion to calculate the
 angle.
 */
- (double)getDeviceAngleInDegreesFromAttitude:(CMAttitude *)attitude {
    if (!_orientation) {
        _orientation = [UIApplication sharedApplication].statusBarOrientation;
    }
    double angle;
    if (UIInterfaceOrientationIsLandscape(_orientation)) {
        //  replaced:      angle = radiansToDegrees(attitude.roll);
        double x = attitude.quaternion.x;
        double w = attitude.quaternion.w;
        double y = attitude.quaternion.y;
        double z = attitude.quaternion.z;
        angle = radiansToDegrees(allOrientationsForRoll(x, w, y, z));
        
    } else {
        double x = attitude.quaternion.x;
        double w = attitude.quaternion.w;
        double y = attitude.quaternion.y;
        double z = attitude.quaternion.z;
        angle = radiansToDegrees(allOrientationsForPitch(x, w, y, z));
    }
    return angle;
}

Unfortunately, the results I am obtaining for range of motion in the landscape orientations are nowhere near correct. Please help!!

**Comment by davwillev** [comment]
**UPDATE:** I have edited the post above, having now swapped around the Roll and Yaw definitions, and it seems to be working: the phone can now be orientated in portrait or landscape and seems to be reporting correct Euler angles for both 'flexion' and 'extension'.

**Comment by srinathtm-apple** [comment]
#1088

**Comment by davwillev** [comment]
Closing as #1088 now merged
