### ISSUE TITLE
Proposal: Is it possible to connect ResearchKit with Apple Health Medical Records?

### ISSUE THREAD

**Issue by teldridge11** [ResearchKit/ResearchKit#1085]
Apple recently came out with medical records support for Health. Is it potentially possible to connect this to ResearchKit for users to anonymously donate their medical records for research purposes?  Probably a long shot, but would be an amazing feature to have.

**Comment by srinathtm-apple** [comment]
Hi @teldridge11 , currently there is no API available for third party apps to query these records from the Health App. So right now, there is not much that we can do with regards to integrating ResearchKit with Health records.
