### ISSUE TITLE
Switching ORKWeightAnswerFormat to use keypad

### ISSUE THREAD

**Issue by dukemike** [ResearchKit/ResearchKit#1087]
I'd like to have the `ORKWeightAnswerFormat` steps use the keypad like `ORKNumericAnswerFormat`. Can anyone point me in the right direction for making this type of change?

This will eliminate the endless scrolling that occurs when the default value is not near the person's actual weight and also remove a perceived "healthy" or "preferred" weight being the default value. These are issues for a project I am working on where most of the users are severely obese.

**Comment by srinathtm-apple** [comment]
@dukemike - This is an excellent point, we are current using a picker in ORKWeightAnswerFormat. We can possibly add a new initializer which allows you to enter the number from a keypad directly. I will look into this change and get back to you soon..

**Comment by ninoguba** [comment]
I agree another initializer would be handy to present it with an ORKNumericAnswerFormat.

@dukemike  As an alternative, you can also use ORKHealthKitQuantityTypeAnswerFormat if you're pulling data from HealthKit.  If not, you can simply just use ORKNumericAnswerFormat for your "generic" weight step.

**Comment by srinathtm-apple** [comment]
@dukemike

I looked at the current implementation for weightAnswerFormat, it is heavily skewed towards using a picker. A lot of the functionality that the different initializers provide is centered around the picker as well. Adding a new initializer might be straight forward, but it would just mean that we would end up creating an instance of ORKNumericAnswerFormat internally and passing it around.

This makes me think that @ninoguba 's suggestion of a generic weight step might be better.

What are your thoughts on this?

**Comment by dukemike** [comment]
Using an `ORKNumericAnswerFormat` will work but I'll have to manage the unit magic myself :(

Thanks for looking into it. It would be helpful to understand why Health.app uses a keypad and to determine if RK should apply the same mentality.

**Comment by dukemike** [comment]
Using `ORKHealthKitQuantityTypeAnswerFormat` also works but when the keypad is displayed the unit is hidden.

**Comment by ninoguba** [comment]
The Medical ID in the Health app uses a picker for weight and height, which became the basis of this, also for consistency and ease of entry.

The hiding unit text is a bug that someone recently reported.

**Comment by srinathtm-apple** [comment]
#1090 

@ninoguba @dukemike would be great if you could review the fix for unit being hidden

**Comment by dukemike** [comment]
@srinathtm-apple That worked for me. Thanks!

**Comment by srinathtm-apple** [comment]
Closing this issue as I believe we have some resolution here.
