### ISSUE TITLE
Help with Navigation using Forms

### ISSUE THREAD

**Issue by greta-ramaneckaite** [ResearchKit/ResearchKit#1091]
Hi,

I'm writing a survey app that is also navigable depending on the answers the user selects. I'm using a form for one question that is supposed to be navigable, but it does not seem to work. The questions are displayed correctly and Xcode doesn't show any errors or issues with the code. I used almost the same navigation for another question and it worked perfectly, but it seems to not function at all for this specific navigation.

In the fun19QuestionStep or fun20QuestionStep if the user picks a value 1 or 2 in the scale, they are supposed to skip the sQuestionStep question and go straight to funOtherQuestionStep. This doesn't seem to work with non of the values available to select. It just navigates to sQuestionStep either way.

**Question declaration:**
`
    let scaleForm = ORKFormStep(identifier: "ScaleForm", title: "...", text: "???")
    let funAnswerFormat = ORKScaleAnswerFormat.init(maximumValue: 4, minimumValue: 1, defaultValue: 1, step: 1, vertical: false, maximumValueDescription: "Strongly Agree", minimumValueDescription: "Strongly Disagree")
    let fun2AnswerFormat = ORKScaleAnswerFormat.init(maximumValue: 4, minimumValue: 1, defaultValue: 1, step: 1, vertical: false)
    
    let fun1QuestionStepTitle = "... to "
    let fun1QuestionStep = ORKFormItem(identifier: "Fun1ChoiceQuestionStep", text: fun1QuestionStepTitle, answerFormat: funAnswerFormat)
    
    let fun2QuestionStepTitle = "... because "
    let fun2QuestionStep = ORKFormItem(identifier: "Fun2ChoiceQuestionStep", text: fun2QuestionStepTitle, answerFormat: fun2AnswerFormat)

    let fun18QuestionStepTitle = "... because "
    let fun18QuestionStep = ORKFormItem(identifier: "Fun18ChoiceQuestionStep", text: fun18QuestionStepTitle, answerFormat: fun2AnswerFormat)
    
    let fun19QuestionStepTitle = "... as a way "
    let fun19QuestionStep = ORKFormItem(identifier: "Fun19ChoiceQuestionStep", text: fun19QuestionStepTitle, answerFormat: fun2AnswerFormat)
    
    let fun20QuestionStepTitle = "... as an attempt"
    let fun20QuestionStep = ORKFormItem(identifier: "Fun20ChoiceQuestionStep", text: fun20QuestionStepTitle, answerFormat: fun2AnswerFormat)
    
    scaleForm.formItems = [
        fun1QuestionStep, fun2QuestionStep, fun18QuestionStep, fun19QuestionStep, fun20QuestionStep
    ]
    steps += [scaleForm]
    
    // 4. Question that is supposed to be skippable
    let sQuestionStepTitle = "Previously"
    let sChoices = [
        ORKTextChoice(text: "Yes", value: 0 as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "No", value: 1 as NSCoding & NSCopying & NSObjectProtocol),
        ORKTextChoice(text: "I am not sure", value: 2 as NSCoding & NSCopying & NSObjectProtocol)
    ]
    let sAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: sChoices)
    let sQuestionStep = ORKQuestionStep(identifier: "SChoiceQuestionStep", title: sQuestionStepTitle, answer: sAnswerFormat)
    steps += [sQuestionStep]
    
    // "Other" option for Q3
    let funOtherAnswerFormat = ORKTextAnswerFormat(maximumLength: 300)
    funOtherAnswerFormat.multipleLines = true
    let funOtherQuestionStepTitle = "Are there other reason?"
    let funOtherQuestionStepText = "If not, please skip this question"
    let funOtherQuestionStep = ORKQuestionStep(identifier: "FunOtherQuestionStep", title: funOtherQuestionStepTitle, text: funOtherQuestionStepText, answer: funOtherAnswerFormat)
    steps += [funOtherQuestionStep]
`

**Question Navigation**
For each question I added navigation since it's supposed to redirect if either question is answered correctly.

`
    let predicateS1 = ORKResultPredicate.predicateForScaleQuestionResult(with: ORKResultSelector(stepIdentifier: scaleForm.identifier, resultIdentifier: fun19QuestionStep.identifier), maximumExpectedAnswerValue: 2)
    let ruleS1 = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateS1, funOtherQuestionStep.identifier)])
    task.setNavigationRule(ruleS1, forTriggerStepIdentifier: fun19QuestionStep.identifier)
    
    let predicateS2 = ORKResultPredicate.predicateForScaleQuestionResult(with: ORKResultSelector(stepIdentifier: scaleForm.identifier, resultIdentifier: fun20QuestionStep.identifier), maximumExpectedAnswerValue: 2)
    let ruleS2 = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateS2, funOtherQuestionStep.identifier)])
    task.setNavigationRule(ruleS2, forTriggerStepIdentifier: fun20QuestionStep.identifier)

`

**Comment by srinathtm-apple** [comment]
@greta-ramaneckaite 

you were pretty close! Only change required is -

task.setNavigationRule(ruleS1, forTriggerStepIdentifier: **scaleForm**.identifier)
and 
task.setNavigationRule(ruleS2, forTriggerStepIdentifier: **scaleForm**.identifier)

The triggerStepIdentifier should be the formStep and not the formItem

**Comment by greta-ramaneckaite** [comment]
@srinathtm-apple 

Oh, thank you so much! I should have read more about task navigation rules.

**Comment by greta-ramaneckaite** [comment]
After fixing it, it seems that only fun20QuestionStep navigation works.  Is it confused by 2 very similar navigations? Is there an overwrite that I missed?

**Comment by srinathtm-apple** [comment]
@greta-ramaneckaite 

Per the documentation -

"The rule will be used to obtain a new destination step when the participant goes forward from the trigger step. You cannot add two different navigation rules to the same trigger step identifier; only the most recently added rule is kept."

Looks like you might need to alter your logic a bit here.

**Comment by greta-ramaneckaite** [comment]
I see, yeah I'll try to go around it then, thanks!

**Comment by greta-ramaneckaite** [comment]
Wouldn't then the best option be to combine both rules using NSCompoundPredicate? Since the navigation has to be that either fun19QuestionStep or fun20QuestionStep has a value less than 2. However, I'm not that familiar with how to use NSCompoundPredicate.

**Comment by srinathtm-apple** [comment]
@greta-ramaneckaite 

You don't need NSCompundPredicate, you can just add multiple (predicate, stepIdentifier) tuples.

let predicateS1 = ORKResultPredicate.predicateForScaleQuestionResult(with: ORKResultSelector(stepIdentifier: scaleForm.identifier, resultIdentifier: fun19QuestionStep.identifier), maximumExpectedAnswerValue: 2)
        let predicateS2 = ORKResultPredicate.predicateForScaleQuestionResult(with: ORKResultSelector(stepIdentifier: scaleForm.identifier, resultIdentifier: fun20QuestionStep.identifier), maximumExpectedAnswerValue: 2)
        let ruleS1 = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateS1, funOtherQuestionStep.identifier), (predicateS2, funOtherQuestionStep.identifier)])
        task.setNavigationRule(ruleS1, forTriggerStepIdentifier: scaleForm.identifier)

**Comment by greta-ramaneckaite** [comment]
@srinathtm-apple 

It doesn't work that way, if you do a tuple with both predicates the rule will only work if both questions are answered with values higher than 2. It won't work if only one of the answers is with a value higher than 2. Isn't there an option to have if either value is picked the rule would apply?
