### ISSUE TITLE
Not Getting Instructions In Range of Motion AT

### ISSUE THREAD

**Issue by Dipaksace** [ResearchKit/ResearchKit#1099]
I am creating  an instance of task of Both Knee and Shoulder motion like below
` let task = ORKOrderedTask.kneeRangeOfMotionTask(withIdentifier: self.identifier, limbOption: ORKPredefinedTaskLimbOption.left, intendedUseDescription: self.intendedUseDescription, options: ORKPredefinedTaskOption.init(rawValue: 0))
`
 `let task = ORKOrderedTask.shoulderRangeOfMotionTask(withIdentifier: self.identifier, limbOption: ORKPredefinedTaskLimbOption.right, intendedUseDescription: self.intendedUseDescription, options: ORKPredefinedTaskOption.init(rawValue: 0))`

But the Instructions for each AT are not appearing as displayed in documentation of ResearchKit.

**Comment by srinathtm-apple** [comment]
@Dipaksace - can you please elaborate on what "Instructions" are not appearing?

Also, did you get a chance to look at the implementation for shoulder and knee range of motion active tasks in the ORKCatalog project? Specifically in the TaskListRow.swift file

**Comment by Dipaksace** [comment]
@srinathtm-apple I'm have initialized the same way in TaskListRow file but the instruction step is asking me to provide for Title and text for each step, even though I have not excluded instruction in initialization.Do I have to manually add instruction steps in the both Range of motion tasks?

**Comment by srinathtm-apple** [comment]
@Dipaksace what instructionStep are you referring to here? Can you please provide a more comprehensive code snippet?

This is all the code that is required to present the range of motion active task - 

let task = ORKOrderedTask.shoulderRangeOfMotionTask(withIdentifier: "identifier", limbOption: .left, intendedUseDescription: nil, options: ORKPredefinedTaskOption.init(rawValue: 0))
let vc = ORKTaskViewController(task: task, taskRun: nil)
self.present(vc, animated: true, completion: nil)

**Comment by Dipaksace** [comment]
![simulator screen shot - iphone 6s - 2018-03-30 at 11 59 35](https://user-images.githubusercontent.com/25100519/38241914-114f143c-3751-11e8-9924-b08fc5bd249e.png)
![simulator screen shot - iphone 6s - 2018-03-30 at 11 59 37](https://user-images.githubusercontent.com/25100519/38241915-119ce3c4-3751-11e8-8098-e2c42c5462bd.png)
![simulator screen shot - iphone 6s - 2018-03-30 at 11 59 39](https://user-images.githubusercontent.com/25100519/38241916-11e9d95e-3751-11e8-9c25-1b99f59672a5.png)
![simulator screen shot - iphone 6s - 2018-03-30 at 11 59 41](https://user-images.githubusercontent.com/25100519/38241918-123d160a-3751-11e8-9300-8c5f0b425a85.png)
![simulator screen shot - iphone 6s - 2018-03-30 at 11 59 46](https://user-images.githubusercontent.com/25100519/38241919-128d1a88-3751-11e8-99f4-9ad11265aacb.png)

You can see for the Default Instruction on Knee Range of Motion Task

**Comment by srinathtm-apple** [comment]
@Dipaksace a fix for this issue was submitted to master - https://github.com/ResearchKit/ResearchKit/pull/1074

Please make sure you pull the latest changes from master.

**Comment by Dipaksace** [comment]
@srinathtm-apple Thank you for the prompt reply.My bad we actually forgot to take pull in our private repository that we are referencing.
