### ISSUE TITLE
[Request] ResearchKit CocoaPod

### ISSUE THREAD

**Issue by steakknife** [ResearchKit/ResearchKit#11]
This would enable seamless version & dependency management in larger production-prospective projects.

**Comment by steakknife** [comment]
https://github.com/dasmer/ResearchKit/commit/208249a3b9cc6dd09fbf451d45d9c75dc178d6c5#diff-917bbaa74a0da81f8c9cac4d12507484

**Comment by matteocrippa** [comment]
yep it would be very useful to have it in cocoapods

**Comment by steakknife** [comment]
@dasmer 's on it.

[Here's the new way to submit a Pod](http://blog.cocoapods.org/CocoaPods-Trunk/) using Trunk

**Comment by natanrolnik** [comment]
Already a Pull-Request #5

**Comment by dasmer** [comment]
Yep @jwe-apple left some comments. Working on it now :smile:

**Comment by francesco-garcia-movile** [comment]
Pull request #5 was already merged!

**Comment by fpg1503** [comment]
Pull request #5 was already merged!

**Comment by steakknife** [comment]
Good work, almost there.

This app Podspec entry should work to use master:

    pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git'

**Comment by steakknife** [comment]
... But probably want to submit it officially too.

**Comment by jwe-apple** [comment]
Have submitted the podspec officially. Let us know if issues arise with it.

**Comment by simonbromberg** [comment]
I installed via Cocoapods into a swift project and opened up the xcworkspace file, but whenever I try to reference ResearchKit (e.g. ORKInstructionStep, or import ResearchKit at the top) I get undefined symbol errors / no such module ResearchKit. Do I need to set up a bridging header to actually get it to work? Something else?

**Comment by steakknife** [comment]
@simonbromberg Did you close the xcode *Project* and open the cocoapod-generated *Workspace* after running `pod` commands?

**Comment by simonbromberg** [comment]
Yes, as I said I opened the xcworkspace file.

**Comment by steakknife** [comment]
Follow directions for bridge headers [here](https://medium.com/@stigi/swift-cocoapods-da09d8ba6dd2).

**Comment by simonbromberg** [comment]
OK, that's what I was asking. Wasn't sure if I needed the bridging header or not.
