### ISSUE TITLE
Refactor layout code

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#110]
Layout code for most of the views is currently a bit over the place. Consider doing some refactoring to make it more homogenous and easier to maintain.

I don't have any specific suggestions right now, but it certainly feels like there is room for simplification.

**Comment by jwe-apple** [comment]
This is a bit of an umbrella issue. Specific tasks should at the least be separate PR's, happy to have multiple PR's reference this.

Things we've been thinking about:
- Further refactor form and step cells; there's still some duplication going on here.
- Simplify the header view. It's common across almost all templates, and its layout code seems more complicated than it needs to be.
- Look at the vertical container view. Consider splitting its implementation. Currently it creates a significant view structure within it and manages that entire structure. Consider giving some control to one or more of its subviews.

**Comment by rsanchezsaez** [comment]
Another item:
 - Try to reuse more code between `ORKVerticalContainerView` and `ORKTableViewContainer` (specifically, on-screen keyboard handling).

**Comment by umerkhan-apple** [comment]
@rsanchezsaez #343 has been merged. Is it okay to close this issue?
