### ISSUE TITLE
Add ORKTableStep to a survey

### ISSUE THREAD

**Issue by mohammed-ali-1** [ResearchKit/ResearchKit#1101]
I need to present some survey questions within a table. Can an ORKTableStep be included inside a survey that has other questions and forms? If the answer is yes, how can I do that? Thanks!

**Comment by srinathtm-apple** [comment]
Hey @mohammed-ali-1 , I think ORKFormStep is what you are looking for. If you want to use ORKTableStep, you should add that as a separate step in a ORKOrderedTask.

**Comment by mohammed-ali-1** [comment]
Hi @srinathtm-apple, thanks for your reply. I apologize for not replying to you earlier as I was on vacation.

I'd like to present something more interesting, like this, to the user:
![screen shot 2018-04-08 at 2 42 28 am](https://user-images.githubusercontent.com/27845458/38460989-a8a98136-3ad6-11e8-8030-160c4aa8aef0.png)

I already use ORKFormStep in my survey, but that is not enough. I think the functionality that I'm looking for requires me to extend ResearchKit. But I'm still new to iOS and Swift, and I don't know how to approach that.

**Comment by ninoguba** [comment]
@mohammed-ali-1 looking at your sample table design, that would be difficult to fit legibly on an iPhone screen when in portrait.  For best usability, I would suggest that you use ORKFormStep for this sample survey.
