### ISSUE TITLE
Add spoken instructions to touchAnywhereStep in range of motion tasks

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1102]
Hi All,
After testing the range of motion tasks with volunteers, several suggested that spoken instructions would be useful to accompany the ORKTouchAnywhereStep as well as the ORKRangeOfMotionStep (see orginal versions of both steps below).

 ```
   NSString *instructionText = ([limbType isEqualToString:ORKLocalizedString(@"LIMB_LEFT", nil)])? ORKLocalizedString(@"KNEE_RANGE_OF_MOTION_TOUCH_ANYWHERE_STEP_INSTRUCTION_LEFT", nil) : ORKLocalizedString(@"KNEE_RANGE_OF_MOTION_TOUCH_ANYWHERE_STEP_INSTRUCTION_RIGHT", nil);
    ORKTouchAnywhereStep *touchAnywhereStep = [[ORKTouchAnywhereStep alloc] initWithIdentifier:ORKTouchAnywhereStepIdentifier instructionText:instructionText];
    ORKStepArrayAddStep(steps, touchAnywhereStep);
    
    ORKDeviceMotionRecorderConfiguration *deviceMotionRecorderConfig = [[ORKDeviceMotionRecorderConfiguration alloc] initWithIdentifier:ORKDeviceMotionRecorderIdentifier frequency:100];
    
    ORKRangeOfMotionStep *kneeRangeOfMotionStep = [[ORKRangeOfMotionStep alloc] initWithIdentifier:ORKKneeRangeOfMotionStepIdentifier limbOption:limbOption];
    kneeRangeOfMotionStep.title = ([limbType isEqualToString: ORKLocalizedString(@"LIMB_LEFT", nil)])? ORKLocalizedString(@"KNEE_RANGE_OF_MOTION_SPOKEN_INSTRUCTION_LEFT", nil) :
    ORKLocalizedString(@"KNEE_RANGE_OF_MOTION_SPOKEN_INSTRUCTION_RIGHT", nil);
    
    kneeRangeOfMotionStep.spokenInstruction = kneeRangeOfMotionStep.title;
    kneeRangeOfMotionStep.recorderConfigurations = @[deviceMotionRecorderConfig];
    kneeRangeOfMotionStep.optional = NO;
    
    ORKStepArrayAddStep(steps, kneeRangeOfMotionStep);
```
I have tried to get this working by trying to implement `touchAnywhereStep.spokenInstruction = touchAnywhereStep.title;` but so far have failed so successfully declare `touchAnywhereStep.title` in the above original code;. Can anybody help here?
Thanks

**Comment by srinathtm-apple** [comment]
Hey @davwillev , I have submitted a fix for this issue. I will merge this into master once folks have reviewed it.

It is a super minor change, so spokenInstruction won't work until a 'start' has been called on a task. Setting the shouldStartTimerAutomatically property to 'YES' will call 'start' as soon as the instruction step is presented. So now if you add something to spokeInstruction (exactly what you have done above), it should work.

Thanks a bunch for pointing this out!

**Comment by davwillev** [comment]
It works, @srinathtm-apple !
Thanks for that :)

**Comment by srinathtm-apple** [comment]
Closing this as the fix has been merged into master.
