### ISSUE TITLE
Provide 1024x1024 icons for all sample apps

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#1108]
Xcode 9 requires 1024x1024 icons for all apps, or it will show the following warning:

<img width="1552" alt="screenshot 2018-04-04 22 44 27" src="https://user-images.githubusercontent.com/444313/38349029-048e91e6-385a-11e8-87aa-6a5a752a7cc7.png">

Provide 1024x1024 icons for all sample apps.

**Comment by rsanchezsaez** [comment]
@srinathtm-apple Could you send a friendly ping to the design team regarding this? :-)

**Comment by simon-apple** [comment]
Closing this out since this has been addressed.
