### ISSUE TITLE
Crash In Sustained Phonation AT

### ISSUE THREAD

**Issue by Dipaksace** [ResearchKit/ResearchKit#1110]
Hello team ,
While working on audioTask I am getting this crash after clicking the GetStarted button in second screen of the same Active Task.
Crash is caused in ORKAudioRecorder.m file at line no 96.
```
Terminating app due to uncaught exception 'NSDestinationInvalidException', reason: 'audioRecorder requires an output directory'
*** First throw call stack:
(0x184d85228 0x183f4c5ec 0x101cc199c 0x101c9a7c0 0x101c9abb8 0x101c99744 0x102dad1d4 0x102dad194 0x102db1d24 0x184d2d650 0x184d2b1a8 0x184c4b488 0x186c11020 0x18f0e5cc0 0x1011eb7e8 0x1846e9fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
P.S I have used the same initializer as mention ORKCatalog>TaskListRow.swift file

**Comment by srinathtm-apple** [comment]
@Dipaksace before presenting the ORKTaskViewController with the initialized audioTask, please make sure that you have provided a path for the outputDirectory property.

**Comment by Dipaksace** [comment]
@srinathtm-apple Thanks, it worked.Can you please mention all of this in AT doc or somewhere else , I had no clue of this.
