### ISSUE TITLE
New image 'map' answer format for RK?

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1118]
Hi All,

Unless I am missing something, RK does not yet have an image 'map' answer format, such as this: https://github.com/ctsit/imagemap

This would be a very useful addition for tracking location of pain, skin lesions, etc.

I have no coding skills, but would be very keen to work with someone that does in order to make this happen.

Best wishes

**Comment by dukemike** [comment]
This appears to be related to #805 and #1030

**Comment by davwillev** [comment]
Certainly #805 looks similar

**Comment by ninoguba** [comment]
@davwillev can we close this to remove duplication?  Let's concentrate all discussion about this feature request to #805 since it is the same or very similar to what you're asking here.

**Comment by davwillev** [comment]
Will do!
