### ISSUE TITLE
Spoken Instruction for a ORKInstructionStep?

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1130]
Hi All,

I'm trying to get spoken instructions to work on text from a ORKInstructionStep (on the range of motion tasks), but when I add the following

`instructionStep1.spokenInstruction = instructionStep1.detailText;`

Xcode returns the error, 'Property 'spokeninstruction' not found on object of type 'ORKInstructionStep'. Am I missing something, or is this not possible?

Thanks in advance for any help

**Comment by ninoguba** [comment]
The spokenInstruction property is currently only available for ORKActiveStep object types so instead of using an ORKInstructionStep, you can use the ORKActiveStep instead.

**Comment by davwillev** [comment]
Thanks for the advice, @ninoguba
