### ISSUE TITLE
How do I require a specific format for an ORKTextAnswerFormat?

### ISSUE THREAD

**Issue by berenyiaustin** [ResearchKit/ResearchKit#1141]
I have an ORKQuestionStep that asks for a participant's name. I need to require first and last name. Is there a parameter for ORKTextAnswerFormat that can require a specific format for the text entry before allowing the user to proceed?

**Comment by ninoguba** [comment]
You will need to collect the first and last name as separate fields/inputs.  Best way is through a ORKFormStep with two ORKFormItems.  You set both ORKFormItems.optional property to FALSE and you set ORKFormStep.optional property to FALSE too.

**Comment by berenyiaustin** [comment]
@ninoguba I'm trying to access the results of an ORKFormStep with the following code 

```
func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        switch reason {
        case .completed:
            let taskResult = taskViewController.result.results
            
            for stepResults in taskResult! as! [ORKStepResult]
            {
                for result in stepResults.results!
                {
                    if result.identifier == "NameStep"
                    {
                        print("Found it.")
                    }
                    if result.identifier == "LocationSelectionStep"
                    {
                        let answerResult = result as! ORKChoiceQuestionResult
                        let answer = answerResult.choiceAnswers
                        locationSelectionResult = answer?.first
                        
                    }
...
```

I've verified that the identifier of the ORKFormStep is `"NameStep"` but the print statement is never called. Is there an extra step to identifying the results of an ORKFormStep?

**Comment by ninoguba** [comment]
You have two for-loops there.  First is iterating through the "steps" and the second is iterating through the "results" on the step.  So if you're looking for the "NameStep" your if statement should be: 

```
if stepResults.identifier == "NameStep"
{
    print("Found it.")
}
```

**Comment by berenyiaustin** [comment]
@ninoguba That did the trick. Thanks.
