### ISSUE TITLE
[Tests] ResearchKit and ORKTest unit tests fail

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#1151]
The *ResearchKit* and *ORKTest* (serialization) unit tests are failing.

**Comment by bgannin** [comment]
I've started working through these papercuts, it's a bit of an iceberg.

**Comment by bgannin** [comment]
Current status: down from 26 to 9 (some were nested/multiple)

**Comment by bgannin** [comment]
Current status: down to 3 failures but it's a rotating series of serialization/test data issues that mask each other. Will hopefully get the remainder tidied up tomorrow 🤞

**Comment by bgannin** [comment]
For some reason ORKShoulderRangeOfMotionStep and ORKNumericAnswerFormat are being difficult in the JSON serialization test only. I might start a PR tomorrow to get additional eyes to help sort out the problem rather than holding up the rest of the test improvements.
