### ISSUE TITLE
[Doc] How is docs/Charts and docs/ChartsAndGraphs Different

### ISSUE THREAD

**Issue by ysf199711** [ResearchKit/ResearchKit#1154]
By looking through docs, it looks like docs/Charts and docs/ChartsAndGraphs contain the same content. Is it a duplicate?

**Comment by srinathtm-apple** [comment]
@ysf199711 Thanks for bringing this up, looks like it is a duplicate. We should consider removing one of those directories, what are your thoughts on this?

**Comment by ysf199711** [comment]
I would say that the original author would know what is going on. How do we reach them?

**Comment by srinathtm-apple** [comment]
@ysf199711 - we looked into this some more and will fix this when we push to stable, which will happen soon.

**Comment by srinathtm-apple** [comment]
This has been resolved, we now only have doc/ChartsAndGraphs.
