### ISSUE TITLE
Allow customization of fonts in charts

### ISSUE THREAD

**Issue by Jonge** [ResearchKit/ResearchKit#1158]
Hello,

Would it be possible to allow font customization in charts? I have found the following pieces of code. 

ORKGraphChartView.m:
```
- (void)updateContentSizeCategoryFonts {
    _xAxisView.titleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
    _yAxisView.titleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption2];
    _scrubberLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
    _noDataLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline];
}
```

ORKPieChartView.m:
```
- (void)updateContentSizeCategoryFonts {
    _titleTextView.titleLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline];
    _titleTextView.textLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    _titleTextView.noDataLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline];
    _pieView.percentageLabelFont = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption2];
    _legendView.labelFont = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
}
```

I believe just moving those to separate properties (and calling `updateContentSizeCategoryFonts` after they're set) should be enough.

Thank you!

**Comment by Jonge** [comment]
Sure! Will try to look at this soon.

**Comment by bgannin** [comment]
I'm working on a PR for this currently. Should have something tonight in ORKTest to demonstrate.

**Comment by bgannin** [comment]
API changes (including IB support) are done. Next up is wiring into appropriate demo areas.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
