### ISSUE TITLE
iOS 12 / Reading health data crash

### ISSUE THREAD

**Issue by invinciible** [ResearchKit/ResearchKit#1159]
Hi ,
I'm currently on iOS 12 beta on my iPhone and updated app with RK 2.0 which works fine on iOS 11.xx however on iOS 12 it's crashing while reading data from HealthKit with the healthKit permission error which is already been mentioned in the info.plist .

**Comment by srinathtm-apple** [comment]
Hey @invinciible , can you please provide us with some more information - logs or repro steps so that we can zero-in on what's going on here?

**Comment by invinciible** [comment]
HI ,
Here's my code 
![screen shot 2018-08-07 at 2 41 36 pm](https://user-images.githubusercontent.com/25017046/43766482-266ff9aa-9a50-11e8-8533-978353876c32.png)

& on iOS 11.4.1 iPhone 6s it's working fine ,however same code crashing on iOS 12 iPhone 5s

Crash logs :

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSHealthShareUsageDescription must be set in the app's Info.plist in order to request read authorization for the following types: HKCharacteristicTypeIdentifierBiologicalSex, HKCharacteristicTypeIdentifierBloodType, HKCharacteristicTypeIdentifierDateOfBirth'
*** First throw call stack:
(0x1a0f91490 0x1a015ea40 0x1a0e963ec 0x1b3e25684 0x1b3e251d0 0x1b3e24a34 0x1b3e24780 0x101207168 0x1ce405b50 0x1ce406234 0x1ce02e408 0x1ce02e534 0x1ce036444 0x1ce70379c 0x1ce704ca0 0x1ce7048b4 0x1ce7005d8 0x1ce3ebfbc 0x1a5719f38 0x1a571eec8 0x1a567df00 0x1a56ac934 0x1a55ed390 0x1a11f09e4 0x1a0ef88a4 0x1a0f201c8 0x1a0f1f914 0x1a0f1a6cc 0x1a0f19b50 0x1a3189584 0x1cdd3ed68 0x100d4b05c 0x1a09da188)
libc++abi.dylib: terminating with uncaught exception of type NSException

**NSHealthShareUsageDescription** is already their in info.plist

**Comment by srinathtm-apple** [comment]
Hey @invinciible , I am unable to reproduce this issue from my side on iOS 12. I would recommend a few steps -
1) remove and re-add HealthKit capabilities and also re-add NSHealthShareUsageDescription in Info.plist
2) try updating to the latest iOS 12 beta

Let me know how that goes.

**Comment by invinciible** [comment]
Hi,
Already tried both the solutions you mentioned before posting here.
I'm on latest iOS 12 beta

**Comment by invinciible** [comment]
Hi ,
I tried Running ORKCatalog demo app. it worked fine on iOS 12.
Tried debugging the issue again in my app and glad I was able to resolve it.

I was using short description as a value in info.plist .
I updated that with long string as a description and no crash it was able to read the information from HealthKit.

Thank you

**Comment by victormanuelfrancodev** [comment]
I have the. same problem =(

**Comment by invinciible** [comment]
Put long description for NSHealthShareUsageDescription in info.plist file

**Comment by dmatora** [comment]
Thank you! Had same problem

**Comment by wawacai** [comment]
Thank you

**Comment by victormanuelfrancodev** [comment]
thank you
