### ISSUE TITLE
invalid import in ORKConsentDocument_Private.h?

### ISSUE THREAD

**Issue by hococoder** [ResearchKit/ResearchKit#1163]
I think there may be an incorrect import in ORKConsentDocument_Private.h.  It is currently `#import "ORKConsentDocument.h"` but i think it should be `#import <ResearchKit/ORKConsentDocument.h>` - at least that is what I needed to change it to in order to compile.

**Comment by srinathtm-apple** [comment]
@hococoder - you are right, this should be resolved once #1162 is approved and merged.

**Comment by hococoder** [comment]
Ah ok great!  I figured it would be somewhere in the pipeline to get fixed, just wanted to make sure you were all aware of it.  Thanks so much for the feedback!
