### ISSUE TITLE
How to remove the highlight of the last label on x-axis in charts?

### ISSUE THREAD

**Issue by ethanyuxinzhang** [ResearchKit/ResearchKit#1164]
<img width="333" alt="2018-08-28 02 34 41" src="https://user-images.githubusercontent.com/7537190/44672203-1d06af00-aa6b-11e8-9032-467852e59180.png">

I wish to remove the highlight of the last label on the x-axis. 

Here are my codes for the titles:

func graphChartView(_ graphChartView: ORKGraphChartView, titleForXAxisAtPointIndex pointIndex: Int) -> String? {
        
        switch pointIndex {
        case 0:
            return "0h"
        case 3:
            return "3h"
        case 6:
            return "6h"
        case 9:
            return "9h"
        case 12:
            return "12h"
        case 15:
            return "15h"
        case 18:
            return "18h"
        case 21:
            return "21h"
        default:
            return ""
        }
    }

**Comment by srinathtm-apple** [comment]
@ethanyuxinzhang - in ORKXAxisView.m : 172 - 179

Remove the if-else block and replace with - label.textColor = self.tintColor;

That should do the trick.

**Comment by frogg** [comment]
@srinathtm-apple yes that works; but it's a bit weird that I have to change code in the Framework itself to make this work.
It would be great if this would be exposed via an API.
I am happy to help here and to integrate that change in a pull request.
To make that API useful it would be great to know for me what this circle is supposed to visualize in the first place.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
