### ISSUE TITLE
ResearchKit/ResearchKit/Consent/ORKConsentDocument_Private.h:33:9: 'ORKConsentDocument.h' file not found

### ISSUE THREAD

**Issue by boscoybarra** [ResearchKit/ResearchKit#1165]
Xcode unable to build die to unfound ORKConsentDocument.h

Xcode Version: 9.4.1

ResearchKit/ResearchKit/Consent/ORKConsentDocument_Private.h:33:9: 'ORKConsentDocument.h' file not found

**Comment by srinathtm-apple** [comment]
@boscoybarra , we just merged in an existing PR which had the fix for this - #1162 

But still, thanks a bunch for calling this out and submitting a PR as well!
