### ISSUE TITLE
Request: Add "sectionWillAppear" delegate method to VisualConsentStepViewController

### ISSUE THREAD

**Issue by mhohmann** [ResearchKit/ResearchKit#1171]
Would there be an option to add a `ORKVisualConsentStepViewControllerDelegate` protocol with the functionality to perform an action when a specific consent section appeared?

Background: I implemented TTS for all boarding steps in my application, as the population of my study potentially has bad eyesight. While this is possible for regular steps through the `ORKTaskViewControllerDelegate` protocol and the `stepViewControllerWillAppear` method, all visual consent sections are treated as a single step, therefore this method is only called once at the beginning. 

Alternatively, a more general `contentDidChangeForStep` method could be added to the `ORKTaskViewControllerDelegate` protocol, to allow for a more fine-grained response to events within any step?

If there is any existing option that I am missing, please let me know.

**Comment by bgannin** [comment]
This seems quite reasonable to me based on your use case and the structure of the class. @srinathtm-apple What do you think about the addition of this delegate and invoking it at the end of -doShowViewController:direction:animated:completion: prior to the next page actually being set?

**Comment by simon-apple** [comment]
Thanks for the feedback! `ORKVisualConsentStepViewController` was since removed from ResearchKit. `ORKWebViewStep` is now used to present consent forms. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
