### ISSUE TITLE
Subspec for only the Charts components

### ISSUE THREAD

**Issue by DreamingInBinary** [ResearchKit/ResearchKit#1172]
I'm interested in using Research Kit solely for its graphing components. Is there a subspec that supports this? Apologies if I missed this already.

As it stands, you'd need to manually download RK, yank the graphs out and then figure out all the other files that they reference to get things to build. That can also lead to issues [like this one](https://github.com/ResearchKit/ResearchKit/issues/734).

It's such a well done, robust set of controls that a lot of developers could make use of, and not to mention that `UIKit` has nothing even remotely close to charting components. 

Thanks for all of your hard work on RK!

**Comment by srinathtm-apple** [comment]
@DreamingInBinary - this is currently not supported. But you are right, it will be interesting to explore options for facilitating something like this. 

Do you have any specific approach in mind?

**Comment by DreamingInBinary** [comment]
It would be an interesting challenge as is. Due to the many imports involved with the charts, it's quite difficult to abstract it out from the rest of RK. For the time being, I ended up just linking the embedded framework to access the charts. Though, it does feel a bit heavy since I'm not using anything else in RK, but I would take that trade off to have these components in my app. 

I think this is worth exploring more, and I'm happy to help if it's something others would find useful as well.

**Comment by Jonge** [comment]
I'm also using only the chart module from ResearchKit, and also would like to see this.

**Comment by DreamingInBinary** [comment]
I've done this locally, but I can see why they don't support it as all of the charts import a lot of other files (ORKSkin/Accessibility Functions/etc). It only took about an hour to get it ripped out of RK, it wasn't too bad. If you only want the charts, I would recommend going this way as including all of RK for the charts isn't quite worth the trade off for a number of reasons.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
