### ISSUE TITLE
ORKCatalog keeps reporting SIGABRT error

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1173]
Hi All,

I'm trying to test out three new range of motion tasks that have previously worked fine when added to ORKCatalog. Recently, however, I keep getting a fatal SIGABRT error when attemptimg to load one of these new tasks.

I've tried reloading the tasks onto the new stable version of RK, and the same error is occurring. The output relating to the error states: Terminating app due to uncaught exception 'NSGenericException', reason: 'Each step should have a unique identifier'

Here is an image of the error in Xcode:
<img width="594" alt="screen shot 2018-09-13 at 18 47 14" src="https://user-images.githubusercontent.com/35876659/45505837-8da90d80-b785-11e8-88c8-5a4b131f546b.png">

I have re-checked the code several times and can't see why this is occurring. Please help!

Thanks

**Comment by srinathtm-apple** [comment]
Hey @davwillev , looks like you are trying to add steps that were created using the same identifier. Can you double check to verify if all the steps are getting a unique identifier?

**Comment by davwillev** [comment]
Thanks @srinathtm-apple 
I used an iterative process and found it was due to an image that I inserted. I'll close the post now :)
