### ISSUE TITLE
Fitness task step images change position after transition

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#118]
When transitioning to a an `ORKFitnessStep`'s from a previous one. The image (if any) moves to a higher position after the transition finishes. This causes a visual glitch.

This happens on *iPhone 5* and *6* screen sizes. *iPhone 4* screen size is not affected. It happens on *stable* as well, so it isn't a recent regression.

**Comment by jwe-apple** [comment]
Sounds like insufficient constraints. What iOS version are you testing on?

**Comment by rsanchezsaez** [comment]
iOS 8.3. It's 100% reproducible on device and simulator (*ORKCatalog*).

**Comment by rsanchezsaez** [comment]
Looks fixed on the *iPhone 6* simulator.

**Comment by jwe-apple** [comment]
Thanks!
