### ISSUE TITLE
Can't sign consent in landscape on iPhone 6

### ISSUE THREAD

**Issue by getaaron** [ResearchKit/ResearchKit#119]
If my iPhone 6 is in landscape when the `ORKConsentReviewStep` appears, the view is too short vertically, which causes vertical scrolling behavior. This makes it impossible to sign.

If I rotate to portrait, then back to landscape, the issue persists.

If I rotate to portrait, sign the form, then back to landscape, the issue no longer persists.

**Comment by rsanchezsaez** [comment]
Confirmed. It happens on *stable* as well.

**Comment by jwe-apple** [comment]
Yep, this is known. In the shipping apps landscape is disabled. If you have a need to actually have rotation enabled, happy to accept a PR.

**Comment by jwe-apple** [comment]
<rdar://problem/20245432>
