### ISSUE TITLE
Stroop Test Active Task shows same start and end time for each test.

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#1190]
In the results files for stroop test active task, the start and end times are the same. It would be very nice if this represented the time it took for the user to respond.

example:
startTime:2018-09-28 18:28:36:860;endTime:2018-09-28 18:28:36:860;color:GREEN;text:BLUE;colorSelected:BLUE

Any ideas?

**Comment by srinathtm-apple** [comment]
@cmetts - how are you querying this value? I am unable to reproduce this on my end.

**Comment by cmetts** [comment]
My apologies  @srinathtm-apple, I was using startDate, endDate instead of startTime, endTime.
