### ISSUE TITLE
Signature doesn't appear on PDF

### ISSUE THREAD

**Issue by getaaron** [ResearchKit/ResearchKit#120]
After capturing a signature, I attempt to apply the signature to the consent document, and then generate a PDF.

The user's name, signature, and date don't appear on the PDF.

I'm pretty sure it's not user error, but here's my code to reproduce the issue.

This code applies the signature and generates the PDF:

    func taskViewController(taskViewController: ORKTaskViewController, didFinishWithReason reason: ORKTaskViewControllerFinishReason, error: NSError?) {
        
        if let signatureResult = taskViewController.result.stepResultForStepIdentifier("consent review step identifier")?.firstResult as? ORKConsentSignatureResult {
            // the cast succeeds
            
            // signatureResult is not nil
            // signatureResult.signature is not nil
            
            signatureResult.applyToDocument(consentDocument)
        }
        
        consentDocument.makePDFWithCompletionHandler { (data, error) -> Void in
            if let data = data where data.length > 0 {
                // data is not nil
                self.PDFData = data
                self.viewPDFButton.hidden = false
            }
        }
        
        taskViewController.dismissViewControllerAnimated(true, completion: nil)
    }

The consent document is successfully generated, but no signature appears on the PDF:

![image](https://cloud.githubusercontent.com/assets/789577/7360629/dfa4df1a-ed12-11e4-998a-cda607537b22.png)

Note that the second signature, as well as the "Participant" string makes it in.

Here's how I create the consent document:

    private var consentDocument: ORKConsentDocument {
        // Create the document
        let consentDocument = ORKConsentDocument()
        consentDocument.title = "Consent to Zombie Research"
        consentDocument.signaturePageTitle = "Consent Signature"
        consentDocument.signaturePageContent = "I agree to participate in this zombie-related research study."

        // Add participant signature
        let participantSignature = ORKConsentSignature(forPersonWithTitle: "Participant", dateFormatString: nil, identifier: "participant signature identifier")
        
        consentDocument.addSignature(participantSignature)
        
        // Add investigator signature for the PDF.
        let investigatorSignature = ORKConsentSignature(forPersonWithTitle: "Zombie Investigator",
            dateFormatString: nil,
            identifier: "investigator signature identifier",
            givenName: "George",
            familyName: "A. Romero",
            signatureImage: UIImage(named: "signature")!,
            dateString: "10/1/1968")
        
        consentDocument.addSignature(investigatorSignature)
        
        // Create "consent sections" in case the user wants more details before giving consent
        let consentOverview = ORKConsentSection(type: .Overview)
        consentOverview.content = "It's important to research zombies so we can get rid of them. Thanks in advance for all of your help researching them."
        
        let consentPrivacy = ORKConsentSection(type: .Privacy)
        consentPrivacy.content = "All information will be strictly confidential, unless a zombie eats your braaaaaaaaains…"
        
        consentDocument.sections = [consentOverview, consentPrivacy]
        
        return consentDocument
    }

Here's how I create the consent review step:

        let signature = consentDocument.signatures!.first as! ORKConsentSignature
        
        let reviewConsentStep = ORKConsentReviewStep(identifier: "consent review step identifier", signature: signature, inDocument: consentDocument)
        
        reviewConsentStep.text = "I love, and agree to perform, zombie research."
        reviewConsentStep.reasonForConsent = "Zombie research is important."

Am I missing something or is this a bug?

**Comment by jwe-apple** [comment]
Yes, unfortunately this is a bit messy, but you have to apply the consent signature result to a copy of the document before running the review step if you want the signature to appear. Try  `[ORKConsentSignatureResult applyToDocument:]`

See "Optionally, Generate a PDF" in https://researchkit.github.io/docs/docs/InformedConsent/InformedConsent.html

**Comment by getaaron** [comment]
Ah, you might want to add "before running the review step" to that doc :)

I tried to do this in `taskViewController:shouldPresentStep:` but this causes a crash:

    func taskViewController(taskViewController: ORKTaskViewController, shouldPresentStep step: ORKStep) -> Bool {
        if step.identifier == "consent review step identifier" {
            if let signatureResult = taskViewController.result.stepResultForStepIdentifier("consent review step identifier")?.firstResult as? ORKConsentSignatureResult {
                // the cast succeeds
                
                // signatureResult is not nil
                // signatureResult.signature is not nil
                
                signatureResult.applyToDocument(consentDocument)
            }
        }
        
        return true
    }

It appears `step` is `nil` when transitioning from `ORKConsentSharingStep` to `ORKConsentReviewStep` but it shouldn't be `nil` according to the method signature.

What's the recommended place to call `applyToDocument:`?

**Comment by getaaron** [comment]
As a feature request, why not automatically apply the signature? Is it expensive?

**Comment by jwe-apple** [comment]
The principle is that the document (and the step) are immutable model objects once the task begins. Mutable things are returned as results. I suppose we could do this at the step view controller level, grabbing both the task result so far and the current step / document, making a copy of the document, and applying the signature. Happy for you to turn this bug into an enhancement bug to attempt this.

**Comment by jwe-apple** [comment]
You know what, looking at this again, this looks like a regression. This *used* to work automatically for presentation (sometime before the open source release). Reclassifying as a bug.

**Comment by jwe-apple** [comment]
Answered too quickly again! Slight confusion on my part, because we used to display the signatures in the mobile version during the consent review, which meant signatures were applied in-line in the consent review step.

The right place to call applyToDocument is after your task is complete, when processing results from the review. That is, in the `taskViewController:didFinishWithReason:` implementation. In that implementation, you should copy the document and apply the signature result.

The main reason we left this is that we feel in most applications the PDF generation will not happen on the mobile device, but instead on a server, partly to limit bandwidth / storage requirements (storing PDF documents is more expensive than storing signature records). The built-in PDF generation can be useful in smaller scale applications, which is why it's there, but it's not the most frequent use case.
