### ISSUE TITLE
appledoc required to build Researchkit but appledoc itself no longer runs under XCode 10

### ISSUE THREAD

**Issue by KsgPhellow** [ResearchKit/ResearchKit#1202]
As the title say, I got the following error when trying to build Researchkit:
"appledoc is required for building ResearchKit's documentation"

After that I installed appledoc as instructed but according to the creator of appledoc, its no longer able to run on XCode 10. As seen here:[https://github.com/tomaz/appledoc/issues/635#issuecomment-434200078](url)

Is it possible to disable the need for appledoc or circumvent this problem?

Thanks.

**Comment by srinathtm-apple** [comment]
@KsgPhellow which scheme were you trying to build against?

AFAIK building the "ResearchKit" scheme shouldn't require appledocs, however the default first scheme for the ResearchKit workspace is "docs" - which will require appledocs.

**Comment by KsgPhellow** [comment]
Hi, 
yeah I tried to build the docs, so my fault on that one.
Nonetheless you should look into this, when someone wants to build the docs part, this wont work under current xcode and swift versions.
