### ISSUE TITLE
Animation for consent review does not fully complete

### ISSUE THREAD

**Issue by mschermann** [ResearchKit/ResearchKit#1205]
Hi, I have just noticed that with the latest build, the animation for consent review does not fully complete (see screenshot). Using the 'go back' chevron breaks the process. 

![img_0324](https://user-images.githubusercontent.com/20361164/47873054-7376cd80-ddcd-11e8-8445-0371f724d887.png)

Seems like that the recent changes to the consent document mess things up.

**Comment by srinathtm-apple** [comment]
@mschermann thanks for pointing this out! we will look into this..

**Comment by srinathtm-apple** [comment]
@mschermann - this should be resolved in latest master right now.
