### ISSUE TITLE
Rotation issues in consent views

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#121]
If you rotate the *iPhone 6* from portrait to landscape in the mid of the consent visual views:
-  Screen layout doesn't update, scrolling is not enabled, and the next button cannot be seen. If you go to the previous screen, the layout updates.
- When the layout updates after switching screens, the video animation view layout is not updated, so the animation and the static images no longer match.

Happens in *stable* as well.

**Comment by jwe-apple** [comment]
Yep. Rotation not enabled in the shipping apps, but we need it for iPad.

**Comment by getaaron** [comment]
Interesting. Do you think it's significant enough to add to the "limitations" section of the technical overview doc?

**Comment by jwe-apple** [comment]
No - I think we should fix the issue, since we want things to work on the iPad.

**Comment by eimantas** [comment]
This probably should be closed as it seems to be fixed in master.

**Comment by rsanchezsaez** [comment]
Yeah, the new *iPad margins* code seems to have fixed it.
