### ISSUE TITLE
Support for data visualization

### ISSUE THREAD

**Issue by sugeerth** [ResearchKit/ResearchKit#1211]

**Comment by sugeerth** [comment]
I am wondering if there are methods for visualization of the medical data into the app? I remember mentioning about the possibility to add visualization components into the dataset

**Comment by bgannin** [comment]
The charting component on ResearchKit can be used somewhat independently as you see fit. Check out [the docs](https://github.com/ResearchKit/ResearchKit/tree/master/docs/ChartsAndGraphs).
