### ISSUE TITLE
Make Task or Step mandatory / Disable Skip Button completely for given task

### ISSUE THREAD

**Issue by KsgPhellow** [ResearchKit/ResearchKit#1218]
Hi,
After reading through the documentation and various guides/tutorials I'm still clueless as to how to disable the skip functionality for Ordered Tasks. 

Would someone mind giving me a heads up?

Thanks in advance

**Comment by ninoguba** [comment]
Make sure you set optional property of the ORKQuestionStep or whichever you're using to FALSE.  Please refer below for the documentation.

http://researchkit.org/docs/Classes/ORKStep.html#//api/name/optional

**Comment by KsgPhellow** [comment]
Thanks for the quick response.
