### ISSUE TITLE
taskViewController(_:shouldPresentStep:) crashes in Swift

### ISSUE THREAD

**Issue by getaaron** [ResearchKit/ResearchKit#122]
In this delegate method:

    func taskViewController(taskViewController: ORKTaskViewController, shouldPresentStep step: ORKStep) -> Bool {
        // use step
    }

`step` is guaranteed by the method signature to be non-nil, and crashes when using `step` if it's not. But this method has many code paths that can return `nil`:

    - (ORKStep *)stepAfterStep:(ORKStep *)step withResult:(ORKTaskResult *)result {
        NSArray *steps = _steps;
        
        if (steps.count <= 0) {
            return nil;
        }
        
        ORKStep *currentStep = step;
        ORKStep *nextStep = nil;
        
        if (currentStep == nil) {
            nextStep = steps[0];
        } else {
            NSUInteger index = [self indexOfStep:step];
            
            if (NSNotFound != index && index != (steps.count-1)) {
                nextStep = steps[index+1];
            }
        }
        return nextStep;
    }

One possible workaround would be to wrap `[ORKTaskViewController -shouldPresentStep:]` in an `if (step) {…}`.

**Comment by jwe-apple** [comment]
Agree, that's the correct fix. `stepAfterStep:withResult:` is correctly annotated as nullable input and nullable result. `shouldPresentStep:` should not be called with a nil `step`.

**Comment by jwe-apple** [comment]
Fixed.
