### ISSUE TITLE
Attributed Text in Surveys

### ISSUE THREAD

**Issue by david-koneksa** [ResearchKit/ResearchKit#1223]
For clinical reasons it is imperative that we are able to use text attributions in the question text and within the answer choices when using  ORKTextChoice.  Some words need to be bold and potentially different colors.  This would be easily implemented if the *attributedText* properties were exposed.

Is there a way this can be done without having to subclass and create a new UI ?

**Comment by srinathtm-apple** [comment]
Hey @david-koneksa , thats a valuable suggestion. I will look into implementing this and get back to you soon!

**Comment by david-koneksa** [comment]
That would be fantastic and a huge time saver for us!

**Comment by srinathtm-apple** [comment]
@david-koneksa quick update - I have an initial implementation that adds a attributedText property to ORKAnswerFormat. I am currently trying to see if I can expand this to both the text and detailText labels, and also figuring out what's the best way to expose them (readwrite properties and/or new initializer). Any thoughts/comments?

**Comment by srinathtm-apple** [comment]
@david-koneksa - created a WIP pull request if that's helpful..

**Comment by david-koneksa** [comment]
@srinathtm-apple Thanks for getting on this so quickly.  I think the new in initializer would be best for me.  Avoids another line of code!  I will; check out the code.

While IO have you is there a way to have the new ORKStepViewController collapse the expanded Navigation / Title area before it is displayed?  That area is so large it reduces the information we can display without having to scroll the view.

Thanks

**Comment by srinathtm-apple** [comment]
@david-koneksa If you wanna completely do away with large titles throughout the framework, you can set prefersLargeTitle to NO in ORKTaskViewController.

**Comment by david-koneksa** [comment]
@srinathtm-apple I can not find **prefersLargeTitle** on **ORKTaskViewController** ?
