### ISSUE TITLE
Task progressLabel isn't visible.

### ISSUE THREAD

**Issue by berenyiaustin** [ResearchKit/ResearchKit#1225]
My task progressLabel isn't visible. How do I make it visible for each of my task?

**Comment by srinathtm-apple** [comment]
@berenyiaustin - can you please provide some more information, is this a custom task or an existing task? Some code snippets might help as well..

**Comment by ninoguba** [comment]
Based on yout sample you only need to use the ORKOrderedTask and that would show the progress labels you’re expecting.

**Comment by berenyiaustin** [comment]
That's it. Thanks!
