### ISSUE TITLE
 How would I implement surveys with suggested answers

### ISSUE THREAD

**Issue by sainianil** [ResearchKit/ResearchKit#1228]
Could you guys guide me how can I implement survey with suggested answers?
- User scales have default value which can be used for this
- How about choice question, number, bool 

- Is it possible to create survey using survey results to show survey with suggested answers?

All question types have concept of default values.

Any idea in this regard would be great help.

Thanks.

**Comment by ninoguba** [comment]
Look in #684 or search for "default" keyword in Open and Closed Issues for previous discussion on this topic.

**Comment by sainianil** [comment]
Thanks @ninoguba - Yes, I've implemented using the stepResult(forStepIdentifier stepIdentifier: String) -> ORKStepResult? delegate method to pre-populate the survey answers.
