### ISSUE TITLE
Spatial Memory - ORKESerializer Issue

### ISSUE THREAD

**Issue by AH24** [ResearchKit/ResearchKit#1234]
Having an issue with the Serialization on the Spatial Memory Test. Other users have had an issue with this, but I have not seen any solutions.

The error is the following:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ORKSpatialSpanMemoryGameTouchSample integerValue]: unrecognized selector sent to instance

I am getting that issue encoding to JSON

Here is what I have in ORKESerialization

```
ENTRY(ORKSpatialSpanMemoryGameTouchSample,
                 nil,
                 (@{
                    PROPERTY(timestamp, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(targetIndex, NSValue, NSObject, NO, nil, nil),
                    PROPERTY(correct, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(location, NSValue, NSObject, NO,
                             ^id(id value) { return value?dictionaryFromCGPoint(((NSValue *)value).CGPointValue):nil; },
                             ^id(id dict) { return [NSValue valueWithCGPoint:pointFromDictionary(dict)]; })
                    })),
           ENTRY(ORKSpatialSpanMemoryGameRecord,
                 nil,
                 (@{
                    PROPERTY(seed, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(sequence, NSNumber, NSArray, NO, nil, nil),
                    PROPERTY(gameSize, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(gameStatus, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(score, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(touchSamples, ORKSpatialSpanMemoryGameTouchSample, NSArray, NO,
                             ^id(id numeric) { return tableMapForward(((NSNumber *)numeric).integerValue, memoryGameStatusTable()); },
                             ^id(id string) { return @(tableMapReverse(string, memoryGameStatusTable())); }),
                    PROPERTY(targetRects, NSValue, NSArray, NO,
                             ^id(id value) { return value?dictionaryFromCGRect(((NSValue *)value).CGRectValue):nil; },
                             ^id(id dict) { return [NSValue valueWithCGRect:rectFromDictionary(dict)]; })
                    })),
           ENTRY(ORKSpatialSpanMemoryResult,
                 nil,
                 (@{
                    PROPERTY(score, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(numberOfGames, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(numberOfFailures, NSNumber, NSObject, NO, nil, nil),
                    PROPERTY(gameRecords, ORKSpatialSpanMemoryGameRecord, NSArray, NO, nil, nil)
                    })),
```

What needs to be changed to make this work without error?

**Comment by srinathtm-apple** [comment]
@AH24 - can you try switching targetIndex to NSNumber instead of NSValue?

**Comment by AH24** [comment]
@srinathtm-apple Looks like the same result

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ORKSpatialSpanMemoryGameTouchSample integerValue]: unrecognized selector sent to instance 0x282b70300'

`PROPERTY(targetIndex, NSNumber, NSObject, NO, nil, nil),`

**Comment by 0xff23** [comment]
is there any updates regarding this issue? Getting same error: `ORKSpatialSpanMemoryGameTouchSample integerValue]: unrecognized selector sent to instance`

**Comment by louie-apple** [comment]
More info here would be really helpful. Can you send us a full backtrace of the exception? Thanks!

**Comment by louie-apple** [comment]
@0xff23 Curious if you are still seeing this, we are hoping for more information from you. 
Additionally, is there any chance you may have an old copy of `ORKESerialization` in your project? (Friendly reminder, this file does not automatically update in your project when you update ResearchKit)

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
