### ISSUE TITLE
How do I dismiss an ORKTaskViewController and push a view controller of my choice?

### ISSUE THREAD

**Issue by pandapancake** [ResearchKit/ResearchKit#1235]
Hi all,

I'm new to ResearchKit and I been doing researching for the past week... I can't find a way to dismiss the ORKtask and push to a new viewController. I tried [https://stackoverflow.com/questions/45827130/how-do-i-dismiss-an-orktaskviewcontroller-and-present-a-view-controller-of-my-ch] but it didn't work. Here is my code:

````import UIKit
import ResearchKit

class MainViewController: UIViewController, ORKTaskViewControllerDelegate {
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func MainViewNextButtonPressed(_ sender: Any) {
        let taskViewController = ORKTaskViewController(task: ConsentTask, taskRun: nil)
        taskViewController.delegate = self
        present(taskViewController, animated: true, completion: nil)
    }
    
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        
        switch reason {
        case .completed:          
            performSegue(withIdentifier: "NewVCSegue", sender: nil)
            break
        case .discarded:
            taskViewController.dismiss(animated: true)
            break
        case .failed:
        break
        case .saved:
            break
        }
    }
}
````

I tried  `self.navigationController?.pushViewController`, viewController segue and present nothing work. Please help :(

Thank you so much!!!

**Comment by srinathtm-apple** [comment]
Hey @pandapancake , there are a few things at play here, to start off, can you try this -

`switch reason {
        case .completed:
            self.dismiss(animated: true) {
                performSegue(withIdentifier: "NewVCSegue", sender: nil)
            }
            break
        case .discarded:
            self.dismiss(animated: true)
            break
        case .failed:
            break
        case .saved:
            break
        }`

**Comment by pandapancake** [comment]
It works!!!!!!!! Thank you so much!!!!!
