### ISSUE TITLE
ORKQuestionStep deprecation

### ISSUE THREAD

**Issue by chumps52** [ResearchKit/ResearchKit#1248]
Whilst looking at the [docs/class reference](http://researchkit.org/docs/Classes/ORKQuestionStep.html), I noticed it states that `ORKQuestionStep`s are deprecated and scheduled for removal in v2.0.

What is the equivalent/replacement for this? My survey currently consists purely of `ORKQuestionStep`s.

**Comment by srinathtm-apple** [comment]
@chumps52 - we are not removing ORKQuestionStep itself, we are merely deprecating a couple of initializers and we highly recommend leveraging the new one - 
+ questionStepWithIdentifier:title:question:answer:

http://researchkit.org/docs/Classes/ORKQuestionStep.html#//api/name/questionStepWithIdentifier:title:question:answer:

**Comment by chumps52** [comment]
@srinathtm-apple Ah ok, thank you!
