### ISSUE TITLE
Hide or disable “Done” button in ORKCompletionStep

### ISSUE THREAD

**Issue by chumps52** [ResearchKit/ResearchKit#1250]
Is it possible to hide the "Done" button when `func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?)` is called?

i.e.:
```
extension StudyVC : ORKTaskViewControllerDelegate {

    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        switch reason {
        case .completed:

        // HIDE BUTTON HERE

        break

        case .failed, .discarded, .saved:
            break
        }
    }
    // DISMISS VIEWCONTROLLER ONCE COMPLETE
}
```

I've seen that, from #1061, `ORKCompletionStepViewController` has a `shouldShowContinueButton` property - is there something similar for `ORKCompletionStep`?

My aim is for a user to press done and then the button is hidden so that they cannot press it multiple times (as when they press done currently there is an ~3 second delay before the ViewController is dismissed, whilst background functions are performed. It is necessary to do it this way due to the targeted patient userbase).

**Comment by srinathtm-apple** [comment]
@chumps52 - the expected flow is to simply dismiss the view controller inside the didFinishWithReason delegate callback.

You could insert a ORKWaitStep which displays a spinner before you present the ORKCompletionStep.

**Comment by chumps52** [comment]
@srinathtm-apple - I see, thank you. Sorry I've been using it wrong - still learning! :)
