### ISSUE TITLE
multi Y-axis & two type of Chart together

### ISSUE THREAD

**Issue by mash3l777** [ResearchKit/ResearchKit#1254]
Can I make like this chart by ResearchKit ?

![image](https://user-images.githubusercontent.com/25553970/54440130-8cb46100-4753-11e9-8508-7450c717e61c.png)

**Comment by srinathtm-apple** [comment]
Hey @mash3l777 - ResearchKit offers some basic charting support - bar graphs, line graphs, etc. You should be able to replicate specific aspects of your image using ResearchKit but maybe not all...

**Comment by mash3l777** [comment]
Hi @srinathtm-apple  thanks for your respond  I do already some chart like this but still not completed 
see this what I do

![](https://thumbs.gfycat.com/RingedKindlyLeafcutterant-small.gif)

still I don't know how to move Y-axis to the right, its now over each other.
