### ISSUE TITLE
[UI] locationQuestionMap too small in height

### ISSUE THREAD

**Issue by yo1995** [ResearchKit/ResearchKit#1255]
### What did you expect to happen?

When I tried to include a location step, I found that the height of map is too small for older devices including iPhone SE, which makes it hard to pinch the map with fingers. Below attached a screenshot.

![Screen Shot 2019-03-20 at 00 17 26](https://user-images.githubusercontent.com/9660181/54658972-4853f880-4aa6-11e9-9c05-bd3e2cdb5d8c.png)

I checked the settings in `/ResearchKit/Common/ORKSkin.m` and found that the 
`ORKScreenMetricLocationQuestionMapHeight` values are just 90 and 150 for those devices. 

Since there has been a newer card style for RK for a while, could we increase those values to fit devices better? If so, I might do a brief PR.

Thanks,

### What are your versions?

* OS: 12.1
* ResearchKit: 2.0.0

**Comment by srinathtm-apple** [comment]
@yo1995 - great catch.. Please submit a PR and I'll merge it in right away!

**Comment by yo1995** [comment]
> @yo1995 - great catch.. Please submit a PR and I'll merge it in right away!

### What actually happened?

when i was trying to fix this issue, i found that the problem stretches even further.
according to #1185 , it adds two types of screens, and leads to a enumerations of *9* screen types as follow 
```c
typedef NS_ENUM(NSInteger, ORKScreenType) {
    ORKScreenTypeiPhoneX,
    ORKScreenTypeiPhoneXSMax,
    ORKScreenTypeiPhone6Plus,
    ORKScreenTypeiPhone6,
    ORKScreenTypeiPhone5,
    ORKScreenTypeiPhone4,
    ORKScreenTypeiPad,
    ORKScreenTypeiPad10_5,
    ORKScreenTypeiPad12_9,
    ORKScreenType_COUNT
};
```

whereas the original matrix of dimensions in ORKSkin.m are designed for *only 8* devices
```c
iPhoneX,  iPhone 6+,  iPhone 6,  iPhone 5,  iPhone 4,  iPad,  iPad 10.5,  iPad 12.9
```
therefore, when I test the UI on ORKScreenTypeiPad12_9, it *displays nothing* as there is an index overflow for acquiring screen metrics.

### What's the possible solution?

in order to get rid of too much complication, I would 
- first delete the **ORKScreenTypeiPhone4** screen type since RK won't compile anymore on that generation of devices of iOS9.
- then adjust the metrics to align with the newer device XSMAX as well as iPhone5 mentioned primarily in this issue.

@srinathtm-apple if this sounds viable, I'll make changes as described above. 😃

**Comment by srinathtm-apple** [comment]
@yo1995 - sounds good to me, looking forward to the PR :D

**Comment by yo1995** [comment]
Set up a PR.

**Comment by srinathtm-apple** [comment]
Closing this as the PR associated with this issue has been merged into master.
