### ISSUE TITLE
Storing User Data with ResearchKit for Developer Usage

### ISSUE THREAD

**Issue by uklejaj** [ResearchKit/ResearchKit#1259]
If the user were to complete a series of tasks/answer the questions, how would the developer get access to the results of their inputs for further study? What is the protocol to do this?

**Comment by srinathtm-apple** [comment]
the taskViewController: didFinishWithReason: error: delegate callback will return a reference to the taskViewController- 

taskViewController.results - will return a ORKResult object which will contain all the responses by the user..
