### ISSUE TITLE
Redoing audio recording

### ISSUE THREAD

**Issue by jhristov** [ResearchKit/ResearchKit#1266]
Hello, is it possible to somehow allow for redoing the speech recording? Now if the user navigates back one slide and tries the recording again one gets a file already exists error.
![IMG_0018](https://user-images.githubusercontent.com/29655331/56424564-743ae780-62b9-11e9-9947-109fa9a770f1.PNG)

**Comment by akshay-yadav-apple** [comment]
Hey @jhristov! 
Can you also attach your code to create the speech recognition step. I tried it on my end with the ORKCatalog app and am able to overwrite the audio file, and unable to recreate the issue.

**Comment by jhristov** [comment]
Ok, thanks for the info. It must be due to the modding I did. We needed to separate the recording from Siri and I changed numerous files.
