### ISSUE TITLE
ORKImageCaptureStep crashes when used on devices that dont support flash

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#1281]
Caused by this line/s in ORKImageCaptureStepViewController.m

`[photoSettings setFlashMode:(AVCaptureFlashModeAuto)];`

The fix should be easy and just need to add logic to determine flash support on the actual device then set this to AVCaptureFlashModeAuto or AVCaptureFlashModeOff, respectively.

**Comment by srinathtm-apple** [comment]
closing this since the associated PR was merged into master
