### ISSUE TITLE
Build fails : no submodule named 'Private' in module 'ResearchKit'

### ISSUE THREAD

**Issue by henryallsuch** [ResearchKit/ResearchKit#1289]
Files such as `ResearchKit/ActiveTasks/ORKSwiftStroopResult.swift` have the import:

```
import ResearchKit.Private
 ```

This is confusing Cocoapods and the build fails with error:

```
<unknown>:0: error: no submodule named 'Private' in module 'ResearchKit'
```

I have removed the imports and the build is successful, as seen in this fork commit:

https://github.com/henryallsuch/ResearchKit/commit/e842a1e768079c361fb1fbdfe501f499f30b69f5

Is there a better way to fix this?

**Comment by chrisortman** [comment]
I tracked this down to how the headers were specified in the .podspec see #1308

**Comment by konDeichmann** [comment]
Hi, 
is there any progress on this issue?
Or an open PR?

**Comment by henryallsuch** [comment]
@konDeichmann see above comment #1308 fixes the issue.
