### ISSUE TITLE
No valid SSL cert on researchkit.org

### ISSUE THREAD

**Issue by heptal** [ResearchKit/ResearchKit#1290]
![49600E62-85DC-441D-9A23-268114625118](https://user-images.githubusercontent.com/1241082/60685233-8e6f7500-9e67-11e9-9c2a-0cecc9604bf5.png)
![4038B02F-E560-4D74-8A29-242E4B16DC1D](https://user-images.githubusercontent.com/1241082/60685234-8e6f7500-9e67-11e9-939a-c7d77f386168.png)

**Comment by jessi-apple** [comment]
Hi there -- thank you for reporting this issue. It has since been resolved.
