### ISSUE TITLE
Serialize ORKResult object tree into JSON

### ISSUE THREAD

**Issue by getaaron** [ResearchKit/ResearchKit#131]
I have a working ResearchKit app, except I'm having trouble serializing the results `ORKResult`, `ORKStepResult`, etc. into JSON to upload to a server.

I see in [the `ORKResult` docs](https://researchkit.github.io/docs/Classes/ORKResult.html) that this isn't supported:

> When you receive a result, you can store it temporarily by archiving it with `NSKeyedArchiver`, because all `ORKResult` objects implement `NSSecureCoding`. If you want to serialize the result object to other formats, you’re responsible for implementing this.

So, I guess I can get this to JSON like so:

- `ORKResult` -> `NSData` via `NSKeyedArchiver`
- `NSData` -> `NSDictionary` via `NSPropertyListSerialization`
- `NSDictionary` -> JSON via `NSJSONSerialization`

But then I get all of `NSKeyedArchiver`'s stuff, and it doesn't really seem optimal.

Is there a better way, perhaps adapting `ORKJSONLogFormatter` (which I haven't fully reviewed, but looks like it's written for logging non-survey results)?

I know JSON isn't ideal for all applications, but it would be great for some.

As a bonus, this feature could make implementing `debugDescription` methods on the result objects easy, which could aid in debugging.

**Comment by jwe-apple** [comment]
There's a JSON implementation in ORKESerialization, look at in the ORKTest app.

It's not part of the framework, but it's an extension.

**Comment by jwe-apple** [comment]
[ORKESerialization](https://github.com/ResearchKit/ResearchKit/blob/31ea7908a24a24092ce490b7717dc8e015f77985/Testing/ORKTest/ORKTest/ORKESerialization.h)

**Comment by jwe-apple** [comment]
There is also a separate JSON serialization specifically for integrating with the Sage Bridge server, in the AppCore repository.

**Comment by getaaron** [comment]
Thanks. I would love to see `ORKESerialization` included in ResearchKit. Would you be open to a PR that moves it into ResearchKit and adds appropriate documentation?

If not, should I write a PR that references it in the documentation?

**Comment by jwe-apple** [comment]
Yeah, let's add a reference to it in the documentation. We think it's likely that ResearchKit will end up with serializations appropriate for integrating with each of several different back ends. If you choose to set up your own back end / tools, then ORKESerialization will get you started, but you'll likely have to modify it in practice.

We'd be interested to learn what those modifications are, and incorporate it into ResearchKit only when we are ready to establish a pattern for handling multiple serializations.

**Comment by jwe-apple** [comment]
I'm going to close this issue, but please do submit a PR for documentation improvement!
