### ISSUE TITLE
Research Kit crashes when we try to add more than one textchoice in one group survey form. Below is my code please help  

### ISSUE THREAD

**Issue by Prabhat123456** [ResearchKit/ResearchKit#1310]
let step = ORKFormStep(identifier: String(describing: "groupedFormStep"), title: NSLocalizedString("Please answer the below given questions", comment: ""), text: "It will help you to understand the cause of your headache")
        
        // First Question
        
        let section01 = ORKFormItem(sectionTitle: NSLocalizedString("How was Your last night sleep?", comment: ""), detailText: NSLocalizedString("Sleep disturbances can be a major contributing factor to your headache", comment: ""), learnMoreItem: nil, showsProgress: true)
        
        let sleepQualityanswer1 = ORKTextChoice(text: "I had a good sleep", value: 0 as NSNumber)
        let sleepQualityanswer2 = ORKTextChoice(text: "I had a bad sleep", value: 1 as NSNumber)
        let sleepQualityanswer3 = ORKTextChoice(text: "My Sleep was as usual", value: 2 as NSNumber)
        let sleepQualityanswerFormat =  [sleepQualityanswer1,sleepQualityanswer2,sleepQualityanswer3]
        let form1ForSleepQuality = ORKFormItem(identifier: "sleepQuality", text: "How was your last night sleep", answerFormat: ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: sleepQualityanswerFormat), optional: true)
        
        
        
        // Second Question
        
       let section02 = ORKFormItem(sectionTitle: NSLocalizedString("How is your wakeup and bedtime last night", comment: ""), detailText: NSLocalizedString("Change in wakeup or sleeptime can cause to headache", comment: ""), learnMoreItem: nil, showsProgress: true)
        
        let answer1ForBedandWakupTime = ORKTextChoice(text: "I slept early last night and got up early", value: 0 as NSNumber)
        let answer2ForBedandWakupTime = ORKTextChoice(text: "I slept late and got up early", value: 1 as NSNumber)
        let answer3ForBedandWakupTime = ORKTextChoice(text: "I slept early and got up late", value: 2 as NSNumber)
        let answer4ForBedandWakupTime = ORKTextChoice(text: "I slept and woke up as usual", value: 3 as NSNumber)
        let answerFormatForBedandWakupTime =  [answer1ForBedandWakupTime,answer2ForBedandWakupTime,answer3ForBedandWakupTime,answer4ForBedandWakupTime]
        let form2ForBedandWakupTime = ORKFormItem(identifier: "BedAndWakUpTime", text: "wakeup", answerFormat: ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: answerFormatForBedandWakupTime), optional: true)
            
        
        
        
        step.formItems = [
          section01,
          form1ForSleepQuality,
          section02,
          form2ForBedandWakupTime
        ]
        
        return ORKOrderedTask(identifier: String(describing: "formTask"), steps: [step])

**Comment by eschramm** [comment]
@Prabhat123456 - I found a bug in section handling - filing a PR momentarily...

**Comment by Prabhat123456** [comment]
Thanks alot :)
