### ISSUE TITLE
Unexpected paging in ORKHTMLPDFWriter

### ISSUE THREAD

**Issue by jakubvano** [ResearchKit/ResearchKit#132]
Current implementation of `ORKHTMLPDFWriter` produces unexpected page breaks, if input HTML has center / right aligned content.

Example of problematic HTML:

``` obj-c
NSMutableString* html = [NSMutableString string];
[html appendString:@"<html><body>"];
for (int i=0; i<200; i++) {
    [html appendString:@"<div align=\"right\">line</div>"];
}
[html appendString:@"</body></html>"];
```

PDF created from this HTML will have unexpectedly large bottom margin.

Upon further investigation I found out that this issue is most likely caused by `[UIWebView viewPrintFormatter]`, however I could not find any solution / workaround for this.

**Comment by jwe-apple** [comment]
If you can create a small stand-alone example of the unexpected behavior, I would suggest filing a radar. If you add the radar number here I can follow up internally.

**Comment by infimache** [comment]
I have filled a radar, number 20760071

**Comment by jwe-apple** [comment]
Thanks!

**Comment by Isuru-Nanayakkara** [comment]
@jakubvano Do you have a link? I can't seem to find it.

**Comment by Isuru-Nanayakkara** [comment]
@jakubvano Do you have a link? I can't find it on open radar.

**Comment by jakubvano** [comment]
@Isuru-Nanayakkara Unfortunatelly, it looks like i did not add it to openradar, and filed it to apple bugreport system under old company account... Only available material I have is this [StackOverflow question](http://stackoverflow.com/questions/29964523/unexpected-page-breaks-when-printing-uiwebview) and my [github repo](https://github.com/jakubvano/HTMLPDFWriter) with example project. Hope it helps

**Comment by umerkhan-apple** [comment]
Issue being tracked on radar. Not an RK bug.
