### ISSUE TITLE
ORKOtherChoiceAnswerFormat?

### ISSUE THREAD

**Issue by xinsight** [ResearchKit/ResearchKit#1327]
I'm mapping a FHIR Questionnaire to ResearchKit Questions. It mostly works, but FHIR has the concept of an `open-choice` question, which is allows the user to select from a list of options, or enter text. For example:

> Gender identity?
> * Female
> * Male
> * Other
>   __________

I know these questions can be broken down into two questions, where the 2nd question is only shown if "Other" is selected, but I was wondering if anyone has attempted to create an `ORKOtherChoiceAnswerFormat` in ResearchKit.

**Comment by srinathtm-apple** [comment]
@xinsight - please checkout ORKTextChoiceOther answer format

**Comment by xinsight** [comment]
Ha, amazing! I was using the last release (2.0), so I didn't see this. Here's the PR where this landed in case anyone else stumbles across this issue:

https://github.com/ResearchKit/ResearchKit/pull/1264/files
