### ISSUE TITLE
Unable to build "master" with carthage

### ISSUE THREAD

**Issue by xinsight** [ResearchKit/ResearchKit#1328]
On "master", the following command fails to build ResearchKit:

`carthage update ResearchKit --platform ios --cache-builds`

```
CompileSwift normal arm64 (in target 'ResearchKitTests' from project 'ResearchKit')
...
/Users/xxx/dev/xxx/Carthage/Checkouts/ResearchKit/ResearchKitTests/ORKActiveTaskResultTests.swift:32:18: error: module 'ResearchKit' was not compiled for testing
@testable import ResearchKit
                 ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

The `ResearchKitTests` are included in the "Archive", which seems incorrect.

<img width="893" alt="schema-build-tests-included" src="https://user-images.githubusercontent.com/465971/70620534-d4e7ad80-1c17-11ea-8fa4-c90408ec4bf9.png">

Unchecking that box (saving to a new branch and updating the Cartfile) allows the carthage command to complete.

Is "master" the 2.1 beta branch - or is there another branch I should be using?

(I'm now getting a weird crash in my app with dyld and the thread sanitizers, so I'm not sure if there are some other build options in ResearchKit that are not working with carthage.)

**Comment by xinsight** [comment]
Here's the fix: faffea0008c4df34802a2e631565e165c69ff081

**Comment by xinsight** [comment]
I removed the thread sanitizer options, and am no longer getting weird crashes during dyld loading.

libclang_rt.asan_iossim_dynamic.dylib
libclang_rt.ubsan_iossim_dynamic.dylib
libclang_rt.tsan_iossim_dynamic.dylib

**Comment by raheelsayeed** [comment]
I am unable to "archive app" but able to build and run the app.

is this related?

**Comment by xinsight** [comment]
I would think so. The PR is now merged, so if you pull in the latest from ResearchKit "master" branch, you can see if you're able to archive.
