### ISSUE TITLE
RK API Documentation is no longer available online

### ISSUE THREAD

**Issue by NirajMedable** [ResearchKit/ResearchKit#1332]
With the new release of the RK/CK Website, the API Documentation that was previously published is no longer available.  Is there a new location for this information?

**Comment by cbaker6** [comment]
You can still access the markdown files via the "docs" folder on GitHub, https://github.com/ResearchKit/ResearchKit/tree/master/docs

**Comment by delfuego** [comment]
It's... kind of amazing that the docs were pulled down without a new home? Help?

**Comment by xmollv** [comment]
Are there any news on this? Seems like a big oversight...

**Comment by srinathtm-apple** [comment]
http://researchkit.org no longer redirects to researchandcare.org

You can find the docs here - http://researchkit.org/docs/index.html

**Comment by chrisnowak** [comment]
Surprised you guys will host anything without https!

**Comment by NirajMedable** [comment]
Thanks @srinathtm-apple!

**Comment by xmollv** [comment]
Thanks @srinathtm-apple! 🎉
