### ISSUE TITLE
totalProgressOfCurrentStep:]: unrecognized selector

### ISSUE THREAD

**Issue by miguelc95** [ResearchKit/ResearchKit#1334]
I am having this issue when I present a ORKTask

<img width="628" alt="Screen Shot 2020-01-27 at 13 04 12" src="https://user-images.githubusercontent.com/15070387/73205042-cab93a00-4105-11ea-8429-4feb19fef888.png">

I can see the introduction step fine but when I click start the app crashes and that message appears.
Do you know if there is a way to fix this?

`import Foundation
import ResearchKit

public class SurveyTask: NSObject, ORKTask {
    public func step(after step: ORKStep?, with result: ORKTaskResult) -> ORKStep? {
          switch step?.identifier {
          case .none:
              return stepWithIdentifier(identifier: introStepID)
            
          case .some(introStepID):
              return stepWithIdentifier(identifier: nameStepID)
            
          case .some(nameStepID):
              return questStep(name: findName(result: result))
            
          case .some(questStepID):
              return stepWithIdentifier(identifier: colorStepID)
            
          case .some(colorStepID):
              return stepWithIdentifier(identifier: summaryStepID)
            
          default:
            return nil
          }
        }
    
    public func step(before step: ORKStep?, with result: ORKTaskResult) -> ORKStep? {
         switch step?.identifier {
           case .some(nameStepID):
               return stepWithIdentifier(identifier: introStepID)
             
           case .some(questStepID):
               return stepWithIdentifier(identifier: nameStepID)
             
           case .some(colorStepID):
               return questStep(name: findName(result: result))
             
           case .some(summaryStepID):
               return stepWithIdentifier(identifier: colorStepID)
             
           default:
             return nil
           }
         }
    
  
  let introStepID = "intro_step"
  let nameStepID = "name_step"
  let questStepID = "quest_step"
  let colorStepID = "color_step"
  let summaryStepID = "summary_step"
  
  public var identifier: String { get { return "survey"} }
  
  public func stepBeforeStep(step: ORKStep?, withResult result: ORKTaskResult) -> ORKStep? {
    
    switch step?.identifier {
    case .some(nameStepID):
        return stepWithIdentifier(identifier: introStepID)
      
    case .some(questStepID):
        return stepWithIdentifier(identifier: nameStepID)
      
    case .some(colorStepID):
        return questStep(name: findName(result: result))
      
    case .some(summaryStepID):
        return stepWithIdentifier(identifier: colorStepID)
      
    default:
      return nil
    }
  }
  
  public func stepAfterStep(step: ORKStep?, withResult result: ORKTaskResult) -> ORKStep? {
    
    switch step?.identifier {
    case .none:
        return stepWithIdentifier(identifier: introStepID)
      
    case .some(introStepID):
        return stepWithIdentifier(identifier: nameStepID)
      
    case .some(nameStepID):
        return questStep(name: findName(result: result))
      
    case .some(questStepID):
        return stepWithIdentifier(identifier: colorStepID)
      
    case .some(colorStepID):
        return stepWithIdentifier(identifier: summaryStepID)
      
    default:
      return nil
    }
  }
  
  public func stepWithIdentifier(identifier: String) -> ORKStep? {
    switch identifier {
      
    case introStepID:
      let instructionStep = ORKInstructionStep(identifier: introStepID)
      instructionStep.title = "The Questions Three"
      instructionStep.text = "Who would cross the Bridge of Death must answer me these questions three, ere the other side they see."
      return instructionStep
      
    case nameStepID:
      let nameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
      nameAnswerFormat.multipleLines = false
      let nameQuestionStepTitle = "What is your name?"
      return ORKQuestionStep(identifier: nameStepID, title: nameQuestionStepTitle, answer: nameAnswerFormat)
      
    case questStepID:
        return questStep(name: "")
      
    case colorStepID:
      let colorQuestionStepTitle = "What is your favorite color?"
      let colorTuples = [
        (UIImage(named: "red")!, "Red"),
        (UIImage(named: "orange")!, "Orange"),
        (UIImage(named: "yellow")!, "Yellow"),
        (UIImage(named: "green")!, "Green"),
        (UIImage(named: "blue")!, "Blue"),
        (UIImage(named: "purple")!, "Purple")
      ]
      var imageChoices:[ORKImageChoice] = []
      for (image, name) in colorTuples {
        imageChoices.append(ORKImageChoice(normalImage: image, selectedImage: nil, text: name, value: name as NSString))
      }
      let colorAnswerFormat: ORKImageChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: imageChoices)
      return ORKQuestionStep(identifier: colorStepID, title: colorQuestionStepTitle, answer: colorAnswerFormat)
      
    case summaryStepID:
      let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
      summaryStep.title = "Right. Off you go!"
      summaryStep.text = "That was easy!"
      return summaryStep
      
    default:
      return nil
    }
  }
  
  func findName(result: ORKTaskResult) -> String? {
    
    if let stepResult = result.result(forIdentifier: nameStepID) as? ORKStepResult, let subResults = stepResult.results, let textQuestionResult = subResults[0] as? ORKTextQuestionResult {
      
      return textQuestionResult.textAnswer
    }
    return nil
  }
  
  func questStep(name: String?) -> ORKStep {
    
    var questQuestionStepTitle = "What is your quest?"
    
    if let name = name {
      questQuestionStepTitle = "What is your quest, \(name)?"
    }
    
    let textChoices = [
      ORKTextChoice(text: "Create a ResearchKit App", value: 0 as NSNumber),
      ORKTextChoice(text: "Seek the Holy Grail", value: 1 as NSNumber),
      ORKTextChoice(text: "Find a shrubbery", value: 2 as NSNumber)
    ]
    let questAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)
    return ORKQuestionStep(identifier: questStepID, title: questQuestionStepTitle, answer: questAnswerFormat)
  }
}
`

**Comment by Pariecemckinney-apple** [comment]
Hello @miguelc95, have you found a solution since you've posted this issue? If not, i'll be happy to dive in and help figure out what's going on. Just let me know!

**Comment by EvieGillie** [comment]
I fixed this by implementing totalProgress for my custom ORKTask
