### ISSUE TITLE
New active task for measurement of visual acuity

### ISSUE THREAD

**Issue by flarmed** [ResearchKit/ResearchKit#134]
We aim to create an active task of measurement near visual acuity for use in ophthalmic clinical trials.

**Comment by jwe-apple** [comment]
Great. Do you have an idea of schedule? Also, plans for how calibration will work?

**Comment by flarmed** [comment]
It is very difficult for me to establish a schedule for creating the task that I am not a professional programmer and I have only two years working with objective-c. A few months ago I created a tool for my personal use to measure visual acuity with the iPhone. The main drawback is the distance from the eye to the screen of the device. You need to know the distance between them in order to validate the results. And I think about a possible solution would be to use the interocular distance reference. Calibrate the instrument telling the patient to place the phone at a distance of 40 cm and measure the distance between the centers of the eyes using AVFoundation + CoreImage. That distance would place the reference to the phone always in the same position and to make serial measurements. There could be other solutions as knowing the distance of focus of the camera, but you can not currently meet that value from iOS exist. Thanks for the support, especially those who are not professionals in this area and just enjoyed the fact programmed to complement ophthalmologist profession. Thank you for your interest, all suggestions are welcome

**Comment by flarmed** [comment]
I created the contentView , activeStep and viewController for visual acuity. When I try to test the custom task xcode gives me error: could not be build module ResearchKit

**Comment by jwe-apple** [comment]
Perhaps a pointer to your non-working branch and exact failing steps? Someone here will be able to help.

**Comment by flarmed** [comment]
Ok. Fixed.

**Comment by p2** [comment]
Nice idea, @flarmed. Are you using a Snellen chart or something different? The problem that you will have, as I'm sure you know, is that the person will cover one eye and you can no longer measure the interpupillary distance. Should still work with an initial measurement, for which you can use the [OpenCV framework](http://opencv.org), which supports face + eye detection. Getting the distance directly from the camera's focusing mechanism would be great indeed!

**Comment by flarmed** [comment]
The measurement of the pupillary distance is only for positioning the machine. To cover the eye this measure is lost and would have to use the accelerometer to know that the patient does not move the device. Another idea is to initially measure the distance between each eye and mouth and so you always have a reference. I am using the Landolt ring to create the test card. The value of distance can not be obtained, since it is a private information of apple.

**Comment by umerkhan-apple** [comment]
@flarmed I wanted to see if you were able to shape this up into an active task? This is quite an interesting feature. If you're stuck and would like some help completing it, feel free to post your progress in a separate branch for us to take a look at.

**Comment by umerkhan-apple** [comment]
@flarmed Friendly ping!

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
