### ISSUE TITLE
ORKTaskResult returns empty results after completing the survey

### ISSUE THREAD

**Issue by majeedyaseen** [ResearchKit/ResearchKit#1342]
After completing the Survey I am getting empty results in the delegate 

`func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
 }`

When I print `taskViewController.result` in the debugger 
The result is  **<ORKTaskResult: 0x280a70e80; identifier: "survey"; results: ()>**

I am using the 2.0 version of Researchkit 

However when I run the same survey on the old Researchkit version. 
I am getting the response as expected.

**Comment by srinathtm-apple** [comment]
RK 2.0 from the stable branch?

Are you running into this on latest master as well?

**Comment by majeedyaseen** [comment]
**RK 2.0 from the stable branch?**

Yes RK2.0 from the stable branch.
However the ActiveTask result is returned as expected in the same RK2.0 stable branch.
So seems the issue is with the results of the survey only.

**Are you running into this on latest master as well?**

No I am not running it on the latest master.

**Comment by majeedyaseen** [comment]
I was able to fix the issue, the problem was here 

**Earlier**
 `taskController = ORKTaskViewController(task: task, restorationData: Data(), delegate: self)`

**Now**
 `taskController = ORKTaskViewController(task: task, restorationData: nil, delegate: self)`

I dont know why there was such behaviour, but thankfully I am able to get the survey results.
