### ISSUE TITLE
We are recommended to use airpods in the listening test documents. Is there a targeted adaptation for airpods?

### ISSUE THREAD

**Issue by 179992096** [ResearchKit/ResearchKit#1348]
We are doing a hearing test program, but not all of our users have airpods, but because each headset will have different sound sensitivity, does researchkit provide a solution?

Question 1: has researchkit been optimized for airpods, and whether the data tested under the circumstances of excluding environmental impact is more accurate.

Question 2: does researchkit have a solution to the problem that different headphone speaker sensitivity results in inconsistent audio output?

**Comment by srinathtm-apple** [comment]
The task by itself is not specific to AirPods, however we provide calibration data for AirPods and EarPods (checkout the retspl and freq vs dBSPL plist files in the repo).

If you have access to the calibration data of the headsets that you will be using, you can plug them in as plist files, point to them in ORKdBHLToneAudiometryAudioGenerator initWithHeadphones initializer and the task should work just fine.
