### ISSUE TITLE
In Text Choice Question, the table with answers is visible immediately under Next button. 

### ISSUE THREAD

**Issue by cleverman** [ResearchKit/ResearchKit#1349]
In ORKCatalog project in Text Choice Question add an additional step with 4-5 answers. See attached images.

Possible temporal fix.
In method `ORKQuestionStepViewController.viewWillAppear`
replace
`[_tableContainer layoutIfNeeded];`
with
`[_tableContainer setNeedsLayout];`

![IMG_1501](https://user-images.githubusercontent.com/4737741/75968744-92f89b80-5ed6-11ea-9f99-e5957564a183.PNG)
![IMG_1502](https://user-images.githubusercontent.com/4737741/75968753-955af580-5ed6-11ea-82e7-49bb22212c10.PNG)
![IMG_1503](https://user-images.githubusercontent.com/4737741/75968762-95f38c00-5ed6-11ea-9263-e510ff86cab4.PNG)

**Comment by cleverman** [comment]
Test device was: iPhone 6s with zoomed screen.

**Comment by srinathtm-apple** [comment]
@cleverman - this has been fixed on master!
