### ISSUE TITLE
Scale question step loses its default value on second visit

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#135]
The scale question step loses its default value on second visit.

Steps to reproduce:
1. Go to a scale question step with a default value: the scale has a default value. Do not input any value.
2. Go back.
2. Go forward again: the scale doesn't have a default value.

**Comment by brucehappy** [comment]
Definitely saw this during my testing, but wrongly assumed it was the intended behavior.

**Comment by jwe-apple** [comment]
Yep, sounds like a bug. note that if you skip the step and then come back, the default value should *not* appear.

**Comment by rsanchezsaez** [comment]
Also, not sure what the expected behaviour is, but when even when a default value shows, the *Next* button is disabled until you interact with the slider.

**Comment by rsanchezsaez** [comment]
The problem seems to be that as soon as you view a question step, the answer is set to `NSNull`. So going back is currently indistinguishable from skipping the question.

To provide the desired behaviour, we could define an empty `ORKSkippedAnswer : NSNull` class which is only set when a question is skipped. That way we can show the default value when the answer is `NSNull`, but avoid showing it when it is `ORKSkippedAnswer`.

This would also keep the current behaviour where: you go to a question, set a value, go back, go forward again, and the step preserves the value that you previously entered.

Does this sound reasonable?

**Comment by rsanchezsaez** [comment]
Fixed via [pull request #157](https://github.com/ResearchKit/ResearchKit/pull/157).
