### ISSUE TITLE
Stable version failed to pass Review

### ISSUE THREAD

**Issue by thanospapazoglou** [ResearchKit/ResearchKit#1377]
Hi,

I have tried to upload an app using the **Stable** branch and it failed due to deprecated API usage of `UIWebView`.
I've noticed that you didn't include PR #1199 to this branch.

**Comment by ajay301985** [comment]
is there any update on this issue. I am not able to submit app to App Store for review because of UIWebview.
@athanasiospap have you got any solutions for it?

**Comment by athanasiospap** [comment]
> is there any update on this issue. I am not able to submit app to App Store for review because of UIWebview.
> @athanasiospap have you got any solutions for it?

I ended up rewriting on my own all the changes of the PR and then it passed.

**Comment by igoreydman** [comment]
@athanasiospap I ran into this issue a little bit ago, if you're using CocoaPods use the master branch of ResearchKit. 

`pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'  `

**Comment by athanasiospap** [comment]
> @athanasiospap I ran into this issue a little bit ago, if you're using CocoaPods use the master branch of ResearchKit.
> 
> `pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'`

I had to use the `Stable` version due to master's UI bugs. So, I rewrote everything from scratch and it worked.

**Comment by Venaseph** [comment]
Is there any solution to this that allows for continued use of 2.0?

**Comment by bengovernment** [comment]
> > @athanasiospap I ran into this issue a little bit ago, if you're using CocoaPods use the master branch of ResearchKit.
> 
> > 
> 
> > `pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'`
> 
> 
> 
> I had to use the `Stable` version due to master's UI bugs. So, I rewrote everything from scratch and it worked.

You rewrote everything from scratch?

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
