### ISSUE TITLE
taskViewController:stepViewControllerWillAppear: is not getting called

### ISSUE THREAD

**Issue by Vivek205** [ResearchKit/ResearchKit#1411]
I have extended the `ORKTaskViewControllerDelegate` and implemented the method `taskViewController:stepViewControllerWillAppear:` .  I have custom logic inside the method, but it is not getting called whenever I open the survey.

Language: Swift

```
    func taskViewController(_ taskViewController: ORKTaskViewController?, stepViewControllerWillAppear stepViewController: ORKStepViewController?) {
        print("will appear", stepViewController)
    }
```

**Comment by sronglongchhem** [comment]
Does other delegate get called?

**Comment by Vivek205** [comment]
I have converted the arguments method to be non-optional, then it started working.

```
    func taskViewController(_ taskViewController: ORKTaskViewController,
                            stepViewControllerWillAppear stepViewController: ORKStepViewController) {
}
```
