### ISSUE TITLE
Multiple issues in Master when using Xcode 12

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1416]
Having upgraded Xcode to v12 I now find that ResearchKit master will not build. There are LOTS of errors and warnings - too many to manually fix!
Can the maintainers please sort this as I can no longer progress my various projects? Thanks.

**Comment by anoukstein** [comment]
ResearchKit master is configured to build with deployment target iOS 11, if you don't accept the upgrade option to set the minimum build to 12.0, it will work.

**Comment by davwillev** [comment]
Thanks, @anoukstein

**Comment by simon-apple** [comment]
Closing since this has been resolved.
