### ISSUE TITLE
Unable to archive project with ResearchKit but successfully works on Simulator

### ISSUE THREAD

**Issue by KhadijaDaruwala** [ResearchKit/ResearchKit#1431]
I have an old project which uses ResearchKit to collect survey information. The project used pod (`pod 'ResearchKit'`) and all worked fine. Now when I want to deploy this app to Testflight, Apple rejected my app saying **ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability**. After some research, I came across some solutions suggesting to remove researchkit cocoapod and  instead to use the ResearchKit project as follows [http://blog.shazino.com/articles/dev/researchkit-setup-project/](). I followed the steps exactly and was successfully able to run my app on the Simulator. The app worked fine on the Simulator as before but when I tried to archive the app it gives an error saying `'ResearchKit/ResearchKit.h' file not found `
<img width="919" alt="Screenshot 2020-11-25 at 3 04 17 PM" src="https://user-images.githubusercontent.com/16515273/100209133-836f2600-2f2f-11eb-9727-bddf492cefeb.png">

I checked many solutions but none of them worked for me 
[https://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64](URL)
[https://stackoverflow.com/questions/42973992/the-bundle-at-my-app-app-researchkit-researchkit-info-plist-does-not-contain-a](url) 
Not sure if this is a bug in the library or I am doing something wrong, Request you to please help me out

**Comment by hiteshborse12** [comment]
Facing same error. Build ResearchKit and drag and dropped ResearchKit into my project. Help?

**Comment by hchoang** [comment]
@hiteshborse12 @KhadijaDaruwala I think what you are trying to do is to install the master branch. You can achieve that with `pod`, put this in your Podfile
```
pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'
``` 
But please note that the master branch still has a lot of bugs and might not suitable for production.

**Comment by KhadijaDaruwala** [comment]
> @hiteshborse12 @KhadijaDaruwala I think what you are trying to do is to install the master branch. You can achieve that with `pod`, put this in your Podfile
> 
> ```
> pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'
> ```
> 
> But please note that the master branch still has a lot of bugs and might not suitable for production.

Thank you so much. This fixed the issue
