### ISSUE TITLE
Inconsistent text color and background color of the buttons

### ISSUE THREAD

**Issue by GovindPrasadBostonTechnologyCorporation** [ResearchKit/ResearchKit#1436]
Hi all,
I have found the text color and background color of the buttons(ORKContinueButton, ORKBorderedButton) are inconsistent in iOS 14.2. It is observed in iPhone 11 Pro Max. The same is working fine in lower iOS versions.
ResearchKit Version - 2.0.0.

Thank you very much in advance!

![Button Issue](https://user-images.githubusercontent.com/59953327/101728727-e8ed1600-3adc-11eb-948d-2747aa6c469d.PNG)
![Button Previous Versions](https://user-images.githubusercontent.com/59953327/101728748-f2767e00-3adc-11eb-86ae-bf26246457e8.PNG)

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. If you’re still seeing this issue in the latest release, please let us know, otherwise we will close it. 
Thanks

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
