### ISSUE TITLE
Testing ORKTextChoiceOther

### ISSUE THREAD

**Issue by Bersk91** [ResearchKit/ResearchKit#1438]
Good day, 
I have been testing the ORKTextChoiceOther Object, specifically with the one available from the ORKCatalog example available, and I have tried many thing but hasn't been able to input any text in the option with any of the different simulators I used (7, 8, 11). When I want to make use of the option Other from the "Text Choice Question" Option in the catalog, I can select the option and the textbox gets shown on screen, but the text input doesn't get activated so I can't immediately write. If I try to select the textbox to fill it up, instead, the textbox gets hidden.
![image](https://user-images.githubusercontent.com/42716004/101874622-90954180-3bcc-11eb-96ca-265bb7cb6633.png)

Is this behavior related only to the simulators and it will work fine once the app is generated? In any case, is there a way to test the functionality?

Thanks in advance

**Comment by YuriyPertsev** [comment]
Hi, @Bersk91! I found the fix: https://github.com/ResearchKit/ResearchKit/pull/1429 which fixed this problem.

**Comment by Bersk91** [comment]
> Hi, @Bersk91! I found the fix: #1429 which fixed this problem.

Thanks, will work with that 👍

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
