### ISSUE TITLE
Change done button text

### ISSUE THREAD

**Issue by isaacthedeveloper** [ResearchKit/ResearchKit#1441]
Is there a way to change the text of the done button at the end of the Survey to something like save, and add an action to make a post request to an API

**Comment by louie-apple** [comment]
Hi @isaacthedeveloper, 

This is not something that is currently supported by ResearchKit. 
However, if you have a fork of ResearchKit, this is something that you could add locally. 

Let us know if you have any other questions!

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
