### ISSUE TITLE
Cannot build iOS 14.3 app + ResearchKit iOS 11, master branch, in Xcode 12.3 on MacBook Pro M1

### ISSUE THREAD

**Issue by cstrajean** [ResearchKit/ResearchKit#1442]
Greetings,
The build fails due to undefined symbols as "auto-linked libraries cannot be found /used":
ld: warning: Could not find or use auto-linked library 'swiftCore' ...
I looked at the developer forum, but could not find a workable solution.
If I use the ResearchKit stable branch the build succeeds. But the stable branch uses UIWebView and the app will be rejected by the App Store. 
Has anyone encountered and resolved this issue? Please help.
Thank you!

**Comment by one1color** [comment]
did you find any solution?

**Comment by cstrajean** [comment]
No, I haven't.

**Comment by one1color** [comment]
i guess i have same problem here. Let me know if you find any solutions

**Comment by zhang-bo-lilly** [comment]
Any update on this? I'm having same issues here. And the problem still exists even when running Xcode from Rosetta.

**Comment by one1color** [comment]
yes, i think it is not optimized yet

**Comment by raheelsayeed** [comment]
Would really like an  update on this? @Pariecemckinney-apple

**Comment by Pariecemckinney-apple** [comment]
Hello, @raheelsayeed This PR (https://github.com/ResearchKit/ResearchKit/pull/1479) was meant to solve this issue with . Are you still experiencing the issue?

**Comment by raheelsayeed** [comment]
Well, I didn't quite to PR #1470 because I saw some alignment issues on question steps 

See pic below.  I guess I could just make that change myself and revert back when the main branch supports Older iOS versions 


![Simulator Screen Shot - iPhone 13 - 2022-03-14 at 18 33 49](https://user-images.githubusercontent.com/7281949/158271911-3cec0d75-864d-4a9a-878c-25f46d5dfce9.png)
.

**Comment by louie-apple** [comment]
Hi @raheelsayeed,

We haven't heard from you on this issue, has your issue been fixed? If yes, please close it, otherwise please let us know. Thanks!

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. If you’re still seeing this issue in the latest release, please let us know, otherwise we will close it. 
Thanks
