### ISSUE TITLE
Fails to build with Xcode 12.4

### ISSUE THREAD

**Issue by duncangroenewald** [ResearchKit/ResearchKit#1446]
Seems lots of deprecated functions being used.

**Comment by hchoang** [comment]
It's working fine for me on `master`. Are you using `stable` version?

**Comment by duncangroenewald** [comment]
Here is an example:

<img width="1407" alt="Screen Shot 2021-02-24 at 4 59 58 pm" src="https://user-images.githubusercontent.com/13807324/108955173-d2109580-76c1-11eb-82d7-65d0cb9ee1ce.png">

**Comment by duncangroenewald** [comment]
I was using main but switched to master and set build for iOS 11.

I fixed the error above by doing the following:

```
let gender = ORKChoiceQuestionResult(identifier: PersonalDetailsTask.Identifier.gender.rawValue)
        if let sgender = self.gender as NSString? {
            gender.choiceAnswers = [sgender]
        }
```
