### ISSUE TITLE
[iPad] Present consent "Learn More" content in form sheet presentation

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#145]
The "Learn More" content in consent presents modally, full screen.  It should probably be presented in form sheet presentation instead. What it looks like now:

![img_0006](https://cloud.githubusercontent.com/assets/11575859/7504271/c2370cd6-f3fd-11e4-856d-b0ee89b6861b.PNG)

**Comment by rsanchezsaez** [comment]
Why is `bounces` disabled on `ORKConsentReviewController`'s `webView`, but enabled on `ORKConsentLearnMoreViewController`'s `webView`. Shouldn't be the same on both?

**Comment by jwe-apple** [comment]
Fair point, saw your PR.
