### ISSUE TITLE
ORKPasscodeViewController asking for Touch ID

### ISSUE THREAD

**Issue by LuisMFlores** [ResearchKit/ResearchKit#1453]
Has anyone encounter this issue while working with ORKPassCodeViewController?

![IMG_3170](https://user-images.githubusercontent.com/24774992/112181426-d2258780-8bd2-11eb-994d-0f91a8ff7429.jpeg)

Seems that the Touch ID feature is true as default from the pic below, but I thought biometrics didn't care if it was Touch ID vs Face ID.
![Screen Shot 2021-03-23 at 12 21 40 PM](https://user-images.githubusercontent.com/24774992/112181541-ea95a200-8bd2-11eb-8411-65029464dd90.png)

Any helps it's appreciated.

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. If you’re still seeing this issue in the latest release, please let us know, otherwise we will close it. 
Thanks
