### ISSUE TITLE
[iPad] Consent review screen should have insets to match rest of iPad UI

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#146]
The consent review screen's content should be inset horizontally and should have more padding at the top of the document, to match the rest of the iPad UI.

The consent review screen looks like this right now:

![img_0005 1](https://cloud.githubusercontent.com/assets/11575859/7504282/d76d9e1c-f3fd-11e4-8e8c-9a997063dafd.PNG)

**Comment by rsanchezsaez** [comment]
I agree about the horizontal insets.

Are you sure about the top padding? Other iPad *Term and Conditions* screens don't seem to have it:

![300px-ios7setup20](https://cloud.githubusercontent.com/assets/444313/7546685/8930f4d8-f5d8-11e4-8c33-9a9d33dda971.PNG)

**Comment by rsanchezsaez** [comment]
A proposal:

![ios simulator screen shot 8 may 2015 23 21 20](https://cloud.githubusercontent.com/assets/444313/7546715/f5a15202-f5d8-11e4-9572-8369b7a85a7b.png)

**Comment by jwe-apple** [comment]
That looks like too much margin to me. Does that match the other screens?

**Comment by rsanchezsaez** [comment]
The webView matches the margins on the other screens, but the HTML document has a little bit of margin, that's why it looks like that.

Should we remove the margin on the HTML document instead? 

See the difference on *iPhone*, for example:

![ios simulator screen shot 8 may 2015 23 33 16](https://cloud.githubusercontent.com/assets/444313/7546858/dac9390c-f5da-11e4-9e8d-2274fef6af70.png)

![ios7-terms2](https://cloud.githubusercontent.com/assets/444313/7546860/e0dc7340-f5da-11e4-9706-3a390a27fa8c.png)

**Comment by jwe-apple** [comment]
Well, that margin was part of the iPhone spec. As long as you preserve the iPhone appearance it's ok to remove the margin from the HTML.

Is the scroll indicator appearing  int he right place? (i.e. fully right)

**Comment by rsanchezsaez** [comment]
But changing the margin only on iPad feels hackish, doesn't it? The same for expanding the webView so its insets are smaller than in the rest of screens.

The metrically coherent way would be what the screenshot shows.

---

I'll take care of the scroll indicator.

**Comment by jwe-apple** [comment]
All of the margin should *either* be in how you position the webview, *or* in the content. Right now it's in the content; as changed it's going to be in the webview layout if I understand you correctly.

**Comment by rsanchezsaez** [comment]
Yeah, but then if we want to be coherent, on *iPhone* the consent document margin will go from 20 pints (the current CSS `margin` value) to 15 points (as defined by `ORKStandardMarginForView()`, which in my opinion is closer to standard iPhone *Terms and Conditions* screens).

**Comment by jwe-apple** [comment]
Yes, do that.

**Comment by jwe-apple** [comment]
(20 pts sounds wrong)

**Comment by rsanchezsaez** [comment]
:+1:

**Comment by rsanchezsaez** [comment]
This is how it looks after the commits in pull request:

![ios simulator screen shot 9 may 2015 00 32 39](https://cloud.githubusercontent.com/assets/444313/7547342/10c68d68-f5e3-11e4-8296-f4ddb979797a.png)

![ios simulator screen shot 9 may 2015 00 33 22](https://cloud.githubusercontent.com/assets/444313/7547341/10a31fd6-f5e3-11e4-9d52-420905afaefe.png)

Great feedback, as always.

**Comment by jwe-apple** [comment]
Great work!
