### ISSUE TITLE
Code signing "ResearchKit.framework" failed.

### ISSUE THREAD

**Issue by CODER-23** [ResearchKit/ResearchKit#1463]
When I export and try to send to App Store Connect, it doesn’t let me, claiming that code signing the framework failed. I contacted the developer team and tried to use one of my Developer Technical Supports, but to no avail. Could you please help me?

**Comment by erik-apple** [comment]
Can you provide any more information about the error message that you saw? The exact text or a screenshot might be helpful.

**Comment by CODER-23** [comment]
Here is the screenshot and distribution logs.
<img width="1136" alt="Screen Shot 2021-07-01 at 2 43 42 PM" src="https://user-images.githubusercontent.com/46251428/124174787-c3285e00-da7a-11eb-8b77-816c8a404637.png">
[DVTITunesSoftwareService.log](https://github.com/ResearchKit/ResearchKit/files/6750202/DVTITunesSoftwareService.log)
[IDEDistribution.standard.log](https://github.com/ResearchKit/ResearchKit/files/6750204/IDEDistribution.standard.log)
[IDEDistribution.verbose.log](https://github.com/ResearchKit/ResearchKit/files/6750205/IDEDistribution.verbose.log)
[IDEDistributionPipeline.log](https://github.com/ResearchKit/ResearchKit/files/6750206/IDEDistributionPipeline.log)

**Comment by erik-apple** [comment]
Is it possible that you're signing it with your development certificate instead of your distribution certificate? I see some spots in the logs where it's referencing a development cert that I would expect it to use distribution cert.

**Comment by CODER-23** [comment]
No, it wasn't that.

**Comment by CODER-23** [comment]
https://user-images.githubusercontent.com/46251428/124193901-a2b9cd00-da95-11eb-80fc-9ba6a152af13.MOV

**Comment by CODER-23** [comment]
Should I be doing anything different @erik-apple ?

**Comment by erik-apple** [comment]
I don't have very much to go off, but you could try the manually manage signing option towards the end. That'd give a few more options for which certificates to sign with, and you might be able to find the issue. That's what my next step would be.

It looks like you're using CareKit as well. If you're using the `main` branch, you may need to include a HealthKit entitlement for Clinical Records. That's another thing you can try if you haven't setup that entitlement already.

**Comment by CODER-23** [comment]
Ok, I will try.

**Comment by CODER-23** [comment]
@erik-apple for some reason the Clinical Records entitlement is grayed out.
<img width="769" alt="Screen Shot 2021-07-02 at 4 52 55 PM" src="https://user-images.githubusercontent.com/46251428/124327529-0e636f00-db56-11eb-88de-603c22eca7da.png">
Also, when I go to the manual signing, I don't have a provisioning profile for some reason.
<img width="1136" alt="Screen Shot 2021-07-02 at 4 55 17 PM" src="https://user-images.githubusercontent.com/46251428/124327689-49fe3900-db56-11eb-9aa9-ae48c1c8a6a6.png">
Can we please go on a call, where I can share my screen and show you in more depth?

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
