### ISSUE TITLE
Denying Face ID permission, app fails to proceed further

### ISSUE THREAD

**Issue by GovindPrasadBostonTechnologyCorporation** [ResearchKit/ResearchKit#1466]
Hello Team,
Denying Face ID permission at the time of Signin, app fails to proceed further.
The Touch ID error alert is presented and on click of ‘OK’ Button, the alert is dismissed and the app remains in passcode page rather than proceeding further.

In the code for this particular scenario goes to  
ORKPasscodeStepViewController > promptTouchId > [secondStrongSelf makePasscodeViewBecomeFirstResponder]
We are currenctly using iPhone x and iOS 14.5.
I am attaching a video related to the issue.
https://user-images.githubusercontent.com/59953327/131077035-950436b2-6e66-49c4-b359-f5789f2bf4f8.mp4

Thank you,
Govind

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello Team,
Any update on the above issue.
Thanks in advance

**Comment by raheelsayeed** [comment]
Not sure if its resolved, but in `ORKPasscodeStepViewController`, i commented out the `UIAlertController`. There's an issue with strong/weak/mainthread references I think.

**Comment by louie-apple** [comment]
Hi @GovindPrasadBostonTechnologyCorporation,
This issue was recently fixed in the main branch(2.2.8). Please pull main and let us know if it fixes your issue.
Thank you!

**Comment by louie-apple** [comment]
Hi @GovindPrasadBostonTechnologyCorporation,

Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
