### ISSUE TITLE
Some unit tests do not pass when trying to build

### ISSUE THREAD

**Issue by codemechanica** [ResearchKit/ResearchKit#1470]
I was able to successfully build with many warnings. I tried running the unit tests during build and not all tests passed,
I am on an intel processor
Xcode 13
macOS Big Sur

<img width="737" alt="Screen Shot 2021-10-10 at 6 20 12 PM" src="https://user-images.githubusercontent.com/57248794/136690010-0e7814d3-ac7f-4855-9649-f1b0ecea3446.png">
<img width="734" alt="Screen Shot 2021-10-10 at 6 20 24 PM" src="https://user-images.githubusercontent.com/57248794/136690014-5dddf42b-80ef-4aab-b5d8-8236d6ef8915.png">

**Comment by louie-apple** [comment]
Hi @codemechanica,

We recently updated our main branch and our tests were passing there. Do you mind checking again?

**Comment by codemechanica** [comment]
I will try it out tomorrow on the latest version of xcode mac os Ventura. My hardware is still the same. Thanks for letting me know!

**Comment by codemechanica** [comment]
<img width="1444" alt="Screenshot 2023-01-09 at 5 37 29 PM" src="https://user-images.githubusercontent.com/57248794/211268428-88819ee7-03df-4774-881f-46ebb07b6160.png">

OS Ventura 13.1
XCode 14.2

**Comment by louie-apple** [comment]
We currently do not support installing via SPM. Could you try adding ResearchKit to your project using the instructions here: https://github.com/ResearchKit/ResearchKit#adding-the-researchkit-framework-to-your-app

**Comment by louie-apple** [comment]
@codemechanica Have you had a chance to try the instructions in our previous message? Please let us know if this is still an issue.

**Comment by codemechanica** [comment]
So I cloned researchkit and tried running it in Xcode 14.2 and could not run:
<img width="278" alt="Screenshot 2023-01-21 at 11 55 59 PM" src="https://user-images.githubusercontent.com/57248794/213872593-6569e7e2-f06a-4e06-88cf-e88d8bf2f6e6.png">

**Comment by louie-apple** [comment]
Hi @codemechanica, 

Looks like you are running the docs target in Xcode. Please only run that target if you are planning to generate documentation to read. In doin so, you may see the error you saw — if you do not have appledoc installed. To do so, just head to `http://appledoc.gentlebytes.com/` and follow the instructions there, otherwise you can just do `brew install appledoc`

For running the ResearchKit target, please follow these instructions https://github.com/ResearchKit/ResearchKit#building

**Comment by louie-apple** [comment]
<img width="365" alt="Screenshot 2023-01-23 at 3 37 52 PM" src="https://user-images.githubusercontent.com/39536869/214176477-0a4d8ab1-b651-4da9-a1b8-60d47c8a50b5.png">

**Comment by codemechanica** [comment]
I can build but it does have some warnings just to let you know:

<img width="1151" alt="Screenshot 2023-01-24 at 11 48 50 PM" src="https://user-images.githubusercontent.com/57248794/214326233-e90e0d56-9e6b-4138-a0ad-350a9309b19c.png">

**Comment by louie-apple** [comment]
Hi @codemechanica,

We recently pushed a new release, 2.2.9-dev (https://github.com/ResearchKit/ResearchKit/releases/tag/2.2.9-dev) on main. Would you please pull this release and see if it resolves your issue?

**Comment by codemechanica** [comment]
It builds successfully but: 

<img width="1154" alt="Screenshot 2023-02-20 at 2 36 27 PM" src="https://user-images.githubusercontent.com/57248794/220017771-2277cb30-c168-45ba-b251-80bf368606fd.png">

**Comment by louie-apple** [comment]
Hi @codemechanica Thank you for sharing that! 
You’re a highly engaged part of the ResearchKit community, so we’d like to hear from you about your experience using ResearchKit. If you’d be interested in talking shop with us, email researchkit@apple.com and we’ll set up a virtual meeting.
Thanks
ResearchKit Team
