### ISSUE TITLE
Text scale question step, display text UI is not proper

### ISSUE THREAD

**Issue by kp08it953** [ResearchKit/ResearchKit#1472]
Hi All,

For a text scale question step, display text UI is not proper 
In horizontal and vertical both - Text scale Question step(s) you can see scrolling and UI is not rendering properly

**Please refer below video and image**

Refer Video link below => Question step > Text scale > Horizontal > While scrolling complete display text UI is not displayed completely
https://user-images.githubusercontent.com/39984088/139000182-2455705a-cff2-47a0-87d6-c750bad4d707.mov

Refer Image below => Question step > Text scale > Vertical > 1st and 11th display text UI is not displayed completely and scrollable wheel is not aligned with the display text
![138645822-6ff0be2e-69ef-4bc4-9c82-af397eb7006c](https://user-images.githubusercontent.com/39984088/139000206-14a78baa-cd17-49b7-aaeb-7c9f107586bc.png)

 Thanks

**Comment by Pariecemckinney-apple** [comment]
Hello @kp08it953, in the video you shared I'm assuming you're referring to the "current selected value" text above the slider. Were you able to get this fixed locally yet? If not, I'd be happy to work through getting a fix in. This definitely sounds like a good case for a PR submission. 

For the image you provided above I think it would be better if you presented an example of some actual text you were hoping to present. Showing this amount of text with the scale answer probably isn't the best user experience and definitely isn't something expected of this questionStep. Are you hoping to use the same amount of text as shown in the image?

**Comment by kp08it953** [comment]
Hello @Pariecemckinney-apple 
Yes, In Video I am referring to current selected value should be visible properly and changed according to selection
I am not able to get fix for it as of now, please look into it

For image we'll try to add some less text within/about 100 characters, should that work fine?

**Comment by louie-apple** [comment]
Hi @kp08it953,
Were you able to work around this issue?

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
