### ISSUE TITLE
Text Scale range shows -0 (negative zero) when set to Continuous Scale

### ISSUE THREAD

**Issue by kp08it953** [ResearchKit/ResearchKit#1474]
Hi All,

For a continuous scale question step, display text is rendering negative zero(-0), Please refer to video

Text Scale widget shows negative zero on ranges that have positive and negative values. Horizontal shown in example. Vertical Scale has the same problem.

Create Continuous Scale text question with a positive and negative range (-5 to 5)
Move slider toward negative. You'll notice -0 (negative zero) appear between 0 and -1.
Expected: Transition from 0 to -1 without -0

https://user-images.githubusercontent.com/39984088/139388173-b31aa4cf-53b7-4a12-b4d6-f60fee7cf961.mov

**Comment by Pariecemckinney-apple** [comment]
Hey @kp08it953 thanks for calling this out. I'll try to reproduce and get back to you soon!

**Comment by kp08it953** [comment]
@Pariecemckinney-apple, Yes please look into it asap, we are waiting for it 
Thanks

**Comment by Pariecemckinney-apple** [comment]
Hello @kp08it953 , I can't seem to reproduce this on my end. What version of RK are you using?

**Comment by kp08it953** [comment]
Hello @Pariecemckinney-apple, I am using version 2.0.0 of ResearchKit

**Comment by kp08it953** [comment]
Hello @Pariecemckinney-apple, are you able to reproduce and fix it? Please provide update on the status

**Comment by Pariecemckinney-apple** [comment]
@kp08it953 Still unable to reproduce this on our end. Can you send over the code you're writing to initialize the step?

**Comment by kp08it953** [comment]
Hello @Pariecemckinney-apple, This is a continuous scale question, we are initialising it with below parameters 
withMaximumValue: 5,
minimumValue: -5,
defaultValue: 2,
vertical: false,
maximumFractionDigits: 0,
maximumValueDescription: Much More,
minimumValueDescription: Much Less

please find the image below for code snippet
![image](https://user-images.githubusercontent.com/39984088/146734300-7e57438d-1689-4921-a3b5-cb628abb8060.png)

But UI still represents -0 value when we scroll as shown in initial video when we opened this issue

**Comment by Pariecemckinney-apple** [comment]
Closing due to no response.
