### ISSUE TITLE
Text Scale default value not set (slider not visible, when we have multiple steps and we do 'Save for Later')

### ISSUE THREAD

**Issue by kp08it953** [ResearchKit/ResearchKit#1475]
Hi All,

In the iOS app, when a Text Scale response is created with a default value in, the slider button is not visible. refer video below

To Reproduce:
As shown in video at third step create form step with multiple text scale questions
When we go to third step and save for later, when we come back there are no default values
Expected: slider button set to default value to be visible

https://user-images.githubusercontent.com/39984088/139398563-8aef3751-af0e-484d-b0ec-b8f01dfe5853.mov

**Comment by Pariecemckinney-apple** [comment]
hello @kp08it953, can you show the code where you're initializing the task the 2nd time? Are you passing in the saved data from the previous task that was ended early?

**Comment by kp08it953** [comment]
Hello @Pariecemckinney-apple, We have found a solution for it, no need to look into this issue anymore.

Sorry for inconvenience
