### ISSUE TITLE
iPhone SE - Accessibly Text Size set to max

### ISSUE THREAD

**Issue by AH24** [ResearchKit/ResearchKit#1477]
Seeing some issues on ResearchKit when users on the iPhone SE (2nd Gen) have their text size set to the max amount.

**Comment by Pariecemckinney-apple** [comment]
Hello @AH24, would you be able to post some images of what you're seeing? and also exactly what part of the framework (ie. formStep, questionStep, etc)? 

Thanks for opening this!

**Comment by Pariecemckinney-apple** [comment]
Closing due to no response.
