### ISSUE TITLE
[iPad] Two finger tapping task vertical spacing improvement

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#148]
The vertical spacing of the two finger tapping active task UI is too compressed. iPad specific metrics should be introduced! Example:

![img_0007](https://cloud.githubusercontent.com/assets/11575859/7504340/4f3a0ef8-f3fe-11e4-8aa5-ab9696b3973d.PNG)

**Comment by edelabar** [comment]
What is the desired location?  Midway between the current location and total taps counter?

**Comment by jwe-apple** [comment]
Make a first pass; it'll get reviewed next week. I would possibly see if it can be done just by adjusting existing metrics first, rather than making a larger change that might break the iPhone specs.

**Comment by jwe-apple** [comment]
As a guess, probably somewhere above center

**Comment by edelabar** [comment]
Fixed when #164 was merged.

**Comment by jwe-apple** [comment]
ta
