### ISSUE TITLE
Image display issue in Dark Mode: knee range of motion

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1481]
@erik-apple @srinathtm-apple 

I spotted an issue with the recently modified version of the predefined knee range of motion active task ('Combines the instructions steps into a single instruction step with body items on iOS 13 and later.' #1459).

I happened to be testing some of my tasks using Dark Mode and spotted that the image in the top left of the screen wasn't displaying properly, and thought I ought to report this:

![darkmode](https://user-images.githubusercontent.com/35876659/145783597-c3a3f51c-6aa0-44d0-b627-5c3793f53a7f.png)

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
