### ISSUE TITLE
Umbrella for module 'ResearchKit' already covers this directory

### ISSUE THREAD

**Issue by smundada** [ResearchKit/ResearchKit#1483]
I'm getting this error when I try to build CardinalKit, another open source repo that uses ResearchKit (https://cardinalkit.org/cardinalkit-docs/). They suggested reaching out here since this seems to be a build error related to ResearchKit that only a few laptops are running into. 

I've attached a screenshot of what this error looks like, along with a build output file
![image](https://user-images.githubusercontent.com/24428373/151098588-323aed93-af6b-4209-a5b2-4c8b1a98483e.png)

**Comment by Pariecemckinney-apple** [comment]
Hello @smundada! Would you mind telling me what Xcode version you're using and could you also list out steps you went through before you got to this error?

**Comment by smundada** [comment]
I realized that this issue is due to Pods and not ResearchKit, so I'm closing the issue

**Comment by thereeceshow** [comment]
Hi @smundada. What was your solution?  I'm having a similar issue.

**Comment by ApolloZhu** [comment]
Adding ResearchKit as a development pod seems to be a possible workaround, i.e. using :path to specify a local copy of ResearchKit.
