### ISSUE TITLE
Unable to push my project with ResearchKit

### ISSUE THREAD

**Issue by Ahmed-Mujahid** [ResearchKit/ResearchKit#1484]
i am unable to push my project with ResearchKit. when ever i push or share project it seems to only have reference of the researchKit but not the file. 

Is there a way to share project with researchKit. Because i have done some minor changes to localised files ect
![Screenshot 2022-01-26 at 9 54 04 PM](https://user-images.githubusercontent.com/45769608/151210422-fe54f092-d543-49c2-a955-9cec5ba0b7ea.png)

**Comment by Pariecemckinney-apple** [comment]
Hello @Ahmed-Mujahid, on your local machine are you actually placing/copying ResearchKit within your project's directory or just dragging and referencing it? My guess would be that the latter is happening.
