### ISSUE TITLE
Accessibility bug: Skip button disappears when increasing contrast

### ISSUE THREAD

**Issue by raheelsayeed** [ResearchKit/ResearchKit#1494]
On iOS 14, when increasing contrast (in  Settings>Accesssibilty), the skip button disappears BUT it **does exist** there
Any quick fix to override that effect? 

Also, on iOS 14, 15 the tintcolor is not consistent. I know that theres a new 15 compatible main branch, but for now-- any ideas on quickly fixing this?

**Comment by Pariecemckinney-apple** [comment]
Hello @raheelsayeed ,
 
Thanks for raising this issue. We’re currently looking into it. I’ll ping you as soon as our test pass is done!

For the tint color issue, where are you seeing this specifically? If you could provide screen shots it would be very helpful!

**Comment by vishnuravi** [comment]
Hey @Pariecemckinney-apple and @raheelsayeed,

I have encountered the issue regarding tint color not being consistent as well. I have attached an example below in which the tint color of the continue button has been set to dark red, but changes to blue after the first step. Interestingly, when attempting to end the task, it returns to dark red:

https://user-images.githubusercontent.com/1212163/173903716-5a1163b0-1c3b-45e9-9dfc-d57ba179ffd1.MP4

**Comment by Pariecemckinney-apple** [comment]
Hello @vishnuravi, thanks for posting this example. Its helps a lot! We’ll take a look and let you know once a fix has been identified.

**Comment by louie-apple** [comment]
We recently merged a pr(https://github.com/ResearchKit/ResearchKit/pull/1519) that fixes this and we haven’t heard from you on this issue, has your issue been fixed? If yes, please close it, otherwise please let us know. Thanks!

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
