### ISSUE TITLE
Present the survey question with conditions

### ISSUE THREAD

**Issue by zxcheergo** [ResearchKit/ResearchKit#1495]
Hello, I am new to ResearchKit framework and I need to develop a feature that can present the survey based on conditions. For example, we detect that the participants experienced several special events (fetched from the dataset) and want them to report their feelings with the survey. Additionally, we also want to present some video clips along with the survey. Can you tell me if these two requirements can be realized?

**Comment by Pariecemckinney-apple** [comment]
Hello @zxcheergo, if I'm understanding correctly the conditions you're looking for won't be checked within ResearchKit itself. With that being said, it would be up to you to add the logic at the app level and present a ResearchKit survey whenever you like. 

In terms of the video clips along with the survey, we have a ORKVideoInstructionStep that can be used to present a video via ResearchKit before a particular step/questions is presented. I hope this helps and please let me know if anything else is needed!

**Comment by zxcheergo** [comment]
> Hello @zxcheergo, if I'm understanding correctly the conditions you're looking for won't be checked within ResearchKit itself. With that being said, it would be up to you to add the logic at the app level and present a ResearchKit survey whenever you like.
> 
> In terms of the video clips along with the survey, we have a ORKVideoInstructionStep that can be used to present a video via ResearchKit before a particular step/questions is presented. I hope this helps and please let me know if anything else is needed!

Thanks for your help. I solved the problem, just as your suggestions.

**Comment by zxcheergo** [comment]
> Hello @zxcheergo, if I'm understanding correctly the conditions you're looking for won't be checked within ResearchKit itself. With that being said, it would be up to you to add the logic at the app level and present a ResearchKit survey whenever you like.
> 
> In terms of the video clips along with the survey, we have a ORKVideoInstructionStep that can be used to present a video via ResearchKit before a particular step/questions is presented. I hope this helps and please let me know if anything else is needed!

I have an another question: When and how could I refresh the OCKDailyTaskView and the related TaskView? I need to modify the tasks presented according to the conditions. Now I need to pull down manually to refresh the page but how to do that automatically?
