### ISSUE TITLE
Navigating back within a OKRPageStep

### ISSUE THREAD

**Issue by raheelsayeed** [ResearchKit/ResearchKit#1496]
Reopening an earlier issue #921 ; is there reason why back navigation within a `ORKPageStep.steps` was not allowed? seems counter intuitive, specially when its used to finish a bunch of tasks in one go-- however with the same navigation rules.

**Comment by louie-apple** [comment]
Thank for raising this issue. While we're investigating why back navigation isn't working here, would you be able to switch over to using `ORKNavigableOrderedTask` instead? Here's an example of switching from pageStep to navigableOrderedTask.

`     let stepOne = ORKQuestionStep(identifier: "stepOne", title: "Question", question: "Which is the purpose of this Study?", answer: ORKAnswerFormat.booleanAnswerFormat())
       
        // Failure step
        let failureStep = ORKInstructionStep(identifier: "failureStep")
        failureStep.title = "Try again"
                
        // Success step
        let successStep = ORKCompletionStep(identifier: "successStep")
        successStep.title = "Great Job!"
        

        let steps = [stepOne, successStep, failureStep]

        let task = ORKNavigableOrderedTask(identifier: "task", steps: steps)

        
        // Creating predicates
        let resultSelector = ORKResultSelector(stepIdentifier: "stepOne", resultIdentifier: "stepOne")
        let stepOneYes = ORKResultPredicate.predicateForBooleanQuestionResult(with: resultSelector, expectedAnswer: true)
        let stepOneNo = ORKResultPredicate.predicateForBooleanQuestionResult(with: resultSelector, expectedAnswer: false)

        let navigationRule = ORKPredicateStepNavigationRule(resultPredicates: [stepOneYes, stepOneNo], destinationStepIdentifiers: ["successStep", "failureStep"], defaultStepIdentifier: nil, validateArrays: false)
        
        // Creating navigation rule and setting it to task
        task.setNavigationRule(navigationRule, forTriggerStepIdentifier: "stepOne")
        
        return task`

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
