### ISSUE TITLE
Support for macCatalyst

### ISSUE THREAD

**Issue by Hengyu** [ResearchKit/ResearchKit#1497]
Hi team,

For the `ResearchKit` framework, do we have plan to adapt it for the macOS platform?

When I turn on the build for macCatalyst option in the build settings of this project, there's only one build error and looks like it could be easily available for macCatalyst if we could resolve that error.

In `ORKEAGLMoviePlayerView.m`:
<img width="790" alt="1" src="https://user-images.githubusercontent.com/4032674/161513912-57720b98-13e6-4b4b-9a8f-5aa661f03186.png">

**Comment by SwiftNativeDeveloper** [comment]
The HealthKit APIs, while they may be available in a catalyst build (not tested), the HKHealthStore will certainly report that HealthKit is not available. Same for on iPad. HealthKit is only functional on iPhone and Apple Watch as it stands with current OS releases.

Are the portions of ResearchKit you're looking to use independent of the Health App being available?

**Comment by Hengyu** [comment]
hi @SwiftNativeDeveloper ,

Thanks for the response!

> Are the portions of ResearchKit you're looking to use independent of the Health App being available?
I'm looking for a ResearchKit portion which supports to be deployed on macCatalyst system. We don't actually need the health app integration. We need the else research functionalities to construct the research page.

**Comment by Pariecemckinney-apple** [comment]
Hello @Hengyu ,

There is currently no support for running ResearchKit on macOS, even with Mac Catalyst. ResearchKit is built specifically for running on iPhones and iPads at the moment and relies heavily on APIs provided by iOS.

**Comment by Pariecemckinney-apple** [comment]
Discussion appears to have ended. Closing!
