### ISSUE TITLE
Split ORKDataLoggerTests and ORKDataLoggerManagerTests to a new test target?

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#150]
Not sure if this is a good idea. 

`ORKDataLoggerTests` and `ORKDataLoggerManagerTests` are by far the slowest tests. This is quite inconvenient for people developing with slower machines. Would it be ok to separate them to a different *test target*?

**Comment by jwe-apple** [comment]
Just run individual tests you want to run with the little arrow icon next to the test in the editor! Magic.

**Comment by rsanchezsaez** [comment]
Ha! Didn't know that, thanks.
