### ISSUE TITLE
Access apple health data - API

### ISSUE THREAD

**Issue by alrojo** [ResearchKit/ResearchKit#1500]
I'm a clinical researcher at Stanford University and I want to use apple health data for my study. I have a group of people and I would like to access their biometrics (step counts and other features collected by smart watches). I'd prefer that the user doesn't have to manually extract and send their data. What options do I have for collecting and centralizing the data for my study?.

**Comment by alrojo** [comment]
Hi @Pariecemckinney-apple that seems to be a SDK that requires an app in app store to access. Is there any APIs that allows access through web requests such as OAUTH 2.0?

**Comment by Pariecemckinney-apple** [comment]
@alrojo Correct, the only way to fetch user health or exercise metrics that is stored within HealthKit has to be done via an IOS app currently. Once you securely access this data via the APIs provided by Apple on the users device (via your app) you're free to transport that data to any secure server of your choosing.

**Comment by alrojo** [comment]
I assume the lack of a web API is to avoid data leakage. Unfortunately, for researchers like me that cannot afford developing a custom app for my clinical studies I would have to rely on third-party developed apps (of which most have predatory data policies) to extract the data from Apple Health. Effectively mitigating the protective effect of not having a web API. That's quite unfortunate. Thanks for your quick responses @Pariecemckinney-apple

**Comment by raheelsayeed** [comment]
There are some frameworks like cardinalkit or smartmarkers that might help you get started, but still would involve someone Making the app.
