### ISSUE TITLE
ORKAnswerFormat.textAnswerFormat UI is treated in the same question and multiple choice

### ISSUE THREAD

**Issue by tyne-admin** [ResearchKit/ResearchKit#1503]
I currently have a ORKFormStep and append my questions as different ORKFormItems depending on whether they are a multiple choice question or a text-based question. In the 2.0.0 cocoa pod version, it used to work fine (The questions were separated). When I use the most-recent (non-stable) version, it seems like the text-based question isn't given its own question box. 

here is a snippet of my code:

```
        let formStep = ORKFormStep.init(identifier: "form", title: "Questions", text: "Complete the survey with the best answer for each question.")
        var formItems = [ORKFormItem]()
        
            for (index, question) in questionList.questionList.enumerated() {
                if question.questionType == "yesNo" {
                    let item = ORKFormItem(identifier: "q\(index)", text: question.question, answerFormat: ORKAnswerFormat.booleanAnswerFormat(), optional: false)
                    formItems.append(item)
                } else if question.questionType == "textBased" {
                
                    let item = ORKFormItem(identifier: "q\(index)", text: question.question, answerFormat:   ORKAnswerFormat.textAnswerFormat(withMaximumLength: 100), optional: false)
                    formItems.append(item)
          }
```

And here is an example image:
![Screen Shot 2022-06-02 at 5 24 57 PM](https://user-images.githubusercontent.com/92927021/171761809-8f705b9e-8ee1-48bf-a3d0-21cf4671a409.png)

The  "If yes..." question isn't being treated as question 12, but rather, embedded inside question 11

**Comment by Pariecemckinney-apple** [comment]
Hello @tyne-admin, thanks for posting this issue. We’ve tracked the issue internally and will update you as soon a fix is identified!

**Comment by kwanhlee** [comment]
Hi @Pariecemckinney-apple, this is my personal GitHub account for the Original Poster of this issue.

I have fixed the issue and made a pull request. Please take a look. It seems like there have been a bug in the code where a boolean value was set to NO instead of YES (which is specified in the header file)

**Comment by kwanhlee** [comment]
@Pariecemckinney-apple,
Sure! But I think it may be a good idea to update the header file to mention that the default value is a NO. 
I won't make a PR for that since it's so trivial, but it would be nice to be included in the next version for people reading the documentation.
