### ISSUE TITLE
iOS 16 Compatibility

### ISSUE THREAD

**Issue by Brett-Best** [ResearchKit/ResearchKit#1509]
Is it expected that any updates will be made to support iOS 16?
It seems this project is a bit abandoned?

**Comment by jstemmle-apple** [comment]
Hi.  Thanks for reaching out.

ResearchKit is still an active project. We are committed to ensuring it works with  iOS 16.  If you see any problems or issues, please do report them here by filing issues on GitHub.

**Comment by Brett-Best** [comment]
https://github.com/ResearchKit/ResearchKit/pull/1491

I’m seeing an issue with this although not in fullscreen mode, the fix in that PR works

**Comment by louie-apple** [comment]
@Brett-Best  Not sure what issue you had, but did the PR we merged (https://github.com/ResearchKit/ResearchKit/pull/1516) (which also addressed issue 1491) fix your issue too?

**Comment by Brett-Best** [comment]
I can’t seem to get it to compile now using cocoapods.

**Comment by Brett-Best** [comment]
<img width="517" alt="Screen Shot 2022-11-10 at 5 39 28 am" src="https://user-images.githubusercontent.com/6104381/200913768-78bf9588-f381-4fb2-b974-aaede72f14fa.png">
@louie-apple

**Comment by Brett-Best** [comment]
CC: @Pariecemckinney-apple

**Comment by louie-apple** [comment]
> <img alt="Screen Shot 2022-11-10 at 5 39 28 am" width="517" src="https://user-images.githubusercontent.com/6104381/200913768-78bf9588-f381-4fb2-b974-aaede72f14fa.png">
> 
> @louie-apple

Hi @Brett-Best, 

Here are our latest CocoaPods Installation guidelines:

 ------------
 For latest stable release

 ```
 pod 'ResearchKit'
 ```
 The latest early development release based off of main is
 ```
pod 'ResearchKit',  :git => 'https://github.com/ResearchKit/ResearchKit.git', :tag => '2.1.1-dev'

 ```
 or  for the latest early development release based off of main

 ```
   pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'main'
 ```

**Comment by Brett-Best** [comment]
Thanks the last few commits made a couple of days ago fixed this for me.
I’m still getting the warnings about the asset catalog.

**Comment by louie-apple** [comment]
No problem! Are these warnings around `The Image set name "" is used by multiple image sets` ? 
If so, that can be fixed by renaming the image. If you have a pr with these fixes, we would be happy to take a look!

Thanks!

**Comment by Brett-Best** [comment]
This also appears to be fixed now.
