### ISSUE TITLE
Using ResearchKit in a C/C++ App

### ISSUE THREAD

**Issue by josharmenta** [ResearchKit/ResearchKit#1510]
Our backend is written in C and our front end is being written in QML. What's the best way to integrate QML with ResearchKit? We're primarily interested in using ResearchKit for survey collection; for compliance reasons we are still collecting paper consent forms.

**Comment by louie-apple** [comment]
We do not have a QML bridge to the ResearchKit UI. As ResearchKit is open source, the best integration for your project might mean building that bridge.
