### ISSUE TITLE
Dynamic Skip Logic

### ISSUE THREAD

**Issue by majidsaleem105** [ResearchKit/ResearchKit#1512]
Hello Everyone,

I've developed 100+ surveys from simple to complex level surveys. We have developed complex surveys using the skip login as well.

We got a new situation to develop a survey with skip logic where we want to utilize the answers from `Survey A` to skip a few questions from `Survey B`.

**For Example:**
Survey A contains questions like:
Q. When do you plan to complete your home assignment work today?
a.	Morning
b.	Afternoon
c.	Evening
d.	Today is a planned off day/rest day 

So, if the person chooses option D as an answer from Survey-A. We want to skip a set of questions from Survey B.

Any suggestion is highly appreciated.

Thanks,
- Majid S.

**Comment by louie-apple** [comment]
Hi @majidsaleem105,

Very cool to hear you have developed so many surveys using ResearchKit. If you don’t mind sharing what you are working on, we would love to learn more about what you do and how we can support you further!
To your point here, ResearchKit makes it very easy to to customize your surveys and adding skip logic as well.
You have two approaches here.
One, is to use our ORKNavigationRules
It’s very easy to setup.
You would create all of the steps you wanted to show in a task and create a ORKNavigableOrderedTask wrapping all of your steps

```
    let eligibilityTask = ORKNavigableOrderedTask(identifier: String(describing: Identifier.eligibilityTask), steps: [
      introStep,
      formStep,
      ineligibleStep,
      eligibleStep
      ])
```

From there, you can apply rules based on certain replies within that Task like this
```
    var resultSelector = ORKResultSelector(stepIdentifier: String(describing: Identifier.eligibilityFormStep), resultIdentifier: String(describing: Identifier.eligibilityFormItem01))
    let predicateFormItem01 = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "Yes" as NSString)

    let predicateRule = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [ (predicateFormItem01, String(describing: Identifier.eligibilityEligibleStep)) ])
     
    eligibilityTask.setNavigationRule(predicateRule, forTriggerStepIdentifier: String(describing: Identifier.eligibilityFormStep))
```

We are essentially saying that for the `eligibilityTask` on the step `formStep` which has a `formItem` with the id of `Identifier.eligibilityFormItem01` if the result is a string that is `Yes` then we will send them to the `eligibleStep` and skip the `ineligibleStep`
So in your examples, what you can do is create SurveyA and SurveyB as separate `ORKFormSteps` in the same `ORKNavigableOrderedTask` and have navigation rules set to skip other steps that you wish to customize. You can also break out each survey to different `ORKFormSteps` around the customization you are looking for.
The other option here, is to dynamically create your surveys.
Consider wrapping your form creation into a function that can be customized:

```
  func customTask(skipSteps: Bool = false) -> ORKFormStep {
    let formStep = ORKFormStep(identifier: String(describing: Identifier.eligibilityFormStep))
    formStep.title = NSLocalizedString("Eligibility", comment: "")
    formStep.isOptional = false
     
    // Form items
    let textChoices: [ORKTextChoice] = [ORKTextChoice(text: "Yes", value: "Yes" as NSString), ORKTextChoice(text: "No", value: "No" as NSString), ORKTextChoice(text: "N/A", value: "N/A" as NSString)]
    let answerFormat = ORKTextChoiceAnswerFormat(style: ORKChoiceAnswerStyle.singleChoice, textChoices: textChoices)
     
    let formItem01 = ORKFormItem(identifier: String(describing: Identifier.eligibilityFormItem01), text: exampleQuestionText, answerFormat: answerFormat)
    formItem01.isOptional = false
    let formItem02 = ORKFormItem(identifier: String(describing: Identifier.eligibilityFormItem02), text: exampleQuestionText, answerFormat: answerFormat)
    formItem02.isOptional = false
    let formItem03 = ORKFormItem(identifier: String(describing: Identifier.eligibilityFormItem03), text: exampleQuestionText, answerFormat: answerFormat)
    formItem03.isOptional = false
     
    if skipSteps == true {
      formStep.formItems = [
        formItem01,
        formItem03
      ]
    } else {
      formStep.formItems = [
        formItem01,
        formItem02,
        formItem03
      ]
    }
     
    return formStep
  }
```

So then what you can do is once SurveyA is done, is take in the result, parse the value, and then see if it meets the criteria you need to skip, and pass in the corresponding value to the customTask function. Like this example:
```
let surveyA = ORKOrderedTask(steps:[customTask(skipSteps: false)]))

// present surveyA, and get results 

let surveyB = ORKOrderedTask(steps:[customTask(skipSteps: (parsedResult.meetsCritera()) == true)]))
```

Please let us know if you have any questions!

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
