### ISSUE TITLE
IOS 16 Bug: dBHL Tone Audiometry screen freezes after checking background noise.

### ISSUE THREAD

**Issue by enwq** [ResearchKit/ResearchKit#1513]
Setting
ResearchKit: 
stable branch
IOS: 
16.0 (iPhone 14 Pro device and simulator)
15.7 (iPhone SE device)

This bug only happened on my iPhone 14 Pro device running IOS 16.0.2
When performing the dBHL Tone Audiometry active task, after completion of background noise check (step 2 of 6, see attached screenshot), the screen froze with debugger output

```
[as_client]     AVAudioSession_iOS.mm:2370  Failed to set category, error: 'what'
Setting AVAudioSessionCategory failed with error message: "The operation couldn’t be completed. (OSStatus error 2003329396.)"
```

The error messages point to the following code in `ORKEnvironmentSPLMeterStepViewController.m`
```
- (void)resetAudioSession {
    NSError *error = nil;
    [[AVAudioSession sharedInstance] setCategory:_savedSessionCategory mode:_savedSessionMode options:_savedSessionCategoryOptions error:&error];
    [[AVAudioSession sharedInstance] overrideOutputAudioPort:AVAudioSessionPortOverrideNone error:&error];
    if (error) {
        ORK_Log_Error("Setting AVAudioSessionCategory failed with error message: \"%@\"", error.localizedDescription);
    }
```
A similar issue has been posted in stackoverflow: [iOS 16 Beta 5 AVAudioSession setCategory produces strange error 'what'](https://stackoverflow.com/questions/73349619/ios-16-beta-5-avaudiosession-setcategory-produces-strange-error-what), suggesting that IOS 16 has added requirements for setting categories of AVAudioSesson.

Thank you very much for your help!

![IMG_0098](https://user-images.githubusercontent.com/54544609/193691634-0e308c58-6e2c-4558-96be-133967fc65ec.PNG)

**Comment by louie-apple** [comment]
Hi enwq, 
We believe this issue was recently fixed in the main branch. Please pull main and let us know if it fixes your issue.
Thank you!
