### ISSUE TITLE
App Store Connect Operation Error

### ISSUE THREAD

**Issue by Brett-Best** [ResearchKit/ResearchKit#1514]
When uploading to ASC using Xcode 14.1 RC I’m getting the below error:
> The app references non-public selectors in `Payload/BnTx Interact iOS.app/Frameworks/ResearchKit.framework/ResearchKit: passcodeViewControllerDidCancel:`

**Comment by mayawald3** [comment]
I am having the same issue. Did you find any solution?

**Comment by louie-apple** [comment]
We’ve heard about public reports of this (not related to ResearchKit), can you confirm that you are seeing a blocking error and not a warning? A warning wouldn't block acceptance into the App Store.

**Comment by mayawald3** [comment]
It is a warning, but when the build is uploaded to App Store Connect, it says the binary is invalid. Also, the build only shows in the TestFlight tab but not at all in the App Store tab.

**Comment by Brett-Best** [comment]
<img width="774" alt="Screen Shot 2023-01-12 at 7 58 43 am" src="https://user-images.githubusercontent.com/6104381/211916509-1a45900e-69b1-4c1a-9c57-f3200a31820f.png">
So the dialog is a bit misleading, it says “error” but the status behind the dialog says “uploaded with warnings”. I am able to select the build in ASC fine -- just hope it doesn’t turn into a blocking issue in the future.

**Comment by louie-apple** [comment]
Thank you for the additional info here. If it does turn into a blocking issue, feel free to re-open this. In the meantime, we will be investigating these warnings!
