### ISSUE TITLE
Module compiled with Swift 5.7 cannot be imported by the Swift 5.7.1 compiler: 

### ISSUE THREAD

**Issue by zxcheergo** [ResearchKit/ResearchKit#1518]
How to fix this problem? The xcode automatically updated and I failed to compile my project.

**Comment by cbaker6** [comment]
Did you try to clean your build folder? "Product-> Clean Build Folder" and then rebuild your project.

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
