### ISSUE TITLE
Keyboard Safe Area Covers Input Fields

### ISSUE THREAD

**Issue by PSchmiedmayer** [ResearchKit/ResearchKit#1520]
Dear ResearchKit team,

We want to report a UI issue we have been experiencing with ResearchKit while working on the [ResearchKitOnFHIR](https://github.com/CardinalKit/ResearchKitOnFHIR) project.
In our testing, the keyboard safe area sometimes covers the input field and leaves a large room between the keyboard and the control buttons (skip and next). Can be reproduced using the [Number Example](https://github.com/CardinalKit/ResearchKitOnFHIR/blob/main/Sources/FHIRQuestionnaires/Resources/NumberExample.json) questionnaire and the iOS simulator in the ReserachKitOnFHIR example app:
<p float="left">
  <img width="320" alt="KeyboardCoversInputField" src="https://user-images.githubusercontent.com/28656495/201822320-12fcb523-f424-4aac-b7b4-6fc3d12757f8.png">
  <img width="320" alt="LargeSpacingBetweenKeyboardAndButtons" src="https://user-images.githubusercontent.com/28656495/201822327-afa0edd1-1bb9-45b5-b7b1-dc42dc9f8ec7.png">
</p>

Thanks a lot for taking a look at the issue and enabling us in using ResearchKit in our projects!

CC @vishnuravi

**Comment by louie-apple** [comment]
Hi @PSchmiedmayer,

Thank you for sharing this with our team, we took a look at your repo and we noticed in your example app, you set your `ORKOrderedTaskView` with an `ignoreSafeArea` call  https://github.com/CardinalKit/ResearchKitOnFHIR/blob/50ccf6b6225e7e8ffca29ba07e33d9d5ad4bcf03/Example/ExampleApp/Questionnaire/QuestionnaireView.swift#L25 -- please add another line there. 

` .ignoresSafeArea(.keyboard, edges: .bottom)`

This will keep the `Next toolbar` pinned to the bottom of the screen.

**Comment by vishnuravi** [comment]
Hi @louie-apple,

The solution you recommended resolves our issue! Thank you so much for taking the time to look into it!

Best,
Vishnu and Paul
@StanfordBDHG

**Comment by louie-apple** [comment]
Glad to hear its working!
