### ISSUE TITLE
Accent Color Usage in ResearchKit

### ISSUE THREAD

**Issue by PSchmiedmayer** [ResearchKit/ResearchKit#1521]
Dear ResearchKit team,

We want to report a UI issue we have been experiencing with ResearchKit while working on the [ResearchKitOnFHIR](https://github.com/CardinalKit/ResearchKitOnFHIR) project.
In our testing, the accent color of the application is not correctly transferred to all UI element such as pickers (blue checkmark) and buttons (Next/Done and Skip Buttons). The bug can be reproduced using the [Number Example](https://github.com/CardinalKit/ResearchKitOnFHIR/blob/main/Sources/FHIRQuestionnaires/Resources/NumberExample.json) and [Skip Logic Example ](https://github.com/CardinalKit/ResearchKitOnFHIR/blob/main/Sources/FHIRQuestionnaires/Resources/SkipLogicExample.json)questionnaires and the iOS simulator in the ReserachKitOnFHIR example app.

<p float="left">
<img width="320" alt="ButtonsAndCheckboxesAccentColor" src="https://user-images.githubusercontent.com/28656495/201822880-f9e57d51-bfcf-47ba-aab2-8053d493e426.png">
<img width="320" alt="LargeSpacingBetweenKeyboardAndButtons" src="https://user-images.githubusercontent.com/28656495/201822883-116a222b-bffb-4c91-9dac-ad0f7f336a1a.png">
</p>

Thanks a lot for taking a look at the issue and enabling us in using ResearchKit in our projects!

CC @vishnuravi

**Comment by cbaker6** [comment]
#1519 should fix this

**Comment by louie-apple** [comment]
Hi @PSchmiedmayer,

Thank you for sharing this with us, we can see it on our end as well. We recently merged: https://github.com/ResearchKit/ResearchKit/pull/1519 which fixes your issue. 

Please merge that into your fork, and let us know if you have any other questions. 

Thank you!

**Comment by PSchmiedmayer** [comment]
Hi @louie-apple,

Thank you for sharing the update and merging the PR! I have updated our fork and will update the Swift Package accordingly. I will get back to you if we can reproduce the fix in our project.

**Comment by PSchmiedmayer** [comment]
Hi @louie-apple,

I have updated the fork at [StanfordBDHG/ResearchKit](https://github.com/StanfordBDHG/ResearchKit) to the latest commits, created a pre-release ([2.1.1-main](https://github.com/StanfordBDHG/ResearchKit/releases/tag/2.1.1-main)) and used that version in the latest commit of [StanfordBDHG/ResearchKitOnFHIR](https://github.com/StanfordBDHG/ResearchKitOnFHIR).

Nevertheless the buttons don't use the accent color of the application and mainly uses the system blue color. Nevertheless it sometimes switches to the accent color. You can reproduce this when going into the example application at  [StanfordBDHG/ResearchKitOnFHIR](https://github.com/StanfordBDHG/ResearchKitOnFHIR) and open the "Skip Logic Example". You can reproduce the Screenshots 2-4 by going into the "Number Validation Example" survey (screenshot  2), enter an invalid input ("a") and the button uses the inactive accent color (screenshot  3), and then enter a valid entry ("1") and the button uses the accent color (screenshot 4).

<p float="left">
<img width="320" alt="Screenshot1" src="https://user-images.githubusercontent.com/28656495/205430542-b91b943d-fa8e-48cd-82da-a00a941586fe.png">
<img width="320" alt="Screenshot2" src="https://user-images.githubusercontent.com/28656495/205430543-a06dea9e-6bc6-4e88-8421-00112429b630.png">
<img width="320" alt="Screenshot3" src="https://user-images.githubusercontent.com/28656495/205430545-d0a784dc-cce8-4164-80f4-36b8006db414.png">
<img width="320" alt="Screenshot4" src="https://user-images.githubusercontent.com/28656495/205430546-3dfaa11f-d37b-4e0e-9a0a-9ab84939fa22.png">
</p>

**Comment by cbaker6** [comment]
@PSchmiedmayer your app uses the SwiftUI lifecycle (https://github.com/StanfordBDHG/ResearchKitOnFHIR/blob/8d7bcbba83619bea253346f511e3776fb311c42f/Example/ExampleApp/ExampleApp.swift#L15) which doesn’t have `window`. I explain more in the PR that fixes this #1519. In summary the discussion in the links mean UIKit views (all ResearchKit) views can’t detect tintColor/accentColor set at the top level of an app that uses the SwiftUI lifecycle. It can detect the tintColor for apps that are based on the older AppDelegate lifecycle (add AppDelegate to a SwfitUI lifecycle app won’t fix this either).

Simply updating your fork of ResearchKit won’t fix the issue, you need to set the tintColor of the top level ResearchKit view “every time” you present the ResearchKit, for example here:

**Comment by PSchmiedmayer** [comment]
Thank you @cbaker6 for your input and help! The fix of manually setting the tint color of the view worked. Thank you for the information on the issue and how this affects SwiftUI applications; greatly appreciated!

**Comment by cbaker6** [comment]
@PSchmiedmayer np, glad I could help. `ResearchKitOnFHIR` looks very interesting btw!

Also, it looks like you and @vishnuravi have made ResearchKit use SPM. Was this accomplished with minor changes to the current framework or did it require a lot of refactoring? Is there any limitations? If it was minor changes and limitations, I wonder if the ResearchKit team would be interested in a PR from you to add SPM to the main repo?

**Comment by PSchmiedmayer** [comment]
Thank you, happy to hear that you like the idea behind [`ResearchKitOnFHIR`](https://github.com/StanfordBDHG/ResearchKitOnFHIR). We think it will greatly simplify using ResearchKit for most of the simple survey use cases that don't rely on the more advanced ResearchKit functionality that can not be expressed in FHIR at this point.

The support did not require any changes to the codebase. The route I chose was using an XCFramework, and the binary [dependency features that the Swift Package Manager (SPM) offers](https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages). The SPM doesn't support mixed language targets or Objective-C Codebases, and therefore, this is easier to support the SPM without having to rewrite the codebase.
I just created a [GitHub Action](https://github.com/StanfordBDHG/ResearchKit/blob/main/.github/workflows/release.yml) at that builds the framework for every release and pushes the XCFramework into the repo, tags the release, and then refers to the [XCFramework in the Swift Package manifest](https://github.com/StanfordBDHG/ResearchKit/blob/main/Package.swift).

We are already in discussions with the ResearchKit team on how we can contribute it to the main ResearchKit repository. Hopefully, we will be able to share some updates soon. In the meantime, we will try to keep our fork up-to-date, and you or anyone else can rely on using the SPM version at [StanfordBDHG/ResearchKit](https://github.com/StanfordBDHG/ResearchKit).
We will use the SPM version to build the next version of the CardinalKit framework relying on the SPM and providing a new modularized architecture. We plan to have the first version done by January to start teaching our Building for Digital Health class ([cs342.stanford.edu](https://cs342.stanford.edu)).
