### ISSUE TITLE
Question Type to Enable Users a File Upload

### ISSUE THREAD

**Issue by PSchmiedmayer** [ResearchKit/ResearchKit#1522]
Dear ResearchKit team,

We are using ResearchKit for a wide variety of projects, and one feature that would be a great addition to the framework would be a question type to collect blob files from users, e.g., PDFs from a lab report. It would be great if that question type could use the system UI to browse for files or enable users to scan a document into a PDF file. The file could be provided at the end of the questionnaire, e.g., a URL pointing to a temporary file directory, e.g., how data is provided using a [`ORKFileResult`](http://researchkit.org/docs/Classes/ORKFileResult.html). 

Thank you for your help and support in maintaining the project!

CC @vishnuravi

**Comment by louie-apple** [comment]
HI @PSchmiedmayer,

This is an interesting request, and might be something we could help build out in the near future. We are curious, if you have something working already and if you have any work blocked by this feature not being available?

**Comment by PSchmiedmayer** [comment]
Hi @louie-apple,
Great to hear from you, and thanks for taking a look at the issue and advocating for it.
We want to use the feature in the [ResearchKitOnFHIR](https://github.com/StanfordBDHG/ResearchKitOnFHIR) Swift Package to translate FHIR tasks for binary file upload to ResearchKit. We will have class projects and research using the ResearchKitOnFHIR Swift Package beginning in January and would like to cover a good amount of FHIR questionnaire types by then.

**Comment by louie-apple** [comment]
Hi @PSchmiedmayer,

Thank you for the update. If you are interested in putting up a PR for this, we’d be interested in seeing what you had in mind.
