### ISSUE TITLE
Using ORKTaskViewController on SwiftUI do not use the entire screen

### ISSUE THREAD

**Issue by raafaelima** [ResearchKit/ResearchKit#1528]
Hey ResearchKit Team, 

I'm facing a strange behavior when using the `ORKTaskViewController` on a SwiftUI view, the viewController seems to not be able to use the entire screen space, being only in the middle of the screen, and adding the navigation controls outside where you expect as viewController. 

I'm using:
```
Xcode 14
iOS: 15.5
Simulator: iPhone 13 Pro
```

| UIKit             |  SwiftUI |
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 13 Pro - 2022-11-28 at 12 56 05](https://user-images.githubusercontent.com/99194323/204283682-3a74a8ca-1b50-4c79-9b28-98faef950f54.png) |  ![Simulator Screen Shot - iPhone 13 Pro - 2022-11-28 at 12 57 49](https://user-images.githubusercontent.com/99194323/204283622-91841286-ea4a-4216-92b6-184c6871c331.png)

**Comment by jacksodl23** [comment]
Adding the `ignoresSafeArea()` modifier to my ORKTaskViewController made it take up more of the screen.
![Simulator Screen Shot - iPhone 14 - 2023-01-17 at 21 48 42](https://user-images.githubusercontent.com/57110480/213070335-0249b323-3cd7-47ad-b753-20075e012407.png)

For reference, this is the code I use to present the task VC:
```
.fullScreenCover(isPresented: $presentingLogOutreachForm) {
            LogOutreachView(contact: contact, team: team, showDidVolunteerBanner: $showingDidVolunteerBanner, showAttemptLoggedBanner: $showingAttemptLoggedBanner)
                .ignoresSafeArea()
        }
```

**Comment by louie-apple** [comment]
When hosting ORKTaskViewController in a SwiftUI view, add these modifiers to the view,
` .ignoresSafeArea(.container, edges: .bottom)
        .ignoresSafeArea(.keyboard, edges: .bottom)`

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
