### ISSUE TITLE
Missing header file build error

### ISSUE THREAD

**Issue by vishnuravi** [ResearchKit/ResearchKit#1529]
When attempting to use the latest commit of ResearchKit from the main branch (https://github.com/ResearchKit/ResearchKit/commit/a89059f5dc2a91f36785b184f914b5e5fdb05877) via CocoaPods we are running into a build error regarding missing header files (see screenshot below).

We have tried clearing all CocoaPods caches, DerivedData, etc., and then reinstalling the pod. We are using Xcode 14.1, iOS 16.1, and Cocoapods 1.11.3.

If anyone has suggestions for what we might try to resolve this, it would be greatly appreciated!

<img width="959" alt="Screenshot 2022-11-29 at 8 51 38 AM" src="https://user-images.githubusercontent.com/1212163/204548833-1ed06453-f052-438a-9a4f-89bbc76d2381.png">

Thank you,
@vishnuravi and @PSchmiedmayer

**Comment by louie-apple** [comment]
Hi @vishnuravi ,

Here are our latest CocoaPods Installation guidelines:

 ------------
 For latest stable release

 ```
 pod 'ResearchKit'
 ```
 The latest early development release based off of main is
 ```
pod 'ResearchKit',  :git => 'https://github.com/ResearchKit/ResearchKit.git', :tag => '2.1.1-dev'

 ```
 or  for the latest early development release based off of main

 ```
   pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'main'
 ```

**Comment by PSchmiedmayer** [comment]
@louie-apple Thank you for your input and help! I can confirm that the commit before the `2.1.1-dev` branch did fix the CocoaPods header issue. We can close that issue.

**Comment by louie-apple** [comment]
No problem @PSchmiedmayer!
