### ISSUE TITLE
`ORKSpeechRecognitionStepIdentifier` missing `FOUNDATION_EXPORT`

### ISSUE THREAD

**Issue by Brett-Best** [ResearchKit/ResearchKit#1534]
https://github.com/ResearchKit/ResearchKit/blob/fc67cc944c9f33a7701214a4bb53ecd03d07f553/ResearchKit/Common/ORKOrderedTask_Private.h#L40-L66
It appears that
```objc
FOUNDATION_EXPORT NSString *const ORKSpeechRecognitionStepIdentifier;
```
is missing from the first code snippet, I’m using it to extract results from when the task view controller completes — instead of using my own hardcoded string.

**Comment by louie-apple** [comment]
Hi @Brett-Best ,
We hadn't expected someone to use this.  We will look into adding it to the export list shortly.  In the mean time you can hard code it to unblock yourself. Thanks!

**Comment by Brett-Best** [comment]
Thankyou, it does!

**Comment by louie-apple** [comment]
Hi @Brett-Best,

You’re a highly engaged part of the ResearchKit community, so we’d like to hear from you about your experience using ResearchKit. If you’d be interested in talking shop with us, email researchkit@apple.com and we’ll set up a virtual meeting.
Thanks
ResearchKit Team

**Comment by Brett-Best** [comment]
Hey @louie-apple, I reached out but haven't heard anything yet - I've just sent a follow-up email.
