### ISSUE TITLE
No Option to Save Results if Task Cancelled

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#1536]
Hello, I have an issue with ResearchKit after updating to 2.1. I am no longer given the option to save results when canceling a task. This is despite the fact that the delegate returns "true" repeatedly when "supportsSaveAndRestore" is called.

After much digging, I find that when the cancel button action is called, the code no longer calls the "dismissWithoutConfirmation" method that was called in the older version of ResearchKit. This function would go through all the results to see if any were "saveable."  Without this function in place, "saveable" is always false, and therefore the "save" option is not offered even though "supportsSaveAndRestore" is true.

There is a similar function in the new version called "shouldDismissWithSwipe", but it is not called at the time the cancel button is pressed. I do get the save option if I tell the cancel action to look there.

Also.... even when I do get the save button by making this modification, and the results are saved... restoration with restoration data also does not work.

You can reproduce the error by following the instructions on the ResearchKit GitHub page to create a new project from scratch. You are never given the option to save a cancelled task even with "supportsSaveAndRestore" is true.

Is anyone having luck with ResearchKit 2.1 when it comes to saving and restoring tasks?

Thanks!

**Comment by cmetts** [comment]
Oh wow.... is ResearchKit officially dead? No response from Apple on this pretty significant issue? My original post for this goes back 2 years, and never got a response. I never upgraded ResearchKit in my project as a result.

Two years later, same problem..... crickets from Apple

Steps to reproduce using Apple's UICatalog demo Project

Download latest stable release of ResearchKit

open research kit project, and compile

copy the research kit project file into UICatalog Project

Modify TaskViewController swift file by adding the following:

func taskViewControllerSupportsSaveAndRestore(_ taskViewController: ORKTaskViewController) -> Bool {
      return true
}

Run ANY of the surveys or single interactions.

Click 'Cancel' top right

You are NEVER given the opportunity to save a task event thought the delegate method is called repeatedly return true.

**Comment by louie-apple** [comment]
Hi @cmetts,

We’re working through issues reported here and this is the one we’re currently investigating. Thanks for your patience!

**Comment by cmetts** [comment]
Thanks very much!

**Comment by cmetts** [comment]
I should add.... that restorationData does not work either to resume a task. (after writing code to save it even though the save button doesn't appear)

**Comment by louie-apple** [comment]
Hi @cmetts,

We recently pushed a new release, 2.2.9-dev (https://github.com/ResearchKit/ResearchKit/releases/tag/2.2.9-dev) on main. Would you please pull this release and see if it resolves your issue?

**Comment by cmetts** [comment]
YES!!!! it works. the save button appears, and restoring remembers where the user was when they saved and has all the previous values in place when going 'back'.

Thank you ResearchKit team! My customers will be so happy.

**Comment by louie-apple** [comment]
🎉 Thanks @cmetts  for confirming. Closing this issue as resolved.
