### ISSUE TITLE
Error: Unexpected CFBundleExecutable Key - when archiving and validating project including ResearchKit

### ISSUE THREAD

**Issue by mayawald3** [ResearchKit/ResearchKit#1539]
I am having trouble archiving and uploading my app which uses ResearchKit to app store connect. It seems as the though the issue has to do with the info.plist. Here is the full error message.
ITMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/Surve.app/ResearchKit/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.
I tried removing the CFBundleExectuable key but that made the app not able to be validated after archiving it. 
Does anyone know a solution for this?

One solution I found online was to check if the info.plist is added to Copy Bundle Resources in Build Phase. If so just remove it from Copy Bundle Resources. I wasn't sure what was meant by this though.

**Comment by louie-apple** [comment]
Hi @mayawald3,

That looks like a problem that could happen when using CocoaPods to add framework projects to your app. Can you confirm whether you’re using CocoaPods to add ResearchKit to your project?

**Comment by mayawald3** [comment]
I did not use CocoaPods to add ResearchKit to my project. I just downloaded the ResearchKit and added it as a framework to my project. It has the option Embed & Sign selected. It is also listed under Copy Bundle Resources.

**Comment by louie-apple** [comment]
Thank you for sharing those details.
You commented that ResearchKit.framework "…is also listed under Copy Bundle Resources." That might be the source of the issue you're seeing.
Take a look at the screenshots below from the `build phases` tab in the target editor. The `ResearchKit.framework`  should NOT be under `Copy Bundle Resources phase`. Instead, it should be under the `Embed Frameworks phase` — that portion should be automatically done by Xcode, so you can just verify that it is there.
More info and instructions for adding ResearchKit to your app can be found here: https://github.com/ResearchKit/ResearchKit#building
Please let us know if these instructions help!

![image](https://user-images.githubusercontent.com/39536869/215909241-08ea8b17-2940-47fc-a705-1c0e745c8b63.png)
![image](https://user-images.githubusercontent.com/39536869/215909258-90029850-c8fc-4ec4-a056-91627b69744e.png)

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
