### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by majidsaleem105** [ResearchKit/ResearchKit#1543]
Hi @louie-apple,

We are using ResearchKit 2.0.0 and looking for the Text Alignment for Consent, Survey Steps, and Summary screens. We are under the impression that we can customize screen text alignment, font sizes, etc with RK 2.0.
Can we make the Text Alignment of our own choice like the CareKit?
Is it possible that we can customize the screens? 

For Example: please consider the attached screenshot.
- We don't want to have a checkmark on the Summary Screen.
- We want to centralize all text on the screen.
- We want to move the `Submit` button up right under the text.

Please advise us on how we can make these customizations.

Thank You,
- Majid S.

![IMG_4835](https://user-images.githubusercontent.com/1611600/222139585-d281a767-67d1-4e4b-9bd9-b4e944e181c9.PNG)

**Comment by majidsaleem105** [comment]
Hi @louie-apple 

Can you please guide me on this?

Thanks,
- Majid S.

**Comment by majidsaleem105** [comment]
Hi @louie-apple 

Do you have any suggestions for us to resolve the Text Alignment problems?

Thanks,
- Majid S.

**Comment by louie-apple** [comment]
Hi @majidsaleem105, 

Can you share with us the code you are using to create those pages?
In terms of consent, we are working on a new example that showcases how to create consent through Instruction Steps, however that guide is not yet available.

For now, we can walk you through, how to achieve the UI that you are looking for.

We don't want to have a checkmark on the Summary Screen.
For that, all you would need to do is use an ORKInstructionStep, without an image:

```
        let instructionStep = ORKInstructionStep(identifier: "id")
        instructionStep.title = NSLocalizedString("Simple Survey", comment: "")
        instructionStep.text = "some text"
        instructionStep.detailText = "Please use this space to provide instructions for participants.  Please make sure to provide enough information so that users can progress through the survey and complete with ease."
```

For this question:

```
We want to centralize all text on the screen.
```

Our screens follow the Apple Human Interface Guidelines, and we recommend keeping that style (https://developer.apple.com/design/human-interface-guidelines/guidelines/overview/)
However, if this something you still wish to do, there a few options.
There is a property exposed on `ORKInstructionStep`
`attributedDetailText` which you can set the alignment for the detail text as an argument of the attributed string,

And for

```
We want to move the Submit button up right under the text.
```

That is not something that is supported with ResearchKit, and is not a UI that is recommended by the Human Interface Guidelines

Alternatively, if you want full control you do have the option of using an `ORKCustomStep` where you can pass in your own `UIView` that has all the modifications you mentioned.

You would use it like this:

```
        let customUIView = CreateMyCustomUIView () // method for you to create
        let customStep = ORKCustomStep(identifier: "id", contentView: customUIView) 
```

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
