### ISSUE TITLE
SSL certificate is invalid on researchkit.org

### ISSUE THREAD

**Issue by mafen** [ResearchKit/ResearchKit#1549]
![image](https://github.com/ResearchKit/ResearchKit/assets/1687761/8eb13fd8-d340-4a8e-b706-38e858e88fc7)

The site displays an error (NET::ERR_CERT_COMMON_NAME_INVALID) if you try to go there 

![image](https://github.com/ResearchKit/ResearchKit/assets/1687761/2e35936e-bea0-4007-8671-0d4cefe932d2)

**Comment by jessi-apple** [comment]
Hi there, thanks for identifying this issue -- it has now been resolved: https://researchkit.org
