### ISSUE TITLE
Issue with ORKTextChoiceOther not behaving as expected

### ISSUE THREAD

**Issue by iadereggalternova** [ResearchKit/ResearchKit#1556]
When ORKTextChoiceOther.choice is used for allowing an "Other" text entry in a single-choice question with the exclusive parameter set to true, the expected behavior is not consistently observed. The issues are twofold:

1. Selecting another option does not close the "Other" text field.
1. When navigating back to the "Other" option after selecting a different one, the text field unexpectedly closes despite the "Other" option remaining selected.

## Steps to reproduce
1. Create a multiple-choice ORKQuestionStep with various ORKTextChoice options and an ORKTextChoiceOther with exclusive set to true.
1. Present the step within a task.
1. Select the "Other" option, enter custom text, and then select a different option.
1. Observe that the text field associated with the "Other" option does not close.
1. Proceed to the next question, then navigate back, and select the "Other" option again.
1. Observe that the text field for the "Other" option closes even though "Other" remains selected.

## Expected Behavior
1. The "Other" text field should close when an exclusive different choice is selected.
1. Upon returning to the question and re-selecting "Other," the text field should reopen and display previously entered text.

## Actual Behavior
1. The "Other" text field remains visible when a different choice is selected.
1. When selecting a different option and then returning to the "Other" option, the text field closes, although "Other" remains selected

## Code sample

```
 let textChoices = [
      ORKTextChoice(text: "Option 1", value: 0 as NSNumber),
      ORKTextChoice(text: "Option 2", value: 1 as NSNumber),
      ORKTextChoice(text: "Option 3", value: 2 as NSNumber),
      ORKTextChoiceOther.choice(withText: "Other", detailText: "", value: 3 as NSNumber, exclusive: true, textViewPlaceholderText: "Tap to write your answer")
  ]

  let singleChoiceQuestionStep = ORKQuestionStep(identifier: "singleChoiceQuestionStep", title: "Single choice question", question: "Select an choice:", answer: ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices))
```
![image](https://github.com/ResearchKit/ResearchKit/assets/120516158/eaa90a87-7e32-4855-a510-7022ed7fcdbf)

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. If you’re still seeing this issue in the latest release, please let us know, otherwise we will close it. 
Thanks

**Comment by louie-apple** [comment]
@PSchmiedmayer Thank you for sharing this with us! We are taking a look!

**Comment by PSchmiedmayer** [comment]
Thank you @louie-apple!

**Comment by louie-apple** [comment]
Hi @PSchmiedmayer 
We recently pushed a new release, 2.2.16 (https://github.com/ResearchKit/ResearchKit/releases/tag/2.2.16) on stable. Would you please pull this release and see if it resolves your issue?

**Comment by PSchmiedmayer** [comment]
Amazing, thank you @louie-apple; I will take a look at this later this week. Thanks for working on an update! 🚀

**Comment by PSchmiedmayer** [comment]
@louie-apple I am happy to follow up that we have updated our fork to RK 3.0 (https://github.com/StanfordBDHG/ResearchKit) and we can report that the issue described here is resolved. Thanks to you and your team for taking a look at this and resolving it!
