### ISSUE TITLE
ORKNumericAnswerFormat - display a validation message

### ISSUE THREAD

**Issue by meyumeapps** [ResearchKit/ResearchKit#1560]
Hi,

We have a requirement to display a validation message to the user when the number they have entered is outside the min/max range.

I'm probably being a bit dense but I can't find how to enable this? 

I can see some support in [ORKSurveyAnswerCellForNumber.m](https://github.com/ResearchKit/ResearchKit/blob/fee76c2d93246c697fed2a7be5800400018d2898/ResearchKit/Common/ORKSurveyAnswerCellForNumber.m#L231)

Thanks
Scott

**Comment by louie-apple** [comment]
Hi @meyumeapps,
Thank you for you for your question.
To make use of the built in validation messages, you need to use `ORKFormStep`, not `ORKQuestionStep`
You can do just that for your `ORKNumericAnswerFormat` answer like this:

```
let numericAnswerFormat = ORKNumericAnswerFormat(style: .integer, unit: "years", minimum: 1, maximum: 120)
let formItem = ORKFormItem(identifier: "ageFormItem", text: "What is your age?", answerFormat: numericAnswerFormat)
let formStep = ORKFormStep(identifier: "ageFormStep", title: "This is a step for age information.", text: nil)
formStep.formItems = [formItem]
```

Any response entered that is not within the `minimum` and `maximum`  parameters, will show the built in validation message. And the user will not be able to proceed until changing their answer.

Please let us know if you have any other questions.

Thanks!

**Comment by meyumeapps** [comment]
Hi @louie-apple thanks for the response.

I did try the form approach but just get the `Invalid value` response rather than the range validation message.

![Simulator Screenshot - iPhone 14 Pro - 2023-12-18 at 14 43 59](https://github.com/ResearchKit/ResearchKit/assets/4252788/91ba8e57-c2d2-47d4-ba9e-bc43f1be45fa)

I did clone ResearchKit and put in a quick patch to demonstrate what we are trying to achieve. Is this something that might be a useful contribution to the project?

Thanks
Scott

![Simulator Screenshot - iPhone 14 Pro - 2023-12-18 at 14 45 45](https://github.com/ResearchKit/ResearchKit/assets/4252788/8efdbb3e-539d-405b-8a47-b6b19ac6c31f)
![Simulator Screenshot - iPhone 14 Pro - 2023-12-18 at 14 45 39](https://github.com/ResearchKit/ResearchKit/assets/4252788/7d965254-74ca-48e0-a025-2a0ac6bcacf6)

**Comment by louie-apple** [comment]
Thank you for sharing this with us. This validation message is the correct message for this answerFormat. However, it looks like you found the right place to customize the message for your use case.

**Comment by marco-theraforge** [comment]
@ meyumeapps Can you share the patch? it seems quite useful...

**Comment by meyumeapps** [comment]
@marco-theraforge I don't have the code in GitHub but this is what I changed:

Class: `ORKSurveyAnswerCellForNumber.m`

Method: `- (void)valueFieldDidChange:(UITextField *)textField {`

```
BOOL isValid = [self isAnswerValid];
    
    if (isValid) {
        if (_errorLabel.attributedText != nil) {
            _errorLabel.attributedText = nil;
            [self setUpConstraints];
        }
    } else {
        NSString *invalidValueString = [answerFormat localizedInvalidValueStringWithAnswerString:sanitizedText];
        
        [self updateErrorLabelWithMessage:ORKLocalizedString(invalidValueString, nil)];
    }
```

Hope it's useful.

**Comment by louie-apple** [comment]
Thank you for raising this issue, and sharing your patch. We will close this issue, however if you see this again, feel free to re-open it.
