### ISSUE TITLE
Charts in ResearchKit framework?

### ISSUE THREAD

**Issue by cstrajean** [ResearchKit/ResearchKit#1571]
Greetings,
I used to be able to draw Charts using ResearchKit framework: ORKDiscreteGraphChartView, ORKLineGraphChartView, ORKPieChartView.
Was this functionality removed from the ResearchKit Public Release 3.0?  I downloaded the main branch.
I could not find the Charts in the ResearchKitUI framework either.
Thank you,
Carmen

**Comment by Pariecemckinney-apple** [comment]
Hello @cstrajean,

Thank you for reaching out and looking through the new updates! ORKCharts have in fact been removed from ResearchKit with the 3.0 release. Now that the Swift Charts (https://developer.apple.com/documentation/charts/creating-a-chart-using-swift-charts) framework is available, developers have access to a robust and native set of apis to visualize the data of their choice. This would be our recommended replacement moving forward. However, In case there are additional functionalities needed on top of Swift Charts, we encourage the community to share ideas or implementations in form of issues and PRs. 

I hope this helps and please let us know if you have any further questions!

**Comment by cstrajean** [comment]
Hello Pariece,
Thank you for your detailed reply.
ResearchKit worked well for me.
I am transitioning to the SwiftUI Charts.
Thank you,
Carmen

**Comment by Pariecemckinney-apple** [comment]
Hey @cstrajean, 

It sounds like you have a path forward here. Closing this issue but please open a new issue if you need anything further.
