### ISSUE TITLE
Question: How initialize ORKStepViewController?

### ISSUE THREAD

**Issue by dasoga** [ResearchKit/ResearchKit#1575]
Hi all,

UPDATE:
This is only happening using **Mac** with **Apple Silicon** chip.

In my old implementation I had these override for init `ORKStepViewController`. But I can't subclassing it anymore.

```
    override init(step: ORKStep?) {
        super.init(step: step)
    }
    
    override init(step: ORKStep, result: ORKResult?) {
        super.init(step: step, result: result)
    }  
```

Now I'm getting these errors:
`Initializer does not override a designated initializer from its superclass`
`Must call a designated initializer of the superclass 'ORKStepViewController'`

There is something curious, some coworker can run this code in a Intel Mac, but me in a Apple Silicon can't run the code.

Can somebody know why this is happening? 
Any clue how I can solve this? (I have a few classes inheritance from ORKStepViewController)

Thank you in advance for your kind response.

attached image
<img width="1840" alt="Screenshot 2024-06-06 at 21 02 45" src="https://github.com/ResearchKit/ResearchKit/assets/11412369/22a670b4-2598-43fb-b251-f577d230df94">

Also here is the implementation of this class in the framework:
<img width="1840" alt="Screenshot 2024-06-06 at 22 06 21" src="https://github.com/ResearchKit/ResearchKit/assets/11412369/4042ac3c-60b3-4313-817e-2635bd9ddd10">

**Comment by Pariecemckinney-apple** [comment]
Hello @dasoga! Thank you for reaching out. If you take a look at the link here you can find the text below: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/


> Conversely, if you write a subclass initializer that matches a superclass convenience initializer, that superclass convenience initializer can never be called directly by your subclass, as per the rules described above in [Initializer Delegation for Class Types](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization#Initializer-Delegation-for-Class-Types). Therefore, your subclass is not (strictly speaking) providing an override of the superclass initializer. As a result, you don’t write the override modifier when providing a matching implementation of a superclass convenience initializer.

So in this case you should be able to drop the "override" from the `init(step: ORKStep, result: ORKResult?)` definition in your subclass leaving you with this:

```
init(step: ORKStep, result: ORKResult?) {
    super.init(step: step)
}
```

**Note: the default implementation of `init(step: ORKStep, result: ORKResult?)` ignores the result and simply calls `init(step: ORKStep?)` so its no need to call the parent definition.** 

I hope this helps and please let me know if there are still issues. Thanks again for reaching out!
