### ISSUE TITLE
Constraint warning on scale slider view

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#158]
`ORKScaleSliderView` inits with a `CGRectZero` frame and only gets its proper dimensions later.

Since we moved adding the constraints to the init method as well, this causes an `UIViewAlertForUnsatisfiableConstraints` log message.

What's the best way to avoid this? Should we move the one time constraint setup back to `updateConstraints`? This method is only called after the current view has proper dimensions.

**Comment by jwe-apple** [comment]
Errm, that might be why we moved it to `updateConstraints` in the first place.

**Comment by rsanchezsaez** [comment]
So tricky. I'll move them back there then.

*UIKit* should have an `addStaticConstraints` method, to be automatically called, only once, just before the first time `updateConstraints` is run. :P

**Comment by jwe-apple** [comment]
File a radar.

**Comment by rsanchezsaez** [comment]
It turns out I was wrong and moving them to `updateConstraints` still triggered the warning. The frame wasn't important, the problem was that `sliderView` still had `translatesAutoresizingMaskIntoConstraints` set to `YES` when `ORKSurveyAnswerCellForScale` called `[self setNeedsUpdateConstraints]`, which triggered the children layout cycle before giving a chance to `ORKScaleSliderView` to be set for autolayout.

I fixed it by making the parent's constraints static, so they are triggered in the expected order.

---

Tangentially related, I've noticed that when the phone is in landscape mode, the scales seem a tad too long (both horizontal and vertical ones, specially vertical ones). What do you think?

**Comment by jwe-apple** [comment]
Nice. We're doing a UI review early next week and this will get covered.
