### ISSUE TITLE
Portuguese localization improvement

### ISSUE THREAD

**Issue by ricardopereira** [ResearchKit/ResearchKit#17]
`Ficheiro não marcado como pagado (não marcado como enviado).`

Word `pagado` means paid in portuguese. It has no sense.

**Comment by bavarious** [comment]
That’s likely a typo: **apagado** means **erased**, **pagado** means **paid**.

**Comment by bavarious** [comment]
I’ve noticed that pull request #18, which replaces **pagado** with **eliminado**, has [been merged](https://github.com/ResearchKit/ResearchKit/commit/f5e0594c757c642beb2e7cf503468b04bf6cb87e). I would like to mention that Apple favour **apagad[ao]** over **eliminad[ao]** on iOS in both pt_PT and pt_BR (pt).

These are the counts I get on iOS pt_PT glossaries published by Apple on April 15, 2014:
````
$  egrep "apagad[ao]" * | wc -l
     192
$ egrep "eliminad[ao]" * | wc -l
      10
````
And these are the counts for pt_BR (pt):
````
$  egrep "apagad[ao]" * | wc -l
     174
$ egrep "eliminad[ao]" * | wc -l
       4
````
If ResearchKit wants to be consistent with iOS terminology-wise, it seems that **apagad[ao]** should be preferred over **eliminad[ao]**.

**Comment by ricardopereira** [comment]
I changed to "apagado" and it has been merged.

**Comment by bavarious** [comment]
Brilliant! I hadn’t noticed the second commit. :+1:

**Comment by jwe-apple** [comment]
@bavarious - this was indeed reviewed here!
