### ISSUE TITLE
Small css fix for the Github page (http://researchkit.github.io/)

### ISSUE THREAD

**Issue by daannijkamp** [ResearchKit/ResearchKit#171]
Can someone add "overflow:hidden" on the tabs class (researchkit.css, line 325)? 
It will prevent scrolling like the image below. 
![img_1209](https://cloud.githubusercontent.com/assets/1774060/7553802/d023a362-f70a-11e4-9c95-0c0ac376391d.jpg)

**Comment by jwe-apple** [comment]
Thanks for the heads-up, taking care of it.
