### ISSUE TITLE
Webviews with bounce enabled should show white during bounce

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#176]
At the moment, the grey background appears when dragging beyond the content size. This should be white.

**Comment by jwe-apple** [comment]
(For example, Learn More screens)

**Comment by rsanchezsaez** [comment]
I think [PR #170](https://github.com/ResearchKit/ResearchKit/pull/170) actually fixed this. Are you sure?

![ios simulator screen shot 12 may 2015 02 14 24](https://cloud.githubusercontent.com/assets/444313/7578399/a3f1265a-f84c-11e4-87d5-0bfacbc0e1fd.png)

**Comment by jwe-apple** [comment]
Interesting, I was testing on iPad. I'll check tomorrow.

**Comment by rsanchezsaez** [comment]
![ios simulator screen shot 12 may 2015 09 31 47](https://cloud.githubusercontent.com/assets/444313/7582932/bb7eb9da-f889-11e4-9359-84678bdc7746.png)

;)

**Comment by jwe-apple** [comment]
Verified
