### ISSUE TITLE
Make custom images for Tone Audiometry Task and Motion Reaction Time Task

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#192]
The *Tone Audiometry* and *Motion Reaction* tasks are currently reusing the instructional images from the *Audio Active* task.

These don't make much sense, specially in *Motion Reaction*. New images need to be created for these tasks.

---

Also, just cosmetic:
- In `ORKCatalog`, I'd rename *Device Motion Reaction Time Task* task to *Reaction Time Active Task*
- In `ORKTest`, I'd rename *Reaction Time* to *Reaction Time Task*.

**Comment by jwe-apple** [comment]
Thanks for filing. This should be covered in the UI review, so I'll tag it.

**Comment by jwe-apple** [comment]
This has been reviewed and the images approved.
