### ISSUE TITLE
signaturePageContent not copied correctly

### ISSUE THREAD

**Issue by stownsend** [ResearchKit/ResearchKit#196]
There appears to be an issue when copying a consent document, the content of signaturePageContent is being set currently to be _signaturePageTitle. 

Would expect that it would be set to _signaturePageContent.

As far as I can tell, this is occurring in ConsentDocument.m, in the copyWithZone:(...) method:

- (instancetype)copyWithZone:(NSZone *)zone {<br>
    ...<br>
    doc.signaturePageTitle = _signaturePageTitle;<br>
    doc.signaturePageContent = _signaturePageTitle; // Issue with signaturePageContent occurs here<br>
    doc.htmlReviewContent = _htmlReviewContent;<br>
    ...<br>
}

As both the review step and creation of a pdf require the copying of the original consent document, this impacts on the generation of html code for both cases. Changing the line to read:

doc.signaturePageContent = _signaturePageContent;

fixes the issue.

**Comment by jwe-apple** [comment]
Analysis looks right. Would merge a PR.

**Comment by jwe-apple** [comment]
Merged #197
