### ISSUE TITLE
User Interface Color Configuration

### ISSUE THREAD

**Issue by httang12** [ResearchKit/ResearchKit#203]
Is there any out of box configuration management class for the color scheme onthings like background color, text color, button color and navigation bar tint color within researchkit?

**Comment by jwe-apple** [comment]
Tint color is respected throughout ResearchKit views. So every image, consent animation, button, etc applies the tintColor UIAppearance property. Other than that, there is no out-of-box customization.

If you have a specific need that you think generalizes well, then it would not be out of the question to add properties that are UIAppearance selectors to allow this kind of customization.

**Comment by jwe-apple** [comment]
@httang12 I'm going to close this issue, but please feel free to raise further issues for anything you feel you need for your app!

**Comment by httang12** [comment]
Ok, thanks!

Date: Tue, 19 May 2015 22:16:06 -0700
