### ISSUE TITLE
stepAfterStep and stepBeforeStep not working properly

### ISSUE THREAD

**Issue by dcleblond** [ResearchKit/ResearchKit#206]
I have a simple subclass for ORKOrderedTask that just spits out the step identifier in the stepBeforeStep and stepAfterStep functions, and then returns a [super stepBeforeStep etc etc] for each. I'm seeing it execute both (first After then Before) for the same step BEFORE it gets to that step. Shouldn't it be spitting out the identifier for After for the step I just answered and Before for the step I'm about to answer? Maybe I'm misunderstanding this.

**Comment by jwe-apple** [comment]
stepAfterStep and stepBeforeStep may be called multiple times, with different arguments, by the task view controller. Any time the results have changed, the task view controller may ask again, since the presence or absence of results may change what steps are available. It needs this information to decide what to show in the navigation bar, or when setting up a new step view controller's navigation controls.

**Comment by dcleblond** [comment]
Maybe I'm misunderstanding the purpose of the functions. 

What I thought would happen is if you answered, say step2 it would fire stepAfterStep on step2 and fire stepBeforeStep on step3 (or the next step in the stack.)

If that's not what is happening, what is the difference between stepBeforeStep and stepAfterStep?

Thanks for responding!

**Comment by rsanchezsaez** [comment]
`stepAfterStep:` and `stepBeforeStep:` are not intended to signal that the steps are going to appear or disappear on the task view controller (i.e., they are not similar to methods like `viewWillAppear:` `viewWillDisappear:`, etc.).

The *task view controller* is purposefully "dumb": it doesn't maintain a stack of previous steps within its task nor knows which the next step is in advance; it only "knows" about the step currently being shown.

Generally, the *task view controller* calls the `stepAfterStep:` and `stepBeforeStep:` methods on the *task* when it needs to know what the *previous* or the *next* step for the *current* step is. The *task view controller* may call these methods several times when you are navigating (for example, `stepAfterStep:` for the current step to get the next step, and an additional `stepAfterStep:` after the transition to know if there exists a valid step after the new current one, and update the `Next`/`Done` button caption accordingly; the same for showing/hiding the back navigation bar button depending if there exist a previous step, etc.).

---

Maybe the `taskViewController:stepViewControllerWillAppear:` method from `ORKTaskViewControllerDelegate` would serve your purposes better.

**Comment by dcleblond** [comment]
I think I understand. They both get called every step regardless, and it's
up to the person writing the subclass to differentiate between the two and
handle the logic. Gotcha.

Thanks!

On Wed, May 20, 2015 at 1:18 PM, Ricardo Sánchez-Sáez <
notifications@github.com> wrote:

> stepAfterStep: and stepBeforeStep: are not intended to signal that the
> steps are going to appear or disappear on the task view controller (i.e.,
> they are not similar to methods like viewWillAppear: viewWillDisappear:,
> etc.).
>
> The *task view controller* is purposefully "dumb": it doesn't maintain a
> stack of previous steps within its task nor knows which the next step is in
> advance; it only "knows" about the step currently being shown.
>
> Generally, the *task view controller* calls the stepAfterStep: and
> stepBeforeStep: methods on the *task* when it needs to know what the
> *previous* or the *next* step for the *current* step is. The *task view
> controller* may call these methods several times when you are navigating
> (for example, stepAfterStep: for the current step to get the next step,
> and an additional stepAfterStep: after the transition to know if there
> exists a valid step after the new current one, and update the Next/Done
> button caption accordingly; the same for showing/hiding the back navigation
> bar button depending if there exist a previous step, etc.).
> ------------------------------
>
> Maybe the taskViewController:stepViewControllerWillAppear: method from
> ORKTaskViewControllerDelegate would serve your purposes better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ResearchKit/ResearchKit/issues/206#issuecomment-103966144>
> .
>



-- 
---
David Leblond
dcleblond@gmail.com
