### ISSUE TITLE
Step navigation rule initializer should have Swift overlay to use tuples

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#224]
The Step navigation initializer and the step navigation rule overall should use tuples in Swift. The Objective-C API is not ideal, but acceptable given we can improve it in Swift. This issue is for adding a Swift overlay initializer and any other necessary components, and potentially hiding the Objective-C initializer in Swift.

**Comment by rsanchezsaez** [comment]
This can be closed as the feature was implemented and merged.

**Comment by YuanZhu-apple** [comment]
Yes.
