### ISSUE TITLE
Less tall continue buttons in compact vertical size class

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#231]
Currently, `Continue` buttons are always 44 points tall.

On the other hand, the standard navigation bar goes from 44 points in portrait to 32 points in landscape.

Should we follow a similar approach with the continue button?

**Comment by jwe-apple** [comment]
You mean compact vertical size class, but yes. We could consider it.

**Comment by rsanchezsaez** [comment]
This issue can now be closed: the referencing PR was merged.

**Comment by YuanZhu-apple** [comment]
Closing it. Thanks @rsanchezsaez !
