### ISSUE TITLE
More parameter validation needed for ORKDeviceMotionStep

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#233]
Currently we have those 3

```    
    if (self.maximumStimulusInterval < self.minimumStimulusInterval) {
        @throw [NSException exceptionWithName:NSInvalidArgumentException
                                       reason:@"maximumStimulusInterval can not be less than minimumStimulusInterval"
                                     userInfo:nil];
    }
    if (self.thresholdAcceleration <= 0) {
        @throw [NSException exceptionWithName:NSInvalidArgumentException
                                       reason:@"thresholdAcceleration must be greater than zero"
                                     userInfo:nil];
    }
    if (self.numberOfAttempts <= 0) {
        @throw [NSException exceptionWithName:NSInvalidArgumentException
                                       reason:@"numberOfAttempts must be greater than zero"
                                     userInfo:nil];
    }
```

No validation check on timeout interval (which will keep the blue circle always showing up if we set to negative)
`maximumStimulusInterval` and `minimumStimulusInterval` also need a negative check

**Comment by rsanchezsaez** [comment]
I'm doing this.

By the way, all the reaction time task class names seem a tad too long. How about renaming them from `ORKDeviceMotionReactionTime...` to `ORKReactionTime...`?

**Comment by rsanchezsaez** [comment]
Additional parameter validation added to [PR #232](https://github.com/ResearchKit/ResearchKit/pull/232).

**Comment by rsanchezsaez** [comment]
By the way, I take you don't want to rename `ORKDeviceMotionReactionTime...` to `ORKReactionTime...`, right?

**Comment by jwe-apple** [comment]
Not at this time. File an issue?

**Comment by rsanchezsaez** [comment]
Filed [Issue #257](https://github.com/ResearchKit/ResearchKit/issues/257).
