### ISSUE TITLE
Camera feed in image capture task does not rotate correctly

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#234]
In the image capture task, under screen rotation, the rotation does not correctly rotate the camera feed to match.

**Comment by brucehappy** [comment]
This was working in my original feature branch.  I'll check master in a little while to see whats up.

**Comment by jwe-apple** [comment]
cool, thanks.

**Comment by brucehappy** [comment]
I just tested this on my iPhone 5 iOS 8.3 using ORKTest, and it rotates along with the app (which excludes upside down portrait).  Which device and os is this happening on?

**Comment by jwe-apple** [comment]
mm, yes. I'm also having trouble reproducing, so I'm returning this to the original reporter. Thanks for looking into it.

**Comment by jwe-apple** [comment]
I've reproduced on iPad. Fix in #239.

**Comment by jwe-apple** [comment]
Fixed in #239
