### ISSUE TITLE
Uncoordinated curly brackets style

### ISSUE THREAD

**Issue by dEn13L** [ResearchKit/ResearchKit#24]
https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/ActiveTasks/ORKRecorder.m

![1](https://cloud.githubusercontent.com/assets/4187743/7151515/05a0bd80-e34d-11e4-8685-cc91914e147c.png)
![2](https://cloud.githubusercontent.com/assets/4187743/7151516/05a24b64-e34d-11e4-9990-13e1d5d57f95.png)

**Comment by kindraywind** [comment]
Also spaces between lines and unimplemented method :\

**Comment by alistra** [comment]
Making a `clang-format` pre-commit hook can fix it for long term

**Comment by haaakon** [comment]
I've mad a clang-format file that tries to adhere to Apples code style. Could use that in this project
https://github.com/haaakon/Apple-clang-format

**Comment by jwe-apple** [comment]
I applied the change in #35.
