### ISSUE TITLE
Revise logging implementation

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#256]
ORK_Log_Debug and ORK_Log_Oops need some control developers can exert besides using DEBUG / NDEBUG.

**Comment by p2** [comment]
+1 from me! I've changed the flag to `ORK_DEBUG` in my checkouts just to silence all the view-did-appear logs which obscure my own logging.

**Comment by rsanchezsaez** [comment]
I'll be working on this.

**Comment by rsanchezsaez** [comment]
@p2: PR submitted. Any feedback is welcome.

**Comment by rsanchezsaez** [comment]
This can be closed.
