### ISSUE TITLE
Rename 'ORKDeviceMotionReactionTime...' to 'ORKReactionTime...'

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#257]
The `ORKDeviceMotionReactionTime...` class names are a tad too long. I don't see any shortcomings to renaming them  to 'ORKReactionTime...'. It's also more in line to other device-motion using tasks like `ORKFitnessTask`.

**Comment by jwe-apple** [comment]
Yeah, I've converted.
