### ISSUE TITLE
Expose keyboard type property on text entry fields

### ISSUE THREAD

**Issue by brenbob** [ResearchKit/ResearchKit#261]
Would be helpful to have access to the same keyboard types supported in iOS, esp. for phone and e-mail entry.

enum UIKeyboardType : Int {
    case Default
    case ASCIICapable
    case NumbersAndPunctuation
    case URL
    case NumberPad
    case PhonePad
    case NamePhonePad
    case EmailAddress
    case DecimalPad
    case Twitter
    case WebSearch
}

**Comment by jwe-apple** [comment]
If adding phone and email, I'd like to have specific answer formats for them, with some form of validation.

**Comment by umerkhan-apple** [comment]
Currently working on this.

**Comment by umerkhan-apple** [comment]
https://github.com/ResearchKit/ResearchKit/pull/312

**Comment by YuanZhu-apple** [comment]
Done in #312
