### ISSUE TITLE
"Learn More" modal views show "Cancel", would "Done" be preferable?

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#266]
When going through consenting, there's always a "Cancel" button top right to abort consenting. When tapping "Learn More" on the individual steps, the learn more view is presented modal and also has a "Cancel" button top right. I feel it would be nicer if it was a "Done" button, both semantically and also to distinguish it from canceling consenting.

**Comment by jwe-apple** [comment]
Agree.

**Comment by YuanZhu-apple** [comment]
Fix in #268
