### ISSUE TITLE
Medication Adherence

### ISSUE THREAD

**Issue by julientherier** [ResearchKit/ResearchKit#291]
> "The treatment of chronic illnesses commonly includes the long-term use of pharmacotherapy. Although these medications are effective in combating disease, their full benefits are often not realized because approximately 50% of patients do not take their medications as prescribed."
[Brown et Bussell, 20011](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3068890/)

I'm wondering if participants/researchers using ResearchKit apps could benefit from a new module dedicated to "Medication Adherence":
• Select current medication using barcode/datamatrix recognition.
• Schedule local notifications based on the medication regimen.
• Any other idea...

What are your thoughts about that?
I know that each country has its own database linking barcode <-> medicine product, which could make difficult such a module.

**Comment by apaola2004** [comment]
Though there are apps to help a patient adhere to a daily regimen, I think this an important feature to add to Researchkit, simply because it will be a component of a universal framework for the future of public and individual health.  For example, strict adherence to HIV antivirals are important at keeping the virus at bay for the individual and drastically lowers the spread of the virus, when those infected are undetectable.

**Comment by apaola2004** [comment]
I am available to help implement this component.  I have 25+ years of software development experience from writing software to predict a weather satellite's attitude in orbit to smartphone applications for the DoD.

**Comment by julientherier** [comment]
Perhaps some questions to know if it could be a great extension to ResearchKit:
• Is "Medication Adherence" a usual part of a clinical study?
• Are the ResearchKit contributors willing to see "Medication Adherence" be part of the framework?
• General design strategy for such feature?

**Comment by p2** [comment]
There are a quite many studies studying medication adherence, it's a big field of research. As such it might be difficult to provide a base framework that is of use to such studies, which often use diverse data sources to get a participant started, such as admission and discharge med lists, reconciled lists from the EHR and even pharmacy fill lists. There often are no public APIs to these services, meaning the respective entities are to be involved in an adherence study, meaning you have to build custom connectors. And then there's the different coding systems in use such as RxNorm, NDC, ATC, ... Those will need external services to handle lookups and inferences.

Medication data is not currently stored in HealthKit. So, in any case, such a research app/module would start out at zero unless it would tie-in to an existing meds app that users use. I think a first step would be to actually build a ResearchKit app that tackles medication adherence, then see if it can be generalized into a useful module.

**Comment by julientherier** [comment]
@p2 "Medication data is not currently stored in HealthKit."
You're right. If it was supported by HealthKit, it could be easier to implement that in the future.
I saw in the WWDC sessions that Apple engineers extend HealthKit based on IoT availability, user and devs requests.

So the first step could be to ask for an HealthKit support of medication data.

**Comment by julientherier** [comment]
I saw the "Medication Tracking" classes in App Core.
Could be an option to import that code in ResearchKit?

**Comment by remotevision** [comment]
:+1: on collecting medication data from HealthKit

**Comment by md0u80c9** [comment]
Should this issue now be closed as it is a core part of CareKit?
