### ISSUE TITLE
Step result cleared on 'skip' action

### ISSUE THREAD

**Issue by brenbob** [ResearchKit/ResearchKit#295]
I have a question step populated with a step result. If I select the 'skip' button instead of 'next', and then return back to the step, the result is gone.

**Comment by rsanchezsaez** [comment]
I'm afraid that's the intended behaviour. The idea is that when a participant skips a step, that step has a null result independently of what was entered before.

**Comment by brenbob** [comment]
I suspected that's the case, but wanted to confirm. Since this can result in unexpected behavior, it might be good to have more explicit messaging on the skip action.

**Comment by YuanZhu-apple** [comment]
skip button can be customized through `skipButtonTitle` on `ORKStepViewController`
