### ISSUE TITLE
Localized numbers for UI elements

### ISSUE THREAD

**Issue by julientherier** [ResearchKit/ResearchKit#300]
Make timer localizable, some region doesn't use arabic numbers.

**Comment by YuanZhu-apple** [comment]
Absolutely. This is also covered by: <rdar://problem/21220738> Numbers should be in Hindi instead of Arabic-Latin.

- Count down timer
- Step progress ( Step 1 of 5 )
- Hz number in `ToneAudioMetry`
- Attempt count in Reaction Time Task ( Attempt 1 of 3 )

**Comment by YuanZhu-apple** [comment]
@umerkhan-apple is working one this.

**Comment by umerkhan-apple** [comment]
https://github.com/ResearchKit/ResearchKit/pull/301

**Comment by YuanZhu-apple** [comment]
Fixed in #301
