### ISSUE TITLE
[Swift] Introduction example does not work.

### ISSUE THREAD

**Issue by pawisoon** [ResearchKit/ResearchKit#303]
I tried that one and get error on 
taskViewController.delegate = self 

Cheers

**Comment by YuanZhu-apple** [comment]
Hey @pawisoon, which branch are you looking at? And the XCode version you have been using?

**Comment by pawisoon** [comment]
Newest xcode 6.4 and master branch. This is my viewcontroller 
![screen shot 2015-06-30 at 23 48 39](https://cloud.githubusercontent.com/assets/6951295/8443896/b9a76204-1f82-11e5-8add-d326c213309e.png)

**Comment by YuanZhu-apple** [comment]
What is the error/exception? I guess the `taskViewController` is not retained properly.

**Comment by pawisoon** [comment]
Rigth. My mistake :D I think I'm tired.. 
Works perfectly now 

![screen shot 2015-07-01 at 01 02 35](https://cloud.githubusercontent.com/assets/6951295/8444786/01ee0acc-1f8d-11e5-9e48-ca081f202d60.png)
