### ISSUE TITLE
ORKHealthKitCharacteristicTypeAnswerFormat does not have a member named 'minimumDate'

### ISSUE THREAD

**Issue by brendenwest** [ResearchKit/ResearchKit#308]
I'm using the code shown in RK documentation to collect a date-of-birth:

        var dobFormat = ORKHealthKitCharacteristicTypeAnswerFormat(characteristicType: HKCharacteristicType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierDateOfBirth))

It works fine for rendering a date picker, but doesn't support the minimumDate property available for ORKDateAnswerFormat.

**Comment by YuanZhu-apple** [comment]
@brenbob `ORKHealthKitCharacteristicTypeAnswerFormat ` set a default minimumDate 150 years to current date. 
Any reason you would like to change this default setting?

**Comment by brenbob** [comment]
I need to ensure respondents have a minimum age. Perhaps 'maximumDate' is the appropriate setting, but that's not supported either.

**Comment by YuanZhu-apple** [comment]
That's a valid point, we can consider expose `minimumDate` and `maximumDate` in the API of `ORKHealthKitCharacteristicTypeAnswerFormat` as optional attributes for date of birth.

**Comment by brucehappy** [comment]
I may not properly understand your purpose, but shouldn't determining whether the subject is at least of a certain age something that should be done in the onboarding process?  For instance, the AsthmaHealth app specifically asks if the subject is over 18 in question # 1:
https://github.com/ResearchKit/AsthmaHealth/blob/master/Asthma/Onboarding/APHInclusionCriteriaViewController.m

I am not suggesting the ability to restrict the minimum and maximum date shouldn't be exposed, however.  I'm just trying to understand if perhaps there is another way to accomplish what you want to do.

**Comment by rsanchezsaez** [comment]
I have implemented this feature in the aforementioned PR.

**Comment by rsanchezsaez** [comment]
This has been merged and the issue can be closed.
