### ISSUE TITLE
What is the offset for the timestamp float in the acceleration and device motion JSON output files

### ISSUE THREAD

**Issue by annashcherbina** [ResearchKit/ResearchKit#309]
Not sure if this is the right place to ask this, but I am working with the 6 Minute Walk test Research Kit data, and was wondering in an example like this from the acceleration output json file: 

{"y":-0.381866455078125,"timestamp":197914.039694875,"z":-1.011611938476562,"x":0.148529052734375}

what does the number 197914.03 seconds refer to (i.e. 197914.03 seconds since when). Comparing across subjects, it doesn't seem to have a single baseline. Is it the system up time?

**Comment by brucehappy** [comment]
I think you are referring to the JSON dictionary produced by ``CMAccelerometerData+ORKJSONDictionary.m``.  The timestamp is from ``CMAccelerometerData``, and more specifically, it is from its superclass, ``CMLogItem`` (which is also the super class for other types of data, like ``CMDeviceMotion``).  Here are the relevant docs:
https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMAccelerometerData_Class/
https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMLogItem_Class/index.html#//apple_ref/occ/instp/CMLogItem/timestamp
>``@property(readonly, nonatomic) NSTimeInterval timestamp``
> The time stamp is the amount of time in seconds since the phone booted.

So, you are correct in your assumption, the timestamp is indeed the uptime.

**Comment by jwe-apple** [comment]
These are the correct references.
