### ISSUE TITLE
UI briefly shows default button titles, although taskViewController: stepViewControllerWillAppear: overrides them

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#310]
Implementing `taskViewController: stepViewControllerWillAppear:` is the current way of modifying the default behavior of any `ORKStepViewController` (e.g. button titles). This approach has one major downside: When the UI flips to the next step, default button titles (e.g. cancel) remain visible for a quarter of a second.

**Comment by oliverschaefer** [comment]
I'd suggest a new `ORKTaskViewControllerDelegate` method, such as `taskViewController: configureStepViewController:`, which should be called from `ORKTaskViewController`'s `viewControllerForStep:` method

**Comment by umerkhan-apple** [comment]
Currently investigating this issue. Stay tuned, will let you know what I find.

**Comment by YuanZhu-apple** [comment]
@umerkhan-apple Can you comment here how this issue is addressed in the PR?

**Comment by umerkhan-apple** [comment]
Having ``[self setupButtons]`` inside ``viewDidLoad`` loads the default button titles in the navigation bar because the custom buttons have not been set at this point. The custom buttons are set inside ``viewWillAppear:`` when the delegate responds to the ``stepViewControllerWillAppear:``.

**Comment by YuanZhu-apple** [comment]
Fixed in #315
