### ISSUE TITLE
ORKHealthKitQuantityTypeAnswerFormat interacts poorly with HKUnit percentUnit

### ISSUE THREAD

**Issue by ubik2** [ResearchKit/ResearchKit#313]
When building a question step with ORKHealthKitQuantityTypeAnswerFormat and HKUnit.percentUnit(), the result is odd.

HealthKit wants to think of percent values as between 0 and 1, so a value of 50% will return 0.50 when you call [sample.quantity doubleValueForUnit:unit] in ORKAnswerDefaultSource.fetchDefaultValueForQuantityType where sample is a HKQuantitySample and unit is HKUnit.percentUnit().

The net result is that the ORKQuestionStepViewController shows a form field that says 0.50% instead of 50%.

One fix would be to special case the percent unit in ORKAnswerDefaultSource. Another approach would be to change the ORKQuestionStepViewController and ORKFormStepViewController.  Perhaps the defaultAnswerChanged method could be changed to clean up the value before displaying it. Unfortunately, this leaves the form field digging into the details of HealthKit.

The simpler fix is to change fetchDefaultValueForQuantityType to override the value for % units, but this seemed a bit ugly as well.

I'm not sure how many other unit types don't match the user expectations here. 

                if ([[unit unitString] isEqualToString: @"%"]) {
                    value = @(100 * [sample.quantity doubleValueForUnit:unit]);
                } else {
                    value = @([sample.quantity doubleValueForUnit:unit]);
                }

For my own code, I ended up creating a custom ORKAnswerFormat, using a % * cm/m unit, and setting an impliedAnswerFormat with a % unit so the displayed unit was still %, but I think it would be better addressed in ResearchKit instead.

**Comment by YuanZhu-apple** [comment]
Thanks @ubik2!
Yes, indeed, a special case is necessary.
It would more safe to compare the unit with  `HKUnit.percentUnit()` directly.
Would you like to make a pull request?
```

            if ([unit == HKUnit.percentUnit()]) {
                value = @(100 * [sample.quantity doubleValueForUnit:unit]);
            } else {
                value = @([sample.quantity doubleValueForUnit:unit]);
            }

```

**Comment by ubik2** [comment]
Created pull request: https://github.com/ResearchKit/ResearchKit/pull/314

**Comment by YuanZhu-apple** [comment]
#314 has been reviewed and merged.
