### ISSUE TITLE
HealthKit heart rate algorithm

### ISSUE THREAD

**Issue by annashcherbina** [ResearchKit/ResearchKit#319]
Hello, 

In the HealthKit heart rate data, I am seeing entries of the format: 

startTime,endTime,type,value,unit,source,sourceIdentifier
2015-03-12T05:35:39-05:00,2015-03-12T05:35:39-05:00,HKQuantityTypeIdentifierHeartRate,1.08333,count/s,Withings,com.withings.wiScaleNG

I noticed that the start time and end time are always the same for HeartRate, and was wondering why that is. If startTime an endTime are the same, how is the number 1.0833 count/s determined? Is this averaged across a specific time interval? How is this translated to beats/minute for display to the user? 

Also, please advice if there is a different venue where HealthKit questions should be directed. I am using both ResearchKit and HealthKit for my research and was wondering the best place to direct questions about these tools. 

Thank you!

**Comment by DanKeen** [comment]
The source for this is from Withings, so it's up to them to produce accurate start and end times for the sample.

HealthKit questions can be asked here - and we'll try to answer them - but the better venue is the iOS Developer Discussion Forum at forums.developer.apple.com

**Comment by annashcherbina** [comment]
Thanks for clarifying. However, in the same file as the Withings example, we have the same timestamp issue from multiple other devices, for example the Apple Watch: 

2015-05-05T20:05:22-05:00,2015-05-05T20:05:22-05:00,HKQuantityTypeIdentifierHeartRate,1.35,count/s,Subject's Apple Watch,com.apple.health.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

Is this a general issue with the algorithm? 
Thanks!

**Comment by DanKeen** [comment]
For the watch, we could probably figure out relatively accurate start and end times. However, due to the way we do PPG, there's not necessarily a clear signal of when the start of the averaging time was. Unlike with a contact-based HR sensor (like a chest strap) there's a lot of noise and interpretation happening, which means the individual heart beats aren't as easy to measure, and so a strict start / end date doesn't work. But I think we could still give a more reasonable start and end time :)

**Comment by annashcherbina** [comment]
That makes sense, thanks. Although the exact start/end times are hard to identify, what is the approximate interval of time (i.e. several seconds, one minute, etc.) over which the averaging is done to report the counts/s

**Comment by DanKeen** [comment]
It depends - could be tens of seconds for certain situations - and that's only for the Watch vs other apps doing a similar thing. I'm not sure you could make any informed guesses here vs just "at this point, HR was deemed to be 81bpm".

**Comment by jwe-apple** [comment]
To address your question about how count/s is determined, I'm guessing this CSV came from one of the apps using AppCore. These specify in their AppDelegate what HealthKit unit to use when serializing sample data retrieved from HealthKit. HKQuantity's doubleValueForUnit: method is used to extract a numeric value in the appropriate unit. If you wanted to display or serialize bpm, you would use a different unit when extracting the data from HealthKit.

**Comment by annashcherbina** [comment]
Thank you jwe-apple. On a related note, I am seeing data for "HKCategoryTypeIdentifierSleepAnalysis" in units of "seconds asleep" and "seconds in bed". Is there a difference in how these are calculated, or is the unit-designation app-specific like with the count/s case? 

Thanks!

**Comment by jwe-apple** [comment]
Again, that sounds app-specific, but it's possible the actual implementation for it is in AppCore. HKCategoryTypeIdentifierSleepAnalysis is a category type in HealthKit, so the underlying data does not have units (it just has objects each with a duration, identifying whether in bed or asleep). Units like "seconds in bed" or "seconds asleep" come from user code, not from HealthKit.
