### ISSUE TITLE
Could not cast value of type 'ORKTaskResult' to 'ORKSpatialSpanMemoryResult'

### ISSUE THREAD

**Issue by pawisoon** [ResearchKit/ResearchKit#320]
Hi!
I'm trying to handle the output from spatial span memory task via taskViewController and my code seems to be ok. I created it by looking on ORK sample project.

Here is how I do it now. 

    func taskViewController(taskViewController: ORKTaskViewController, didFinishWithReason reason: ORKTaskViewControllerFinishReason, error: NSError?) {
        //handle output
        
        let taskResult = taskViewController.result as ORKResult
        
        
        let questionResult = taskResult as! ORKSpatialSpanMemoryResult
        
        

        println("Score \(questionResult.score) Number of games \(questionResult.numberOfGames) Number of failuers \(questionResult.numberOfFailures)")
        

        dismissViewControllerAnimated(true, completion: nil)
    }

And i got  cast error on it. 
Could not cast value of type 'ORKTaskResult' (0x1030e8fa8) to 'ORKSpatialSpanMemoryResult' (0x1030e8aa8).
(lldb) 

Can somebody help me with this?

Cheers

**Comment by YuanZhu-apple** [comment]
Hey @pawisoon 
`ORKSpatialSpanMemoryResult` and `taskResult` are both subclass of `ORKResult`.

Here is an example how to parse ORKTaskResult:
```
    for (ORKStepResult *sResult in taskViewController.result.results) {
        NSLog(@"--%@", sResult);
        for (ORKResult *result in sResult.results) {
            if ([result isKindOfClass:[ORKDateQuestionResult class]]) {
                ORKDateQuestionResult *dqr = (ORKDateQuestionResult *)result;
                NSLog(@"    %@:   %@  %@  %@", result.identifier, dqr.answer, dqr.timeZone, dqr.calendar);
            } else if ([result isKindOfClass:[ORKQuestionResult class]]) {
                ORKQuestionResult *qr = (ORKQuestionResult *)result;
                NSLog(@"    %@:   %@", result.identifier, qr.answer);
            } else if ([result isKindOfClass:[ORKTappingIntervalResult class]]) {
                ORKTappingIntervalResult *tir = (ORKTappingIntervalResult *)result;
                NSLog(@"    %@:     %@\n    %@ %@", tir.identifier, tir.samples, NSStringFromCGRect(tir.buttonRect1), NSStringFromCGRect(tir.buttonRect2));
            } else if ([result isKindOfClass:[ORKFileResult class]]) {
                ORKFileResult *fileResult = (ORKFileResult *)result;
                NSLog(@"    File: %@", fileResult.fileURL);
            } else if ([result isKindOfClass:[ORKToneAudiometryResult class]]) {
                ORKToneAudiometryResult *tor = (ORKToneAudiometryResult *)result;
                NSLog(@"    %@:     %@", tor.identifier, tor.samples);
            } else {
                NSLog(@"    %@:   userInfo: %@", result.identifier, result.userInfo);
            }
        }
    }
```

**Comment by pawisoon** [comment]
Is it possible to get an answer in Swift? I don't code in Obj-c :/

**Comment by coxy1989** [comment]
In case you are still in need @pawisoon 

        if let results = taskViewController.result.results {
            print("\(results)")
            for result in results {
                if let dateQuestionResult = result as? ORKDateQuestionResult {
                    print("\(dateQuestionResult.identifier), \(dateQuestionResult.answer), \(dateQuestionResult.timeZone), \(dateQuestionResult.calendar)")
                }
                else if let questionResult = result as? ORKQuestionResult {
                    print("\(questionResult.identifier), \(questionResult.answer)")
                }
                else if let tappingResult = result as? ORKTappingIntervalResult {
                    print("\(tappingResult.identifier), \(tappingResult.samples), \(NSStringFromCGRect(tappingResult.buttonRect1)) \(NSStringFromCGRect(tappingResult.buttonRect1)))")
                }
                else if let fileResult = result as? ORKFileResult {
                        print("\(fileResult.identifier), \(fileResult.fileURL)")
                }
                else if let toneAudiometryResult = result as? ORKToneAudiometryResult {
                    print("\(toneAudiometryResult.identifier), \(toneAudiometryResult.samples)")
                }
                else if let result = result as? ORKResult {
                    print("\(result.identifier), \(result.userInfo)")
                }
            }
        }

**Comment by YuanZhu-apple** [comment]
@coxy1989 Thanks!

**Comment by pawisoon** [comment]
@coxy1989 cheers! you're life saver.
I added it to my code and changed it  a little bit but I still cant get output from SpatialSpanMemoryTest... 
The results should be type of OKTSpatialSpanMemoryResult with identifier cognitive.memory.spatialspan
maybe there's an issue in the way I start the activity? 
I got the button and on it's click i present the view controller 
  var spatialSpanMemoryTask: ORKTask {
        return ORKOrderedTask.spatialSpanMemoryTaskWithIdentifier(Identifier.SpatialSpanMemoryTask.rawValue, intendedUseDescription: "Spatial Span Memory Active Task", initialSpan: 3, minimumSpan: 2, maximumSpan: 15, playSpeed: 1.0, maxTests: 1, maxConsecutiveFailures: 3, customTargetImage: nil, customTargetPluralName: nil, requireReversal: false, options: nil)
    }
    
    


   func taskViewController(taskViewController: ORKTaskViewController, didFinishWithReason reason: ORKTaskViewControllerFinishReason, error: NSError?) {
        if let results = taskViewController.result.results {
            println("Results \(results)")
            for result in results {
                
                if let questionResult = result as? ORKQuestionResult {
                    print("\(questionResult.identifier), \(questionResult.answer)")
                }
                else if let tappingResult = result as? ORKTappingIntervalResult {
                    print("\(tappingResult.identifier), \(tappingResult.samples), \(NSStringFromCGRect(tappingResult.buttonRect1)) \(NSStringFromCGRect(tappingResult.buttonRect1)))")
                }
                else if let toneAudiometryResult = result as? ORKToneAudiometryResult {
                    print("\(toneAudiometryResult.identifier), \(toneAudiometryResult.samples)")
                }
                else if let questionResult = result as? ORKSpatialSpanMemoryResult{
                    println("Score \(questionResult.score) Number of games \(questionResult.numberOfGames) Number of failuers \(questionResult.numberOfFailures)")
                }
                else{
                    println("No printable results.")
                }
                
            }
        }
        
        dismissViewControllerAnimated(true, completion: nil)
        taskViewController.dismissViewControllerAnimated(true, completion: nil)
    }

**Comment by pawisoon** [comment]
@coxy1989 cheers! you're life saver.
I added it to my code and changed it a little bit but I still cant get output from SpatialSpanMemoryTest...
The results should be type of OKTSpatialSpanMemoryResult with identifier cognitive.memory.spatialspan
maybe there's an issue in the way I start the activity?
I got the button and on it's click i present the view controller

 var spatialSpanMemoryTask: ORKTask {
       return ORKOrderedTask.spatialSpanMemoryTaskWithIdentifier(Identifier.SpatialSpanMemoryTask.rawValue, intendedUseDescription: "Spatial Span Memory Active Task", initialSpan: 3, minimumSpan: 2, maximumSpan: 15, playSpeed: 1.0, maxTests: 1, maxConsecutiveFailures: 3, customTargetImage: nil, customTargetPluralName: nil, requireReversal: false, options: nil)
    }

**Comment by pawisoon** [comment]
@coxy1989 cheers! you're life saver.
I added it to my code and changed it a little bit but I still cant get output from SpatialSpanMemoryTest...
The results should be type of OKTSpatialSpanMemoryResult with identifier cognitive.memory.spatialspan
maybe there's an issue in the way I start the activity?
I got the button and on it's click i present the view controller

``` 
var spatialSpanMemoryTask: ORKTask {
        return ORKOrderedTask.spatialSpanMemoryTaskWithIdentifier(Identifier.SpatialSpanMemoryTask.rawValue, intendedUseDescription: "Spatial Span Memory Active Task", initialSpan: 3, minimumSpan: 2, maximumSpan: 15, playSpeed: 1.0, maxTests: 1, maxConsecutiveFailures: 3, customTargetImage: nil, customTargetPluralName: nil, requireReversal: false, options: nil)
    } 
``` 

``` 
  func taskViewController(taskViewController: ORKTaskViewController, didFinishWithReason reason: ORKTaskViewControllerFinishReason, error: NSError?) {
        if let results = taskViewController.result.results {
            println("Results \(results)")
            for result in results {
                
                if let questionResult = result as? ORKQuestionResult {
                    print("\(questionResult.identifier), \(questionResult.answer)")
                }
                else if let tappingResult = result as? ORKTappingIntervalResult {
                    print("\(tappingResult.identifier), \(tappingResult.samples), \(NSStringFromCGRect(tappingResult.buttonRect1)) \(NSStringFromCGRect(tappingResult.buttonRect1)))")
                }
                else if let toneAudiometryResult = result as? ORKToneAudiometryResult {
                    print("\(toneAudiometryResult.identifier), \(toneAudiometryResult.samples)")
                }
                else if let questionResult = result as? ORKSpatialSpanMemoryResult{
                    println("Score \(questionResult.score) Number of games \(questionResult.numberOfGames) Number of failuers \(questionResult.numberOfFailures)")
                }
                else{
                    println("No printable results.")
                }
                
            }
        }
        
        dismissViewControllerAnimated(true, completion: nil)
        taskViewController.dismissViewControllerAnimated(true, completion: nil)
    }
    
``` 

Could you please help me with this?

**Comment by coxy1989** [comment]
Hi @pawisoon, 

Is this function being called? If not, make sure you have set the delegate property of the presenting ORKTaskViewController.

**Comment by pawisoon** [comment]
Yes taskViewController func is being called every time some activity ends i got output  from last else statement .
I used this tutorial http://www.raywenderlich.com/104575/researchkit-tutorial-with-swift just instead of using new class for activity I put it inside my ViewController. 

when I call spatialMemoryTask i set delegate property like that 


```
 let taskViewController = ORKTaskViewController(task: spatialSpanMemoryTask, taskRunUUID:nil)
            taskViewController.delegate = self
            presentViewController(taskViewController, animated: true, completion: nil)
```

**Comment by coxy1989** [comment]
Have you checked what type you are actually getting back by including:

   else if let result = result as? ORKResult {
                print("\(result.identifier), \(result.userInfo)")
            }

or alternatively by setting a break point ?

**Comment by pawisoon** [comment]
I'm getting  this from first print statement 
Results [<ORKStepResult: 0x7fa2f245e880>, <ORKStepResult: 0x7fa2f25ec650>, <ORKStepResult: 0x7fa2f25dd490>, <ORKStepResult: 0x7fa2f2448bd0>]
and on 
else if let result = result as? ORKResult   I got this 
instruction, nilinstruction1, nilcognitive.memory.spatialspan, nilconclusion, nil

**Comment by coxy1989** [comment]
Fixed:

      if let results = taskViewController.result.results as? [ORKStepResult] {
            println("Results: \(results)")
            for stepResult: ORKStepResult in results {
                
                for result in stepResult.results as! [ORKResult] {
                    
                    if let questionResult = result as? ORKQuestionResult {
                        print("\(questionResult.identifier), \(questionResult.answer)")
                    }
                    if let tappingResult = result as? ORKTappingIntervalResult {
                        print("\(tappingResult.identifier), \(tappingResult.samples), \(NSStringFromCGRect(tappingResult.buttonRect1)) \(NSStringFromCGRect(tappingResult.buttonRect1)))")
                    }
                    if let toneAudiometryResult = result as? ORKToneAudiometryResult {
                        print("\(toneAudiometryResult.identifier), \(toneAudiometryResult.samples)")
                    }
                    if let spatialSpanResult = result as? ORKSpatialSpanMemoryResult {
                        println("Score \(spatialSpanResult.score) Number of games \(spatialSpanResult.numberOfGames) Number of failuers \(spatialSpanResult.numberOfFailures)")
                    }
                    else{
                        println("No printable results.")
                    }
                    
                }
            }

        }

The result children are nested twice.

**Comment by pawisoon** [comment]
@coxy1989 you re my hero! Thanks a lot! 
Can you just tell me what's a difference between statement like this 
```
taskViewController.result.results as? [ORKStepResult]
```
 and without [ ] brackets?

**Comment by coxy1989** [comment]
Indeed

 as? [ORKStepResult] conditionally downcasts to an array of ORKStepResults.
 as? ORKStepResult  conditionally downcasts to ORKStepResult.

TaskViewController.result.results is of type [ORKStepResult] (an array). Each ORKStepResult also has an array of ORKResults. Therefore we need to iterate over the ORKStepResult array and for each entry iterate over it's child results.
