### ISSUE TITLE
Task Progress - API Design

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#322]
It would be valuable to let users know how many steps of a given task are already completed (= fully answered and not skipped). Currently this requires iterating through the `ORKTaskResult`, which is only available through the task view controller. That information should be available even if the task itself is not currently presented via the view controller. 

The implementation of such a new feature would possibly require changes to `ORKStep`, `ORKTaskViewController`, `ORKStepViewController` and/or `ORKTaskViewControllerDelegate`.

**Comment by oliverschaefer** [comment]
One way would be to add a `completed` property to `ORKStep`. That property should be set through the step view controller once the associated result changes. The step view controller could ask the task view controller's delegate whether a step with a particular result should be marked as completed or not: `taskViewController:isStepCompleted:withResult:`

`ORKTask` should include something like `progressOfTask:withResult:`. The number of completed steps in any `ORKOrderedTask` subclass could simply be returned by filtering the completed steps out of the steps array.

**Comment by umerkhan-apple** [comment]
@oliverschaefer From my understanding, you are trying to calculate the number of completed steps in any `ORKOrderedTask` using a `completed` property from `ORKStep`. This same result can be achieved by iterating through `ORKTaskResult` (which is the current implementation) vs iterating through all `ORKStep` (which is your suggested implementation). 

Why do you recommend this implementation then? Is there a specific use case or reason for which it would be useful?

**Comment by oliverschaefer** [comment]
@umerkhan-apple Yep, you are completely right. But there are situations were you don't have the `ORKTaskResult` object to iterate through. I'm currently working on an app that features a set of survey tasks. The user selects a particular task from a table view to bring up the task view controller. I'd like to include the number of completed/total steps in each table view cell. As long as the task view controller is present, iterating through `ORKTaskResult` gets the job done. But what if I need to update the completed/total steps count for the other cells? Their tasks are not currently attached to a task view controller, so no task result is available. Of course I could save the task result somewhere and load it when needed, but that seems to be less performant than querying the task directly?

**Comment by umerkhan-apple** [comment]
@oliverschaefer It seems that the surveys in your app are only completed by one particular user and you want to track the progress of that one user. In order to achieve this, you can store the information you need to display progress when storing the results from the task. It is not recommended to add a completed property into `ORKStep` because it would limit the usability to one user per survey, and the model for `ORKTask` is to allow multiple users to complete the survey.

**Comment by oliverschaefer** [comment]
@umerkhan-apple Okay. I've changed my implementation which now keeps the task's restoration data once the user switches from task to task. The actual progress is than calculated from the `ORKTaskResult` as does the standard implementation. However i've noticed an issue when restoring `ORKTaskViewController` (that is initializing it with `initWithTask: restorationData:`). The task view controller restores its' state and calls `applicationFinishedRestoringState` directly thereafter. This method configures the restored step view controller and finally displays it. Since there is no way to set the task view controller's `delegate` property before state restoration finishes, no delegate calls are made when the restored step view controller is displayed. I assume this is not expected behavior?

**Comment by umerkhan-apple** [comment]
@oliverschaefer That is not the expected behavior. However, lets start a new issue targeting this problem. If possible, include a sample project with the implementation, so the bug can be reproduced.

**Comment by oliverschaefer** [comment]
@umerkhan-apple opened #325 with exemplary project
