### ISSUE TITLE
ORKTaskViewController state restoration

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#325]
There is an issue when restoring `ORKTaskViewController` (that means initializing it with `initWithTask: restorationData:`). The task view controller restores its' state and calls `applicationFinishedRestoringState` directly thereafter. Since there is no way to set the task view controller's delegate property before state restoration finishes, no delegate calls are made. An exemplary project can be found under: https://github.com/oliverschaefer/ORKTaskRestorationSample

**Comment by umerkhan-apple** [comment]
@oliverschaefer I was able to reproduce the bug and will post a PR with the fix soon.

**Comment by umerkhan-apple** [comment]
@oliverschaefer Please review https://github.com/ResearchKit/ResearchKit/pull/326

**Comment by oliverschaefer** [comment]
@umerkhan-apple Yep, that solves the issue. Can be merged safely.

**Comment by YuanZhu-apple** [comment]
#326 Merged.
