### ISSUE TITLE
Expose hasBeenPresented property of ORKStepViewController

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#336]
When `stepViewControllerWillAppear:` gets called, it would be nice to know if it is for the first time or not (maybe the view was covered by another view controller which got dismissed). Exposing the `hasBeenPresented` property of `ORKStepViewController` would be an easy solution.

**Comment by YuanZhu-apple** [comment]
Good idea, as long as it is `readonly`

**Comment by oliverschaefer** [comment]
@YuanZhu-apple I've created a PR for this. Please review
