### ISSUE TITLE
CustomRecorder in ORKTest not working as intended

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#340]
The `CustomRecorder` sample class used in the `ORKTest` app doesn't seem to work as intended.

Steps to reproduce:
- Run `ORKTest`'s *ActiveStep Task* and go *Step 5* (*Button Tap*).
- Tap start timer.

Actual result:
- Green area doesn't show and tappable orange button appears partially covered by navigation bar.

Expected result
- Green area should show below step header, and tappable orange button should appear inside green area.

---

The problem seems to be that `CustomRecorder` adds the green view directly to `activeStepView.customViewContainer` (passed in `- (void)viewController:willStartStepWithView:`). However, `activeStepView.customView` property is not updated with the custom view, so the relevant `ORKVerticalContainerView` constrains are not updated accordingly.

**Comment by YuanZhu-apple** [comment]
Yes, I think that sample is outdated. I will review them later.

**Comment by rsanchezsaez** [comment]
I have a fix, I'll submit a PR.
