### ISSUE TITLE
Incorporating APC Dashboard into Application

### ISSUE THREAD

**Issue by skoth001** [ResearchKit/ResearchKit#344]
I was wondering if anybody could help me incorporate the dashboard into my application, I am writing it in swift

**Comment by jwe-apple** [comment]
Do you have a backing database, or do you just want the dashboard UI?

And - what's your intent? Are you looking to port the dashboard to Swift, extract the Objective-C implementation from APC and use it standalone within your app more or less as is, or to port it to ResearchKit (the latter two could be compatible)?

**Comment by skoth001** [comment]
So I made an application that takes advantage of research kit, but I want to incorporate the dashboard ui, to show some of the results from the surveys and tasks that I have created

**Comment by umerkhan-apple** [comment]
@skoth001 Can you achieve this by using the newly added Charts library?

**Comment by skoth001** [comment]
That's what I ended up using.

**Comment by rsanchezsaez** [comment]
This issue can be closed, right?

**Comment by YuanZhu-apple** [comment]
Yes. Closing it.
