### ISSUE TITLE
restarting an already taken survey: ORKOrderedTask?

### ISSUE THREAD

**Issue by kristofer** [ResearchKit/ResearchKit#364]
There seems to be little doc related to this, but only tangentially: Once the user has taken my survey, how to re-enable the survey for them to take it again?

If it has not been taken by the user, one can take it. Once taken, it cannot be taken again. 
If the user has completed it, how to reset it to be able to be taken again?

**Comment by YuanZhu-apple** [comment]
@kristofer You use a same `ORKOrderedTask`, but each time you need to set up a new `ORKTaskViewController` with it. Then present the new `ORKTaskViewController` each time.

**Comment by kristofer** [comment]
I am doing this in swift, and I suppose that destroying the existing taskViewController is not something I can do? I tried making it a instance var of the viewcontroller that is embedded in a nav controller, (I do all my init in that view's viewDidLoad())

when I set the instance var to nil after the dismissViewControllerAnimated() in taskViewController(taskViewController: ORKTaskViewController,
        didFinishWithReason reason: ORKTaskViewControllerFinishReason,
        error: NSError?)

nothing happened, it seems the old taskViewController is still around.

I'm getting the impression Swift doesn't like me doing manual object management.

**Comment by YuanZhu-apple** [comment]
No need to set your ivar to nil.
Just make your ivar = `a new TaskVC`, and then present it.

**Comment by kristofer** [comment]
I see where I'm going wrong. I put all the survey setup in the viewDidLoad() of a generic viewcontroller embedded in a nav controller (which is called from my main tabview controller) and that is really only being called once by the tabview controller. I have to figure out a way to present the taskViewController from the nav controller, rather than the generic viewcontroller I have there in my storyboard.

hmmmm....

**Comment by kristofer** [comment]
and I am getting a 
```
2015-08-06 16:28:50.872 Secretary[25984:2466587] Presenting view controllers on detached view controllers is discouraged <Secretary.SurveyViewController: 0x7f8e98476f10>.
```
as well.

**Comment by kristofer** [comment]
it might be good to have a little snippet that shows how create a taskviewcontroller in code from a navigation controller and then be able to put that wherever, like as a controller for a tabviewcontroller...

**Comment by YuanZhu-apple** [comment]
@kristofer Did you see `ORKCatalog`?
https://github.com/ResearchKit/ResearchKit/tree/master/samples/ORKCatalog

**Comment by acegreen** [comment]
@YuanZhu-apple what if I'm not presenting ORKTaskViewController but rather having one of my VCs in my tabBarViewController assigned as ORKTaskViewController. There shouldn't be the need to always present this VC. Also there should be a method to reset an already started task on an ORKTaskViewController instance
