### ISSUE TITLE
Add a property to ORKStepResult which indicates which assistive technology was enabled

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#369]
If a user enabled assistive technology, he/she could take more time solving a problem (e.g. TowerOfHanoiTower). 

So having that property on all step result, information of whether an assistive technology was enabled during any given step is available. 

These functions can help you determine whether an assistive technology is running:

BOOL UIAccessibilityIsVoiceOverRunning()
BOOL UIAccessibilityIsSwitchControlRunning()

And these constants can be used as the value of the property mentioned above:

NSString *const UIAccessibilityNotificationVoiceOverIdentifier
NSString *const UIAccessibilityNotificationSwitchControlIdentifier

**Comment by rsanchezsaez** [comment]
I have implemented this.

**Comment by rsanchezsaez** [comment]
This feature has been merged and the issue can be closed.
