### ISSUE TITLE
Vertical slider label no longer line-breaks

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#381]
We have longer labels on the vertical slider. The bottom one no longer breaks into multiple lines, the top one still does.

This is a regression some time after c856b29933af99bcee91dd7af733a90cc09885ab.

![screen shot 2015-08-18 at 11 48 19](https://cloud.githubusercontent.com/assets/358485/9349073/a839aede-4640-11e5-9264-c1e7f9b6f9e0.png)

**Comment by umerkhan-apple** [comment]
https://github.com/ResearchKit/ResearchKit/pull/407
