### ISSUE TITLE
Question step title label chops off one character

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#386]
I've only seen this happening on this one question, and only on 4" screens:

When linebreaking the label chops off "g" from "performing". I double checked and there is no space nor any hidden characters in the string.

![screen shot 2015-08-20 at 23 14 31](https://cloud.githubusercontent.com/assets/358485/9395967/e9ab8016-4791-11e5-8f1e-9522ab2b6e35.png)

**Comment by YuanZhu-apple** [comment]
Does this happen on a device? And what is the iOS version?

**Comment by p2** [comment]
Happens on Simulator (Xcode 6.4, iOS 8) and on device (iPhone 5S, I _think_ iOS 8 but am not sure, is a tester's device).

**Comment by umerkhan-apple** [comment]
@p2 Unable to reproduce the bug on Simulator or Hardware. Could you possibly share a sample project and the exact text size setting?

**Comment by p2** [comment]
Apologies, I checked again and indeed there were some `\u{00a0}` (non-breaking) spaces in the string. If those are replaced with regular spaces the problem disappears.
