### ISSUE TITLE
X-Axis Labels are overlayed with large amounts of data

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#388]
![x axis labels](https://cloud.githubusercontent.com/assets/11466704/9399259/95b26752-4766-11e5-8dd5-3bf46b8e111e.png)

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Because the titles are provided by the developer, maybe this is not an issue of the framework.

If a developer skips some titles when feeding the chartView, the overlapping can be avoid.
```
func graphChartView(graphChartView: ORKGraphChartView, titleForXAxisAtIndex pointIndex: Int) -> String {
        if (pointIndex%2 == 1) {
            return "\(pointIndex + 1)"
        }
        return ""
    }
```
Comments?

**Comment by rsanchezsaez** [comment]
Yeah, I agree about your proposed workaround being enough for `convergence` for now.

Maybe later we can provide more robust support by providing a delegate method which tells the graph an interval for reference lines and labels (third point of [Issue #379](https://github.com/ResearchKit/ResearchKit/issues/379)).

**Comment by rsanchezsaez** [comment]
This can be closed, as the new `dataSource` methods provide maximum flexibility to the developer.

**Comment by YuanZhu-apple** [comment]
Yep.
