### ISSUE TITLE
[Swift] Reaction time task doesn't detect shaking the device 

### ISSUE THREAD

**Issue by pawisoon** [ResearchKit/ResearchKit#400]
Hi all!
I added reaction time task to my app and it doesn't detect shaking the phone.
Example in ORKCatalog works on my device but my implementation of this task in my app doesn't.
I got similar issue with dismissing the screen and I solved it by one statement.

I start the activity by 
```
            let taskViewController = ORKTaskViewController(task: reactionTimeTask, taskRunUUID: nil)
            taskViewController.delegate = self
            presentViewController(taskViewController, animated: true, completion: nil)
```
and the task 
```
 //reaction time task
    
    private var reactionTimeTask: ORKTask {
        return ORKOrderedTask.reactionTimeTaskWithIdentifier(Identifier.ReactionTime.rawValue, intendedUseDescription: "Reaction time task", maximumStimulusInterval: 10, minimumStimulusInterval: 4, thresholdAcceleration: 0.5, numberOfAttempts: 3, timeout: 3, successSound: exampleSuccessSound, timeoutSound: 0, failureSound: UInt32(kSystemSoundID_Vibrate), options: nil)
    }
```

Any ideas what could go wrong?

Also is there any documentation on what values each of prebuild activities returns? For eg. is there any way to get finger tapping count returned in taskViewController using result handler? 

Cheers 
P

**Comment by remotevision** [comment]
I haven't tried using it myself, but have you authorized your application to use ```Motion Sensor```?

**Comment by pawisoon** [comment]
@remotevision you mean adding CoreMotion.framework to app directory? Or is there other way to do this?

**Comment by rsanchezsaez** [comment]
@pawisoon: can you post a minimal example project to *GitHub* showing the problem?

**Comment by pawisoon** [comment]
@rsanchezsaez  here: https://github.com/pawisoon/ResearchKit-App 
When you press the reaction time task the blue bubble shows up but it doesn't respond to shaking the phone.

**Comment by rsanchezsaez** [comment]
@pawisoon: Sorry for my late reply. I went on to check the issue but the repo is no longer there. Were you able to solve the issue?

**Comment by rsanchezsaez** [comment]
I think this may be closed, unless somebody is able to reproduce it.

**Comment by YuanZhu-apple** [comment]
Closed.

**Comment by majeedyaseen** [comment]
I am facing the same issue with the ReactionTime Active Task. The blue dot doesn't disappear when I am shaking my phone.

Here is how I have implemented it 

`    func ReactionTime (_ indexpath: IndexPath, cell: UITableViewCell) -> Void {
        let reaction = ORKOrderedTask.reactionTime(withIdentifier: "ReactionTime", intendedUseDescription: "This is the stroop test", maximumStimulusInterval: 2, minimumStimulusInterval: 1, thresholdAcceleration: 0.5, numberOfAttempts: 1, timeout: 1, successSound: 1, timeoutSound: 2, failureSound: 3, options: ORKPredefinedTaskOption.init(rawValue: 0))
        let reactionViewController = ORKTaskViewController(task: reaction, taskRun: nil)
        present(reactionViewController, animated: true, completion: nil)
    }
`
