### ISSUE TITLE
Step title is sometimes taller than necessary

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#405]
Sometimes the question step title label is taller than it should be. I have observed this when a question step title label is about to take three lines, but it actually fits in two. This causes the step to scroll even when the title is two lines, when it shouldn't be needed.

See the difference in height when removing the `?` character from the title in the _8th step_ of the _Scale Tests_ in `ORKTest`, on an _iPhone 6_.

It happens both on _iOS 8.4.1_ and on _iOS 9_, both on device and simulator.

---

Correct height:

![screen shot 2015-08-26 at 23 03 10](https://cloud.githubusercontent.com/assets/444313/9507516/aeaac22e-4c46-11e5-8894-f4dc25f013e6.png)

---

Wrong height:

![screen shot 2015-08-26 at 23 00 54](https://cloud.githubusercontent.com/assets/444313/9507517/aecbd3e2-4c46-11e5-93f9-520381d80850.png)

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple: do you think this could be an *iOS 9 SDK* bug regarding `UILabel`'s `intrinsicContentSize` calculations?

 I've looked into it and I can't find anything on *ResearchKit*'s code that would cause this.

**Comment by kelseydedoshka-apple** [comment]
@rsanchezsaez are you still seeing this issue on iOS 10?

**Comment by akshay-yadav-apple** [comment]
@rsanchezsaez This seems to be resolved on iOS 11.
