### ISSUE TITLE
Convert ORKTest into UICollectionView

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#419]
Should we convert `ORKTest`'s main view controller into a `UICollectionView`?

At the rate it's growing, it won't fit on the screen soon. This will also provide the opportunity to reorganize the different items in sections.

**Comment by YuanZhu-apple** [comment]
Sure. I like it.

**Comment by rsanchezsaez** [comment]
Cool, I'll do this soon.
