### ISSUE TITLE
Add version tags

### ISSUE THREAD

**Issue by vtourraine** [ResearchKit/ResearchKit#42]
I think it would be very useful to start tagging “versions” of the framework.

It would be useful to keep track of the progress being made, new features/tasks being added, and would facilitate a lot of things going forward. 

I’m not sure if keeping track of the versions from the framework itself would be interesting, but having at least Git tags seems very important to me. It’s also basically mandatory for CocoaPods, and other similar dependencies managers.

```
git tag 1.0
git tag push --tags
```

**Comment by YuanZhu-apple** [comment]
Tag pushed.

**Comment by vtourraine** [comment]
Fantastic, thanks.
