### ISSUE TITLE
problem installing ResearchKit via Cocoapods for level > 1.0

### ISSUE THREAD

**Issue by avrahamleff** [ResearchKit/ResearchKit#447]
ResearchKit podspec file https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit.podspec is at v1.1.2 but cannot be accessed as a CocoaPod

pod search ResearchKit
-> ResearchKit (1.0.0)
   ResearchKit is an open source software framework that makes it easy to create apps for medical research or for other research projects.
   pod 'ResearchKit', '~> 1.0.0'
   - Homepage: https://www.github.com/ResearchKit/ResearchKit
   - Source:   https://github.com/ResearchKit/ResearchKit.git
   - Versions: 1.0.0 [master repo]

**Comment by YuanZhu-apple** [comment]
Here is what I got:
```
pod search ResearchKit


-> ResearchKit (1.1.2)
   ResearchKit is an open source software framework that makes it easy to create apps for medical research or for other research projects.
   pod 'ResearchKit', '~> 1.1.2'
   - Homepage: https://www.github.com/ResearchKit/ResearchKit
   - Source:   https://github.com/ResearchKit/ResearchKit.git
   - Versions: 1.1.2, 1.0.0 [master repo]
```
BTW, what is your pod version?
```
pod --version
0.37.2
```

**Comment by avrahamleff** [comment]
pod --version
0.38.2

**Comment by avrahamleff** [comment]
Not sure if this is relevant (pod commands such as "install" have been working fine, but the "pod search" commands gives these error messages before returning "ResearchKit (1.0.0)"

---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- pod/command/plugins
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
---------------------------------------------

**Comment by avrahamleff** [comment]
I did an rm -rf on the .cocoapods directory, reinstalled cocopods and now get
-> ResearchKit (1.2)
   ResearchKit is an open source software framework that makes it easy to create apps for medical research or for other research projects.
   pod 'ResearchKit', '~> 1.2'
   - Homepage: https://www.github.com/ResearchKit/ResearchKit
   - Source:   https://github.com/ResearchKit/ResearchKit.git
   - Versions: 1.2, 1.1.2, 1.0.0 [master repo]

Thanks for pointing in the right direction!
