### ISSUE TITLE
Version 1.2 Build Errors in Xcode 6.4 Base SDK iOS 8.4

### ISSUE THREAD

**Issue by sayan1886** [ResearchKit/ResearchKit#452]
CompileC /Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/Objects-normal/x86_64/ORKFitnessStepViewController.o ResearchKit/ActiveTasks/ORKFitnessStepViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd ResearchKit
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fobjc-arc -fmodules -fmodules-cache-path=Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang ResearchKit -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=8.0 -iquote Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/ResearchKit-generated-files.hmap -ILibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/ResearchKit-own-target-headers.hmap -ILibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/ResearchKit-all-non-framework-target-headers.hmap -ivfsoverlay Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/all-product-headers.yaml -iquote Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/ResearchKit-project-headers.hmap -ILibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -ILibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/DerivedSources/x86_64 -ILibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/DerivedSources -FLibrary/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/Objects-normal/x86_64/ORKFitnessStepViewController.d --serialize-diagnostics Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/Objects-normal/x86_64/ORKFitnessStepViewController.dia -c ResearchKit/ResearchKit/ActiveTasks/ORKFitnessStepViewController.m -o Library/Developer/Xcode/DerivedData/ResearchKit-gsteofdkzuamunbnpihpfkxhtxhi/Build/Intermediates/ResearchKit.build/Debug-iphonesimulator/ResearchKit.build/Objects-normal/x86_64/ORKFitnessStepViewController.o

In file included from ResearchKit/ResearchKit/ActiveTasks/ORKFitnessStepViewController.m:32:
In file included from ResearchKit/ResearchKit/ActiveTasks/ORKFitnessStepViewController.h:32:
In file included from ResearchKit/ResearchKit/ResearchKit_Private.h:32:
In file included from ResearchKit/ResearchKit/ResearchKit.h:34:
In file included from ResearchKit/ResearchKit/Common/ORKTask.h:35:
In file included from ResearchKit/ResearchKit/Common/ORKResult.h:33:
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:167:92: error: expected '>'
+ (ORKTextScaleAnswerFormat *)textScaleAnswerFormatWithTextChoices:(NSArray <ORKTextChoice *> *)textChoices
                                                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:167:93: error: expected ')'
+ (ORKTextScaleAnswerFormat *)textScaleAnswerFormatWithTextChoices:(NSArray <ORKTextChoice *> *)textChoices
                                                                                            ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:167:68: note: to match this '('
+ (ORKTextScaleAnswerFormat *)textScaleAnswerFormatWithTextChoices:(NSArray <ORKTextChoice *> *)textChoices
                                                                   ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:173:95: error: expected '>'
+ (ORKValuePickerAnswerFormat *)valuePickerAnswerFormatWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                                                              ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:173:96: error: expected ')'
+ (ORKValuePickerAnswerFormat *)valuePickerAnswerFormatWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                                                               ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:173:72: note: to match this '('
+ (ORKValuePickerAnswerFormat *)valuePickerAnswerFormatWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                                       ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:175:92: error: expected '>'
+ (ORKImageChoiceAnswerFormat *)choiceAnswerFormatWithImageChoices:(NSArray<ORKImageChoice *> *)imageChoices;
                                                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:175:93: error: expected ')'
+ (ORKImageChoiceAnswerFormat *)choiceAnswerFormatWithImageChoices:(NSArray<ORKImageChoice *> *)imageChoices;
                                                                                            ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:175:68: note: to match this '('
+ (ORKImageChoiceAnswerFormat *)choiceAnswerFormatWithImageChoices:(NSArray<ORKImageChoice *> *)imageChoices;
                                                                   ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:178:83: error: expected '>'
                                               textChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                                                  ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:178:84: error: expected ')'
                                               textChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                                                   ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:178:60: note: to match this '('
                                               textChoices:(NSArray<ORKTextChoice *> *)textChoices;
                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:505:60: error: expected '>'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:505:61: error: expected ')'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                            ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:505:37: note: to match this '('
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                    ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:520:60: error: expected '>'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:520:61: error: expected ')'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                                            ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:520:37: note: to match this '('
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices
                                    ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:526:50: error: expected '>'
@property (copy, readonly) NSArray<ORKTextChoice *> *textChoices;
                                                 ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:526:51: error: expected member name or ';' after declaration specifiers
@property (copy, readonly) NSArray<ORKTextChoice *> *textChoices;
                           ~~~~~~~                ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:526:1: error: property requires fields to be named
@property (copy, readonly) NSArray<ORKTextChoice *> *textChoices;
^                          ~~~~~~~~~~~~~~~~~~~~~~~
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:526:51: error: expected ';' at end of declaration list
@property (copy, readonly) NSArray<ORKTextChoice *> *textChoices;
                                                  ^
                                                  ;
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:526:51: error: expected identifier or '('
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:569:60: error: expected '>'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices NS_DESIGNATED_INITIALIZER;
                                                           ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:569:61: error: expected ')'
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices NS_DESIGNATED_INITIALIZER;
                                                            ^
ResearchKit/ResearchKit/Common/ORKAnswerFormat.h:569:37: note: to match this '('
- (instancetype)initWithTextChoices:(NSArray<ORKTextChoice *> *)textChoices NS_DESIGNATED_INITIALIZER;
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by rsanchezsaez** [comment]
Version 1.2 only supports Xcode 7 and higher. I suggest you update Xcode.

If you absolutely need Xcode 6.x support, you'll need to checkout version
1.1.2 (there's a commit tag for it).

**Comment by sayan1886** [comment]
Ok
