### ISSUE TITLE
Animations for Consent Sections not playing after leaving visual consent step

### ISSUE THREAD

**Issue by jamiedaniel** [ResearchKit/ResearchKit#455]
To replicate:

1. Run ORKTest
2. Select Consent
3. Navigate to consent review step
4. Navigate backward 2-4 times
5. Navigate forward and notice that the animation in not visible but played the correct amount of time.

**Comment by YuanZhu-apple** [comment]
@umerkhan-apple is investigating.

**Comment by YuanZhu-apple** [comment]
Fixed by #459
