### ISSUE TITLE
Create changelog file?

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#458]
Should we create and maintain a `changelog.txt` file on the repo with the major changes in each version? 

It’d be nice for people to easily keep updated on what's new. It may be also good to link it from [researchkit.org](www. researchkit.org). For example, many of the *RK framework* users may not aware that there’s now a *Charting* module included with the *1.2* release.

It could also be good to write a (quick and short) blog post each time a new RK version is released (and/or send an email to the mailing list).

**Comment by YuanZhu-apple** [comment]
I like the idea to have a `changelog.txt`. 
Do you mean to add link to the `changelog` from researchkit.org? 

I am not sure about a blog, but I can send an email to dev-list.

**Comment by rsanchezsaez** [comment]
A `RELEASE-NOTES.md` file has been added.
