### ISSUE TITLE
Making task citable

### ISSUE THREAD

**Issue by julientherier** [ResearchKit/ResearchKit#460]
Active tasks and surveys are used in clinical studies, and probably some of these studies will be published.

So it would be very useful to make those [tasks/surveys citable](https://guides.github.com/activities/citable-code/), perhaps by linking them to a DOI?

**Comment by YuanZhu-apple** [comment]
I will look into it.

**Comment by akshay-yadav-apple** [comment]
@julientherier With the last ResearchKit release (1.5), ResearchKit is citable using the DOI. 
currently: https://doi.org/10.5281/zenodo.826964

Is it okay to close the issue?

**Comment by julientherier** [comment]
@akshay-yadav-apple that's a good news, thanks. I'll close this one indeed.
I think that would have been even better to use data.mendeley.com as they also provide versioning and DOI for an individual file. So if one day you could move from Zenodo to Mendeley Data that will be a great improvement.
