### ISSUE TITLE
htmlReviewContent and makePDFWithCompletionHandler

### ISSUE THREAD

**Issue by sharpred** [ResearchKit/ResearchKit#461]
If my consent document uses htmlReviewContent, when I use makePDFWithCompletionHandler to write the PDF, only the first page (with the html) is written to the pdf.  The consent page with signatures does not get written. I am using iOS 8.3 and Swift. if I comment out the htmlReviewContent line and use the summary and content from my ORKVisualConsentStep all is ok.

**Comment by YuanZhu-apple** [comment]
When `htmlReviewContent ` property is set, the review content is reproduced exactly as provided in the property in the consent review step, and the `sections` and `signatures` properties
 are ignored.

**Comment by sharpred** [comment]
OK thanks for clarifying

**Comment by iaarpit** [comment]
What if I want a signature with htmlReviewContent property set? @YuanZhu-apple Is there any easy way to do it?
