### ISSUE TITLE
Duplicated results in two-finger tapping task

### ISSUE THREAD

**Issue by julientherier** [ResearchKit/ResearchKit#465]
On an iPhone 5, iOS9, master branch, I often get the taps duplicated in the results.

![img_2414](https://cloud.githubusercontent.com/assets/1104275/9986790/13eef886-6041-11e5-8760-27f622552eb9.PNG)

**Comment by YuanZhu-apple** [comment]
Same result is due to the limited precision of result printing. 

![img_0002](https://cloud.githubusercontent.com/assets/11466704/10000887/b6cbe480-6053-11e5-8252-4170d947ff01.PNG)

**Comment by julientherier** [comment]
I did several tests and I've got the feeling float precision is not the only issue.
In fact, the problem is fixed using `touch.timestamp`rather than `CACurrentMediaTime()`.
I'll do a PR for that fix.
