### ISSUE TITLE
Chart dates overlap on x-axis

### ISSUE THREAD

**Issue by brenbob** [ResearchKit/ResearchKit#469]
Assuming AppCore dashboard charts are being ported into ResearchKit, my tester has reported this bug. The first two dates along the bottom of every chart are squished together in both full-size and normal view modes.

![image](https://cloud.githubusercontent.com/assets/1683986/10009188/e4a4d49a-608d-11e5-9653-15509d7f0bdc.png)

**Comment by rsanchezsaez** [comment]
Thanks for the report.

Is the App in the screenshot built with *AppCore* charts? If that's the case, please report this issue on the *AppCore* repository.

The label layout code in *ResearchKit* charts module has changed, it'd be good if you could try to reproduce this with RK charts and report back the results.

**Comment by brenbob** [comment]
It's built with AppCore charts. I'm not quite ready to make the Xcode 7 leap, but as soon as I do, will update this issue if it repro's with RK charts.
