### ISSUE TITLE
Consider returning ORKTaskResult.results and ORKStepresult.results as dictionaries rather than arrays

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#473]
.results currently returns an array of children ORKResults. It may be prudent to consider returning these results as a dictionary, because it would allow more robust code where the developer wishes to have the answer for a particular question (eg. to use it elsewhere within the app) rather than having all of the results in one go.

Example: The first step of my survey is a form, with a number of patient identifiers (Hospital No, NHS No, First name, Surname, Date of birth, gender, ethnicity, postcode).

I needed to extract first name and surname in order to provide the patient's name later.

To do this my code had to refer to stepResults[2] and stepResults[3]: clearly you need to know the index within the array of the results.

However, we set identifiers for each ORKFormItem which generated the result.

It would therefore be more robust and intuitive to lookup stepResults.valueForKey("firstName") and stepResults.valueForKey("lastName").

Aware this may be a significant API change for current applications.

**Comment by YuanZhu-apple** [comment]
An convience lookup method has been provided in `ORKCollectionResult` which is the super class of `ORKStepResult` and `ORKTaskResult`.
```
/**
 Looks up the child result containing an identifier that matches the specified identifier.
 
 @param identifier The identifier of the step for which to search.
 
 @return The matching result, or `nil` if none was found.
 */
- (nullable ORKResult *)resultForIdentifier:(NSString *)identifier;
```

**Comment by md0u80c9** [comment]
Ah thanks :-).
