### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#479]
Been looking at this today but it is a complex issue.

I have implemented printing support for my app, but it would be nice to see it built into ResearchKit.

There would be a use for both printing out of results (to either provide patients or to add to non-electronic records), and to print blank questions (the use case springing immediately to mind is as part of an investigating site's research file which is mandatory for all research, but other cases may occur where a patient or professional may want a paper version of a survey or form).

Consent has some PDF creation built in so some work has been done.

The first issue is that ORKResults do not disclose any of their localised text in the result contents. Classes operating on ORKResults currently need to know the corresponding ORKQuestionStep if they are to display the results to the user. I think to support result management either the ORKResult may need to return its corresponding QuestionStep object or extract and provide relevant data from that step. The former may be better as you may want to render an option list either by just showing the selected choice(s) or in other cases showing what all the available options were.

ORKResult subclasses could add A createHTMLSummary function. Subclasses which do not support printing return a blank string or a 'not available'. Otherwise they would put the step title in H1, and then summarise the question result within a <p>block.

The print function may need to support the user addition of CSS for formatting.

**Comment by YuanZhu-apple** [comment]
Thanks @md0u80c9, this feature would be very helpful!

`createHTMLSummary` could reside on ORKTaskResult and taking an ORKTask instance as a parameter.

**Comment by oliverschaefer** [comment]
@YuanZhu-apple This issue might be related to issues #89, #90 and especially #91. In fact, there might be even more cases, where a textual representation of an `ORKResult` object can be needed. Besides rendering HTML  there should also be a `createTextSummary` method that simply returns an `NSString`. or an `NSAttributedString`. Also we should consider adding some kind of delegate callback, to allow for formatting modifications. @md0u80c9 Can you share some of your work, just to let us know how far you've come?

**Comment by md0u80c9** [comment]
Hi Oliver: At the moment my App is simply taking the ORKOrderedTask and the ORKTaskResult objects, and then traversing the two of them simultaneously to produce the results into the <body> tag of HTML. I then produce some CSS to sort the styling out. It is far from ideal - and currently has a particularly ugly 'pyramid of doom' for the cases until the cases have been built onto the ORKResult objects.

I agree you need some way to access the ORKTask object from the ORKResult object in order to produce the results.

The ORKTask object probably needs some properties to configure the output styling (plaintext being one styling option).

I agree with you that it does relate to those issues.

**Comment by oliverschaefer** [comment]
@md0u80c9 Andrew, you are right, we need a flexible way to configure the output styling. But `ORKTask` might be the wrong place for all of this. Borrowing some of AirPrint's concepts, we could also use an `ORKResultFormatter` that takes in both task and result objects and outputs them in any desired format (using specific subclasses). All styling properties could be managed by the formatters and won't bother `ORKTask`. @YuanZhu-apple @umerkhan-apple  What do you think?

**Comment by md0u80c9** [comment]
YuanZhu-Apple: The concern I have about passing an ORKTask instance as a parameter is that you would need to know that the ORKResult instance was related to the ORKTask instance.

If the ORKResult instance instead also returned its corresponding Task item (so a step, a form, that particular question, etc - to the best granularity that is achievable); then the results functions could refer to that data without being concerned as to whether they had been passed a valid item.

**Comment by md0u80c9** [comment]
oliverschaefer: I like that idea - it makes a lot of sense.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Yes, agree to let `ORKResultFormatter` to handle the doc generation.

**Comment by YuanZhu-apple** [comment]
@md0u80c9 I see you point about check a result's corresponding task item. 

A cleaner way could be create an `ORKResultIterator` take both the ORKTaskResult object and ORKTask object, which is able to enumerate through all the question results with their corresponding  task item.

**Comment by md0u80c9** [comment]
OK, if you can all ignore the really nasty pyramid of doom appearance on this code (I was going for 'get it working' rather than 'make it nice'.) This is a quick and dirty print routine I currently have.

You can see the loop requires ORKTaskResult to be tied to ORKOrderedTask (and there are probably a few assumptions in this code which for a 'proper' solution need addressing).

It would be cleaner if ORKResults have knowledge of the ORKSteps that they came from to reduce that interdependence where possible. If the results could be retrieved from the ORKResult objects, then the PrintFormatter (and I guess this is a very simplistic form of what ORKResultFormatter would look like) doesn't need knowledge of the different result types.

Thoughts?

```
public func HTMLFromStrokeNurseAdmission(task: ORKOrderedTask, taskResult: ORKTaskResult) -> String {
    var finishedHTML = "<html>" +
        "<head>" +
        "<style>" +
          "p + p {" +
            "margin-top: .3em;" +
            "mergin-bottom: 0em;" +
          "}" +
          "</style>" +
        "</head>" +
        "<body>"
    
    for step in task.steps {
        if let title = step.title {
            finishedHTML += "<h1>" + title + "</h1>"
        }

        if step is ORKFormStep {
            let formStep = step as! ORKFormStep
            if let formItems = formStep.formItems {
                if let stepResults = taskResult.stepResultForStepIdentifier(step.identifier)?.results {
                    if formItems.count == stepResults.count {
                        for item in 0...(formItems.count-1) {
                            if stepResults[item] is ORKTextQuestionResult {
                                let textResult = stepResults[item] as! ORKTextQuestionResult
                                if let answer = textResult.textAnswer {
                                    if let questionStem = formItems[item].text {
                                        finishedHTML += "<p>" + questionStem + ": " + answer + "</p>"
                                    }
                                }
                                
                            }
                            
                            if stepResults[item] is ORKNumericQuestionResult {
                                let numberResult = stepResults[item] as! ORKNumericQuestionResult
                                if let answer = numberResult.numericAnswer?.stringValue {
                                    if let questionStem = formItems[item].text {
                                        finishedHTML += "<p>" + questionStem + ": " + answer
                                        if let units = numberResult.unit {
                                            finishedHTML += " " + units
                                        }
                                        finishedHTML += "</p>"
                                    }
                                }
                            }
                            
                            if stepResults[item] is ORKDateQuestionResult {
                                let dateResult = stepResults[item] as! ORKDateQuestionResult
                                if let answer = dateResult.dateAnswer {
                                    let answerFormat = formItems[item].answerFormat as! ORKDateAnswerFormat
                                    let dateFormatter = NSDateFormatter()
                                    
                                    if answerFormat.style == ORKDateAnswerStyle.Date {
                                        dateFormatter.dateFormat = "dd/mm/yyyy"
                                    }
                                    else {
                                        dateFormatter.dateFormat = "dd/mm/yyyy hh:mm"
                                    }

                                    
                                    if let questionStem = formItems[item].text {
                                        finishedHTML += "<p>" + questionStem + ": " + dateFormatter.stringFromDate(answer) + "</p>"
                                    }
                                }
                            }

                            if stepResults[item] is ORKChoiceQuestionResult {
                                let choiceResult = stepResults[item] as! ORKChoiceQuestionResult
                                if choiceResult.questionType == ORKQuestionType.SingleChoice {
                                    if let choiceAnswers = choiceResult.choiceAnswers {
                                        if choiceAnswers.count == 1 {
                                            if formItems[item].answerFormat is ORKTextChoiceAnswerFormat {
                                                let answerFormat = formItems[item].answerFormat as! ORKTextChoiceAnswerFormat
                                                let answer = answerFormat.textChoices[choiceAnswers[0].integerValue].text
                                                if let questionStem = formItems[item].text {
                                                    finishedHTML += "<p>" + questionStem + ": " + answer + "</p>"
                                                }
                                            }
                                            if formItems[item].answerFormat is ORKValuePickerAnswerFormat {
                                                let answerFormat = formItems[item].answerFormat as! ORKValuePickerAnswerFormat
                                                let answer = answerFormat.textChoices[choiceAnswers[0].integerValue].text
                                                if let questionStem = formItems[item].text {
                                                    finishedHTML += "<p>" + questionStem + ": " + answer + "</p>"
                                                }

                                            }
                                        }
                                    }
                                }
                            }
                            
                        }
                    }
                }
            }
            
        }
    }
    
    finishedHTML += "</body></html>"
    return finishedHTML
}
```

**Comment by oliverschaefer** [comment]
@md0u80c9 Hey Andrew, I've added basic result printing support via a new `stringForAnswer:` method of `ORKAnswerFormat`, as suggested by @YuanZhu-apple. See #463 for more details. From here, we could:

- Implement an `ORKResultIterator` that goes through all task results and collects the printable data (e. g. title, text and answers). The iterator could return a string dictionary for every iteration that stores all printable information
- Implement an `ORKResultFormatter` that takes a string dictionary and formats the contained information. When it comes to HTML output, we should definitely consider using https://github.com/groue/GRMustache as a template engine

@YuanZhu-apple @umerkhan-apple @rsanchezsaez Please let me know what you think about this.

**Comment by md0u80c9** [comment]
@oliverschaefer : Brilliant. I've been busy trying to sort things out on my actual app at the minute; I'm hoping that gives me a few better ideas on how to achieve this generically.

**Comment by oliverschaefer** [comment]
@md0u80c9 Hey Andrew, any news?

**Comment by md0u80c9** [comment]
Hi oliver: Unfortunately no printing progress in terms of a generic solution. I have written printing stuff for the app I'm writing but have made quite extensive use of CSS + tables to get my formatting which wouldn't work in a more generalised solution.

In terms of output I managed to improve my abstractions with some protocol extensions (in Swift). Bear in mind to do this all your ORKFormItems need to be uniquely identifiable:

`protocol ReturnsResultAsString {
    var resultAsString : String? { get }
}

extension ORKBooleanQuestionResult : ReturnsResultAsString {
    var resultAsString: String? {
        if let hasAnswer = answer as? Bool {
            if hasAnswer {
                return "Y"
            } else {
                return "N"
            }
        }
        return nil
    }
}

extension ORKTextQuestionResult : ReturnsResultAsString {
    var resultAsString: String? {
        return textAnswer
    }
}

extension ORKNumericQuestionResult : ReturnsResultAsString {
    var resultAsString: String? {
        return numericAnswer?.stringValue
    }
}

extension ORKChoiceQuestionResult : ReturnsResultAsString {
    var resultAsString: String? {
        if let stringAnswer = choiceAnswers?[0] as? String {
            return stringAnswer
        }
        if let numberAnswer = choiceAnswers?[0] as? NSNumber {
            return numberAnswer.stringValue
        }
        return nil
    }    
}`

This means you can just use:

`myTaskResult.resultsInDictionary()`

To enumerate a dictionary of answers in string format ready for printing. Minor problem here is dates because ORKDateQuestionResult does not pass what type of date result has been passed. If possible, I think it would be sensible to pass the date format since you need to know if you are dealing with a date, a time, or both.

**Comment by YuanZhu-apple** [comment]
@md0u80c9 @oliverschaefer Anyone of you want to start working on this one? 
Since I finally merged #463 ...

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Yep, me.

**Comment by oliverschaefer** [comment]
@YuanZhu-apple What do you think about this general design:
- Collect all printable information (title, answers etc.) and store it in a dictionary
- Format the information in that dictionary to actually "print" the results

We could introduce an `ORKPrintable` protocol, with a `printableInfoWithResult:` method that returns the dictionary. Every entity that conforms to that protocol (task, step) provides a set of keys to access the information contained in the dictionary.

We could introduce an `ORKPrintFormatter` that iterates through all tasks/steps and formats the information it finds. It should also be used to modify the printed output (e.g. short/medium/long output styling). One possible implementation would be an `ORKPrintHTMLFormatter` that uses an HTML template engine for printing (I'd suggest using GRMustache for that). This would easily allow different institutions to use different layouts. Using HTML would also work seamlessly with the existing PDF creation functionality in RK.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Thanks for thinking about this feature.
1. Prefer to use `ORKStep`/ `ORKResult` pairs in an array as input
2. Let `ORKPrintFormatter` deal directly with native objects, then we don't need `ORKPrintable`(I guess?)
3. Try not to create dependency with other 3rd party framework.

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Hey Yuan, I've given some thought to this issue. Here is the class hierarchy that I came up with so far
![researchkitprintuml](https://cloud.githubusercontent.com/assets/13077832/12701344/37c28bb4-c807-11e5-87fb-3ce06d12214e.png)
What do you think?

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Thanks! 

This make sense to me.
I would be nice to optionally give developer a chance to override default step printing behavior in the delegate.

Support multiple printing style can complicated. Do you have some idea in mind?

**Comment by oliverschaefer** [comment]
@YuanZhu-apple do you mean the ORKPrintFormatterStyle enum? Let's look at choice questions for example. Short style: print only the selected choice, long style: print all choices and highlight selected choice. I'm not sure yet if we really need medium style.

**Comment by YuanZhu-apple** [comment]
Maybe we can make `ORKPrintFormatterStyle` more descriptive, like
 - Include original question
 - Include all choices
 - Include timestamp for each step

And you might also want to consider what if the output html contains images.

**Comment by oliverschaefer** [comment]
You are right, should we use an NS_Options bit mask for the print formatter style instead?

Can you help me find suitable options that we should include?

Von meinem iPhone gesendet

**Comment by YuanZhu-apple** [comment]
`NS_Options` Yes.
Feel free to make up a list to fit your use case:)

**Comment by oliverschaefer** [comment]
I think it would be the easiest if we start with a mockup of the styled html output. Do you prefer a special tool for that? Or is there a dedicated design team at Apple that could help? (Guess Mr. Ive is too busy... :-) )

**Comment by YuanZhu-apple** [comment]
I guess we can start with plain html (something similar in consent PDF generation). But give developer the opportunity to attach their own CSS style sheet.

**Comment by md0u80c9** [comment]
Hi YuanZhu and oliverschaefer,

Really sorry I haven't contributed to this discussion for a couple of weeks - paid work getting in the way!

You might want to look at what I've done with my app, CaseNotes, where I've implemented printing support. Bear in mind some of the results have to be heavily customised, and the code itself has been built around protocol-orientated Swift rather than Objective C.

I'm happy for things to be used, but don't want to drop the code into the public domain at this stage. If you want to drop me an email at andrew.hill@doctors.org.uk, I'll set up a DropBox directory you can look at the code from. Ideas welcome - the solution I've implemented could do with some refinement, but probably isn't a bad starting point!

**Comment by oliverschaefer** [comment]
@md0u80c9 Hi Andrew, thanks for the update. Nice to hear that you made some progress with your own work. I've been busy treating patients and couldn't add much to the existing discussion, either. At the moment I'm thinking about a smart way to generate plain html output. The easiest (I think) would be some sort of a template engine. Yet, @YuanZhu-apple reminded me, that we shouldn't create dependencies with any 3rd party frameworks, so that engine (if we really take this challenge) would have to be built right into RK...Ideas welcome :-)

**Comment by oliverschaefer** [comment]
@md0u80c9 @YuanZhu-apple @umerkhan-apple Hi guys, I finally found some time to implement printing support. Since this is quite a big one, it would be nice if you could take a look at the basic code design before I proceed. Simply check out my printing branch, run ORKTest and hit Learn more on a step of your choice.

**Comment by md0u80c9** [comment]
@oliverschaefer : I've downloaded your PR now. Just looking on ORKStep: have you added a new task to test printing? I couldn't see from the task list where the printing support had been added. I'm just going to look over the code now :-).

I have sent you a link to my DropBox containing CaseNotes which is my RK app for managing stroke patient admissions. If @YuanZhu-apple or @umerkhan-apple (or any of the other RK developers) want access please let me know an email address and I'll send you a link for access.

The code structure for printing in there may or may not be helpful: so in it I render custom HTML for each printable survey. As you can see the output is customised somewhat - but that may give you some idea about where you might have 'standard' output for a particular component of a survey versus 'custom' output (so you can mix and match pre-designed print layouts for some steps versus steps that need fine-tuning.)

One issue you may find is that I used the protocol-orientated Swift model for building the various survey components, so printable surveys (each section of the patient's record is a survey) have an 'IsPrintable' protocol, and we then just print all those 'printable' components - something which is a bit trickier to do in Obj C. It still has quite a few optimisations I could make there (mainly the CSS formatting is awful and needs work; and I could optimise the screen rendering and print rendering together in some of the surveys), but might help give you some thoughts on structure.

**Comment by oliverschaefer** [comment]
@md0u80c9 Just run one of the existing tasks and hit the Learn more button to see the HTML output (without css)

**Comment by md0u80c9** [comment]
Ah - thanks for that, it's rendering on-screen. I think I was expecting it to open an AirPrint dialogue or suchlike!

**Comment by oliverschaefer** [comment]
@md0u80c9 Yeah, it's just in place to check the rendering quickly. Will change that in an upcoming PR update

**Comment by md0u80c9** [comment]
oliver: Had a look. You might want to look at the work in CareKit - I noticed (having had a look this morning), that there is an OCKDocument and OCKHTMLPDFWriter class which have very similar functionality to some of the functions you are using.

Given the close relationship between the two libraries, is there a way for these to be 'unified' across libraries?

**Comment by umerkhan-apple** [comment]
@md0u80c9 Both frameworks very well with each other. You can import CareKit and use the Document Exporter for printing purposes. The exporter is completely independent of other modules in CareKit.
