### ISSUE TITLE
Add an answer format for Height input 

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#484]
2-column picker view for height (if current locale uses ft and inches). 

![14e7a6a4-6639-11e5-8a77-75f051a0bdaa](https://cloud.githubusercontent.com/assets/11466704/10186447/e6241000-6705-11e5-9f1e-57612c9eb1ed.jpeg)

Health App has a 2-column picker too.

**Comment by PedroMaganinho** [comment]
@YuanZhu-apple I am a medical student and for my thesis I am trying to make a urological app using ResearchKit. How can I use this Height answer format? Can I put this in meters?  
I have another question. I am using ResearchKit and know I have all the questions I want. These issues do I get a result. Currently I'm trying to present this outcome in a dashboard as the applications that already exist. Unfortunately when I import APPCORE  for my project it's not working. Can you help me?

**Comment by YuanZhu-apple** [comment]
@PedroMaganinho This is feature request we received, not yet implemented.

For the dashboard, you can check out the chart library we just introduce in ResearchKit, which very easy to use. Open `ORKCatalog` app, you will find some demo.

**Comment by PedroMaganinho** [comment]
@YuanZhu-apple Thank you!!! I will try! If I have any doubt can I ask you?

**Comment by YuanZhu-apple** [comment]
Sure, just create a issue. Many other developers can help you too.

**Comment by EdAmorim** [comment]
@YuanZhu-apple @PedroMaganinho I'm having some trouble with the same subject. I have created an issue (#499). Can anyone help me with that?

**Comment by rsanchezsaez** [comment]
I'm almost done implementing this, I'll probably finish it tomorrow.

**Comment by rsanchezsaez** [comment]
Done.

**Comment by rsanchezsaez** [comment]
This has been merged and the issue can be closed.

**Comment by ninoguba** [comment]
@rsanchezsaez thanks for adding this! Only wondering why there isn't one for weight yet.   I can work on implementing ORKWeightAnswerFormat if no one else has started on it.  I will just use your work as a base and adapt it for weight.

**Comment by ninoguba** [comment]
I'm almost done with my implementation of ORKWeightAnswerFormat...
