### ISSUE TITLE
Authenticate Passcode and Edit Passcode crash in ORKTest

### ISSUE THREAD

**Issue by julientherier** [ResearchKit/ResearchKit#485]
I run the ORKTest project and tried to test the Authentication feature in the simulator.

`Terminating app due to uncaught exception 'NSGenericException', reason: 'Could not find Keychain item.'`

**Comment by umerkhan-apple** [comment]
@julientherier This was intended functionality, as the developer should not present those two screens if a passcode has not been created.

To make it a bit more clear, I will go ahead and update ORKTest to disable those buttons, until a passcode has been created using the Consent Module. I'll also update the error message to be more explicit as to why there was no keychain item and what steps can be taken to avoid the exception.

**Comment by julientherier** [comment]
Thanks. Indeed I missed we need to create passcode in the consent module first. The update would be very helpful.

**Comment by umerkhan-apple** [comment]
@julientherier Please review the PR. I have provided more visible ways to create, remove, edit and authenticate passcode in ORKTest. Also updated the documentation on the passcode view controller, and provided 2 helper class functions. Hope this helps! :)

**Comment by julientherier** [comment]
Thanks @umerkhan-apple that was fast!

It is very clear now how the code works, and I've been able to use ORKTest without any issue.
The new Passcode section is very useful.

I only have 2 comments:
• I've got this console message while running ORKTest on my iPhone5 `Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 563160167_Portrait_iPhone-Simple-Pad_Default`
• The titles in ORKTest are not resolved (see below), while everything works in ORKCatalog. Any idea?
![img_2443](https://cloud.githubusercontent.com/assets/1104275/10216528/123967ce-682a-11e5-8690-b7ba9a974f8d.PNG)

**Comment by umerkhan-apple** [comment]
@julientherier I am not able to reproduce the localized title error as displayed in the screenshot. Could there be some bundle issue on your end where the strings file did not update for ORKTest?

**Comment by rsanchezsaez** [comment]
The localization error seems to happen when your device uses a language other than *U.S. English*. I was seeing the same unresolved strings on *U.K. English*, but it worked correctly when I switched my phone to *U.S. English*. So probably the strings need to be filled in all the supported languages.

**Comment by julientherier** [comment]
@rsanchezsaez you're right. The same behavior here with U.K. English vs. U.S. English.

**Comment by umerkhan-apple** [comment]
@julientherier @rsanchezsaez The console message is a separate bug. It appears for the selection survey task as well. The localization issue is also a separate bug. We need to have it set up for a fallback language (U.S. English) if translations are not available. I will go ahead and create separate issues for both of them.

**Comment by umerkhan-apple** [comment]
#494 #495
