### ISSUE TITLE
Localization fallback language

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#495]
Localization does not have any fallback language set.
If translations are not available, it should automatically revert to the U.S. English.
Currently, it shows the localization key instead of the U.S. English's value for the key.

**Comment by LukeJamesFitzpatrick** [comment]
This comment on Stack Over Flow should help you out about default localization language fallback http://stackoverflow.com/questions/3263859/localizing-strings-in-ios-default-fallback-language 

Also, you can use a service like http:www.localizer.co to localize your website / app, setup is simple, post a string of code into your web app, and it's done.
