### ISSUE TITLE
Creating graphs in Objetive-C

### ISSUE THREAD

**Issue by EdCA3** [ResearchKit/ResearchKit#499]
Hi! I am a 6th grade Medicine student and I’m developing a medical app using Research Kit. Unfortunately, I’m not used to create apps, but thanks to Research Kit and after watching many tutorials, I was able to make the consent and all the questions I want patients to answer. Besides that, I have created all the sums (based on patients’ answers) needed in order to generate some scores. Now I want to show that scores (with some text explaining the results)  and also the percentage of questions answered using colorful graphs at the end of the questionnaire. I’m having difficulties doing that kind of graphs but I found  in ORKcatalog  that it’s possible. My app is in Objetive-C because I found it easier to work, but the ORKCatalog is in Swift. 
Can anybody tell me the steps to create the graphic results as it appears in ORKcatalog?
Thanks a lot for your help.

**Comment by YuanZhu-apple** [comment]
Maybe our updated API document can help you?
http://researchkit.org/docs/Classes/ORKGraphChartView.html

**Comment by rsanchezsaez** [comment]
@EdCA3: If you read more about *Objective-C* and *Swift*, and look at side-by-side snippets or examples, it's possible to figure out how to figure out what's happening on *Swift* and try to re-implement it on *Objective-C*.

If you are still struggling, I'd suggest posting a more specific question on the [ResearchKit forum](https://forums.developer.apple.com/community/researchkit) or on [StackOverflow](http://stackoverflow.com/questions/tagged/researchkit).

In any case, I agree that it would be desirable to have a better Charts introduction document, similar to *[Creating Surveys](http://researchkit.org/docs/docs/Survey/CreatingSurveys.html)*, *[Obtaining Consent](http://researchkit.org/docs/docs/InformedConsent/InformedConsent.html)* or *[Active Tasks](http://researchkit.org/docs/docs/ActiveTasks/ActiveTasks.html)*. Anyway, I suggest closing this issue and opening a new one specifically requesting improved Charts documentation.

**Comment by YuanZhu-apple** [comment]
I will close this one, once we get the charts documentation done.

**Comment by YuanZhu-apple** [comment]
http://researchkit.org/docs/docs/Charts/ChartsAndGraph.html

Chart's documentation is available now.

**Comment by JValderramaN** [comment]
Hi, I was reviewing the ResearchKit docs and http://researchkit.org/docs/docs/Charts/ChartsAndGraph.html seems to not work (404 not found).

**Comment by YuanZhu-apple** [comment]
@JValderramaN Updated link: http://researchkit.org/docs/docs/ChartsAndGraphs/ChartsAndGraphs.html
