### ISSUE TITLE
Should ORKTaskViewController restorationData take an optional NSData parameter?

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#501]
Hi,

It may be my misunderstanding of the API - apologies if that is the case. However, working from Swift, ORKTaskViewController takes a required NSData parameter for restorationData.

If you are supporting a restorable task there are two states - a 'new' form, or a 'reopened draft'. If it is new, there won't be any NSData.

Rather than using a different initialiser for ORKTaskViewController, it seems more logical to me to make the restorationData optional - if it is not supplied then we are creating a 'new' task rather than restoring an existing one.

**Comment by YuanZhu-apple** [comment]
@md0u80c9 Creating TaskVC for different purposes requires different sets of parameters, I feels separate them out can reduce the confusions for developers.

**Comment by md0u80c9** [comment]
Thanks YuanZhu-apple.

I have attached a code example below (in Swift).

self.detailItem!.valueForKey("strokeNurseDraft") contains the saved state if one exists.

If there is no savedDraft, we have to open ORKTaskViewController using a different initialiser: as you can see the two code paths look very different.

```
        let savedDraft = self.detailItem!.valueForKey("strokeNurseDraft") as? NSData
        let taskViewController : ORKTaskViewController
        if let draft = savedDraft {
            taskViewController = ORKTaskViewController(task: StrokeNurseAdmission, restorationData: draft, delegate: self)
        }
        else {
            taskViewController = ORKTaskViewController(task: StrokeNurseAdmission, taskRunUUID: nil)
            taskViewController.delegate = self
        }
        presentViewController(taskViewController, animated: true, completion: nil)
```

**Comment by YuanZhu-apple** [comment]
@md0u80c9 Yes, that is right solution! You can keep this piece code inside your project. For the developers who are not using `restorationData`, they can simply use use  `ORKTaskViewController(task:task, taskRunUUID: nil)`, which is less noise to them.

**Comment by md0u80c9** [comment]
Indeed. My point was that if NSData becomes optional, the code to open a task which supports restorationData looks like this (whether the draft data is available or not):

```
let savedDraft = self.detailItem!.valueForKey("strokeNurseDraft") as? NSData
let taskViewController : ORKTaskViewController
taskViewController = ORKTaskViewController(task: StrokeNurseAdmission, restorationData: savedDraft, delegate: self)
presentViewController(taskViewController, animated: true, completion: nil)
```

If the other initialisers are still also kept and function as above, a task which is not using restorationData would open like this:

```
let taskViewController : ORKTaskViewController
taskViewController = ORKTaskViewController(task: StrokeNurseAdmission, taskRunUUID: nil)
taskViewController.delegate = self
presentViewController(taskViewController, animated: true, completion: nil)
```

**Comment by YuanZhu-apple** [comment]
Yeah, I am convinced.
Just need to add nil case handling inside the `restorationData:` initializer. 
Open a PR?

**Comment by md0u80c9** [comment]
OK - will do.

**Comment by md0u80c9** [comment]
Completed and merged.
