### ISSUE TITLE
Progress label updating

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#504]
Currently the progress label gets updated when a user navigates from one step to another. It does not receive updates when the result of the current step view controller changes. This behavior could be useful with a dynamic task, which adjusts its total number of steps based on the given answers.

**Comment by YuanZhu-apple** [comment]
Do you think these frequent updates could be a noise for the user? 
Also I afraid this feature would encourage a user to select the answer resulting a shorter survey.

**Comment by oliverschaefer** [comment]
`ORKOrderedTask` does not support dynamic changes of it's steps array (since `steps` is a readonly property). So this feature would be dedicated to developers who implement their own task. When a task is capable of doing dynamic updates, we should communicate that to the user, shouldn't we?

Maybe we could add a property to `ORKTaskViewController` that controls whether these frequent updates should be done or not.

**Comment by umerkhan-apple** [comment]
@oliverschaefer I would recommend that we only change the first part of the progress. For example, if you are on Step 2 of 10, and you chose option A, it would take you to Step 3 of 10. But if you choose option B, it would take you to Step 9 of 10.

A similar example can be seen in an AppCore app, GlucoSuccess.

**Comment by YuanZhu-apple** [comment]
So in use case mentioned by @umerkhan-apple, the progress label only need to be changed during a step switching. And it is more like the paper based survey, each question has its own sequence number and total number is fixed.

**Comment by oliverschaefer** [comment]
@YuanZhu-apple @umerkhan-apple Ok guys, I get the point :-). Could we however, built in the possibility to do frequent updates, if the developer wishes so?

**Comment by umerkhan-apple** [comment]
@oliverschaefer If I understand this correctly, we want to provide the developers a way to update the navigation bar title (which in your case has the progress). Updating that title could be for any number of reasons, one of which you listed as when the current step view controller's result changes.

So my main concern is why a developer cannot just use a custom navigation item? If you look at `ORKTest` under `Miscellaneous`, there is `Custom Navigation Item`. This example demonstrates what you are wanting to do with the navigation title, if I understand correctly.

Would you be okay with that solution, or is there a reason we would specifically want to provide methods to tweak the progress?

**Comment by oliverschaefer** [comment]
@umerkhan-apple Jep, I know this feature in ORKTest, I've written that code :-) And that way would be completely okay for me.
