### ISSUE TITLE
ORKTaskViewController's output directory doesn't seem to be restored

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#506]
There seems to be a problem with the bookmarked `outputDirectory` data in `ORKTaskViewController`, and the output directory bookmark is not correctly decoded when restoring a task.

Steps to reproduce:

1. Set a breakpoint inside `ORKURLFromBookmarkData()`.
2. Run `ORKTest`
3. Launch the *Navigable Ordered Task* item.
4. Go to the second question, cancel the task, and save the results for later.
5. Launch the task again.
6. Step through `ORKURLFromBookmarkData()` and notice how `URLByResolvingBookmarkData:...` returns a `nil` URL. The returned error is *The file doesn't exist (code: 4)*, even though the folder seems to exist (as created by `ensureDirectoryExists:outputDirectory`).

It happens both on the simulator and on an *iPhone 6*, running *iOS 9.0.2*.

**Comment by rsanchezsaez** [comment]
This [merged PR](https://github.com/ResearchKit/ResearchKit/pull/252) has comments that are relevant to this issue.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for catching it, see my fix.

**Comment by rsanchezsaez** [comment]
Fixed by linked PR.
