### ISSUE TITLE
Choose keyboard for textfield

### ISSUE THREAD

**Issue by nicholas12345** [ResearchKit/ResearchKit#507]
Hi, is there a way to choose keyboard type on textfield? For example, I have one field where user enters his email address so it would be pretty good to change for that field keyboard type to be E-mail address.

**Comment by YuanZhu-apple** [comment]
To change keyboard type:
https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKAnswerFormat.h#L1269

For email input, the best solution is to use `ORKEmailAnswerFormat ` https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKAnswerFormat.h#L1288

**Comment by nicholas12345** [comment]
Thanks a lot! However, it appears that I only have autocapitalization and autocorrection, no keyboardType. It is probably added in some later version of Researchkit (failed to add latest Researchkit in project as I didn't convert yet to iOS 9 and Swift 2). 

Same appears for ORKEmailAnswerFormat, I don't have it. Well, I will consider this closed and once I manage to get the latest Researchkit in project, I will reopen if needed.

Many thanks once again.

**Comment by YuanZhu-apple** [comment]
If you cannot use `1.2.1`, you can try `1.1.2` which is compatible with Xcode 6.

**Comment by nicholas12345** [comment]
Ok, I imported 1.1.2 and I don't have .keyboardType or ORKEmailAnswerFormat. I searched through ORKAnswerFormat.h in imported Reearchkit 1.1.2 code and couldn't find any of those two references that I can see on the link you provided. So it appears those functionalities aren't backported for XCode 6, if I am right?

**Comment by YuanZhu-apple** [comment]
Yeah, you are right. Those features are not in RK 1.1.

**Comment by nicholas12345** [comment]
Ok then, closing this. Will reopen in case I need again once I move to the latest version. 
Many, many thanks for the help!
