### ISSUE TITLE
Continue button is disabled on scale with default values

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#511]
Should the *Continue button* be enabled when a scale question has a default value?

The behavior has always been for the button to be disabled until you interact with the scale slider, but it feels like it should be enabled if a default value is there.

**Comment by YuanZhu-apple** [comment]
Yes, you are right, *Continue button* should be enabled in this senario like the date picker(with a default date).

**Comment by umerkhan-apple** [comment]
Addressed in PR #526
