### ISSUE TITLE
Throw exception on invalid RegEx used in ORKTextAnswerFormat

### ISSUE THREAD

**Issue by codecadwallader** [ResearchKit/ResearchKit#519]
As an extension of #476 , it was suggested that it would be helpful to throw an exception if an invalid regular expression is used within ORKTextAnswerFormat's initializer.

See https://github.com/ResearchKit/ResearchKit/pull/476#discussion_r41573726 for context.

**Comment by umerkhan-apple** [comment]
Fixed as part of #538 

https://github.com/umerkhan-apple/ResearchKit/blob/85097a5e20a3c03e8ce097c93050e77d446386dc/ResearchKit/Common/ORKAnswerFormat.m#L1931-L1949
