### ISSUE TITLE
Website Docs are out of date

### ISSUE THREAD

**Issue by chrisvariety** [ResearchKit/ResearchKit#521]
I believe they haven't been updated at all for 1.2.

For example: http://researchkit.org/docs/Classes/ORKTextChoice.html

`exclusive` is not mentioned there, even though it should be since 1.2 includes `exclusive`

Compare to cocoadocs, which are up to date: http://cocoadocs.org/docsets/ResearchKit/1.2/Classes/ORKTextChoice.html

**Comment by YuanZhu-apple** [comment]
Docs from 1.2 has been updated.
