### ISSUE TITLE
[ORKTaskViewController requestPedometerAccessWithHandler:]_block_invoke Pedometer access: error=(null)

### ISSUE THREAD

**Issue by sharpred** [ResearchKit/ResearchKit#522]
I am using Xcode7, Swift2

I get the following error when running three active tasks on my device;

2015-10-09 19:19:41.257 sscapp[951:147368] [ResearchKit][Warning] __59-[ORKTaskViewController requestPedometerAccessWithHandler:]_block_invoke Pedometer access: error=(null)

This appears to relate to the use of queryPedometerDataFromDate line 385 of ORKTaskViewController.m

My app is written in Swift and my tasks are as follows;

private var shortWalkTask: ORKTask {
    let identifier : String = "shortWalkTask"
    let description : String = "Complete a short walk"
    return ORKOrderedTask.shortWalkTaskWithIdentifier(identifier, intendedUseDescription: description, numberOfStepsPerLeg: 20, restDuration: 20, options: [])
}

private var fitnessTask: ORKTask {
    let description : String = "This task will measure your fitness"
    let identifier = "fitnessTask"
    return ORKOrderedTask.fitnessCheckTaskWithIdentifier(identifier, intendedUseDescription: description, walkDuration: 20, restDuration: 20, options: [])
}

private var timedWalkTask: ORKTask {
    let description : String = "Walk 100 metres in three minutes"
    let identifier = "timedWalkTask"
    return ORKOrderedTask.timedWalkTaskWithIdentifier(identifier, intendedUseDescription: description, distanceInMeters: 100.0, timeLimit: 180.0, options: [])
}

If I make a similar call to queryPedometerDataFromDate in Swift
pedometer.queryPedometerDataFromDate(fromDate!, toDate: toDate!, withHandler: handler)

I get a valid response (See below) which would suggest my entitlements and device are set up correctly

"CMPedometerData,<startDate 2015-10-02 09:57:47 +0000, endDate 2015-01-23 00:00:00 +0000, steps 0, distance 0, floorsAscended 0, floorsDescended 0 currentPace (null) currentCadence (null)>"

Any ideas why this fails in ResearchKit? (sorry am a newbie to iOS and don't really know my way around objective-c to debug) - some suggestions elsewhere it could be related to scope of CMPedometer (class property vs local variable?)

**Comment by YuanZhu-apple** [comment]
I don't think anything is falling, since it says:
`2015-10-09 19:19:41.257 sscapp[951:147368] [ResearchKit][Warning] __59-[ORKTaskViewController requestPedometerAccessWithHandler:]_block_invoke Pedometer access: error=(null)`

This is just a normal debug message in ReseachKit, so don't worry about it. 
We can change to only print when the error is not nil.

**Comment by sharpred** [comment]
Hmm, okay. But the task fails immediately after the five second countdown finishes with a .Failed reason and this is the only item logged.

**Comment by sharpred** [comment]
I figured it out.  I had not specified an outputDirectory for my task.  Apologies for wasting your time.

**Comment by YuanZhu-apple** [comment]
Do you able to reproduce this in `ORKTest` or `ORKCatalog`?
