### ISSUE TITLE
Skip to step with specific identifier

### ISSUE THREAD

**Issue by nicholas12345** [ResearchKit/ResearchKit#525]
I browsed through documentation and ORKcatalog but couldn't find answer:
is there a way to skip from one step to some other step by specifying step identifier of the step to skip to?
For example, check if current step answer is true or false; if true. proceed. Else, skip to step with id "question5". 
Thanks

**Comment by md0u80c9** [comment]
nicholas12345: Yes. Set your task up as an ORKNavigableOrderedTask which does exactly as you describe (rather than an ORKOrderedTask).

Set up all yours steps just as you would an ORKOrderedTask.


Then at the end you can set up navigation rules based on either predicates or direct steps.

ORKTask has suitable code inside which demonstrates setting this up (do a quick Find for ORKPredicateStepNavigationRule and you can see how to set the rules up).

**Comment by md0u80c9** [comment]
Quick piece of sample code from my app in Swift: 

```
public var StrokeNurseAdmission: ORKNavigableOrderedTask {
    var steps = [ORKStep]()

//  [ set the steps up above this]
    let task = ORKNavigableOrderedTask(identifier: "StrokeNurseAdmission", steps:steps)

// Now build navigation rules
    
    
// If the patient was an inpatient at the time of stroke then skip outpatient onset time and omit the ambulance details
// If the patient was an outpatient we move from the 'were they an inpatient?' to the outpatient symptom onset time

    let inptResultSelector = ORKResultSelector(stepIdentifier: "InpatientStroke", resultIdentifier: "Inpatient")
    let predicateNotInpt = ORKResultPredicate.predicateForBooleanQuestionResultWithResultSelector(inptResultSelector, expectedAnswer: false)
    let predicateNotInptRule = ORKPredicateStepNavigationRule(resultPredicates: [predicateNotInpt], destinationStepIdentifiers: ["OutptSymptomOnsetTime"])
    
    task.setNavigationRule(predicateNotInptRule, forTriggerStepIdentifier: "InpatientStroke")
    task.setNavigationRule(ORKDirectStepNavigationRule(destinationStepIdentifier: "PresentingHistory"), forTriggerStepIdentifier: "InptSymptomOnsetTime")

    return task
```

**Comment by md0u80c9** [comment]
Nicholas12345: let us know how you got on. Are you Ok to close this issue?

**Comment by umerkhan-apple** [comment]
@nicholas12345 Did @md0u80c9 response help resolve your issue?

**Comment by nicholas12345** [comment]
Yeah, let's close it. Many thanks!

**Comment by Natelegreat1** [comment]
For some reason, in my `ORKOrderedTask`, `ORKResultSelector` is being flagged as an `unresolved identifier` even though all other RK items are fine. 
I am using a pod file and have `#import <ResearchKit/ResearchKit.h>` in the bridge file. Is another #include required?

**Comment by YuanZhu-apple** [comment]
`ORKResultSelector` is a new API introduce post 1.2 release.
For 1.2, please refer to this example:
https://github.com/ResearchKit/ResearchKit/blob/stable/Testing/ORKTest/ORKTest/MainViewController.m#L2109

On Wed, Oct 21, 2015 at 10:54 PM, Nathaniel Blumer <notifications@github.com

**Comment by Natelegreat1** [comment]
That makes sense.

I have `pod 'ResearchKit'` in my pod file 
Terminal shows the following : `Using ResearchKit (1.2.1)`

Weird eh?

**Comment by YuanZhu-apple** [comment]
That's right, latest release is 1.2.1 (with a bug fix on the top of 1.2)

**Comment by Natelegreat1** [comment]
Is there something special I need to include in the Build Settings? 
Even though terminal confirms `Using ResearchKit (1.2.1)`, I am still unable to use any of the newer API components...

**Comment by YuanZhu-apple** [comment]
Sorry, I was wrong about `ORKResultSelector`, it is actually in 1.2.

You just need to:
```
#import <ResearchKit/ResearchKit.h>
```
or in swift
```
import ResearchKit
```

**Comment by Natelegreat1** [comment]
I have `#import <ResearchKit/ResearchKit.h>` in my bridge file -- I am writing in Swift.
if I try `import ResearchKit`:
`No such module 'ResearchKit'`

Again, the weird part is that I can use some of the API but not all! :-1:

**Comment by YuanZhu-apple** [comment]
`ORKResultSelector` works fine in our ORKCatalog app(Swift demo)
You might want to check your project settings.
<img width="471" alt="screen shot 2015-10-22 at 3 30 31 pm" src="https://cloud.githubusercontent.com/assets/11466704/10680146/f50c1f9e-78d1-11e5-9023-9e306537408f.png">

**Comment by Natelegreat1** [comment]
If I am using Cocopods, is it not ok it looks like this: <img width="791" alt="screen shot 2015-10-23 at 23 42 01" src="https://cloud.githubusercontent.com/assets/2666640/10708716/adc0628a-79df-11e5-9e0a-e17b9e069736.png">

Do I still need to compile the ResearchKit manually and include it?

**Comment by Natelegreat1** [comment]
Any ideas? The fact that I can use SOME of the ResearchKit implies that the framework is included in some capacity... but I can't figure out why anything from v1.1+ won't work!

**Comment by YuanZhu-apple** [comment]
What's your pod file looks like? Are you using Objective-C or swift? 
I just played cocoapod a bit, it seems I have to use the workspace to compile the app.

Here is how my `Podfile` looks like:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RKPod' do
	pod ‘ResearchKit’, ‘1.2.1’
end

target 'RKPodTests' do

end

target 'RKPodUITests' do

end
```
