### ISSUE TITLE
Capital text on ORKFormItem

### ISSUE THREAD

**Issue by nicholas12345** [ResearchKit/ResearchKit#529]
Why is text in ORKFormItem always capital? Is there a way to override it or remove it so it shows text normally?

**Comment by YuanZhu-apple** [comment]
`always capital` is by design. Make it has a clear visual distinction with its section content.

**Comment by nicholas12345** [comment]
And I assume there is no way to override it?

**Comment by YuanZhu-apple** [comment]
For now, there is no way to override it.
