### ISSUE TITLE
Where exactly is Heart Rate Data in Fitness activity results

### ISSUE THREAD

**Issue by khanxc** [ResearchKit/ResearchKit#530]
This is basically not an issue. Where exactly will I get the heart rate data while using the Fitness activity ? Even I don't see the Heart Rate identifier in the below code    

  ``` Swift
    if let fileresult = result as? ORKFileResult {
                             print("idf -->\(fileresult.identifier)")
                                let content = try? String(contentsOfURL: fileresult.fileURL!, encoding: NSUTF8StringEncoding)
                                print("File contents\(content)")
 } 
```
And I heart rate was stored continuously to HealthKit through an app in apple watch at the same time of taking the fitness test.
![img_0004](https://cloud.githubusercontent.com/assets/5825355/10483926/a7c72612-729f-11e5-98b4-da0b84beec23.PNG)

**Comment by YuanZhu-apple** [comment]
I believe there is a few minutes delay to sync heart rate data from Apple Watch to iPhone's HealthKit. 
Did you try to use a heart rate strap? Remember to pair it with iPhone directly (settings -> bluetooth).

And if the heart rate data is in real time, then you should be able to see a heart rate label at the bottom on the walking step.

**Comment by khanxc** [comment]
@YuanZhu-apple Thanks for your response. I did not try with a heart rate strap. But through Apple Watch doesn't `HKWorkout` class provide real time data?. I tried with this below code 
```Swift
self.workoutSession = HKWorkoutSession(activityType: .Running, locationType: .Indoor)
self.workoutSession!.delegate = self;

// Start the workout session
self.healthStore.startWorkoutSession(self.workoutSession!)
```
And  `HKQuery` output seems to be near to real time in the Apple watch. So if there is even a delay by a minute RK doesn't fetch it?

**Comment by lehn0058** [comment]
If you have real time health data collected from the Apple Watch and are trying to query it from it's paired iPhone, you will likely have some trouble. The Apple Watch doesn't stream fitness data in real time to the iPhone because this would be a huge battery drain, especially for long workouts (think of runners training for a marathon where they could be exercising for over 5 hours). The Apple watch batches up its health kit data and syncs it with the iPhone at opportune times. Normally, this happens within a few minutes of completing a workout. I have noticed that if I want to view HealthKit data immediately after completing a workout on the apple watch I need to open the health app on the iPhone to manually trigger a sync.

One thing to try is to make sure you are relating your health samples to the workout you end up recording. If you just let the apple watch collect the samples, it won't know that they belong to a specific workout.

    // Create a workout sample
    let workout = HKWorkout(activityType: HKWorkoutActivityType.Running,
        startDate: startDate,
        endDate: endDate,
        duration: endDate.timeIntervalSinceDate(startDate),
        totalEnergyBurned: self.currentActiveEnergyBurned,
        totalDistance: self.currentDistance,
        metadata: nil)
    
    // Save the workout
    self.healthStore.saveObject(workout) { success, error in
        // Associate the accumulated samples with the workout
        if success {
            
            let predicate = HKQuery.predicateForSamplesWithStartDate(startDate, endDate: endDate, options: HKQueryOptions.None)
            let startDateSort = NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: true)
            
            let activeEnergyQuery = HKSampleQuery(sampleType: HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierActiveEnergyBurned)!, predicate: predicate,
                limit: 0, sortDescriptors: [startDateSort]) {
                    (sampleQuery, results, error) -> Void in
                    
                    if results?.count > 0 {
                        self.healthStore.addSamples(results!, toWorkout: workout, completion: { success, error in
                            // ...
                        })
                    }
            }
            
            let heartRateQuery = HKSampleQuery(sampleType: HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeartRate)!, predicate: predicate,
                limit: 0, sortDescriptors: [startDateSort]) {
                    (sampleQuery, results, error) -> Void in
                    
                    if results?.count > 0 {
                        self.healthStore.addSamples(results!, toWorkout: workout, completion: { success, error in
                            // ...
                        })
                    }
            }
            
            let distanceQuery = HKSampleQuery(sampleType: HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDistanceWalkingRunning)!, predicate: predicate,
                limit: 0, sortDescriptors: [startDateSort]) {
                    (sampleQuery, results, error) -> Void in
                    
                    if results?.count > 0 {
                        self.healthStore.addSamples(results!, toWorkout: workout, completion: { success, error in
                            // ...
                        })
                    }
            }
            
            self.healthStore.executeQuery(activeEnergyQuery)
            self.healthStore.executeQuery(heartRateQuery)
            self.healthStore.executeQuery(distanceQuery)
        }
    }
