### ISSUE TITLE
ORKPredicateNavigationStepRule suggestion: PreStep and PostStep options

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#535]
I have a complex form (you may have guessed from my earlier issue reports / PRs) which includes a test for significant past medical history as part of a screening process.

Where an issue is present, we want to ask more details before proceeding.

I've set up a minimised example of the form steps as follows:

* Step 1 - Diseases
- Does the patient have disease A?
- Does the patient have disease B?
- Does the patient have disease C?

* Step 2 - Disease A (only show this step is answered yes to Disease A)
- Questions pertinent to Disease A

* Step 3 - Disease B (only show this step is answered yes to Disease B)
- Questions pertinent to Disease B

* Step 4 - Disease C (only show this step is answered yes to Disease C)
- Questions pertinent to Disease C

* Step 5 - More questions

So the predicates need to 'fall through' the list. At the moment ORKPredicateStepNavigationRules act upon completion of a step: I cannot see a way where this can easily be done using step navigation rules.

I wonder if they could/should be expanded into 'Pre' and 'Post' Step rules. A 'Pre' step would operate before the step is displayed. A 'Post' step would operate as the current ORKPredicateStepNavigationRule does on completion of that step.

For this you would therefore set up 'pre' rules for each of steps 2-4 that says 'If you answered Step 1 as 'No' to the relevant question, skip me and move to the next step.

**Comment by umerkhan-apple** [comment]
@md0u80c9 If I understand what you're asking for correctly, then I believe the current ORKPredicateStepNavigationRules should be sufficient in achieving your use case.

1. Create an ORKNavigableOrderedTask with all the steps in it (Step1 - Step 5).
2. Build predicate navigation rules as following:
```
    /**
     Build navigation rules going from Step1 to Step 2,3,4 (depending on answer choice).
     */
    ORKResultSelector *resultSelector = [ORKResultSelector
                                         selectorWithResultIdentifier:Step1Identifier];
    
    NSPredicate *predicateQuestionChoiceA = [ORKResultPredicate
                                             predicateForChoiceQuestionResultWithResultSelector:resultSelector
                                             expectedAnswerValue:Step1ChoiceA];
    
    NSPredicate *predicateQuestionChoiceB = [ORKResultPredicate
                                             predicateForChoiceQuestionResultWithResultSelector:resultSelector
                                             expectedAnswerValue:Step1ChoiceB];
    
    NSPredicate *predicateQuestionChoiceC = [ORKResultPredicate
                                             predicateForChoiceQuestionResultWithResultSelector:resultSelector
                                             expectedAnswerValue:Step1ChoiceC];
    
    ORKPredicateStepNavigationRule *predicateRule = [[ORKPredicateStepNavigationRule alloc]
                                                     initWithResultPredicates:@[predicateQuestionChoiceA,
                                                                                predicateQuestionChoiceB,
                                                                                predicateQuestionChoiceC]
                                                     destinationStepIdentifiers:@[Step2,
                                                                                  Step3,
                                                                                  Step4]];

    [task setNavigationRule:predicateRule forTriggerStepIdentifier:Step1Identifier];
```
- Create a direct rule to lead to the fall through step (Step 5).
```
    /**
     Direct rule to go to Step 5 from Step 2,3,4.
     */
    ORKDirectStepNavigationRule *directRule = nil;
    directRule = [[ORKDirectStepNavigationRule alloc]
                  initWithDestinationStepIdentifier:Step5Identifier];
    [task setNavigationRule:directRule forTriggerStepIdentifier:Step2Identifier];
    [task setNavigationRule:directRule forTriggerStepIdentifier:Step3Identifier];
    [task setNavigationRule:directRule forTriggerStepIdentifier:Step4Identifier];
```

**Comment by md0u80c9** [comment]
Hi Umer,


I don't think it does. In my example, Step 1 has a set of Boolean options, rather than a single choice option.

So, you may need to go to steps 1, 3, 4, 5. Or steps 1, 2, 4, 5. Or steps 1, 2, 5. Etc.

As I understand it your example would take you to Step 1, then EITHER 2, 3 or 4, then 5.

Am I correct?

**Comment by umerkhan-apple** [comment]
@md0u80c9 

So, I just used a single choice result predicate as an example. There is a result predicate for boolean options also.

The example coded above will accomplish the second set of patterns that you mentioned:
`Step 1, then either 2, 3, or 4, then 5.`

Now if you would like to provide different paths, such as
1,3,4,5 or 1,2,4,5
you can define them the same way use result predicates.

__Following the pattern (1,3,4,5):__
If user is on Step 1 and chooses C, they go to Step 3 (demonstrated in example code).
Then user us on Step 3 and chooses A, they go to Step 4 (can be created using example code).
and so on...

Using predicate rules, you should be able to define your navigation paths.

**Comment by md0u80c9** [comment]
I'll have another look over the sample code this evening - thanks :-).

**Comment by md0u80c9** [comment]
Ah - think I get you:

In Step 1, use the predicate you suggested to point to Steps 2, 3, 4 if A,B or C is provided, or 5 if none of them. The predicate will go to the first step in the list.

In Step 2, use the predicate to point to steps 3 or 4 if B or C is provided, or 5 if none of them.

In Step 3, use the predicate to point to step 4 if C is provided, or 5 if none of them.

Obviously not perfect as it scales to the power n, but it would certainly work!

**Comment by umerkhan-apple** [comment]
Agreed. It does not scale very well.

I was brainstorming about your approach with preStep and postStop. if we were to continue with that approach, I am not able to see the benefit from it. Wouldn't we still need to create all the same rules, but now they will be defined on the step itself vs the task? Did I understand the concept behind preStep and postStop correctly?

**Comment by md0u80c9** [comment]
If we had a preStep and a postStep, wouldn't you implement as follows:

Step 1:
3 disease Boolean answers, let's give them the IDs DiseaseA, DiseaseB, DiseaseC.

Step 2 preStep: If DiseaseA=FALSE, Direct step to Step 3.

Step 3 preStep: If DiseaseB=FALSE, Direct step to Step 4.

Step 4 preStep: If DiseaseC=FALSE, Direct step to Step 5.

So we would fall through each question prior to displaying it, if you see what I mean.

**Comment by rsanchezsaez** [comment]
This sounds like a good idea, as it would add some nice flexibility of `ORKNavigableOrderedTask`.

One relatively simple solution I can think of could be keeping the current `stepNavigationRule` machinery in place (as they effectively are *post step* rules), and then adding the following *APIs*:

    - (void)setSkipNavigationRule:(ORKStepNavigationRule *)stepNavigationRule forStepIdentifier:(NSString *)stepIdentifier;
    - (ORKStepNavigationRule *)skipNavigationRuleForStepIdentifier:(NSString *)stepIdentifier;
    - (void)removeSkipNavigationRuleForStepIdentifier:(NSString *)stepIdentifier;

So you could skip certain steps based on predicates.

This would be backwards compatible, as the `ORKNavigableOrderedTask` would behave normally if you don't use the skip steps at all.

@YuanZhu-apple, @umerkhan-apple: Do you think this is sensible? Do you want me to give it a stab?

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for the suggestion.
In existing API: `- (void)setNavigationRule:(ORKStepNavigationRule *)stepNavigationRule           forTriggerStepIdentifier:(NSString *)triggerStepIdentifier;`, 

`stepNavigationRule` defines the next step of `triggerStepIdentifier`.

Can you clarify how the new API works? Is `stepIdentifier` the step to be skipped or the step triggering the rule?

**Comment by rsanchezsaez** [comment]
Ah, you are right, my explanation was not very clear. `stepIdentifier` is both the *step triggering the rule* and the *step to be potentially skipped*, as they are the same. For this, we need a new type of skip navigation rule, which doesn't have any *destination step*:


    @interface ORKNavigableOrderedTask : ORKOrderedTask

    ...

    - (void)setSkipNavigationRule:(ORKSkipStepNavigationRule *)stepNavigationRule forStepIdentifier:(NSString *)stepIdentifier;
    - (ORKSkipStepNavigationRule *)skipNavigationRuleForStepIdentifier:(NSString *)stepIdentifier;
    - (void)removeSkipNavigationRuleForStepIdentifier:(NSString *)stepIdentifier;

    ...

    @end


    @interface ORKSkipStepNavigationRule : NSObject <NSCopying, NSSecureCoding>

    /**
     Returns whether the targeted step should skip.
     
     Subclasses must implement this method to calculate if the targeted step should skip based on the passed task result.
 
     @param taskResult      The up-to-date task result, used for calculating the destination step.
 
     @return YES if the step should skip.
     */
    - (NSString *)stepShouldSkipWithTaskResult:(ORKTaskResult *)taskResult;

    @end


    @interface ORKPredicateSkipStepNavigationRule : ORKStepNavigationRule

    /**
     Returns an initialized predicate skip step navigation rule using the specified result predicate.
 
     @param resultPredicate            An result predicates. If the result predicate matches, the step will skip.
 
     @return An initialized skip predicate step navigation rule.
     */
    - (instancetype)initWithResultPredicate:(NSPredicate *)resultPredicate NS_DESIGNATED_INITIALIZER;

    @end

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for the API draft! 
Looks good to me.  Feel free to give a stab.

**Comment by md0u80c9** [comment]
Yes this looks good to me @rsanchezsaez !

**Comment by rsanchezsaez** [comment]
@md0u80c9 I have implemented this functionality in the above linked pull request, I hope it suits your needs.

**Comment by rsanchezsaez** [comment]
This has been merged and the issue can be closed.
