### ISSUE TITLE
send array content via mail?

### ISSUE THREAD

**Issue by PedroMaganinho** [ResearchKit/ResearchKit#536]
is it possible to send the content of an array via mail?

-(void)sendEmail
{

        if ([MFMailComposeViewController canSendMail])
        {
            MFMailComposeViewController *mail = [[MFMailComposeViewController alloc] init];
            mail.mailComposeDelegate = self;
            [mail setSubject:@"subject"];
            [mail setMessageBody:@"content of the email" isHTML:NO];
            [mail setToRecipients:@[@"xxxx@xxx.com"]];
            
            [self presentViewController:mail animated:YES completion:NULL];
        }
        else
        {
            NSLog(@"the device is not supported");
        }
    
}

**Comment by md0u80c9** [comment]
Yes. There are several ways to do it. Hopefully this is complete enough - much of it is cut and paste from my project so let me know if there are gaps you can't fill.

You could just convert your ORKTaskResult object to NSData and send it raw. But that gives you headaches at the other end.

The way I opted for was to produce a CSV file.

So, create a conversion function, and put your header rows into an array.

Then create an empty dictionary to store your results.

For each data type I set up a small number of conversion functions, such as this (in Swift):

```
func textResultToDictionary(taskResult: ORKTaskResult, stepIdentifier: String, resultIdentifier: String, dictionaryKey: String) -> (result: String, validation: String) {
    var result : String = ""
    var validation: String = ""
    if let stepResult = taskResult.stepResultForStepIdentifier(stepIdentifier)?.resultForIdentifier(resultIdentifier) as? ORKTextQuestionResult {
        if let choice = stepResult.textAnswer {
            result = choice
        }
        else {
            validation = "* " + dictionaryKey + " was not provided.\n"
        }
    }
    return (result, validation)
}
```

I worked through my ORKTask pulling out data fields by calling each routine in turn:

```
    dataOutput = textResultToDictionary(strokeNurseData!, stepIdentifier: "PatientIdentifiers", resultIdentifier: "Forename", dictionaryKey: "S1Forename")
    dataToExport["S1Forename"] = dataOutput.result
    parsingWarnings += dataOutput.validation
```

Then to construct the CSV there is a basic loop to work your way through the dictionary and add the commas:

```
    // First write out the header
    for headerKey in SSNAPHeaderRowKeys {
        csvFile += headerKey
        if headerKey == SSNAPHeaderRowKeys[SSNAPHeaderRowKeys.count - 1] {
            csvFile += "\n"
        }
        else {
            csvFile += ","
        }
    }
    
    // Now record the data row
    for headerKey in SSNAPHeaderRowKeys {
        if let headerValue = dataToExport[headerKey] {
            csvFile += headerValue
        }
        
        if headerKey == SSNAPHeaderRowKeys[SSNAPHeaderRowKeys.count - 1] {
            csvFile += "\n"
        }
        else {
            csvFile += ","
        }
    }
```

The resulting file, in csvFile, is ready to go. As a neat side-effect, the validation string contains any validation errors which may have occurred, which you can include in the body of your text ;-).

Last thing to do is to compose the email: your view controller needs to support MFMailComposeViewControllerDelegate.

```
    @IBAction func prepareDataForSSNAPTapped(sender: AnyObject) {
        let picker = MFMailComposeViewController()
        picker.mailComposeDelegate = self
        picker.setToRecipients(["ResearchKitIsAwesome@myemail.ac.uk"])
        picker.setSubject("Here comes my data!")
        
        let csv = CSVFile(detailItem!) // This is the function we have described above.
        let fileData: NSData? = csv.CSVfile.dataUsingEncoding(NSUTF8StringEncoding)

        var messageBody = "The attached data is ready for import."
        
        if csv.parsingWarnings != "" {
            messageBody += "\n\nThe following errors were detected in the data which will have to be corrected after import:\n\n" + csv.parsingWarnings
        }
        picker.setMessageBody(messageBody, isHTML: false)
        
        picker.addAttachmentData(fileData!, mimeType: "text/csv", fileName: "SSNAP.csv")
        
        presentViewController(picker, animated: true, completion: nil)
    }
    
    func mailComposeController(controller: MFMailComposeViewController, didFinishWithResult result: MFMailComposeResult, error: NSError?) {
        dismissViewControllerAnimated(true, completion: nil)
    }

```
Bear in mind that in my example this data is not encrypted or protected - and you should consider that issue very carefully. In my case we're using the UK N3 network for data transmission so no problems, but if you are sending patient data back to researchers, you should have some sort of encryption plan for that data.

Hope that helps :-).

**Comment by PedroMaganinho** [comment]
@md0u80c9 thank you! I will try!

**Comment by YuanZhu-apple** [comment]
Yes, please check out:

- (void)addAttachmentData:(NSData*)attachment mimeType:(NSString*)mimeType
fileName:(NSString*)filename

On

MFMailComposeViewController
