### ISSUE TITLE
Animation glitch if you are editing a text field in a form

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#539]
There's an animation glitch if you are editing a text field in a form and tap next.

Steps to reproduce:
- Go to `ORKTest`'s *Mini Form* example.
- Tap any text field (e.g., the first `MESSAGE` section which has the `Your message` placeholder).
- Scroll down and tap `Next`.
- Observe the animation glitch.

**Comment by umerkhan-apple** [comment]
I tried to reproduce the bug on iPhone 6S running 9.0 and was unsuccessful.
However, I was able to reproduce the bug on iPhone 6S simulator running 9.1.

What device and os did you find the bug on? Could it be a bug related to 9.1?

**Comment by rsanchezsaez** [comment]
Sorry for the late reply. This seem to have been resolved on *iOS 9.2*. Closing.
