### ISSUE TITLE
Exclude predefined instruction

### ISSUE THREAD

**Issue by khanxc** [ResearchKit/ResearchKit#540]
In ORKPredefinedTaskOption struct there is a option to exclude instructions.
```Swift
 public static var ExcludeInstructions: ORKPredefinedTaskOption { get }
```
But is there any way to remove only the predefined instruction? Like the one in the screenshot below?. Because Exclude instruction option excludes all the Instruction steps.

![simulator screen shot 20-oct-2015 8 40 00 am](https://cloud.githubusercontent.com/assets/5825355/10596806/a85860f4-7705-11e5-9045-1742550789d7.png)

**Comment by YuanZhu-apple** [comment]
You can always rebuild the task based on your need. 
```
ORKOrderedTask *activeTask = [ORKOrderedTask fitnessTask...];
NSArray *steps = activeTask.steps;
// Restruct `steps`
// create a new ordered task from it  
```

**Comment by umerkhan-apple** [comment]
@khanxc Did you have any other concerns or Is it okay to close this issue?
