### ISSUE TITLE
Skip steps

### ISSUE THREAD

**Issue by EdCA3** [ResearchKit/ResearchKit#544]
I want people to answer different questions at different times (for example: the first time they use the app, then after 1 month, 2months...). What can I do in order to skip the questions they have already answer before to the questions I want them to answer at that particular time?

**Comment by YuanZhu-apple** [comment]
Create different versions of ORKTask in runtime?

**Comment by EdCA3** [comment]
I have no experience creating apps. Can you give me an example?

**Comment by EdCA3** [comment]
Ideally, it should be possible to skip all the consent and basic information parts and automatically starts in a certain group of questions the second time they run the app.

**Comment by rsanchezsaez** [comment]
The first time the user launches the app, you could persistently the current date and time (for example, by saving them to `NSUserDefaults`, for example). You could also store the number of app launches there. 

Then, you could check against the stored values, and depending on the desired condition you could create and present a custom `ORKTask` with the desired content (consent, basic information, actual study questions).
