### ISSUE TITLE
Add a Image under or above a scale.

### ISSUE THREAD

**Issue by ascholz81** [ResearchKit/ResearchKit#547]
I have a current need to display an image of a 1 to 10 scale.  The image helps to divide the scale so people answer with a reasonable likeness in thought.
1 - 4 = small effort
5 - 7 = medium effort
9 - 10 = large effort

This is easier displayed in a horizontal image as opposed to text.  Since scale images are for min/max they won't help here.  Currently, I believe the only way to accomplish this is with an instruction step before the scale question.  However, I have several questions that use this scale, so showing the instruction step before each one would be tedious.

1)  Is there a way besides ORKInstructionStep to show an image?
2)  Perhaps this could be extended to most question types so that an image may be shown between the question and answer section.  This could be helpful in a form step for other reasons than a scale.

**Comment by YuanZhu-apple** [comment]
Please check out `ORKImageChoiceAnswerFormat`

<img width="375" alt="screen shot 2015-10-26 at 11 27 05 am" src="https://cloud.githubusercontent.com/assets/11466704/10738410/93f391f0-7bd4-11e5-8748-f33d7e9d4c65.png">

**Comment by ascholz81** [comment]
That won't work for my instance.  Even though I broke the scale into 3 sections, the client is using the 1 to 10 scale to further break down the estimate of effort.  So I still need an instruction image that they don't select as the answer.  Since image choice is the answer format the FormItem will need an answer.  I know leaving the answer format nil will keep the user from choosing anything.

|---------------|------------------|---------|
1                 5                      8         10
small           medium            large
effort           effort                 effort

(Prettier as an image.)

**Comment by umerkhan-apple** [comment]
@ascholz81 I may not be understanding your use case exactly. Though from your description and the scale diagram you drew above, why can't you create use the image choices module to have 3 images? Image 1 = (1-4) Small effort, Image 2 = (5-7) Medium effort, Image 3 = (9-10) Large effort.

**Comment by ascholz81** [comment]
The answer must be a value from 1 - 10. I can't use the image approach.

**Comment by YuanZhu-apple** [comment]
Have you tried `ORKScaleAnswerFormat` ?

**Comment by ascholz81** [comment]
Yes, I am using scale answer format to obtain my value.  (Sorry I didn't mention that earlier.)  I would just like a way to present the image of the scale for easy reference within the same question.  Placing an instruction step ahead of it wouldn't be as accessible for the user.

**Comment by YuanZhu-apple** [comment]
So you would like to display an image under or above the scale? ehh...

**Comment by ascholz81** [comment]
Yes.  Above the scale, between the question text and the scale. That is
also why I thought this may be a more base level feature that could be used
on other question types.

**Comment by ascholz81** [comment]
I apologize, I can not share the image.

**Comment by YuanZhu-apple** [comment]
Something like this?

<img width="376" alt="screen shot 2015-10-28 at 1 26 53 pm" src="https://cloud.githubusercontent.com/assets/11466704/10802074/d823c1b6-7d77-11e5-9328-881a3b935554.png">

**Comment by ascholz81** [comment]
Yes

**Comment by YuanZhu-apple** [comment]
Maybe we can add an `image` beneath the `textLabel`?

**Comment by ltartaglia** [comment]
I've a similar issue. If you implement this feature (add an image beneath the textLabel) you will solve my problem too. Thanks!

**Comment by umerkhan-apple** [comment]
#778 #708

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
