### ISSUE TITLE
change view controller

### ISSUE THREAD

**Issue by PedroMaganinho** [ResearchKit/ResearchKit#554]
Hello,
Until today, I made an app with consent, survey and after that the app opens the email and sent to me an attachment with the results. 
After that my app restart and goes to the consent again. 
I want that, after sending the email, the app goes to a new view controller where I can show the results of the  survey and a message to the patients.
Can I make that?

**Comment by YuanZhu-apple** [comment]
Yes, your app is responsible to pick which view controller to show. 

Maybe you can save some records in the [NSUserDefaults](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSUserDefaults_Class/) when user finished the consent, and use those records to decide.
