### ISSUE TITLE
ResearchKit without HealthKit?

### ISSUE THREAD

**Issue by kristofer** [ResearchKit/ResearchKit#555]
I want to use researchkit for it's survey capabilities, and not collect health data. RK is a great survey wizard thingie, why do I need to have healthkit involved?

**Comment by YuanZhu-apple** [comment]
You don't need to use healthkit or have healthkit involved in your app.

I just had an app using RK, without requesting HealthKit entitlement.
<img width="489" alt="screen shot 2015-10-30 at 12 49 14 pm" src="https://cloud.githubusercontent.com/assets/11466704/10856384/a79935c4-7f04-11e5-9881-b2221e3c41fa.png">

**Comment by dadixon** [comment]
I'm having this same issue. I'm not using HealthKit and don't have entitlements on but Apple is rejecting my app. I'm just using the survey from ResearchKit. I don't know what to take out to make this pass Apple's approval.
