### ISSUE TITLE
Pie Chart title labels overlap

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#558]
```
func pieChartView(pieChartView: ORKPieChartView, titleForSegmentAtIndex index: Int) -> String {
        
        switch index {
        case 0:
            return "Steps"
        case 1:
            return "Tasks"
        case 2:
            return "Surveys completed"
        default:
            return "test"
        }
    }
```

<img width="370" alt="screen shot 2015-11-04 at 1 59 25 pm" src="https://cloud.githubusercontent.com/assets/11466704/10953343/5ebb4986-82fc-11e5-8ed2-d7a6ecd449c5.png">

**Comment by YuanZhu-apple** [comment]
I am working on this.

**Comment by p2** [comment]
Having the same issue, although not quite this dramatic. Interestingly when I make the overlapping text longer, the legend breaks to two lines and no longer overlaps.

**Comment by YuanZhu-apple** [comment]
@p2 There is a calculation bug at https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Charts/ORKCenteredCollectionViewLayout.m#L49

The last `attributes` should be `lastItemAttributes` instead.
My fix will be shipped with our next release, if you can't wait, just try it in your repo.

**Comment by p2** [comment]
Ah cool, thanks. I can wait (for now).

FWIW, I was about to submit a pull request to be able to customize the fonts. But seemed overkill, all I’d want to change is the caption fonts to be footnote, because they’re really small (percentages and legend). Are you married to the idea to keep these caption fonts or could they be the slightly larger footnote fonts?

**Comment by rsanchezsaez** [comment]
I believe this can be closed as it correctly works on `master`. Thanks for the fix!

**Comment by YuanZhu-apple** [comment]
Yes, it has been fixed in https://github.com/YuanZhu-apple/ResearchKit/commit/d87372923b608613ce7a0d94366bcd29f4df5169
