### ISSUE TITLE
Uniqueness of ORKStep and ORKFormSteps

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#562]
Hi,

Just a couple of observations on doing some work on my app this weekend.

At present ORKSteps need unique identifiers.

It can get a bit messy if you fail to make an ORKStep identifiers unique - the error can be difficult to pin down. The error is not in the construction phase but of course when the Task is called. And in a complex task that can then be a way away.

I think I have an individual solution - use a protocol extension to the Collection of ORKSteps to check for duplicates. I have not yet looked but I suspect this is something that could be solved within ResearchKit itself (apologies - still trying to get App ready so haven't delved directly into the ResearchKit to look yet).

Is it possible to 'fail early' if the ORKStep identifier is non-unique? Happy to try and implement a solution if someone has a clean proposal which is acceptable.

**Comment by YuanZhu-apple** [comment]
Yes, we can definitely catch it during the init of `ORKOrderedTask`.
Something like
```
- (instancetype)initWithIdentifier:(NSString *)identifier steps:(NSArray<ORKStep *> *)steps {
    self = [super init];
    if (self) {
        ORKThrowInvalidArgumentExceptionIfNil(identifier);
        
        _identifier = [identifier copy];
        _steps = steps;
       
       // Call [self validateParameters]; here 
    }
    return self;
}

- (void)validateParameters {
    NSArray *uniqueIdentifiers = [self.steps valueForKeyPath:@"@distinctUnionOfObjects.identifier"];
    BOOL itemsHaveNonUniqueIdentifiers = ( self.steps.count != uniqueIdentifiers.count );
    
    if (itemsHaveNonUniqueIdentifiers) {
        @throw [NSException exceptionWithName:NSGenericException reason:@"Each step should have a unique identifier" userInfo:nil];
    }
}
```

Can you make a PR?

**Comment by md0u80c9** [comment]
Yes I'll have a look at that over the weekend - thanks for that :-).

Looks like the sort of thing we may need a unit test for as well to demonstrate it's working.

**Comment by YuanZhu-apple** [comment]
Fixed by @rsanchezsaez.
