### ISSUE TITLE
Typo: ORKStepNavigationRule 'destionationStepIdentifiers'

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#563]
There are three instances of this typo in ORKStepNavigationRule.h and ORKStepNavigationRule.swift. Here is one of them (a quick 'find' shows the other two in the above files:

- (instancetype)initWithResultPredicates:(NSArray<NSPredicate *> *)resultPredicates
              destinationStepIdentifiers:(NSArray<NSString *> *)destinationStepIdentifiers
                   defaultStepIdentifier:(nullable NSString *)defaultStepIdentifier NS_DESIGNATED_INITIALIZER NS_SWIFT_UNAVAILABLE("Use the Swift init(resultPredicatesAndDestionationStepIdentifiers: [(NSPredicate, String)], defaultStepIdentifierOrNil: String?) initializer instead.");

**Comment by md0u80c9** [comment]
PR created for this.

**Comment by YuanZhu-apple** [comment]
PR has been merged
https://github.com/ResearchKit/ResearchKit/pull/564
