### ISSUE TITLE
ORKRegistrationStep passcodeValidationRegex is case-insensitive

### ISSUE THREAD

**Issue by rliljest** [ResearchKit/ResearchKit#566]
Currently the NSRegularExpression used with ORKAnswerFormat uses the NSRegularExpressionCaseInsensitive option. This makes it impossible to make a case-sensitive passcodeValidationRegex in ORKRegistrationStep (which could be used to enforce concepts such as "password must contain one lowercase and one uppercase letter").

Potential fix I have ready locally (creating this issue first per contribution guidelines):
- Create new NSRegularExpressionOptions property in ORKAnswerFormat.h for ORKTextAnswerFormat class
- Initialize to NSRegularExpressionCaseInsensitive in commonInit (for backwards compatibility)
- Update ORKTextAnswerFormat methods validateParameters, copyWithZone:, and isTextRegexValidWithString: to use new property

From there we could either
- Assume that the ORKRegistrationStep passcodeValidationRegex will always want to be case-insensitive (potentially breaking existing code that assume case insensitivity)
- Expose a new transparent NSRegularExpressionOptions property on ORKRegistrationStep that is backed by the ORKTextAnswerFormat NSRegularExpressionOptions, and leave it to the caller to set something other than NSRegularExpressionCaseInsensitive

**Comment by YuanZhu-apple** [comment]
Thanks for the proposal!

I agree we should expose `NSRegularExpressionOptions`  in `ORKAnswerFormat.h` and  `ORKRegistrationStep.h` to replace current pattern string.
Also please take care of `ORKESerialization.h`.

**Comment by umerkhan-apple** [comment]
Fixed in #897
