### ISSUE TITLE
Informed Consent animations are static

### ISSUE THREAD

**Issue by SNagra** [ResearchKit/ResearchKit#571]
The visual consent screen animations never animate, is there an option that I am missing to turn them on?

**Comment by rliljest** [comment]
Are you using all of the specified animation steps in the correct order? There are only 7 built-in animations:

ORKConsentSectionTypeOverview -> ORKConsentSectionTypeDataGathering
ORKConsentSectionTypeDataGathering -> ORKConsentSectionTypePrivacy
ORKConsentSectionTypePrivacy -> ORKConsentSectionTypeDataUse
ORKConsentSectionTypeDataUse -> ORKConsentSectionTypeTimeCommitment
ORKConsentSectionTypeTimeCommitment -> ORKConsentSectionTypeStudySurvey
ORKConsentSectionTypeStudySurvey -> ORKConsentSectionTypeStudyTasks
ORKConsentSectionTypeStudyTasks -> ORKConsentSectionTypeWithdrawing

If you don't need all of these consent sections or need to add some of your own, then you need to come up with the animations yourself via the customAnimationURL property on ORKConsentSection

**Comment by SNagra** [comment]
They must be used in a certain in order to have them animate?

**Comment by YuanZhu-apple** [comment]
Yes.
