### ISSUE TITLE
ORKLocation has no member 'address'

### ISSUE THREAD

**Issue by UberJason** [ResearchKit/ResearchKit#574]
Hello!

I just cloned ResearchKit to poke around at the forms and answer formats, so I attempted to build the ORKCatalog project. However, there is a compile error in ResultTableViewProviders.swift:

![screen shot 2015-11-24 at 7 56 58 pm](https://cloud.githubusercontent.com/assets/5779307/11385310/91a6d858-92e5-11e5-9bd6-0ec8b8b4a24e.png)

A quick look at the ORKLocation header confirms that there is indeed no address property:

![screen shot 2015-11-24 at 7 58 25 pm](https://cloud.githubusercontent.com/assets/5779307/11385343/cdc1c1ae-92e5-11e5-95e8-eb6cf8306605.png)

There's a userInput property which is commented as "The human readable address typed in by user." Is it possible this field was changed at some point without updating the ORKCatalog project, causing the error?

**Comment by YuanZhu-apple** [comment]
Yes, you are right. Can you put up a PR to fix it? Thanks!

**Comment by UberJason** [comment]
Would you want the userInput field changed to "address", or to change the ORKCatalog project to just use "userInput" instead?

**Comment by YuanZhu-apple** [comment]
Change the ORKCatalog project to just use "userInput" instead.

**Comment by UberJason** [comment]
Will do!

**Comment by Natelegreat1** [comment]
I think this item can be closed :) 
"userInput" works perfectly in v1.3
