### ISSUE TITLE
Revise Date Formatter Implementation

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#577]
`ORKAnswerFormat` uses multiple instances of date formatters, which basically do similar work. They need to be consolidated and proper localization support must be provided.

**Comment by remypanicker** [comment]
@oliverschaefer If I'm inferring your proposed solution properly, you're implying that there should be a single date formatter, and the date format of that cached instance should be set depending on the formatting requirements. I believe the different date formatters are cached properly because setting the date format on an instance of `NSDateFormatter` is almost as slow as creating a new instance.

**Comment by oliverschaefer** [comment]
@remypanicker Thanks for your comment. My concerns aren't that much about performance. A single date formatter instance should make it easier for developers to understand/add to the framework. Besides that, the current implementation has some drawbacks in terms of localization. We are having a lengthy discussion with @YuanZhu-apple @umerkhan-apple @md0u80c9 about this one. Please see #463 for more details.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Can you make a list of dateFormatters usage in `ORKAnswerFormat.m`?

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Here you are:
- <b>`ORKDateAnswerFormat`</b> has a `resultDateFormatter` method, which uses `ORKResultDateFormatter`, `ORKResultTimeFormatter` and `ORKResultDateTimeFormatter`
- <b> `ORKTimeIntervalAnswerFormat` </b> uses `ORKTimeIntervalLabelFormatter` which is basically a `NSDateComponentsFormatter`

My concerns are mostly about localization. The `ORKResult...Formatters` set an explicit date and/or time format, which is not localization friendly. If we need to present the collected results to the user (e. g. any form of printing support) we'd need to introduce additional date formatters that do the job. To avoid this, I think we should refactor the current implementation.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer I did a quick scan, `resultDateFormatter`, `stringFromDate:` and `dateFromString:` on `ORKDateAnswerFormat` is not being used in anywhere. Can you confirm?

**Comment by oliverschaefer** [comment]
@YuanZhu-apple I'm currently using it in #463, but didn't see it elsewhere.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer If you are the only consumer, feel free to modify it.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Is this one OK to be closed?
