### ISSUE TITLE
UILabel tint color within ORKTaskViewController

### ISSUE THREAD

**Issue by remotevision** [ResearchKit/ResearchKit#579]
I am trying to apply a global color scheme throughout my app but am having a challenge changing the tint color of labels within a ```ORKQuestionStep``` of a task. 

Set tint color at UIView
```UIView.appearanceWhenContainedInInstancesOfClasses([ORKTaskViewController.self]).tintColor = UIColor().darkPurple```

Also tried setting tint color at UILabel
```UILabel.appearanceWhenContainedInInstancesOfClasses([ORKTaskViewController.self]).tintColor = UIColor().darkPurple```

Here is the result. The title and choices are black. Only the selected choice turns ```darkPurple()```
<img width="371" alt="screen shot 2015-12-11 at 9 12 43 pm" src="https://cloud.githubusercontent.com/assets/338559/11759917/201ae462-a04c-11e5-908b-126d18935479.png">

**Comment by YuanZhu-apple** [comment]
Yes, that's expected, only the selected label get tint color.
