### ISSUE TITLE
Refreshing chart data

### ISSUE THREAD

**Issue by swaffoja** [ResearchKit/ResearchKit#582]
I have a `ORKLineGraphChartView` chart that needs to update when a user taps a segmented control. I am trying to identify the best way to force a refresh. The only way I have found to refresh the chart is to re-set the dataSource. Two questions:

1) Is there a better way to update a chart?
2) Is there a way to animate chart changes?

    func dateRangeDidChange(sender:UISegmentedControl) {
        generatePlotPointsForSegment(sender.selectedSegmentIndex)
        self.dateLineChart!.dataSource = self
    }

<img width="343" alt="screen shot 2015-12-16 at 1 06 46 pm" src="https://cloud.githubusercontent.com/assets/887384/11850966/e8216894-a3f5-11e5-919b-edd6e2fc5989.png">

**Comment by rsanchezsaez** [comment]
1) You're correct, the proper way of updating the chart at the moment is re-setting the `dataSource`. Implementing a `reloadData` method may be a good idea.

2) Did you try calling `-animateWithDuration:` after setting the new `dataSource`? What happens if you do that?

**Comment by swaffoja** [comment]
1) Thanks for the confirmation
2) I thought I tried it, but clearly did not. `-animateWithDuration:` after setting the new `dataSource` does in fact animate the chart.

Thanks!
Jonathan

**Comment by rsanchezsaez** [comment]
@swaffoja: In case this is still of interest, I implemented the `reloadData` methods on the just merged [Pull Request #602](https://github.com/ResearchKit/ResearchKit/pull/602), so you can use that one instead of re-setting the `dataSource` (although re-setting it continues to just work fine).

**Comment by swaffoja** [comment]
Thanks! I'll switch to reloadData for clarity.
