### ISSUE TITLE
Line Charts

### ISSUE THREAD

**Issue by PedroMaganinho** [ResearchKit/ResearchKit#584]
Hello,
I am having a problem with my charts.

I have 2 charts. The first one represent IPSS score over the time. The second represent IIEF-5 score over the time. 

With my code
    if(ipssPoints.count && iiefPoints.count) {
        self.plotPoints = @[ipssPoints, iiefPoints];
        self.graphCells = @[[self createGraphCellWithTag:0 andTitle:@"IPSS"],
                            [self createGraphCellWithTag:1 andTitle:@"IIEF-5"]];

unfortunatelyonly only appear  ipsspoints in two charts. If I change the code to 
    if(ipssPoints.count && iiefPoints.count) {
        self.plotPoints = @[iiefPoints, pssPoints];
        self.graphCells = @[[self createGraphCellWithTag:0 andTitle:@"IPSS"],
                            [self createGraphCellWithTag:1 andTitle:@"IIEF-5"]];

Only appear iiefPoints in the two charts.

How can I  change the code to appear ipsspoint in ipss chart and iiefpoint in IIEF-5 chart?
Thanks a lot!

**Comment by rsanchezsaez** [comment]
This looks like a problem with your code, as opposed to an issue within *ResearchKit*.

Anyway, if you could show more code we may be able to help, namely, the content of `createGraphCellWithTag:andTitle:` function, and how the `self.plotPoints` property is used by the graphs.

Also, please format your code so it's easier to read (surround it by three backticks: ```).

**Comment by PedroMaganinho** [comment]
My code is here:
```           
      [ipssPoints addObject:[[ORKRangedPoint alloc] initWithValue:ipssSum]];
      [iiefPoints addObject:[[ORKRangedPoint alloc] initWithValue:iief5Sum]];
            }

       if(ipssPoints.count && iiefPoints.count) {
        self.plotPoints = @[ipssPoints, iiefPoints];
        self.graphCells = @[[self createGraphCellWithTag:0 andTitle:@"IPSS"],
                                       [self createGraphCellWithTag:1 andTitle:@"IIEF-5"]];
    }

Thanks

**Comment by rsanchezsaez** [comment]
Can I see your implementations of the `-graphChartView:pointForPointIndex:plotIndex:` and  `-graphChartView:numberOfPointsForPlotIndex:` `dataSource` methods? I feel the problem may be in those, since it looks you are returning the same set of points for both graphs.

**Comment by PedroMaganinho** [comment]
@rsanchezsaez i solve my problem. thanks for your help

**Comment by rsanchezsaez** [comment]
No problem. It'd be good if you could close the issue ('Close Issue' button next to the green 'Comment' one).
