### ISSUE TITLE
Include of non-modular header when creating new chart type (Radar)

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#585]
Hi all,

Wonder if you could help. I need to add a radar chart type - which I thought would be a nice addition to ResearchKit in any case so have created a branch for this which I'm working towards becoming a PR.

I've duplicated all of the Pie source files, and changed all instances of Pie to Radar - we have ORKRadarChartRadarView.h etc. The plan was to get to a build that I could add a 'duplicate' pie chart type to ORKCatalog which responds to class names of 'Radar' type so I can then reconstruct those classes with the correct drawing routines.

I've then added an import to researchkit.h:

#import <ResearchKit/ORKRadarChartView.h>

I'm getting an error back of 'Import of non-modular header inside framework module 'ResearchKit'.

I get the impression from a brief read online this is usually the result of an import containing a global include - apart from UIKit in ORKRadarChartLegendCell (ORKPieChartLegendCell) (which I can't see how that can be avoided, nor why it wouldn't trigger the same error in the master build since ORKPieChartLegendCell contains the same).

Am I missing something? Is there something extra somewhere I need to be adding?

Any ideas welcome!

Drew

**Comment by rsanchezsaez** [comment]
Can you check that your newly added `ORKRadarChartRadarView.h` header is set to *public* in the *Framework target membership*? See the right hand panel of the screenshot below.

![screen shot 2015-12-21 at 14 54 57](https://cloud.githubusercontent.com/assets/444313/11933270/d7dcb29e-a7f2-11e5-82b6-1842f928d7ed.png)

If that doesn't help, upload your non-working branch and I'll have a look.

**Comment by md0u80c9** [comment]
Ah - perfect. Done that and compiles nicely now. Right - time to play with the drawing functions!

**Comment by rsanchezsaez** [comment]
:+1:

If you have any questions about the code in `ORKPieChartView` and friends, let me know and I may be able to help.

**Comment by md0u80c9** [comment]
Thanks - I’ll definitely take you up on that!

We now have a Pie chart that pretends it’s a radar map, so that’s a good start. Next up will be to draw the radar map over the top of the pie chart and see how we go from there :-).
