### ISSUE TITLE
ORKGraphChartView checks wrong delegate method for respondsToSelector

### ISSUE THREAD

**Issue by dhanushram** [ResearchKit/ResearchKit#589]
In `ORKGraphChartView`, we have the following code (line 1073, in `_axCreateAccessibilityElements` method):

        if ([_dataSource respondsToSelector:@selector(pieChartView:titleForSegmentAtIndex:)]) {
            element.accessibilityLabel = [self.dataSource graphChartView:self titleForXAxisAtPointIndex:pointIndex];

The below should read as below checking the appropriate delegate: `graphChartView:titleForXAxisAtPointIndex:`

        if ([_dataSource respondsToSelector:@selector(graphChartView:titleForXAxisAtPointIndex:)]) {
            element.accessibilityLabel = [self.dataSource graphChartView:self titleForXAxisAtPointIndex:pointIndex];

**Comment by YuanZhu-apple** [comment]
Good catch, thx!
