### ISSUE TITLE
ORKDirectStepNavigationRule cannot be initialized with nil from Swift

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#603]
The docs say to pass `nil` for the step identifier to jump to if the task should end prematurely. However, since the header file is wrapped in `NS_ASSUME_NONNULL` and the initializer does not specify _nullable_, it's not possible to pass nil to the initializer ([line 196](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKStepNavigationRule.h#L196)). Same problem with the `destinationStepIdentifier` ivar.

**Comment by rsanchezsaez** [comment]
That's mistake in the documentation, you should pass `ORKNullStepIdentifier` instead of `nil` for building a rule that ends the task. I'll update the docs in a new PR.

**Comment by p2** [comment]
Aaaah I see. Thanks for clarifying!
