### ISSUE TITLE
Data storage for keeping the data before it gets uploaded.

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#607]
- It takes `NSData *` or `Files` and save them in the disk. 
- App's uploader can retrieve them and delete them once uploading it done.

**Comment by md0u80c9** [comment]
I used CoreData for my app for this purpose with 'RKResults' as the entity and the result stored in an attribute as a transformable. : you can then add 'createdDate', 'uploadedDate', 'surveyName' as attributes.

**Comment by p2** [comment]
FWIW, we have implemented a `DataQueue` in our framework that works similarly to what's envisioned here. It transparently creates a FIFO queue in case upload fails.

https://github.com/chb/c3-pro-ios-framework/tree/master/Sources/DataQueue

(yes, it's finally open source!)
