### ISSUE TITLE
Passive health data collection module

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#608]
- Fetch pre-specified types of data from HealthKit (Once a day), and send to its delegate.
- App can decide how to use these data.

**Comment by md0u80c9** [comment]
Yes this will be really helpful.

**Comment by scdi** [comment]
Has this been implemented yet?

**Comment by umerkhan-apple** [comment]
@scdi A data collector module was released with RK 1.4.

**Comment by cmetts** [comment]
Where can I learn more about the new data collector module? Examples? Documentation?
