### ISSUE TITLE
Unit tests failed due to `ORKReviewStep` serialization  testings.

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#613]
Test: testORKSecureCoding in ORKJSONSerializationTests failed on iPhone 6s
Assertions: failed: caught "NSInvalidUnarchiveOperationException", "Class 'ORKReviewStep' has a superclass that supports secure coding, but 'ORKReviewStep' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant."

File: ORKJSONSerializationTests.m:619

Test: testORKSerialization in ORKJSONSerializationTests failed on iPhone 6s
Assertions: ((unregisteredList.count) equal to (0)) failed: ("1") is not equal to ("0") - Classes didn't implement ORKSerialization (
    ORKReviewStep
)
File: ORKJSONSerializationTests.m:321

Test: testTaskModel in ORKJSONSerializationTests failed on iPhone 6s
Assertions: failed: caught "NSGenericException", "Each step should have a unique identifier"

File: ORKJSONSerializationTests.m:260

**Comment by rsanchezsaez** [comment]
This [Pull Request](https://github.com/ResearchKit/ResearchKit/pull/604) I submitted some days ago fixes this.

**Comment by rsanchezsaez** [comment]
This issue can be closed.

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple Friendly ping to close this issue. :)
