### ISSUE TITLE
toneAudiometryTaskWithIdentifier includes speech instructions

### ISSUE THREAD

**Issue by u84six** [ResearchKit/ResearchKit#616]
Is this a copy and paste issue? Not sure what speech instructions have to do with tone audiometry.

**Comment by YuanZhu-apple** [comment]
https://github.com/ResearchKit/ResearchKit/blob/dd4e4fdbceee1c876f3d83a8668d1117b8d4dc21/ResearchKit/Common/ORKOrderedTask.m#L814

It's optional.
