### ISSUE TITLE
When calling presentViewController for any ORKTaskViewController causes landscape mode

### ISSUE THREAD

**Issue by u84six** [ResearchKit/ResearchKit#617]
I'm trying to show all the screens in portrait, but when I present any of the surveys, consent, activities, it's  forcing the screen to go in landscape mode. This happens on iPhone 6, 5, 4...

**Comment by YuanZhu-apple** [comment]
Have you tried with project settings to limit app supported orientations? 
![screen shot 2016-02-03 at 5 44 03 pm](https://cloud.githubusercontent.com/assets/11466704/12803237/c4af2f30-ca9d-11e5-8c39-bf7dca5d1898.png)

**Comment by u84six** [comment]
Well my app needs a mix. The problem is that the presenter is in portrait and when I call presentViewController with any rk view controller, it switches to landscape. That shouldn't be the default behavior. Is this a defect?

**Comment by u84six** [comment]
This one has been resolved. The problem that my previous screen had a slight autolayout issue that I couldn't even see that was causing the next screen to go into landscape. Kind of a strange side effect for iOS.
