### ISSUE TITLE
Signature Line UI element problem precluding consent...

### ISSUE THREAD

**Issue by joeborelli** [ResearchKit/ResearchKit#623]
There's not enough space below the signature line.  Most signatures will be cut off.
![image1](https://cloud.githubusercontent.com/assets/17461886/13302340/60ef2c9a-db17-11e5-985c-e64d697b9789.PNG)
![image1](https://cloud.githubusercontent.com/assets/17461886/13302349/6faebc00-db17-11e5-92e2-ee454fa010e3.PNG)

**Comment by YuanZhu-apple** [comment]
@joeborelli Yes, currently the line is at 10%  to the bottom of drawable area. Do you think it should be moved to 20% to the bottom?

To make the change, you only need to modify these two lines:
https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L222
https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L238

Do you want create a pull request?

**Comment by joeborelli** [comment]
Dear Yuan,

I’ll let our developer (Pablo at YML) answer that (pull request), but we do want much more space below the line so that signatures are not cut off.  I’d say 30% at least for flamboyant signatures (e.g. John Hancock)!

Thank you for the prompt response!


A. Joseph Borelli, Jr., M.D.
Board of Directors
American Sleep Apnea Association
www.sleepapnea.org <http://www.sleepapnea.org/>
www.sleeptember.org <http://www.sleeptember.org/>

**Comment by YuanZhu-apple** [comment]
@joeborelli Can you ask Pablo to make a Pull Request? It would be more efficient to submit the change from your side.

I guess only two lines need to be changed:
https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L222
https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L238


Thanks,
Yuan

**Comment by joeborelli** [comment]
He was copied.  Is this urgent?

**Comment by YuanZhu-apple** [comment]
Not at all, just leave this issue open and we can make this change in next
release by ourself.

**Comment by joeborelli** [comment]
We have implemented this change on our side.

On Thursday, February 25, 2016, Albert Borelli Jr <joeborelli1@mac.com>
wrote:

> He was copied.  Is this urgent?
>
>
> On Feb 25, 2016, at 5:19 PM, Yuan Zhu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> @joeborelli <https://github.com/joeborelli> Can you ask Pablo to make a
> Pull Request? It would be more efficient to submit the change from your
> side.
>
> I guess only two lines need to be changed:
>
> https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L222
>
> https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/Consent/ORKSignatureView.m#L238
>
> Thanks,
> Yuan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ResearchKit/ResearchKit/issues/623#issuecomment-189009872>
> .
>
>
>

-- 
*Pablo C. Arce*
Lead Program Manager - Y Media Labs
*917.536.1891*
pablo.arce@ymedialabs.com
www.ymedialabs.com

**Comment by joeborelli** [comment]
Getting a pull request of the framework is way to risky at this point, so
we are modifying it from our side.  It allows for a safer solution at this
point.

*Pablo C. Arce*
Lead Program Manager - Y Media Labs
*917.536.1891*
pablo.arce@ymedialabs.com
www.ymedialabs.com

**Comment by joeborelli** [comment]
Thank you!

A. Joseph Borelli, Jr., MD

**Comment by kelseydedoshka-apple** [comment]
@joeborelli closing this issue since you have resolved the issue on your end.

**Comment by rsanchezsaez** [comment]
Since I feel this is a worthwhile usability improvement, I went ahead and submitted [Pull Request](https://github.com/ResearchKit/ResearchKit/pull/894).

**Comment by kelseydedoshka-apple** [comment]
@rsanchezsaez great thanks for submitting the PR!

**Comment by rsanchezsaez** [comment]
My pleasure. :-)
