### ISSUE TITLE
Can I modify an ORKQuestionStepViewController so that it has additional views?

### ISSUE THREAD

**Issue by u84six** [ResearchKit/ResearchKit#634]
I know that ORKStepViewController UI is generated based on the answer format. So how would I override the creation of the view so that I can add more controls? For example, be able to add a button on the screen that can be handled to do something when clicked, but the ORKQuestionStepViewController still behaves as usual (i.e. returns an answer result).

**Comment by rsanchezsaez** [comment]
Have a look at [`ORKActiveStepViewController`'s `customView`](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/ActiveTasks/ORKActiveStepViewController.h#L72-L82) property. You could possibly add a subview including your custom controls there.

The issue is that `ORKActiveStepViewController` doesn't handle *questions*. You could have and *active step* with your custom controls, followed by one or more *question steps*. If you need both the custom controls and the question to be on the same step, I'm afraid you may have to modify the internals of RK.

**Comment by u84six** [comment]
I noticed that ORKQuestionStepViewController has an ORKQuestionStepCustomView. Is that the equivalent to ORKActiveStepViewController's customView?

**Comment by YuanZhu-apple** [comment]
@u84six ORKQuestionStepCustomView would entirely replace the default questionView for the answer format. Not sure if that is the behavior you want.

Can you tell me more about your use case and  the button you want to add?

**Comment by u84six** [comment]
Let's say I want to add a button that launches a webpage or something so that they can read a doc before continuing the question step. Can that be done or is it best to just create my own ORKStep and ORKStepViewController?

**Comment by YuanZhu-apple** [comment]
Have you tried learn more button with in RK?
<img width="376" alt="screen shot 2016-03-09 at 12 14 30 pm" src="https://cloud.githubusercontent.com/assets/11466704/13649047/888d51da-e5f0-11e5-961f-99ca880a664d.png">

In taskVC's delegate implement this two methods:

```
/**
 Asks the delegate if there is Learn More content for this step.
 
 The task view controller calls this method to determine whether a
 Learn More button should be displayed for the step.
 
 The standard templates in ResearchKit for all types of steps include a button
 labeled Learn More (or a variant). In consent steps, this is internal to
 the implementations of the step and step view controller, but in all other steps,
 the task view controller asks its delegate to determine if Learn More content is available,
 and to request that it be displayed.
 
 @param taskViewController  The calling `ORKTaskViewController` instance.
 @param step                The step for which the task view controller needs to know if there is Learn More content.
 
 @return `NO` if there is no Learn More content to display.
 */
- (BOOL)taskViewController:(ORKTaskViewController *)taskViewController hasLearnMoreForStep:(ORKStep *)step;

/**
 Tells the delegate that the user has tapped the Learn More button in the step.
 
 The standard templates in ResearchKit for all types of steps include a button
 labeled Learn More (or a variant). In consent steps this is internal to
 the implementations of the step and step view controller, but in all other steps,
 the task view controller asks its delegate to determine if Learn More content is available.
 
 This method is called only if the delegate returns `YES` to
 `taskViewController:hasLearnMoreForStep:` for the current step, and the user
 subsequently taps on the Learn More button.
 
 When this method is called, the app should respond to the Learn More action by
 presenting a dialog or other view (possibly modal) that contains the Learn More content.
 
 @param taskViewController  The calling `ORKTaskViewController` instance.
 @param stepViewController  The `ORKStepViewController` that reported the Learn More event to the task view controller.
 */
- (void)taskViewController:(ORKTaskViewController *)taskViewController learnMoreForStep:(ORKStepViewController *)stepViewController;

```

When get called in `learnMoreForStep:`, you can launch anything you want.

**Comment by u84six** [comment]
Thanks for the suggestion. That might work.

**Comment by u84six** [comment]
So it looks like I can enable it, set the title, and handle click. Can I replace the item with an icon? I see there's a defaultLearnMoreButtonItem, so how can I override that with my own button? I'm not finding a way to access the property.

**Comment by YuanZhu-apple** [comment]
No, that's not supported.
