### ISSUE TITLE
Modify ResearchKit.podspec to include .swift files

### ISSUE THREAD

**Issue by jennadavis077** [ResearchKit/ResearchKit#642]
I am coding in swift, and using Cocoa Pods to manage my dependencies. I am unable to use the argument resultPredicatesAndDestinationStepIdentifiers because it exists in  ORKStepNavigationRule.swift (located in the common directory), and the ResearchKit.podspec only imports .m and .h files, not .swift files. This podspec should be modified to support .swift files.

**Comment by rsanchezsaez** [comment]
Thanks for the report, I've submitted a pull request fixing this.
