### ISSUE TITLE
Signature view should support 3D touch for stroke width

### ISSUE THREAD

**Issue by samfalconer** [ResearchKit/ResearchKit#652]
I have a patch that adds 3D touch capability to the stroke width of the signature view. Push harder and the line becomes thicker.

There is also a fallback to base the stroke width on the speed of the stroke for devices that don't support 3D touch.

**Comment by samfalconer** [comment]
I have submitted PR #653

**Comment by oliverschaefer** [comment]
@samfalconer Thanks for bringing this up. Could you also add the support for Apple Pencil with this PR?

**Comment by samfalconer** [comment]
@oliverschaefer This *should* work with the Apple Pencil's force feedback as is. However, I don't own an Apple Pencil so I am unable to test this personally.

As far as other features of that device, shading using the altitude and azimuth seems out of the scope of a signature view like this. Additionally, it would be difficult to do well with just CoreGraphics.

The only other Apple Pencil feature is preciseLocationInView. It would be great if someone with an Apple Pencil could test its existing precision here to see if using this method is worth it (keeping in mind it would require an additional API check to support iOS < 9.1).

**Comment by samfalconer** [comment]
@oliverschaefer Looks like UIForceTouchCapabilityAvailable only checks for 3D touch. So I've updated the PR to check for UITouchTypeStylus on the touches as well.

Would be great if someone with an Apple Pencil could test this on-device.

I have checked this against older API's (iOS 8.1 simulator) and everything seems to fallback correctly.
