### ISSUE TITLE
ORKChart Data Source

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#655]
I don't know if this is the right place for it...but if I'm trying to graph some of the results of a health survey such as how many times one answer was chosen...how do I do it? I'm grabbing the data points in a separate function, but function is not run until after the pie chart is set up

**Comment by rsanchezsaez** [comment]
Could you post some code, or a minimal complete project to GitHub?

**Comment by kothapas** [comment]
class PieChartDataSource: NSObject, ORKPieChartViewDataSource {
    
    var totalCount: Int = 0
    var homeCount: Int = 0
    var workCount: Int = 0
    var commuteCount: Int = 0
    var outCount: Int  = 0
    
    func fetchResults() {
        ORKTaskResult.cmh_fetchUserResultsForStudyWithDescriptor("dailystudy", withCompletion: {CMHFetchCompletion in
            if(nil == CMHFetchCompletion.0) {
                return
            }
            
            
            if let resultsArray = CMHFetchCompletion.0 as? [ORKTaskResult]{
                for result in resultsArray {
                    let stepResult = result.stepResultForStepIdentifier("location")
                    if let results = stepResult?.results as? [ORKChoiceQuestionResult] {
                        let choice = results[0].choiceAnswers![0] as! Int
                        switch choice {
                        case 0:
                            self.homeCount+=1
                            self.totalCount+=1
                        case 1:
                            self.workCount+=1
                            self.totalCount+=1
                        case 2:
                            self.commuteCount+=1
                            self.totalCount+=1
                        case 3:
                            self.outCount+=1
                            self.totalCount+=1
                        default:
                            break                        }
                    }
                }
                print(self.homeCount)
                print(self.commuteCount)
                print(self.workCount)
                print(self.outCount)
                print(self.totalCount)
            }
        })
        self.HomePercentage = 25//(CGFloat(homeCount)/CGFloat(totalCount))*100
        self.WorkPercentage = 25//(CGFloat(workCount)/CGFloat(totalCount))*100
        self.CommutePercentage = 25//(CGFloat(commuteCount)/CGFloat(totalCount))*100
        self.OutPercentage = 25//(CGFloat(outCount)/CGFloat(totalCount))*100
        
    }

    
    enum PieChartSegment: Int {
        case Home, Work, Commute, Out
    }
    
    var HomePercentage: CGFloat = 25
    var WorkPercentage: CGFloat = 25
    var CommutePercentage: CGFloat = 25
    var OutPercentage: CGFloat = 25

    func numberOfSegmentsInPieChartView(pieChartView: ORKPieChartView) -> Int {
        self.fetchResults()
        return 4;
        
    }
    
    func pieChartView(pieChartView: ORKPieChartView, valueForSegmentAtIndex index: Int) -> CGFloat {
        switch PieChartSegment(rawValue: index)! {
        case .Home:
            return (CGFloat(homeCount)/CGFloat(totalCount))*100
        case .Work:
            return WorkPercentage
        case .Commute:
            return CommutePercentage
        case .Out:
            return OutPercentage
        }
    }
}

**Comment by kothapas** [comment]
i want to use the result that i get from fetchResults() as my data points for the ORK Chart

**Comment by kothapas** [comment]
never mind I got it

**Comment by nikhiljay** [comment]
can you explain how you got it?

**Comment by rsanchezsaez** [comment]
@nikhiljay: If you don't yet have the `reloadData` method in your release, you can cause a reload by setting the *data source* again like this: `yourPieChartView.dataSource = yourOriginalDataSourceObject`.

**Comment by nikhiljay** [comment]
Ok I got it thanks!
