### ISSUE TITLE
Initializing ORKPredicateStepNavigationRule

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#656]
Is there a reason xcode doesn't give me an option to initialize this with anything other than a coder?

**Comment by rsanchezsaez** [comment]
From *Objective-C*, you can use:

    - (instancetype)initWithResultPredicates:(NSArray<NSPredicate *> *)resultPredicates
                  destinationStepIdentifiers:(NSArray<NSString *> *)destinationStepIdentifiers
                       defaultStepIdentifier:(nullable NSString *)defaultStepIdentifier;
    - (instancetype)initWithResultPredicates:(NSArray<NSPredicate *> *)resultPredicates
                  destinationStepIdentifiers:(NSArray<NSString *> *)destinationStepIdentifiers

From *Swift* those are not available, and you should instead use the safer:

   init(resultPredicatesAndDestinationStepIdentifiers tuples: [ (resultPredicate: NSPredicate, destinationStepIdentifier: String) ], defaultStepIdentifierOrNil: String? )

There's a bug if you import *ResearchKit* through *Cocoapods* which doesn't provide the needed file for the Swift initializer. If that's your case, a workaround is to copy the [ORKStepNavigationRule.swift file](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKStepNavigationRule.swift) from the main repo to your local project.

**Comment by kothapas** [comment]
When I copy it to my local project, do you mean along with the rest of my project files? If so, it gives me an error of cannot invoke ORKPredicateStepNavigationRule.init with an argument list of  type ...

**Comment by kothapas** [comment]
When I try to include it wi

**Comment by rsanchezsaez** [comment]
Are you using Cocoapods then? Yeah, I meant to include the *Swift* file along with the rest of your project files.

Have a look at the [TaskFactory.swift](https://github.com/ResearchKit/ResearchKit/blob/master/Testing/ORKTest/ORKTest/TaskFactory.swift) file for a working example on how to init `ORKPredicateStepNavigationRule`s.

---

If the problem persists, can you provide specific steps and complete error messages and/or upload a minimal project to GitHub showing the issue.

**Comment by kothapas** [comment]
I got a workaround on this

**Comment by kothapas** [comment]
I'm sorry but I need help on this once again. I copied the file as you said into the same place as my other files.The error from the survey task disappears but in the ORKStepNavigationRule.swift file, I am getting this error:

Cannot invoke 'ORKPredicateStepNavigationRule.init' with an argument list of type '(resultPredicates: [NSPredicate], destinationStepIdentifiers: [String], defaultStepIdentifier: String?, validateArrays: Bool)'

I even tried taking out the validateArrays parameter, but then that comes up with the error:

'init(resultPredicates:destinationStepIdentifiers:defaultStepIdentifier:)' is unavailable in Swift: Use the Swift init(resultPredicatesAndDestinationStepIdentifiers: [(NSPredicate, String)], defaultStepIdentifierOrNil: String?) initializer instead.

public var SurveyTask: ORKNavigableOrderedTask {
    
    let instructionID = "Instruction Step"
    let question1ID = "question 1"
    let question2ID = "question 2"
    let completionChoice1ID = "completionChoice 1"
    let completionChoice2ID = "completionChoice 2"
    
    
    let instructionStep = ORKInstructionStep(identifier: instructionID)
    instructionStep.title = "Daily Log"
    instructionStep.text = "First, we'd like to ask you some questions about how you felt today."
    
    
    let question1 = ORKQuestionStep(identifier: question1ID, title: "Did you have a headache today?", answer: ORKAnswerFormat.booleanAnswerFormat())
    
    let question2 = ORKQuestionStep(identifier: question2ID, title: "How long did your headache last?", answer: ORKAnswerFormat.integerAnswerFormatWithUnit("hours"))
    
    let completionStep1 = ORKInstructionStep(identifier: completionChoice1ID);
    completionStep1.title = "Thank you for letting us know you didn't have any headaches today!"
    
    let completionStep2 = ORKInstructionStep(identifier: completionChoice2ID);
    completionStep2.title = "Thank you for logging your headache!"
    
    let task = ORKNavigableOrderedTask(identifier: "first survey", steps: [instructionStep, question1, question2, completionStep1, completionStep2])
    
    let question1Predicate = ORKResultPredicate.predicateForBooleanQuestionResultWithResultSelector(ORKResultSelector(resultIdentifier: question1ID), expectedAnswer: false)
    
    let predicatedNavigationRule = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers:
        [ (question1Predicate, completionChoice1ID) ])
    let directNavigationRule1 = ORKDirectStepNavigationRule(destinationStepIdentifier: completionChoice2ID)
    task.setNavigationRule(directNavigationRule1, forTriggerStepIdentifier: question2ID)
    
    let directNavigationRule2 = ORKDirectStepNavigationRule(destinationStepIdentifier: ORKNullStepIdentifier)
    task.setNavigationRule(directNavigationRule2, forTriggerStepIdentifier: completionChoice1ID)

    return task;
    
}

**Comment by kothapas** [comment]
Just ended up deleting the pod and just downloading the project

**Comment by rsanchezsaez** [comment]
Sorry about your troubles. There's an ongoing PR that, among other things, fixes this issue when importing the project through Cocoapods. Hopefully it'll be merged soon.
