### ISSUE TITLE
allow plot fill color of ORKLineGraphChartView to be set by the delegate

### ISSUE THREAD

**Issue by dukemike** [ResearchKit/ResearchKit#658]
Currently, all plots have a fill color of 60% of their plot color. ``ORKGraphChartView:fillColorForPlotIndex:`` could be used to allow a plot to not be filled.

**Comment by rsanchezsaez** [comment]
This would be a nice feature to have. I see you implemented it in your fork, could you submit a *pull request* with this feature?

**Comment by YuanZhu-apple** [comment]
@dukemike How is going along the pull request:)

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple: The feature has been merged and the issue can be closed.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks!
