### ISSUE TITLE
Horizontal discrete graph

### ISSUE THREAD

**Issue by pascalhuynh** [ResearchKit/ResearchKit#659]
Hi, I was wondering if it is possible to draw Horizontal discrete graph with ORKDiscreteGraphChartView.
Thanks for the help,
Pascal

**Comment by rsanchezsaez** [comment]
This is not currently possible, but I think extending `ORKDiscreteGraphChartView` to do this should not be too complicated.

If you want this feature, let's keep this issue open and I may try to implement this in the coming weeks if I find the time.

**Comment by pascalhuynh** [comment]
Great @rsanchezsaez  !

**Comment by simon-apple** [comment]
Thanks for the feedback! This feature was since removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
