### ISSUE TITLE
Broken ResearchKit logo image on developer.apple.com/opensource/

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#66]
Not sure if this is the best place to report it, but the *ResearchKit* logo image is broken [here](https://developer.apple.com/opensource/) (it shows as a not found image).

**Comment by DanKeen** [comment]
Yup! I think we never noticed because we're all using Retina MBP's or iPhone / iPads to access. The @2x version is there but not the @1x. Thanks for the heads up, we'll follow up.

**Comment by rsanchezsaez** [comment]
Ah, the marvels of using outdated hardware! ;)

By the way, it also looks broken on *iPhone 6*'s Safari.

**Comment by DanKeen** [comment]
Huh, so it does. Odd I didn't notice as that's what I carry!

**Comment by DanKeen** [comment]
Should be fixed now. Verified on a non-retina monitor and my iPhone 6.

**Comment by rsanchezsaez** [comment]
Yeah, it looks good over here as well. :+1:
