### ISSUE TITLE
Graphing HealthKit Data Using ORKDiscreteGraph

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#660]
So in one function, I am trying to call the function that stores the healthkit data I'm trying to collect in an array. These data points are the ones I'm trying to feed into the graph but I'm coming across errors when I try to graph those datapoints. I tried using using dispatch_after but it gives me an ns range exception

class StepsTableViewController: UITableViewController, ORKGraphChartViewDataSource {

    let healthManager:HealthKit = HealthKit()
    let HealthKitStore:HKHealthStore = HKHealthStore()
    
    var plotPoints = [
                        [
                            ORKRangedPoint(minimumValue: 0, maximumValue: 2),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 4),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 6),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 8),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 10),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 12),
                            ORKRangedPoint(minimumValue: 0, maximumValue: 14)
                        ]
                ]

    func readSteps() -> Void
    {
        var stepsOver = [Double]()
        print("Entered read profile")
        let calendar = NSCalendar.currentCalendar()
        
        let interval = NSDateComponents()
        interval.day = 1
        
        // Set the anchor date to Monday at 3:00 a.m.
        let anchorComponents =
            calendar.components([.Day, .Month, .Year, .Weekday], fromDate: NSDate())
        
        let offset = (7 + anchorComponents.weekday - 2) % 7
        anchorComponents.day -= offset
        anchorComponents.hour = 3
        
        let anchorDate = calendar.dateFromComponents(anchorComponents)
        
        let quantityType =
            HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierStepCount)
        
        // Create the query
        let query = HKStatisticsCollectionQuery(quantityType: quantityType!,
                                                quantitySamplePredicate: nil,
                                                options: .CumulativeSum,
                                                anchorDate: anchorDate!,
                                                intervalComponents: interval)
        
        // Set the results handler
        query.initialResultsHandler = {
            query, results, error in
            
            if error != nil {
                // Perform proper error handling here
                print("*** An error occurred while calculating the statistics: \(error!.localizedDescription) ***")
                abort()
            }
            
            let endDate = NSDate()
            let startDate =
                calendar.dateByAddingUnit(NSCalendarUnit.Day,
                                          value: -6, toDate: endDate, options: [])
            
            // Plot the weekly step counts over the past 3 months
            results!.enumerateStatisticsFromDate(startDate!, toDate: endDate) {
                statistics, stop in
                
                if let quantity = statistics.sumQuantity() {
                    let stepsValue = quantity.doubleValueForUnit(HKUnit.countUnit())
                
                    stepsOver.append(stepsValue)
                    //self.plotPoints.append(ORKRangedPoint(minimumValue: 0, maximumValue: CGFloat(stepsValue)))
                    print(stepsValue)
                    
                }
            }
     }
        
        dispatch_async(dispatch_get_main_queue(), {
            self.HealthKitStore.executeQuery(query)
        })
    }
    
    @IBOutlet weak var Steps: ORKDiscreteGraphChartView!
    
    func getDayOfWeek(today:String)->Int {
        
        let formatter  = NSDateFormatter()
        formatter.dateFormat = "MMM d, yyyy"
        let todayDate = formatter.dateFromString(today)!
        let myCalendar = NSCalendar(calendarIdentifier: NSCalendarIdentifierGregorian)!
        let myComponents = myCalendar.components(.Weekday, fromDate: todayDate)
        let weekDay = myComponents.weekday
        return weekDay
    }
    
    func numberOfPlotsInGraphChartView(graphChartView: ORKGraphChartView) -> Int {
        return plotPoints.count
    }
    
    func graphChartView(graphChartView: ORKGraphChartView, pointForPointIndex pointIndex: Int, plotIndex: Int) -> ORKRangedPoint {
        return self.plotPoints[plotIndex][pointIndex] as! ORKRangedPoint
    }
    
    func graphChartView(graphChartView: ORKGraphChartView, numberOfPointsForPlotIndex plotIndex: Int) -> Int {
        return plotPoints[plotIndex].count
    }
    
    func maximumValueForGraphChartView(graphChartView: ORKGraphChartView) -> CGFloat {
        return 10000
    }
    
    func minimumValueForGraphChartView(graphChartView: ORKGraphChartView) -> CGFloat {
        return 0
    }
    
    func graphChartView(graphChartView: ORKGraphChartView, titleForXAxisAtPointIndex pointIndex: Int) -> String? {
        var dateformatter = NSDateFormatter()
        dateformatter.dateStyle = .MediumStyle
        switch pointIndex {
        case 0:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-6*24*60*60))))
        case 1:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-5*24*60*60))))
        case 2:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-4*24*60*60))))
        case 3:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-3*24*60*60))))
        case 4:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-2*24*60*60))))
        case 5:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate().dateByAddingTimeInterval(-1*24*60*60))))
        case 6:
            return String(getDayOfWeek(dateformatter.stringFromDate(NSDate())))
        default:
            break;
        }
        return ""
    }

    override func viewDidLoad() {
        
        
        super.viewDidLoad()
        
        self.healthManager.readSteps()
        
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(3 * Double(NSEC_PER_SEC))), dispatch_get_main_queue(), {
           self.Steps.dataSource = self
        })
        
        
        
    
        
        
        // Optional custom configuration
        Steps.axisColor = UIColor.whiteColor()
        Steps.verticalAxisTitleColor = UIColor.orangeColor()
        Steps.scrubberLineColor = UIColor.redColor()
        Steps.referenceLineColor = UIColor.blueColor()
        //Steps.drawsConnectedRanges = true
        Steps.showsVerticalReferenceLines = true
        Steps.showsHorizontalReferenceLines = true
        
        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem()
    }

**Comment by dukemike** [comment]
Rather than setting the data source in `dispatch_after` you can assign it after enumerating the statistics in the results handler.
