### ISSUE TITLE
How to Return something other than NSDate object for TimeofDayAnswerFormat

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#665]
For a question like when did the onset of a symptom start, is there a way to return something other than a nsdate object, because its a complex data structure

**Comment by rsanchezsaez** [comment]
There's no out-of-the-box way of returning something different than an `NSDate` for that kind of answer format.

Your best bet would the to post-process the result and convert/simplify it to fit your needs.
