### ISSUE TITLE
Creating Custom Active Tasks

### ISSUE THREAD

**Issue by craylward** [ResearchKit/ResearchKit#673]
I've seen a few issues involving the creation of a custom active task, particularly creating the custom view for a task step. I'd like to create a task that displays accelerometer/gyroscope info for 20 seconds during the active step. I've started by creating `accelerometerStep.swift` (subclassing ORKActiveStep), `accelerometerTask.swift` (subclassing ORKOrderedTask), and `accelerometerStepViewController.swift` (subclassing ORKActiveStepViewController) files. I've checked out the tutorial at [https://www.raywenderlich.com/117433/accessing-heart-rate-data-researchkit-study](https://www.raywenderlich.com/117433/accessing-heart-rate-data-researchkit-study) but this doesn't go into detail about creating a custom view for the view controller. Can anyone provide some guidance with implementing the `ORKActiveStepCustomView` _using swift_? or guidance in general about creating a custom active step view?

**Comment by julientherier** [comment]
We have listed some of our ResearchKit tutorials on our blog.
Please visit http://www.shazino.com and navigate under the "ResearchKit/CareKit section".
Hope [this one](http://blog.shazino.com/articles/dev/researchkit-new-active-task/) would be helpful, even if written in Obj-C.

**Comment by alexwasner** [comment]
@craylward I was doing the exact same thing today. In swift, to set the stepViewControllerClass as your steps ViewController, you do this:
 ` static func stepViewControllerClass() -> AccelerometerStepViewController.Type {
        return AccelerometerStepViewController.self
    }`
Then in your viewDidLoad of the AccelerometerStepViewController, you can add your custom content like this: `let container = UIView(frame: [frame goes here])
        customView = container`
