### ISSUE TITLE
Starting a Signature Stroke in the Top Part of the View Fails

### ISSUE THREAD

**Issue by samfalconer** [ResearchKit/ResearchKit#674]
Starting to stroke part of the signature from near the top of ORKSignatureView fails.

For example, if you wanted to draw a tall letter "I" starting from the top of the view, you would be unable. Also, drawing the cross on the top of a tall capital "T" is impossible.

Attached is a screenshot where I have drawn a horizontal stroke starting from the closest to the top of the view that was possible, to demonstrate how you can't start a stroke near the top. Additionally, I drew a vertical stroke **starting from the bottom** all the way up the view, to show how much further the view goes vertically.

I didn't notice this behavior myself while working on #653 because the signatures I tried started from near the bottom of the view, however there are many people who start their signatures from the top and go down.

I witnessed someone not being able to use the signature view because of this bug.

It looks like this bug existed before #653.

![img_2202](https://cloud.githubusercontent.com/assets/3956038/15048999/0ad05bb0-12ba-11e6-87f8-edfb53392e62.png)

**Comment by YuanZhu-apple** [comment]
I can confirm this issue. 
To draw a vertical line, I have to start from bottom to top. Top to bottom fails.

**Comment by umerkhan-apple** [comment]
PR #894 should fix this issue. Let me know if the issue still remains.

**Comment by rsanchezsaez** [comment]
Actually, the already merged [PR #894](https://github.com/ResearchKit/ResearchKit/pull/894) didn't fix the issue.

I submitted [PR #898](https://github.com/ResearchKit/ResearchKit/pull/898) which does fix it.

**Comment by umerkhan-apple** [comment]
#898 Fixes the issue! Thanks!
