### ISSUE TITLE
Expose ORKActiveStepTimerView to custom ActiveStepViewController

### ISSUE THREAD

**Issue by alexwasner** [ResearchKit/ResearchKit#675]
Hello, 
I'm trying to create a new instance of `ORKActiveStepTimerView` in my custom StepViewController and adding it to the `customView` in `viewDidLoad`. When I try to create a new instance `ORKActiveStepTimerView()` it is saying ORKActiveStepTimerView is an unresolved identifier.

**Comment by YuanZhu-apple** [comment]
@alexwasner `hasCountDown` on activeStep can make `ORKActiveStepTimerView` shows up.
Do you mind to share more about your use case?
``` 
   if ([self.activeStep hasCountDown]) {
        ORKActiveStepTimerView *timerView = [ORKActiveStepTimerView new];
        _activeStepView.activeCustomView = timerView;
    } else {
        _activeStepView.activeCustomView = nil;
    }
```

**Comment by umerkhan-apple** [comment]
@alexwasner Are you still experiencing this issue?

**Comment by alexwasner** [comment]
I've since moved on to a different project, but I believe I just worked around the limitation when it came up. No clue if the issue is still there.
