### ISSUE TITLE
Storing users' data in iCloud

### ISSUE THREAD

**Issue by stevemoser** [ResearchKit/ResearchKit#676]
On the [best practices wiki page](https://github.com/ResearchKit/ResearchKit/wiki/best-practices) it states:

> Do not use iCloud to store health information.

However on [Apple's Privacy page](http://www.apple.com/privacy/approach-to-privacy/) it states:

> And any Health data backed up to iCloud is encrypted both in transit and on our servers.

Why is it ok for Apple to store health data on iCloud but not ResearchKit apps? Maybe they have access to private APIs for iCloud encryption?

(I'm not sure if there is a better place for this question like on the dev forums.)

**Comment by YuanZhu-apple** [comment]
@stevemoser CloudKit is not HIPPA compliance. Please consult a lawyer for the details.

**Comment by stevemoser** [comment]
Ok, thank you. Closed.
