### ISSUE TITLE
Datasource execution does not update view

### ISSUE THREAD

**Issue by sukh-cohaesus** [ResearchKit/ResearchKit#677]
Hello

I'm having some issues with my view not displaying the data retrieved from Health Store query. Looking at the logs the async response is coming after I set the `dataSource` on my charts, to be specific its `ORKLineGraphChartView`.

My datasource is an external class which extends `: NSObject, ORKGraphChartViewDataSource`. Within here I have a singleton instance which is basically my Health Store. The steps I take are below:

1. Check for `isHealthDataAvailable`
2. Check `requestAuthorizationToShareTypes`
3. Execute `HKStatisticsCollectionQuery` query

All of the above steps is all within a completion handler.

I set the data source as a property of my `TableViewController`. Then within my `viewDidLoad` I'm assigning the `dataSource` to the property, i.e. 

	@IBOutlet var stepsChart: ORKLineGraphChartView!
	let stepChartDataSource = dataSource()

	override func viewDidLoad() {
	    super.viewDidLoad()
	    stepsChart.dataSource = stepChartDataSource
	}

Looking at the sample I can't quite see where I'm going wrong as its using hard coded data. Is there a way for me to refresh / reload the table?

EDIT: Just to add, this appears to happen after I complete the "onboarding" process where I'm performing rewind segue to parent viewcontroller which then fires off another segue into the dashboard. When running the app from cold where the user has already completed the onboarding process and therefore performs segue to the Dashboard, the data appears fine here (I haven't come across a time where it fails here although I would assume it potentially could as its all asynchronous)

**Comment by rsanchezsaez** [comment]
Yes, use the `reloadData` method after receiving the data you want to plot.

 (This method was added recently, it may yet not be in your release, if that's the case, just set the `dataSource` again and the data will reload.)

**Comment by sukh-cohaesus** [comment]
Thanks for prompt response!

I did come across `reloadData` method but I can't seem to find it. All being said I can resolve that, or use your alternative solution...

Which then leads me to another question. Excuse my stupidity here but how would one go about setting the dataSource again? This is primarily my issue.

So as an example, looking at the sample app which is largely what I'm following (ORKSample project) within the **DashboardTableViewController** we have the following:

    class DashboardTableViewController: UITableViewController {
        
        @IBOutlet var lineGraph: ORKLineGraphChartView!
        ...
        let lineGraphDataSource = LineGraphDataSource()    
        ...
        override func viewDidLoad() {            
            ...
            let lineGraphDataSource = LineGraphDataSource() 
        }
        ...
    }
 
Where here would I set the data source again? Issue primarily as I can see is the asynchronous part from the query to the Health Store...

    ... 
    query.initialResultsHandler = { query, results, error in
            
        guard let statsCollection = results else {
            completion(steps: nil, error: error!)
            return
        }
        
        // Plot the weekly step counts over the past 3 months
        statsCollection.enumerateStatisticsFromDate(startDate, toDate: endDate) { statistics, stop in
            
            if let quantity = statistics.sumQuantity() {
                let date = statistics.startDate
                let value = quantity.doubleValueForUnit(HKUnit.countUnit())
                
                // Add to collection
                collection.append([date: CGFloat(value)])
            }
        }
        
        completion(steps: collection, error: nil)
    }

    HKHealthStore().executeQuery(query)

**Comment by sukh-cohaesus** [comment]
I suppose I could use `NSNotificationCenter` to fire off when I got the data and from here I can set the data source. Is there a better way though?

**Comment by celteeka** [comment]
@ghost not sure what did you end up doing. I did this and it worked. Not sure if it is the best way though since I don't seem to have the reloadData() method yet.
```swift
    // Set the results handler
    stepsQuery.initialResultsHandler = {query, results, error in
    let endDate = NSDate()
    let startDate = calendar.dateByAddingUnit(.Day, value: -7, toDate: endDate, options: [])
    if let myResults = results{
        var points = [ORKRangedPoint]()
        myResults.enumerateStatisticsFromDate(startDate!, toDate: endDate) { statistics, stop in
            if let quantity = statistics.sumQuantity(){
                let date = statistics.startDate
                let steps = quantity.doubleValueForUnit(HKUnit.countUnit())
                print("\(date): steps = \(steps)")
                let point = ORKRangedPoint(value: CGFloat(steps))
                points+=[point]
           }
        } //end enumeration block
        dispatch_async(dispatch_get_main_queue()){
           self.lineGraphChartView.dataSource = StepsGraphDataSource(steps: points)
            self.lineGraphChartView.animateWithDuration(1)
        }
    } //end if let

    }

    healthStore?.executeQuery(stepsQuery)
```
Hope this helps
