### ISSUE TITLE
CocoaPod with ResearchKit as dependency fails to build with linker error

### ISSUE THREAD

**Issue by apbendi** [ResearchKit/ResearchKit#679]
It seems something in ReseachKit's podspec definition interacts with a change in CocoaPods 1.0.0 such that ResearchKit can not be included as a dependency in a library. Doing so results in the following linker error: `ld: 252 duplicate symbols for architecture x86_64`

It's not clear if this is a CocoaPods issue or ResearchKit issue.

An example project can be found here: https://github.com/apbendi/ORKPodFailure

I've also reported the issue with CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/5304

Thanks in advance for any help you can provide!

**Comment by jdkizer9** [comment]
I've also run into this. A temporary work around is described [here](http://stackoverflow.com/a/32108247/6327650). Alternatively, you can update your Podfile post_install script to do it for you:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_NO_COMMON_BLOCKS'] = 'NO'
    end
  end
end
```

I'm currently trying to publish a cocoapod library that has a dependency on ResearchKit. I haven't figured out how to update this setting from the podspec, so it fails to build while lint'ing, and therefore I can't publish it. I could use this fix ASAP!

**Comment by apbendi** [comment]
@jdkizer9 interesting way to work around it. I went the route of forking and fixing the issue, then pointing my podfile to my fork. I've also submitted the changes; hopefully they're incorporated soon: https://github.com/ResearchKit/ResearchKit/pull/680

I too have a Pod published with RK as a dependency- the fact I can't push an update until it's resolved is definitely not optimal
