### ISSUE TITLE
Getting an ORKFormStep into Consent Document

### ISSUE THREAD

**Issue by sukh-cohaesus** [ResearchKit/ResearchKit#683]
Hi all

I have a task where I want to display the Consent Document across which will have a Welcome (which will basically be `ORKConsentSectionType` of case `Overview`) followed by a `ORKFormStep` and then the subsequent consent section types i.e privacy, data use etc...

Is this possible at all?

Also within the `Overview` type of  `ORKConsentSectionType` , is it possible to modify the _Learn More_ link to open an external URL?

Thanks in advance :)

**Comment by sukh-cohaesus** [comment]
Actually ignore this - managed to get a workaround by including Instruction Step within the Ordered Task instead of going directly into the consent document.

Only issue now is there is no functionality in place to get a custom URL in. I would like to have the following

- Title
- Text description (several paragraphs which can be separated by newline)
**- External link (styled in blue, as already implemented in Consent Sections i.e. Learn More)** 
 - Get Started

I'm almost there but for that external link...

Heres my code atm:

    let instructionStep = ORKInstructionStep(identifier: "IntroStep")
    instructionStep.title = "Welcome"
    instructionStep.text = "Lorem ipsum \n dolor..."
    return instructionStep

Any suggestions?

**Comment by YuanZhu-apple** [comment]
Just handle the learn more action by implementing delegate method `- (void)taskViewController:(ORKTaskViewController *)taskViewController learnMoreForStep:(ORKStepViewController *)stepViewController;` 

And change the learn more button's title by setting `learnMoreButtonTitle` on `ORKStepViewController`. In delegate method: `- (void)taskViewController:(ORKTaskViewController *)taskViewController stepViewControllerWillAppear:(ORKStepViewController *)stepViewController;`
