### ISSUE TITLE
Support default value property for ORKTimeOfDayAnswerFormat and others

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#684]
I'm using an ORKFormItem with an ORKTimeOfDayAnswerFormat.  Would be great if it provides a way to initialize it with a default value, just like other answer formats (i.e. ORKScaleAnswerFormat or ORKDateAnswerFormat).

**Comment by YuanZhu-apple** [comment]
@ninoguba Did you use http://researchkit.org/docs/Classes/ORKTimeOfDayAnswerFormat.html#//api/name/initWithDefaultComponents: ?

**Comment by ninoguba** [comment]
Yes. That only defaults the value for the picker. I'm using this answer
format for a question within ORKFormStep.

On Monday, May 23, 2016, Yuan Zhu <notifications@github.com> wrote:

> @ninoguba <https://github.com/ninoguba> Did you use
> http://researchkit.org/docs/Classes/ORKTimeOfDayAnswerFormat.html#//api/name/initWithDefaultComponents:
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ResearchKit/ResearchKit/issues/684#issuecomment-221133522>
>


-- 
Sent from Gmail Mobile

**Comment by YuanZhu-apple** [comment]
@ninoguba To show default value not only in picker, use http://researchkit.org/docs/Classes/ORKTaskViewController.html#//api/name/defaultResultSource

**Comment by ninoguba** [comment]
That works but a little elaborate just to set default values.  What if the step is first run then an ORKResult instance must be created from scratch.

An easier workaround I implemented is just to use the placeholder property to show the default value, but the user still has to tap on the question to actually set it and once they do, the default value of the picker gets set as the question's value.  This is fine for my needs now.

**Comment by cmetts** [comment]
I agree with ninoguba that defaultResourceSource is too elaborate to set a default value. We need something like the picker supports, but for TextAnswers so that we can set any value we like. I have the same problem in that the default value needs to be based on results that are coming in the current task, not a prior task. Is there any way to do this?

**Comment by YuanZhu-apple** [comment]
@ninoguba, @cmetts 
[ORKTaskResultSource](http://researchkit.org/docs/Protocols/ORKTaskResultSource.html) is the generic way to pre-fill values for all kinds of questions, don't need to build ORKTaskResult, just implement the protocol.

**Comment by cmetts** [comment]
Ah! ok great thanks. I'll give that a try.

**Comment by cmetts** [comment]
I am trying to implement ORKTaskResultSource to provide a default value for a Question that has format:

ORKAnswerFormat *format = [ORKTextAnswerFormat integerAnswerFormatWithUnit:@""];

I am able to do this when using a previously generated ORKStepResult, but I need to be able to create a ORKStepResult programmatically. The code below is the only way I have been able to write it without generating warning in Xcode, but it does not set a default value (no error). Can you please advise me how to get this done?

Thanks


- (nullable ORKStepResult *)stepResultForStepIdentifier:(NSString *)stepIdentifier {

    if ([stepIdentifier isEqualToString:@"demo_mrn"]) {
        
        NSObject *theAnswer = @"31415927";
        
        ORKQuestionResult *theResult = [[ORKQuestionResult alloc] initWithIdentifier:@"demo_mrn"];
        theResult.questionType = ORKQuestionTypeText;
        theResult.answer = theAnswer;
        
        NSArray *resultArray = [NSArray arrayWithObject:theResult];
        
        ORKStepResult *stepResult = [[ORKStepResult alloc] initWithStepIdentifier:@"demo_mrn" results:resultArray];

        return stepResult;
    } else {
        return nil;
    }
}

**Comment by YuanZhu-apple** [comment]
@cmetts `integerAnswerFormatWithUnit:` creates a `ORKNumericAnswerFormat` not a `ORKTextAnswerFormat`. And you should create a [ORKNumericQuestionResult](http://researchkit.org/docs/Classes/ORKNumericQuestionResult.html) to match it.

**Comment by cmetts** [comment]
when I try this:

`
NSInteger theAnswer = 31415927;
ORKNumericQuestionResult *theResult = [[ORKNumericQuestionResult alloc] initWithIdentifier:@"demo_mrn"];
        theResult.answer = theAnswer;
'

I get error that property "answer" is not on ORKNumericQuestionResult.

**Comment by YuanZhu-apple** [comment]
@cmetts 

```
theResult.numericAnswer = @(31415927);
```

**Comment by cmetts** [comment]
thanks, just found that, but thanks for quick response!

**Comment by cmetts** [comment]
bingo! Thanks so much YuanZhu.

Here is complete code for anyone interested:

`- (nullable ORKStepResult *)stepResultForStepIdentifier:(NSString *)stepIdentifier {
    
    if ([stepIdentifier isEqualToString:@"demo_mrn"]) {
        
        //NSInteger theAnswer = (int)31415927;
        
        ORKNumericQuestionResult *theResult = [[ORKNumericQuestionResult alloc] initWithIdentifier:@"demo_mrn"];
        
        theResult.numericAnswer = @(31415927);

        NSArray *resultArray = [NSArray arrayWithObject:theResult];
        
        ORKStepResult *stepResult = [[ORKStepResult alloc] initWithStepIdentifier:@"demo_mrn" results:resultArray];

        return stepResult;
        
    } else {
        return nil;
    }

}
`

**Comment by cmetts** [comment]
I am finding that this method:

- (nullable ORKStepResult *)stepResultForStepIdentifier:(NSString *)stepIdentifier {

Is only only the first time a step is shown. If a user goes back a question or more, it is not run again. If the user took a different path because of branching logic, or responded with different answers, I need to modify the result of the step using this method. I see no way to do this with this only being called the first time the field is shown. 

Are there any ways to achieve this?

**Comment by YuanZhu-apple** [comment]
@cmetts `stepResultForStepIdentifier:` is called when the step is fresh.
After the user has seen the step, an answer has been preserved if user hit `continue` or `back`; 
but `skip` would reset the step back to fresh.

Maybe you can prepare a set steps with different default answer.
