### ISSUE TITLE
Immediately Step

### ISSUE THREAD

**Issue by tonylibra** [ResearchKit/ResearchKit#686]
When I set the optional property in the TextChoiceAnswerFormat step, the immediately step will be triggered automatically, to hope this should not be default. There is a very real world example. If there is a lot of choices, we have to force user to read the all of the choices by scroll to the end of the tableView, and click the next button to next question. If the immediately jump is by default, the user may have no idea there is more choices when scroll down.
Now, I just maintain the my local branch which disabled immediately step. Hope developers in this community could evaluate this issue, and I would like to do the pull request.

**Comment by YuanZhu-apple** [comment]
@tonylibra Quick around:
Subclass `ORKQuestionStep` and override `isFormatImmediateNavigation`.

In the future, we might limit `isFormatImmediateNavigation` to boolean only, what do you think?

**Comment by YushengYang18** [comment]
@YuanZhu-apple 
Yes, I think it is good for me in the future. Thank you very much.

By the way, I just open another issue about StepViewController Text Display. If it is possible, could you please have a look.

**Comment by kelseydedoshka-apple** [comment]
@tonylibra closing this issue as YuanZhu-apple's answer above was sufficient!
