### ISSUE TITLE
Setting "navigationBar.barStyle = .Black" does not work in ORKSample 

### ISSUE THREAD

**Issue by swaffoja** [ResearchKit/ResearchKit#688]
The app I am developing is organized similar to the ORKSample app. I have a ResearchContainerViewController that segues to the appropriate controller when the app loads. I am using the ResearchContainerSegue verbatim.

I want to use a dark navigation bar in my app. Changing the navigation bar style should be as simple as this: 

```
class ActivityViewController: UITableViewController {
    
    // add this method to ActivityViewController in ORKSample to see issue
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // change bar style to dark... Text will appear white. Status bar should also 
        // be white but remains black
        navigationController?.navigationBar.barStyle = .Black
    }
    ...
```

Unfortunately, the status bar text color does not change. I'm guessing that this issue is related to the "ResearchContainerSegue" segue but I haven't been able to figure it out yet.

I understand ORKSample is really just a sample project that isn't intended to be production ready... but does anyone have any thoughts on what to try?

![simulator screen shot may 25 2016 4 35 32 pm](https://cloud.githubusercontent.com/assets/887384/15557217/7d11b114-2297-11e6-92ed-850b9060c079.png)

**Comment by swaffoja** [comment]
The view hierarchy for the ActivityViewController in ORKSample is `ResearchContainerViewController > UITabBarController > UINavigationController > ActivityViewController`. The status bar color (light vs. dark) is managed by the top-most view controller which is ResearchContainerViewController. Setting preferredStatusBarStyle in the ResearchContainerViewController will change the color.

    override func preferredStatusBarStyle() -> UIStatusBarStyle {
        return .LightContent
    }

**Comment by inaldor** [comment]
Saved my life. thank you
