### ISSUE TITLE
Is it possible to programmatically set values to question steps based on answers from other questions appearing before in an ordered task? 

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#689]
I've seen examples where the title of a question step can be changed dynamically at the stepViewControllerWillAppear delegate.  I have a need to set the default value of a scale question based on the answer of another scale question appearing before it.  Any suggestions?

**Comment by bishalg** [comment]
This is tricky one ! 
As we provide the next question based on predicate value and not based on answer value, can't imagine how this would be possible ? Lets hope someone from ResearchKit come up with the solution.

**Comment by YuanZhu-apple** [comment]
@ninoguba,  I can see @bishalg's idea works  
> use `ORKNavigableOrderedTask` to provide the next question based on user's answer

**Comment by ninoguba** [comment]
But that only makes it possible to redirect to another step with its questions already defined.  What I'm asking is to actually redefine certain questions with a default value using answers from a previous step/question.

For example,

Step 1:
Question:  How are you feeling on a scale of 1 - 10?
Answer: 5

Step 2:
Some video here or a custom activity

Step 3:
Question:  How are you feeling now, on a scale of 1 - 10?  Default value should be 5 (based on answer on Step 1)
Answer: ?

The purpose of this to have some form of benchmarking.  We like them to see how they felt better or worse after the interim activity.

**Comment by YuanZhu-apple** [comment]
### Solution 1

Use just one question step, and modify it in the run time.

Use `http://researchkit.org/docs/Classes/ORKTaskViewController.html#//api/name/defaultResultSource`
And modify it change the default value on scale.

For the question text, you can also modify it in the run time:(http://researchkit.org/docs/Classes/ORKStep.html#//api/name/text).

### Solution 2
1. Subclass `ORKOrderedTask`
2. Override `stepAfterStep` [http://researchkit.org/docs/Protocols/ORKTask.html#//api/name/stepAfterStep:withResult:]

Each time provide a new question step with your desire question and default value.
Call super to handle other steps.

**Comment by ninoguba** [comment]
Solution 2 looks good. Thanks!
