### ISSUE TITLE
Change the "Cancel" action text on ORKTaskViewController

### ISSUE THREAD

**Issue by bishalg** [ResearchKit/ResearchKit#690]
Right now ORKTaskViewController shows "_End Task_" for _Cancel_ action.

![simulator screen shot may 27 2016 11 25 12 am](https://cloud.githubusercontent.com/assets/805689/15598844/e5fb2446-23fd-11e6-998f-c9eb94d8e7e0.png)

On Line 1130 

https://github.com/ResearchKit/ResearchKit/blob/9f5caad71d474af0014ff4885ee3292fe7434e24/ResearchKit/Common/ORKTaskViewController.m

`NSString *discardTitle = saveable? ORKLocalizedString(@"BUTTON_OPTION_DISCARD", nil) : ORKLocalizedString(@"BUTTON_OPTION_STOP_TASK", nil);
`  
It uses `BUTTON_OPTION_STOP_TASK` how do we change this text ? 
_Task_ is rather a technical term, hence i need to show different message for different survey question types.

**Comment by YuanZhu-apple** [comment]
@bishalg If you don't care about `save and restore`, you can set your own `cancelButtonItem` on `ORKStepViewController` and implement a custom action handler.

**Comment by kelseydedoshka-apple** [comment]
@bishalg did @YuanZhu-apple 's answer above help resolve your issue or do you still need assistance here?

**Comment by bishalg** [comment]
@kelseydedoshka-apple  - it works ! 
Thanks @YuanZhu-apple 👍
