### ISSUE TITLE
Pie chart layout layers crash

### ISSUE THREAD

**Issue by sukh-cohaesus** [ResearchKit/ResearchKit#691]
Hello

I'm having a weird crash with the Pie chart data source. The error is

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'`

Which is being thrown within at

`CAShapeLayer *segmentLayer = _segmentLayers[idx];`

within this method of `ORKPieChartPieView` class

```
- (void)layoutPieChartLayers {
    NSInteger numberOfSegments = [_parentPieChartView.dataSource numberOfSegmentsInPieChartView:_parentPieChartView];
    for (NSInteger idx = 0; idx < numberOfSegments; idx++) {
        CAShapeLayer *segmentLayer = _segmentLayers[idx];
        segmentLayer.frame = _circleLayer.bounds;
        segmentLayer.path = _circleLayer.path;
        segmentLayer.lineWidth = _circleLayer.lineWidth;
    }
}
```

Here's my code

```
    class PieChartDataSource: NSObject, ORKPieChartViewDataSource {

        private let pieColors = [
            UIColor.greenColor(),
            UIColor.grayColor(),
        ]
        private var pieValues = [Double]()

        override init() {
            super.init()
            
            HealthKitManager.sharedInstance.getHealthAuthorization() { succeeded, error in
                guard succeeded else {
                    print(error!.description)
                    return
                }
                
                self.getData()
            }
            
        }
        
        func getData() {
            
            HealthKitManager.sharedInstance.queryDailySteps() { result, error in
                
                let max: Double = 100 // 100%
                let steps: Double = (max / 10000) * result!
                let remaining = steps < max ? max - steps : 0
                if steps != 0 {
                    self.pieValues = [steps, remaining]
                } else {
                    self.pieValues = [remaining]
                }
            }
        }
        
        func numberOfSegmentsInPieChartView(pieChartView: ORKPieChartView ) -> Int {
            return pieValues.count
        }
        
        func pieChartView(pieChartView: ORKPieChartView, valueForSegmentAtIndex index: Int) -> CGFloat {
            if pieValues.count > index {
                return CGFloat(pieValues[index])
            } else {
                return 0
            }
        }
        
        func pieChartView(pieChartView: ORKPieChartView, colorForSegmentAtIndex index: Int) -> UIColor {
            return pieColors[index]
        }
    }
```

Any thoughts?

**Comment by sukh-cohaesus** [comment]
Seems like the `pieValues.count` within `numberOfSegmentsInPieChartView` is returning zero multiple times first and then right at the end returns 2...guessing this is where the issue / crash is happening. 

Question: Is there away for me to control this as I believe this is due to the query I'm running in a background thread for the HealthKit steps...

If you require any further code / info please let me know.

**Comment by rsanchezsaezsc** [comment]
Could you upload a minimum project exhibiting the problem?

**Comment by rsanchezsaez** [comment]
Could you upload a minimum project exhibiting the problem?

**Comment by sukh-cohaesus** [comment]
Think I've resolve this... @rsanchezsaez Thanks for getting in touch, I'll re open this and supply a code sample if this appears again.

**Comment by rsanchezsaez** [comment]
@sukh-cohaesus If you could still provide an easy way to reproduce this, I'd be interested in fixing this edge case on `ORKPieChartPieView` so it doesn't crash.

**Comment by sukh-cohaesus** [comment]
@rsanchezsaez Sure will do mate...give me few days to get over the launch and I'll see if I can get a small project for you :)

**Comment by rsanchezsaez** [comment]
@sukh-cohaesus Any news on this?

**Comment by p2** [comment]
I am running into the same issue and I think this crash happens if at least one segment returns zero. This is done when initializing the pie chart in `ORKPieChartPieView.m:147`:

```objc
- (void)updatePieLayers {
    [_segmentLayers makeObjectsPerformSelector:@selector(removeFromSuperlayer)];
    [_segmentLayers removeAllObjects];
    ...
    NSInteger numberOfSegments = [_parentPieChartView.dataSource numberOfSegmentsInPieChartView:_parentPieChartView];
    for (NSInteger idx = 0; idx < numberOfSegments; idx++) {
        CAShapeLayer *segmentLayer = [CAShapeLayer layer];
        ...        
        if (value != 0) {
            ...
            [_segmentLayers addObject:segmentLayer];
        }
    }
}
```

It doesn't add the layer to the array if the segment's value is zero. But then in `ORKPieChartPieView.m:235`:

```objc
- (void)layoutPieChartLayers {
    NSInteger numberOfSegments = [_parentPieChartView.dataSource numberOfSegmentsInPieChartView:_parentPieChartView];
    for (NSInteger idx = 0; idx < numberOfSegments; idx++) {
        CAShapeLayer *segmentLayer = _segmentLayers[idx];
        ...
    }
}
```

It accesses one `_segmentLayers` item for every segment, as returned by dataSource's `numberOfSegmentsInPieChartView:`, without checking whether that value is zero. I think this could be responsible for the crash described here, at least in my case the crash disappears when I never return zero from `pieChartView(pieChartView:valueForSegmentAtIndex:)`.
