### ISSUE TITLE
Boolean validation on selection

### ISSUE THREAD

**Issue by sukh-cohaesus** [ResearchKit/ResearchKit#697]
Hello

Not sure if this is an issue or more a feature request. I have an eligibility form (using ORKForm) where I have text and couple of boolean question types.

For the text I can apply validation easily using `textAnswerFormatWithValidationRegex` and this shows a nice alert when validation fails.

However for the boolean types `ORKBooleanAnswerFormat` I can't seem to see anywhere that would allow me to apply validation immediately or when the user attempts to go to the next screen. Only way I can do this is right at the end of the `ORKOrderedTask` where I can check this value - but this is quite late as I have the `ConsentDocument` here too...

Any ideas? :)

**Comment by YuanZhu-apple** [comment]
@sukh-cohaesus Implement this delegate to prevent proceeding and throw alert.

```
/**
 Asks the delegate if the task view controller should proceed to the specified step.
 
 The task view controller calls this method before creating a step view
 controller for the next or previous step.
 
 Generally, when a step is available, the task view controller presents it when
 the user taps a forward or backward navigation button, but the results entered or other circumstances can make this action inappropriate. In these
 circumstances, you can implement this delegate method and return `NO`.
 
 If you return `NO`, it's often appropriate to present a dialog or take
 some other UI action to explain why navigation was denied.
 
 @param taskViewController  The calling `ORKTaskViewController` instance.
 @param step                The step for which presentation is requested.
 
 @return `YES` if navigation should proceed to the specified step; `NO` if navigation should not proceed.
 */
- (BOOL)taskViewController:(ORKTaskViewController *)taskViewController shouldPresentStep:(ORKStep *)step;
```

**Comment by sukh-cohaesus** [comment]
Perfect thank you.
