### ISSUE TITLE
Remove ork_firstResponderView and track current cell directly

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#70]
On review of the recent ork_firstResponderView change, we feel it's not necessary to have this hack to get the first responder. Instead, the table view container should track the currently active cell via a delegate relationship.

**Comment by rsanchezsaez** [comment]
Note: relevant change introduced in [merge #32](https://github.com/ResearchKit/ResearchKit/pull/32).

**Comment by rsanchezsaez** [comment]
Attempt to fix this at [pull request #83](https://github.com/ResearchKit/ResearchKit/pull/83). See the description for details.

**Comment by jwe-apple** [comment]
@rsanchezsaez merge #32 didn't introduce it, it just renamed it.

**Comment by jwe-apple** [comment]
Change verified. Closing.
