### ISSUE TITLE
Getting "No output directory..." error message with ORKImageCaptureStep

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#700]
Read through the docs and used the same code in ORKCatalog to add the ORKImageCaptureStep to my ORKOrderedTask and I didnt see anywhere that I need to set an output directory explicitly.  When I tap on the Capture Image button I get this message:

"No output directory was specified for captured images."

Did I miss anything here? How should I specify the output directory?

**Comment by brucehappy** [comment]
You'll need to set the ``outputDirectory`` property on the ``ORKTaskViewController``.  This happens in ``ORKCatalog`` when the ``ORKTaskViewController`` is created.
https://github.com/ResearchKit/ResearchKit/blob/master/samples/ORKCatalog/ORKCatalog/Tasks/TaskListViewController.swift#L109

**Comment by ninoguba** [comment]
@brucehappy Thank you for pointing what I missed!
