### ISSUE TITLE
HealthKit access screen does not disappear

### ISSUE THREAD

**Issue by ghost** [ResearchKit/ResearchKit#703]
This appears to be more a HealthKit issue than a ResearchKit issue - feel free to let me know if this is the wrong place and I'll close accordingly.

For reference and to avoid me duplicating myself, I've got a StackOverflow post:

http://stackoverflow.com/questions/37658129/strange-healthkit-access-issue

Any thoughts? Seems like a big issue which can also be replicated on multiple devices on the ORKSample app.

**Comment by YuanZhu-apple** [comment]
@sukh-cohaesus Can you file a bug with bugreport.apple.com?
