### ISSUE TITLE
ORKSample: No such module 'ResearchKit'

### ISSUE THREAD

**Issue by malhal** [ResearchKit/ResearchKit#704]
Hi there, just trying out the project and I noticed the ORKSample project doesn't build, fails with No such module 'ResearchKit'. Then I noticed the sample is designed to link to a pre-built version of the framework which isn't included, hence it's in red. I prefer to build against a live version of the framework code, to do that the fix is in the ORKSample project or target build settings, enter this for the Framework Search Paths:

`../../build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)`

which translates into:

Debug: ../../build/Debug-iphoneos
Release: ../../build/Release-iphoneos 

Which is the correct relative path from the sample to where the ResearchKit framework gets built to.

With this modification now the project can be set up with a dependency on the ResearchKit project and find the framework that is built, and uses the correct Debug/Release version too. To make it work the red version of the framework needs removed from dependencies, linked and embedded. Then drag the ResearchKit project into the ORKSample, add ResearchKit sub-project's framework product as an embedded framework on the General tab in the ORKSample and it should automatically be added to everything required in build phases. Now it will successfully build without displaying the no such module error.

Please let me know if there is a good reason for doing it the first way thanks.

**Comment by jp-gorman** [comment]
I've just noticed the same, mind you I'm new to OSX10/IOS8, but I would have thought a demo framework would build out of the box with the sample. Is there something fundamental both of us are missing ? Why no comment on something so fundamental since June ? @malhal Did you get any closure on this outside of this defect? I reviewed some of the other apps on the Framework and similar issues there (mPower etc.) - Assuming for now it's a noob issues for me on OSX.

**Comment by malhal** [comment]
Haven't been able to test this again, this project now requires Xcode 8 because of the CAAnimationDelegate and for some reason my install has no simulators and I can't add any new ones because the create button in the form doesn't work.

**Comment by markmalone** [comment]
Thanks! Having to manually update the path is making simple build for first-timers harder than it should be.

**Comment by kelseydedoshka-apple** [comment]
@malhal - I am no longer seeing the issue on the latest stable, therefore closing this. Feel free to re-open the issue if you are still having difficulties.

**Comment by ryanoboril** [comment]
Issue is still present on stable branch.  Is it required to download research kit separately and manually link it?

**Comment by rsanchezsaez** [comment]
@ryanoboril Can you upload a sample project exhibiting the issue, and provide detailed instructions on how you reached that state?

I've tried several ways of creating a new *ResearchKit* project, and I've never experienced this issue.

**Comment by ryanoboril** [comment]
@rsanchezsaez I stand corrected, this is an issue with the OCKSample project, not the ORKSample project.  The OP's issue was exactly what I was experiencing with the CareKit sample project, I didn't realize this was the ResearchKit issues page.  

Sorry about that!  :-)

**Comment by SBlincov** [comment]
I I just encountered this problem and found solution! Firstly, after starting the project in xcode (ORKSample), you need to select a team in the project settings. Next, you need to give a unique bundle identifier. After, you need to transfer the project file ResearchKit.xcodeproj (it's in the root of the repository) to the project you just opened. How to do this is written in the readme. After these steps, the error disappears and the application can be launched on the emulator or device.

**Comment by JamMaster1999** [comment]
This problem exists again in the ResearchKit 2.1 release. 
I'm very new to this framework/Xcode, could someone please explain how to fix the (no such module 'researchkit').
I checked that I already have the framework added to both the project, and the target (in this case ORKSample, but the problem persists for all the .xcodeproj files on GitHub repos).
@SBlincov Do you think you can explain again more thoroughly(for a beginner) how to fix the issue please? Thank you
