### ISSUE TITLE
ORKSample: Blank white screen after dismissing Notification Center

### ISSUE THREAD

**Issue by malhal** [ResearchKit/ResearchKit#705]
Blank white screen after dismissing Notification Center or Control Center. Possibily similar to #694

Run the app, use Touch ID, on Activities tab, bring down NC, slide up NC, blank white screen.

**Comment by ninoguba** [comment]
I think it is exactly the same root cause as #694.

**Comment by malhal** [comment]
Yep this bug looks like it is caused by the application delegate method used for resuming, applicationWillEnterForeground won't get called when the application activates from NC.
