### ISSUE TITLE
Update to support iOS 10 SDK HealthKit API changes

### ISSUE THREAD

**Issue by king7532** [ResearchKit/ResearchKit#713]
ResearchKit framework fails to build using Xcode 8 and the iOS 10 SDK in [`ORKHealthQuantityTypeRecorder.m:131`](https://github.com/ResearchKit/ResearchKit/blob/9f5caad71d474af0014ff4885ee3292fe7434e24/ResearchKit/ActiveTasks/ORKHealthQuantityTypeRecorder.m#L131) because the following HealthKit API has been removed:

`-[HKAnchoredObjectQuery initWithType:predicate:anchor:limit:completionHandler:]`

See the [HealthKit Changes for Objective-C in iOS 10.0 API Diffs](https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Objective-C/HealthKit.html)

Instead it has been replaced with:

``` objc
- (instancetype)initWithType:(HKSampleType *)type
                   predicate:(nullable NSPredicate *)predicate
                      anchor:(nullable HKQueryAnchor *)anchor
                       limit:(NSUInteger)limit
              resultsHandler:(void(^)(HKAnchoredObjectQuery *query, NSArray<__kindof HKSample *> * _Nullable sampleObjects, NSArray<HKDeletedObject *> * _Nullable deletedObjects, HKQueryAnchor * _Nullable newAnchor, NSError * _Nullable error))handler HK_AVAILABLE_IOS_WATCHOS(9_0, 2_0);
```

**Comment by king7532** [comment]
The above pull request 710 aleady implements the changes.

**Comment by YuanZhu-apple** [comment]
@king7532 I'd like to keep `master` as it is until we full embrace XCode8 GM. For now, the xcode8 branch is availble to use.

**Comment by umerkhan-apple** [comment]
Merged!
