### ISSUE TITLE
[iPad] Make HealthKit optional

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#73]
HealthKit is not available on iPad. Make HealthKit optional in ResearchKit by making all use of HealthKit features conditional on HealthKit framework being present.

**Comment by rsanchezsaez** [comment]
Could you detail a bit what does this issue involve?

Currently, HealthKit just gives a *Health data is unavailable on this device* error when trying to authorize, which at first sight looks semi-reasonable: it's the same behaviour as if the participant denies HealthKit access to the research app.

Or do you want to make the HK related classes unavailable on the iPad?

**Comment by jwe-apple** [comment]
Hmm, looks like this has already been fixed. We used to see crashes when trying to access HealthKit.

**Comment by kristofer** [comment]
wait no, I'd like to use researchkit to collect data that is not health related.
I just want to use the wizard capability and then handle the data myself. I'm not asking health questions.
