### ISSUE TITLE
[iPad] Pickers are not aligned properly on iPad

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#75]
It happens on all kinds of pickers: `date`, `time`, `timeInterval`, and `choice`.
The pickers should align to the center of the screen.

![screen shot 2015-04-21 at 15 53 49](https://cloud.githubusercontent.com/assets/11575859/7264260/a5597b0a-e83e-11e4-8340-cc3832b7427f.png)

**Comment by rsanchezsaez** [comment]
Pull request submitted.
