### ISSUE TITLE
Is it possible to reinitialize step when it is shown?

### ISSUE THREAD

**Issue by sandroeiler** [ResearchKit/ResearchKit#750]
I am stuck with following problem, I hope you can help me.

I want to set the 'minimum date' of my current steps' datepicker to 1 day after the selected day of the previous step. As it seems for me that predicates won't help me, does anyone have an idea how this could be done?
I would try with updating my Step or FormItem through **ORKTaskViewControllerDelegate** method _taskViewController(taskViewController:ORKTaskViewController, didChangeResult:ORKTaskResult)_ but don't see any way to reinitialize the next step.

Additionally would that be possible for several FormItems in one step? If I set the date in datepicker1, can the minimum date in datepicker2 be updated?

**Comment by YuanZhu-apple** [comment]
I think you can  Subclass `ORKDateAnswerFormat` and override `minimumDate`. Create your own method to make `minimumDate` settable.

**Comment by sandroeiler** [comment]
Thanks a lot!!! Worked for me like you said.
My subclass for ORKDateAnswerFormat looks like this:
```
import Foundation
import ResearchKit

class Custom_Date_Answer_Format: ORKDateAnswerFormat {
  
  var Minimum_Date = NSDate()
  
  override var minimumDate: NSDate? {
      get {
          return Minimum_Date
      }
      set {
          if newValue! is NSDate {
              Minimum_Date = newValue! as NSDate
        } else {
            print("We have a problem here...")
        }
      }
    }
  
    func Set_Minimum_Date ( minimumDate: NSDate ) {
        self.Minimum_Date = minimumDate
    }
  }
```
