### ISSUE TITLE
[iPad] Visual metrics for iPad

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#76]
- Add `ORKScreenTypeiPad` and create visual metrics for iPad in `ORKSkin`.
Make UI elements on iPad not stay on the top and leave bottom half empty. Instead, make the vertical alignment more vertically centered, like in the initial setup of a new iPad

![img_0005](https://cloud.githubusercontent.com/assets/11575859/7264342/6d0da5b8-e83f-11e4-9177-bc090a2b0298.PNG)

![img_0003](https://cloud.githubusercontent.com/assets/11575859/7264295/0a6a71a2-e83f-11e4-81b7-cafc07441b7c.PNG)

- The size of the consent signature area needs to be adjusted.  It would look better if we increase the height and reduce the width of this area on both iPad and iPhone 6+.

![screen shot 2015-04-21 at 16 00 26](https://cloud.githubusercontent.com/assets/11575859/7264362/8ee850fc-e83f-11e4-9e87-dedf8a890e39.png)

**Comment by rsanchezsaez** [comment]
In progress.

**Comment by jwe-apple** [comment]
If we need different metrics for the 6+, then yes. The original specs had 6+ metrics the same as the 6, but there is some scope to change that.

**Comment by rsanchezsaez** [comment]
I made the following iPad adjustments:
- modify ORKScreenMetricTopToCaptionBaseline to be similar to the *initial setup screen top to title baseline* height
- add ORKScreenMetricTopToIllustration which adds a margin on top of the consent images (also similar to the one on intro images)

I didn't modify any iPad font sizes, but that's a possibility now.

It could be that after adding the top and side margins, the changes on [issue #78](https://github.com/ResearchKit/ResearchKit/issues/78) make the visual consent images a tad too big on iPad. I guess designers will have to have a look just in case.

**Comment by jwe-apple** [comment]
Happy with this to start with. I'll be raising separate issues for the remainder.
