### ISSUE TITLE
Is predicateForChoiceQuestionResultWithResultSelector:resultSelector matchingPatterns:patterns superfluous?

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#760]
Hi,

Just building a test suite for the Predicates (PR incoming; the idea is that it will ensure we have robust testing for Predicate changes per the PR I've submitted and the one in progress to tidy the syntaxes for Swift and Obj C).

In the current code there is the option to provide an array of patterns. However, I wonder looking at the documentation whether this is superfluous because I think you can join multiple patterns using the | indicator. Is that correct, and if so can it be deprecated / removed? Or is there a circumstance where having the additional call is useful?

**Comment by umerkhan-apple** [comment]
Merged!
