### ISSUE TITLE
Choice predicate match - bug or misinterpretation?

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#761]
Hi,

Ongoing work on extending the ORKTest suite to run a full set of tests on Predicates.

I was checking out the Predicate match syntax. Not sure if my understanding is wrong, or if there is an issue with the predicate.

Below is the code snippet of the ORKForm. The idea is simple - you get given a single choice list, and you're asked to click on a word which contains Cat. The Predicate is asking to match Cat*.

For some reason, I'm only getting a pass if you choose 'Cat'; yet I had expected that the \* should mean you also get passes for Cathedral or Catheter.

Have I missed something here? Or has the testing been useful!!!

Best wishes,

Andrew

```
    //  Test expected multiple choices
    {
        ORKAnswerFormat *answer = [ORKAnswerFormat choiceAnswerFormatWithStyle:ORKChoiceAnswerStyleSingleChoice textChoices:[NSArray arrayWithObjects:@"Cat",@"Catheter", @"Cathedral",@"Dog", nil]];
        ORKQuestionStep *step = [ORKQuestionStep questionStepWithIdentifier:@"question_04"
                                                                      title:@"Choose a word which contains the word 'Cat'?"
                                                                     answer:answer];
        step.optional = NO;
        [steps addObject:step];
    }

    {
        // If we answer 'Yes' to Question 4, then proceed to the pass screen
        ORKResultSelector *resultSelector = [ORKResultSelector selectorWithResultIdentifier:@"question_04"];
        NSPredicate *predicateQuestion = [ORKResultPredicate predicateForChoiceQuestionResultWithResultSelector:resultSelector matchingPattern:@"Cat*"];

        ORKPredicateStepNavigationRule *predicateRule = [[ORKPredicateStepNavigationRule alloc] initWithResultPredicates:@[predicateQuestion]
                                                                                              destinationStepIdentifiers:@[@"question_04_pass"]];
        [task setNavigationRule:predicateRule forTriggerStepIdentifier:@"question_04"];
    }
```

**Comment by md0u80c9** [comment]
I had similar troubles with a string predicate - to try to match the string *og. I'm not sure whether this is the way I'm using the predicate, or whether this is an issue with the generation of predicates using match.

I've uploaded the predicate tests as a PR, disabling question_07, which is a match test which causes a sigAbt.

The PredicateTests PR basically runs through a set of different questions, each assigned a predicate, to check the various functions.

**Comment by md0u80c9** [comment]
@rsanchezsaez - was the original predicate work yours? Could you have a quick look at these tests and see what you make of the 'match' code? I've had a further look at this today and I can't seem to get test 4 to match all instances which begin with Cat; and test 7 still SigAbts.

**Comment by umerkhan-apple** [comment]
@rsanchezsaez Friendly ping! :)

**Comment by rsanchezsaez** [comment]
We figured the problem out in [these PR comments](https://github.com/ResearchKit/ResearchKit/pull/763#pullrequestreview-8339487):

> These patterns use the same format accepted by `NSRegularExpression` (see [here](https://www.raywenderlich.com/30288/nsregularexpression-tutorial-and-cheat-sheet) for more info).
> 
> Hence, the proper expression is: `Cat.*`.
> 
> `.` means _any character_, and `*` mans _the previous character repeated 0 or more times_. 
> 
> (...)
> 
> Same as above, the correct pattern is `.*og` rather than `*og`.
> 
> `*og` is an invalid regular expression because there no character preceding the `*` symbol. :)

**Comment by umerkhan-apple** [comment]
Sounds good. Closing issue for now.
