### ISSUE TITLE
Invalid format in AX_GRAPH_POINT_%@ for Russian localization

### ISSUE THREAD

**Issue by rliljest** [ResearchKit/ResearchKit#765]
The current value of "AX_GRAPH_POINT_%@" in Localized/ru.lproj is "Точка: %d" which is almost certainly incorrect. Every other localized value has a %@ format specification, not %d

**Comment by umerkhan-apple** [comment]
@rliljest Would you be able to provide a PR with the fix?

**Comment by stevebaranski** [comment]
It appears that this issue is eligible for closure, as it was resolved as suggested via [this commit](https://github.com/ResearchKit/ResearchKit/commit/e52e22e8f541311080ae3658beb0b88a5c3bdcba#diff-67301cb2c9c0b9f4e07b69a4c1a50b45R556).

**Comment by rsanchezsaez** [comment]
Thanks for helping in cleaning old invalid bugs!
