### ISSUE TITLE
ORKGraphChartView crashes without datasource

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#766]
It may happen that an `ORKGraphChartView` sees its first layout before a data source has been assigned. The [`numberOfPlots`](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Charts/ORKGraphChartView.m#L582) method returns **1** by default, when it's called in the `layoutSubviews` » `updateYAxisPoints` methods this leads to a crash.

The default `numberOfPlots` should be **0** to avoid this crash.

This is somewhat related to #691 .

**Comment by p2** [comment]
Following up, documentation of `- (NSInteger)numberOfPlotsInGraphChartView:(ORKGraphChartView *)graphChartView` says that **1 plot** is assumed if that method is not implemented. So to prevent this crash, the internal methods could do index range checking before accessing array members.

**Comment by umerkhan-apple** [comment]
Fix merged!
