### ISSUE TITLE
Layout issue for inputs in ORKTaskView

### ISSUE THREAD

**Issue by Geosef** [ResearchKit/ResearchKit#774]
My team and I noticed issues with the layout of ORKTasks within ORKTaskViews in both sliders and text inputs. We have not tried other inputs to verify if they are affected or not.
<hr />
This is text input prior to being tapped in the field:
![screen shot 2016-08-01 at 3 02 27 pm](https://cloud.githubusercontent.com/assets/5271942/17307128/27b84fec-57f9-11e6-8134-13b2d8ae75cb.png)
<hr />
Once tapped for input, the field and title both shrink: 
![screen shot 2016-08-01 at 3 02 37 pm](https://cloud.githubusercontent.com/assets/5271942/17307127/27b77c0c-57f9-11e6-8910-44523bc42f95.png)
The placeholder text is cut off already.
<hr />
This is after "12" has been entered:
![screen shot 2016-08-01 at 3 02 49 pm](https://cloud.githubusercontent.com/assets/5271942/17307126/27b4df1a-57f9-11e6-8dab-e51d348035b9.png)
The field is so small you cannot see any input and the title is also cut off.
<hr />
And after a medium length string of numbers:
![screen shot 2016-08-01 at 3 02 55 pm](https://cloud.githubusercontent.com/assets/5271942/17307129/27b8edb2-57f9-11e6-9368-81bed5a8cf8a.png)
The title has reappeared, but the first few characters of the input are still cut off.
<hr />
This is a slider with very short descriptions for min/max:
![screen shot 2016-08-01 at 3 08 56 pm](https://cloud.githubusercontent.com/assets/5271942/17307306/09a608cc-57fa-11e6-82ed-74c3ab777f22.png)
<hr />
This is the same slider after being tapped for input:
![screen shot 2016-08-01 at 3 09 10 pm](https://cloud.githubusercontent.com/assets/5271942/17307327/213ce744-57fa-11e6-94a2-ce6e94a61bd8.png)
The slider is so small you can't change the value.
<hr />
Finally, a slider with really long descriptions:
![screen shot 2016-08-01 at 3 09 24 pm](https://cloud.githubusercontent.com/assets/5271942/17307356/48d534fa-57fa-11e6-89ca-7632cebb0538.png)
<hr />

We believe a minimum width should be in place to handle text input and short descriptions on sliders. It may also be worthwhile looking into other inputs and seeing how they are affected.

**Comment by YuanZhu-apple** [comment]
@Geosef Assume you had some customization, can I see them in some sample code?

**Comment by Geosef** [comment]
I'm using the ORKTaskViewController a part of the Symptom tab in CareKit, per the CareKit sample application.

In the view controller for the tab view (named OverviewViewController in the code), I've added extensions for delegates for the symptom tracker and the task view. 

```
extension OverviewViewController: OCKSymptomTrackerViewControllerDelegate {
	func symptomTrackerViewController(_ viewController: OCKSymptomTrackerViewController, didSelectRowWithAssessmentEvent assessmentEvent: OCKCarePlanEvent) {
		
		
		// Lookup the assessment the row represents.
		guard let activityType = ActivityType(rawValue: assessmentEvent.activity.identifier) else { return }
		guard let sampleAssessment = sampleData.activityWithType(type: activityType) as? Assessment else { return }
		/*
		Check if we should show a task for the selected assessment event
		based on its state.
		*/
		guard assessmentEvent.state == .initial ||
			assessmentEvent.state == .notCompleted ||
			(assessmentEvent.state == .completed && assessmentEvent.activity.resultResettable) else { return }
		
		// Show an `ORKTaskViewController` for the assessment's task.
		let taskViewController = ORKTaskViewController(task: sampleAssessment.task(), taskRun: nil)
		taskViewController.delegate = self
		
		symptomTrackerNavController.pushViewController(taskViewController, animated: true)
		
	}
}

extension OverviewViewController: ORKTaskViewControllerDelegate {
	func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: NSError?) {
				
		guard reason == .completed else { return }
		guard let event = symptomTrackerViewController.lastSelectedAssessmentEvent,
			activityType = ActivityType(rawValue: event.activity.identifier),
			sampleAssessment = sampleData.activityWithType(type: activityType) as? Assessment else {return}
		
		let carePlanResult = sampleAssessment.buildResultForCarePlanEvent(event, taskResult: taskViewController.result)
		
		symptomTrackerViewController.store.update(event, with: carePlanResult, state: .completed) { (success, _, error) in
			if !success {
				print(error)
			}
		}
		
		symptomTrackerNavController.popViewController(animated: true)
	}

}
```

This is the only reference to the ORKTaskView in our app. No attempts for customization.

**Comment by YuanZhu-apple** [comment]
@Geosef `taskViewController` is supposed to be presented, instead of being pushed.

**Comment by Geosef** [comment]
We have changed `taskViewController` to now be presented/dismissed, rather than pushed/popped; however, this did not affect the layout issue.

**Comment by YuanZhu-apple** [comment]
@Geosef That's weird. 
Are you using ResearchKit master or stable releases? 
Can you reproduce that in any of the ResearchKit sample/test apps?

**Comment by Geosef** [comment]
@YuanZhu-apple We are using 1.3.1 via CocoaPods. I could not reproduce the issue in either the ResearchKit sample app nor the CareKit sample app; however, our project is in iOS10 which could result in autolayout issues that I'm not 100% aware of. I tried converting the CareKit sample app to Swift 3/iOS 10, but it wasn't playing nice so I really couldn't test it.

**Comment by Geosef** [comment]
@YuanZhu-apple any update?

**Comment by YuanZhu-apple** [comment]
@Geosef ResearchKit is not officially support iOS 10 yet. 

1) you can try the branch: https://github.com/ResearchKit/ResearchKit/tree/stable_xcode80_candidate
2) If you don't mind, please share a minimum iOS 10 project using RK 1.3.1, I can try to play it.

**Comment by Geosef** [comment]
@YuanZhu-apple We tried using both the CareKit and ResearchKit 'stable_xcode80_candidate' branches to no avail. We were able to reproduce the issue in a minimum project and have attached it.

[CKRKDemo.zip](https://github.com/ResearchKit/ResearchKit/files/421316/CKRKDemo.zip)

**Comment by Geosef** [comment]
@YuanZhu-apple any update?

**Comment by YuanZhu-apple** [comment]
@Geosef I confirm that this is an issue. 
Caused by
https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKVerticalContainerView.m#L655
It get fixed, once I change it to `UILayoutPriorityDefaultHigh`.

Can you verify that, and make a pull request for me?
