### ISSUE TITLE
[iPad] Make visual assets bigger on iPad

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#78]
In active tasks and consent the visual assets look a bit small. Experiment with whether the @3x assets could be repurposed at @2x for iPad to get 150% size increase. Also adjust RKSkin layout metrics to match, if necessary.

Example:
![img_0005](https://cloud.githubusercontent.com/assets/11575859/7264481/bed2f51e-e840-11e4-9499-af9cb4f4fc5b.PNG)

**Comment by brucehappy** [comment]
Submitted PR #107 for this one.  I know that #76 collides with this as noted in the PR.

@jwe-apple is this what you were after?
![ios simulator screen shot apr 24 2015 7 41 29 pm](https://cloud.githubusercontent.com/assets/5296062/7330321/8b45ba02-eaba-11e4-8eca-16eb2079c72b.png)

**Comment by brucehappy** [comment]
Oh, and do note that I didn't create any new assets for iPad 1x, so its just scaling down the 2x, which does lead to slightly pixelated images, which can be noticeable after each consent animation finishes and the image replaces it.

**Comment by jwe-apple** [comment]
Yep, good first pass.
