### ISSUE TITLE
Range of Motion Active Tasks

### ISSUE THREAD

**Issue by darrenlevy** [ResearchKit/ResearchKit#781]
Assignee: @darrenlevy
## Milestone

Build two Range of Motion Active Tasks for ResearchKit. I will create a task for measuring the knee’s range of motion and another for the shoulder. It will be extendable, so tasks measuring other joints can easily be added.
## Description

A goniometer is typically used by doctors to measure patients’ range of motion. Thanks to ResearchKit’s Device Motion Recorder Configuration we can get this measurement without a goniometer. By placing your iPhone right on your joints’ access of rotation we can get a range of motion. Over time, patients, doctors and researchers will be able to see how flexibility improves.
The patient will be instructed how to place their phone in the proper position and receive instructions on how to move their joint.
A new results class will also be created to handle the different measurements to send to the server.

**Comment by umerkhan-apple** [comment]
Merged!
