### ISSUE TITLE
Extending consent document rendering

### ISSUE THREAD

**Issue by chrisortman** [ResearchKit/ResearchKit#783]
Hi, I am trying to figure out how to customize the footer of each page of the consent document when it is rendered to PDF (our IRB is requiring us to include some information on every page of the consent document)

I first thought I could do it by customizing the HTML but the problem there is I have no idea where the page breaks will be

Then I thought I would try subclassing ORKHTMLPDFWriter and ORKHTMLPDFPageRenderer but the compiler didn't think either of those classes existed (I'm in swift, and I don't know how to tell if they're supposed to be private or they are just not exposed. I'm also using cocoa pods so maybe it's a problem with the podspec?)

Then I thought I would try to just build my own PDF writer, but that is going to result in a lot of duplication. Is there a better way that I'm missing? If not can we discuss changes that I could make (and submit a PR for) to allow some flexibility?

**Comment by chrisortman** [comment]
As a possible means of extension I was thinking something like this

https://github.com/chrisortman/ResearchKit/commit/421d7d7c921a9c7b22226aac911ea9af86265ce9

What do you thing?

**Comment by YuanZhu-apple** [comment]
@chrisortman I think the quick work around is to [swizzle](http://nshipster.com/method-swizzling/) `- (void)drawFooterForPageAtIndex:(NSInteger)pageIndex inRect:(CGRect)footerRect {`

Long term, would it be easier to just pass in the desired the foot text? Then `ORKHTMLPDFWriter ` can adjust the size of page content with the footer's size.

**Comment by chrisortman** [comment]
In my case I needed it in the header and drawn with a gray background. I
don't know if every irb will require something like this? How would you
decide what font/size to use? Would you be able to calculate size for
multiple lines?

**Comment by YuanZhu-apple** [comment]
@chrisortman OK, I can see a custom renderer is required in this case.

**Comment by chrisortman** [comment]
Would you like me to start a pull request with the changes I've made and
then I can work on whatever other changes you'd need?

**Comment by chrisortman** [comment]
I think this can be closed?
