### ISSUE TITLE
ORKSignatureView uses invalid graphics context

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#784]
## Steps to reproduce
- Setup an `ORKOrderedTask` containing a single `ORKSignatureStep`
- Attach this task to an `ORKTaskViewController` and present it
- Once the task finishes, save the task view controller's restoration data
- Instantiate a `ORKTaskViewController` with the saved restoration data
- Access the `result` property of the newly instantiated task view controller
## Expected behavior
- No warning messages printed to the console
## Actual behavior
- `invalid context 0x0` error messages printed to the console
## Root cause
- `ORKTaskViewController`'s state restoration routine will recreate the `ORKSignatureStepViewController`
- The recreated step view controller will be shown, which leads to a `viewWillAppear`call even if the task view controller itself hasn't been presented so far
- Within it's `viewWillAppear` implementation `ORKSignatureStepViewController` copies the path array of the restored step result. Therefore, `ORKSignatureView`'s `signatureExists` property will return `YES`
- Once the result property of is accessed, `ORKTaskViewController` updates the current step result, which accesses `ORKSignatureStepViewController`'s result property
- Since `signatureExists` returns `YES`, `ORKSignatureStepViewController` instantiates a new `ORKSignatureResult` and accesses the `signatureImage` property of `ORKSignatureView`
- This access leads to a `UIGraphicsBeginImageContext` call that passes `self.bounds.size`
- Since the view hasn't actually appeared on screen, both width and height are 0, which leads to an invalid image context
## Proposed fix
- If either `self.bounds.height`or `self.bounds.width` are 0, return a default size to create the image context

@syoung-smallwisdom Please have a look at this

**Comment by oliverschaefer** [comment]
@syoung-smallwisdom friendly ping

**Comment by syoung-smallwisdom** [comment]
@oliverschaefer 
Sorry, I was on vacation when this came in and then I forgot to reply. I think your solution is a good one. Would you like for me to address the issue or would you prefer to submit your own fix? Thanks!

**Comment by oliverschaefer** [comment]
@syoung-smallwisdom Thanks for getting back to me. I'll submit a fix that I already tested in a separate PR and let you know.

**Comment by oliverschaefer** [comment]
@syoung-smallwisdom Added PR #809. Please have a look at it.

**Comment by kelseydedoshka-apple** [comment]
@oliverschaefer thanks for creating a fix for this in PR #809. Closing this issue since the PR has been merged!
