### ISSUE TITLE
Active Task Custom Results

### ISSUE THREAD

**Issue by craylward** [ResearchKit/ResearchKit#790]
Using swift, what is the proper way to add to the results of a ORKStepViewController? I've implemented an active step that produces an ORKFileResult but I'm not sure how to add that ORKFileResult to the result.results. 

Documentation [here](http://researchkit.org/docs/Classes/ORKStepViewController.html#//api/name/result) notes that "Subclasses may call super to obtain a clean, empty result object appropriate for the step, to which they can attach appropriate child results". I'm not sure how to translate this to swift code.

**Comment by YuanZhu-apple** [comment]
@craylward You need to subclass ORKActiveStepViewController and override [result](http://researchkit.org/docs/Classes/ORKStepViewController.html#//api/name/result)

**Comment by craylward** [comment]
So tis is the approach I've taken:
`    override var result: ORKStepResult? {
            let sResult = super.result
            var results = sResult?.results
            fileResult = ORKFileResult(identifier: self.step!.identifier)
            results?.append(fileResult!)
            sResult?.results = results
            return sResult

    }`

But what if the file result data is updated at the end of the view controller's lifetime... the ORKFileResult object appended to the result the way I have it now does not update if I add data in a function within the view controller.

**Comment by umerkhan-apple** [comment]
@craylward You can store the fileResult once the step's view controller has finished.

**Comment by kelseydedoshka-apple** [comment]
@craylward - friendly ping to see if Umer's suggestion above helped resolve your issue?

**Comment by craylward** [comment]
Prior to Umer's response, I implemented a solution by declaring the following in my ViewController class:

`    var _result: ORKStepResult?
    override var result: ORKStepResult? {
        get {
            if _result == nil {
                return super.result
            }
            else {
                return _result
            }
        }
        set {
            _result = newValue
        }
    }`

and then assigning a value to the results with the following while the ViewContoller is presented:

`                     let fileResult = ORKFileResult(identifier:"acc")
            fileResult.fileURL = outputDir!.appendingPathComponent(self.step!.identifier + "_accel.json")
            fileResult.contentType = "application/json"
            fileResult.startDate = startTime!
            fileResult.endDate = endTime!
            
            let stepResult = super.result
            stepResult?.results?.append(fileResult)
            result = stepResult`

NOTE: This is used to gather accelerometer data from the Apple Watch during a task using the ORKWaitStepViewController.

I created an ORKOrderedTask, ORKWaitStep, and an associated ORKWaitStepViewController. Based on Umer's response, I'm assuming the assignment of a value to the fileResult of the view controller would need to take place in the ORKWaitStep.

Based on advice from another thread (not sure the exact reference off the top of my head), I associated the ORKViewController to the ORKStep using the following code in the ORKWaitStep class: 

`    static func stepViewControllerClass() -> TremorConnectStepWViewController.Type {
        return TremorConnectStepWViewController.self
    }`

I'm a little confused on why this code is necessary/works to create custom steps/viewcontrollers. Perhaps I haven't looked into other solutions far enough. If that part of the implementation could be explained I'd greatly appreciate it. Let me know if anything needs further clarification. Otherwise, this issue can be considered closed.

**Comment by kelseydedoshka-apple** [comment]
@craylward - glad you were able to find a solution. In terms of your follow up questions - are you asking about the last code snippet you provided in the above comment of why your solution was necessary vs. those suggested by Yuan and Umer?

**Comment by craylward** [comment]
To keep it simple: Umer indicates to "store the fileResult once the step's view controller has finished". Does this take place in the ORKWaitStepViewController, ORKWaitStep, or ORKOrderedTask?

**Comment by umerkhan-apple** [comment]
@craylward You are correct in assuming that the assignment of a value to the fileResult would take place in the ORKWaitStep. And once you are done processing that result, you can call `goForward` to proceed to the next step after the wait step.

As for the `stepViewControllerClass` method, it helps provide a way for step subclasses to specify which view controller subclass is associated with it. If it is not implemented, it will use the view controller class that is associated with the superclass. Overriding this method allows you to provide your own view controller for a step.

**Comment by craylward** [comment]
Awesome, thanks for the answers!
