### ISSUE TITLE
ORKPasscodeStepViewController should report in its delegate if Touch ID was used or not

### ISSUE THREAD

**Issue by boland25** [ResearchKit/ResearchKit#791]
It would be useful for the ORKPasscodeStepViewController to add to its delegate call whether or not the user authenticated using touch ID.

This is necc. for an app that I am building, and have put some thought into how this will work...
1. In ORKPasscodeStepViewController, at the end of the method `promptTouchId`, call  

```
[self.taskViewController.delegate taskViewController:self didChangeResult:[self result]];
```
1.  add BOOL to `ORKStepResult` called `touchIdEnabled` and populate it with `_isTouchIdAuthenticated` Boolean.

```
passcodeResult.touchIdEnabled = _isTouchIdAuthenticated;
```
1.  Implement in the class that is its delegate, `taskViewController:didChangeResult`

``` SWIFT
func taskViewController(taskViewController: ORKTaskViewController, didChangeResult result: ORKTaskResult) {
        if let stepResult = result.results?.first as? ORKStepResult, passcodeResult = stepResult.results?.first as? ORKPasscodeResult {
            print(passcodeResult.touchIdEnabled)
        }
    }
```

If there are other ways, I am open to other suggestions, but I would like to implement and submit a PR.

**Comment by boland25** [comment]
apparently I don't even need to force the delegate call at the end of promptTouchID, as its already set up to make that call on its own, removing those lines.  Those lines were troublesome anyway

**Comment by umerkhan-apple** [comment]
Merged!
