### ISSUE TITLE
-[UILabel textRectForBounds:limitedToNumberOfLines:] method should not be called directly.

### ISSUE THREAD

**Issue by stevemoser** [ResearchKit/ResearchKit#795]
The `-[UILabel textRectForBounds:limitedToNumberOfLines:]` method should not be called directly.

ORKFormStepViewController.m in: labelWidth
return [sharedLabel textRectForBounds:CGRectInfinite limitedToNumberOfLines:1].size.width;

The document for UILabel says:

> This method should only be overridden by subclasses that want to change the receiver’s bounding rectangle before performing any other computations.

Without researching it much more I'm not sure what the best fix is. At very least I imagine it would be helpful if there was a comment stating that the documentation was ignored for a specific reason.

**Comment by umerkhan-apple** [comment]
@stevemoser Has calling this method directly caused any bugs or issues for you?

**Comment by stevemoser** [comment]
@umerkhan-apple I have not.

**Comment by umerkhan-apple** [comment]
@stevemoser Great. Will go ahead and close the issue and look into adding a comment on the reason for ignoring the documentation. Thanks!
