### ISSUE TITLE
Option of providing text in multiple choice questions in survey

### ISSUE THREAD

**Issue by afrozk** [ResearchKit/ResearchKit#800]
In Survery module , if i want to add a questions such as 
1. What is your favourite drink? 
Options:
1. Tea
2. Coffee
3. Others
In case user selects others, we want to show a text field where user can add any drink.
This feature is highly required in multiple questions option.

**Comment by md0u80c9** [comment]
Hi afrozk,

You can do that by using the predicates.

Create an ordered task, with your multiple choice question as step 1, an 'other' text step as step 2, and then your 'next question' or your finish as step 3.

Then set a predicate to step 1, so if the answer is anything other than 'other' we skip to step 3.

Hope that helps.

**Comment by afrozk** [comment]
Thank you md0u80c9 . Really Appreciate for quick response.
