### ISSUE TITLE
Progress Bar Not Showing Up

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#808]
For some reason, the progress bar of my survey tasks is not showing up. I didn't set any options for the task, yet it is being hidden. 

Also, a question for anybody could help. I need help on designing a regex. I have a multi choice question. I basically need to skip a question, if one of the users choices doesn't include "Others". How could I go about doing this?

Thank You.

**Comment by kothapas** [comment]
Got Progress Bar to show up, but any help on second question is appreciated.

**Comment by berenyiaustin** [comment]
@kothapas how did you get your progress bar to show?
