### ISSUE TITLE
ORKPredicateStepNavigationRule breaks build by using Predicate in Swift 3

### ISSUE THREAD

**Issue by asynchrony-ringo** [ResearchKit/ResearchKit#810]
On both `master` and `stable_xcode80_cadidate`, ORKPredicateStepNavigationRule is using Predicate for Swift 3 which is breaking the build on beta 6. According to [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md), Swift will remain using NSPredicate.

**Comment by kelseydedoshka-apple** [comment]
@asynchrony-ringo closing this issue as the fixes above have been merged!
