### ISSUE TITLE
ORKQuestionStepCellHolderView symbol visibility is hidden resulting in "symbol not found for architecture arm64" when archiving 

### ISSUE THREAD

**Issue by celteeka** [ResearchKit/ResearchKit#812]
Hi RK team,
  In an attempt to create a custom step I am instantiating ORKQuestionStepViewController and then setting my custom view like this:

`var result = ORKQuestionStepViewController(step: myCustomStep)
result.customQuestionView = MyCustomStepView()
result.customQuestionView.delegate = result
`

where MyCustomStepView is defined like this:
`class MyCustomStepView : ORKQuestionStepCellHolderView {...}`

The reason I am subclassing ORKQuestionStepCellHolderView instead of ORKQuestionStepCustomView is because if I don't, I then get an 'invalid selector sent to...' error in [ORKQuestionStepViewController#viewDidAppear](https://github.com/ResearchKit/ResearchKit/blob/75142028b0cc95575ceb7fd6207a0f7fa1724167/ResearchKit/Common/ORKQuestionStepViewController.m#L338):

`ORKSurveyAnswerCellForPicker *cell = (ORKSurveyAnswerCellForPicker *)[(ORKQuestionStepCellHolderView *)_questionView.questionCustomView cell];
`

The 'cell' property is defined in ORKQuestionStepCellHolderView instead of the super class ORKQuestionStepCustomView. 

Regardless of this other error, and going back to my attempt on using ORKQuestionStepCellHolderView, everything works fine until I want to archive my project. 

I'm getting the following error:

`Undefined symbols for architecture arm64:
"_OBJC_CLASS_$_ORKQuestionStepCellHolderView", referenced from:
     _OBJC_CLASS_$__TtC6myapp11MyCustomView in MyCustomView.o
"_OBJC_METACLASS_$_ORKQuestionStepCellHolderView", referenced from:
    _OBJC_METACLASS_$__TtC6myapp11MyCustomView in MyCustomView.o
ld: symbol(s) not found for architecture arm64 
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
`

After digging around I found this other similar issue ([#572](https://github.com/ResearchKit/ResearchKit/issues/572) which was solved by adding ORK_CLASS_AVAILABLE to the symbol in order to make it public.

I posted my question and @YuanZhu-apple replied confirming the bug. 
I'll can definitely submit the PR for this. I just wanted to [follow the rules for contributing](https://github.com/ResearchKit/ResearchKit/blob/master/CONTRIBUTING.md) to this amazing project! 

Thanks in advance,
Seb

**Comment by kelseydedoshka-apple** [comment]
@celteeka thanks for submitting a PR to fix this! Closing this issue since PR #814 has been merged.
