### ISSUE TITLE
ORKScaleAnswerFormat and ORKContinuousScaleAnswerFormat would benefit from a common superclass

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#817]
Hi,

Just progressing the HL7CCD work again today, and spotted that ORKScaleAnswerFormat and ORKContinuousScaleAnswerFormat only have ORKAnswerFormat as a common ancestor.

If you use isKindOfClass, you then have to treat the two entirely differently which is of course an unfortunate quirk.

I think they need a common superclass, with continuous and discrete scales being subclasses.

Unfortunately the best naming convention is API-breaking (and potentially tricky to spot in the code): to have ORKScaleAnswerFormat as the superclass, and ORKContinuousScaleAnswerFormat and ORKDiscreteScaleAnswerFormat as the subclasses. We could choose another name for ORKScaleAnswerFormat but that may inhibit clarity.

Are there any better solutions to this?

**Comment by umerkhan-apple** [comment]
In order to avoid confusion, I would recommend doing a check for both classes when using isKindOfClass.

**Comment by rsanchezsaez** [comment]
I think this would be a nice improvement and make the *scale data format* names clearer (I'm in favor of ignoring backwards source code compatibility when the change results in a nicer API).

@umerkhan-apple: Do you want me to do this improvement when I have time? Or do you prefer to leave these as currently is?
