### ISSUE TITLE
Commit 74326bae Breaks the sizing of the completion checkmark

### ISSUE THREAD

**Issue by syoung-smallwisdom** [ResearchKit/ResearchKit#820]
This commit has broken the checkmark that is used as the completion step for every active task.

![simulator screen shot sep 12 2016 1 52 35 pm](https://cloud.githubusercontent.com/assets/5649217/18452598/68fa7aa8-78f0-11e6-8a20-486cd6f50c70.png)

**Comment by syoung-smallwisdom** [comment]
This commit was made to fix issue https://github.com/ResearchKit/ResearchKit/issues/774

**Comment by kelseydedoshka-apple** [comment]
@syoung-smallwisdom this issue has been resolved!
