### ISSUE TITLE
Which Swift Version?

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#823]
Hi @YuanZhu-apple ,

Following the release of Xcode 8, which version of Swift should we be using for the Swift components of ResearchKit?

I'm getting compile issues having changed from Xcode 7 to 8 that it thinks some of the code is being compiled in Swift 3 and some in 2.3 (my current HL7 CCD branch from Master doesn't use any Swift at all). I'm aware there are some switches in the code at present to support suggesting both 2.3 and 3 support; but I suspect there are some issues with the build switches being unable to support both versions. I suspect if we have to choose a single version for compiling I would propose Swift 3 would be preferable to encourage migration ASAP in line with the Swift team's 'Swift 2.3 is temporary' message; and projects using Swift 2 would then be incentivised to migrate in order to use the newer library.

**Comment by dsunderhaft** [comment]
I am experiencing the same issues. One caveat, When I compile in Xcode 8 to ios9.3 or below I do not have any issues.  The issues only occur when I compile to ios10.

**Comment by umerkhan-apple** [comment]
Migration to Swift 3.0 has been completed. You should 3.0 for development with the latest RK master. Let me know if there is still an issue.
