### ISSUE TITLE
ORKPasscodeStep: 'Could not add Keychain item' generic exception

### ISSUE THREAD

**Issue by whiteof** [ResearchKit/ResearchKit#826]
After updated to XCode 8 and Swift 3, getting the error message 'Could not add Keychain item.' for ORKPasscodeStep.

**Comment by jdkizer9** [comment]
I'm having the same issue. @whiteof any success working around this?

**Comment by jdkizer9** [comment]
@whiteof, I resolved this by adding an entitlements file, see https://forums.developer.apple.com/thread/60617 for more info.

**Comment by umerkhan-apple** [comment]
Does this error message show on device also, or just simulator?

**Comment by umerkhan-apple** [comment]
Closing for now. Happy to re-open if the issue still exists! :)
