### ISSUE TITLE
ORKTextChoice value:id syntax on Swift 3

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#827]
Hi,

Just reworking my Stroke CaseNotes project on Xcode 8 this afternoon, using the XCode80_stable branch, and completing the Swift 3 conversion. So far not as painful as I thought (I happily will trade the one-off code reformatting for Xcode 8's one-click code signing!)

One difference I did find is that in Swift using ORKTextChoice(text: value:) is a bit messier. Principally value is an id which has to conform to NSCoding & NSCopying & NSObjectProtocol - so plain strings don't automatically conform and the compiler is suggesting:

ORKTextChoice(text: "ITU / CCU / HDU", value:"ICH")
should become:
ORKTextChoice(text: "ITU / CCU / HDU", value:"ICH" as NSCoding & NSCopying & NSObjectProtocol)

Which is of course just a little bit messy. 

Is there a better way of doing this? Should value be changed from being an id into something which is more restrictive but will conform more easily?

**Comment by syoung-smallwisdom** [comment]
@md0u80c9 
Hi there, you can cast it as an NSString. For example:

````
ORKTextChoice(text: "ITU / CCU / HDU", value:"ICH" as NSString)
````

**Comment by kelseydedoshka-apple** [comment]
@md0u80c9 Instead of casting to NSCoding & NSCopying & NSObjectProtocol you can cast your value to a type that conforms to those. As @syoung-smallwisdom mentioned you can cast it as a NSString, or for number values NSNumber.
