### ISSUE TITLE
Height of customView defined by ORKActiveStepViewController subclass always 0

### ISSUE THREAD

**Issue by jdkizer9** [ResearchKit/ResearchKit#830]
I'm attempting to create a custom Active Task via external interfaces and I'm running into problems when defining my custom view. My trivial view is defined as such:

``` swift
class CTFGoNoGoView: UIView {

    override init(frame: CGRect) {

        super.init(frame: frame)
        self.backgroundColor = UIColor.blueColor()

    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func sizeThatFits(size: CGSize) -> CGSize {
        let minDimension: CGFloat = min(size.height, size.width)
        return CGSizeMake(minDimension, minDimension)
    }

    override func intrinsicContentSize() -> CGSize {
        return CGSizeMake(375.0, 375.0)
    }

}
```

My trivial view controller is defined as such:

``` swift
class CTFGoNoGoStepViewController: ORKActiveStepViewController {

    let goNoGoView: CTFGoNoGoView = CTFGoNoGoView(frame: CGRectZero)

    override func prepareStep() {
        super.prepareStep()
        if self.customView == nil {
            self.customView = self.goNoGoView
        }
    }  
}
```

It appears as the height constraint of the super view (_customViewContainer) of the custom view is being set to 0 (see attached image) at some point, but it is unclear where.

![screen shot 2016-09-28 at 6 53 25 pm](https://cloud.githubusercontent.com/assets/6721921/18935276/e9c5f2ca-85ac-11e6-82c4-78c2fa20f660.png)

Side bar:

What is the proper way to create a new Active Task? The problem I have with the [blog here](http://blog.shazino.com/articles/dev/researchkit-new-active-task/) is that I'd prefer to extend RK and not fork it. I think I am approaching it the correct way, but if anyone else has a better solution, I'm interested in learning about it.

**Comment by umerkhan-apple** [comment]
A couple suggestions could be to provide an actual CGRect when creating your custom view.
Also maybe not check if it is nil before setting it, because the super may already have specified one?

Side note: There is a GoNoGo Active Task available here if you would like to take a look at it for reference #936
