### ISSUE TITLE
Date Step - Mismatch between picker.date and what is shown in the UIDatePicker

### ISSUE THREAD

**Issue by mirlhaq** [ResearchKit/ResearchKit#833]
Creating the `ORKDateAnswerFormat` with a particular `NSCalendar` is not enough to ensure the time zone, provided with the calendar, is used by the picker (particularly in the _UI side of things_).

Check how `_pickerView.date` and the date displayed in the UI are different:
![picker view bug](https://cloud.githubusercontent.com/assets/570932/19054351/6f62333a-8995-11e6-8601-cdc9b946d2e2.png)

**The problem is** :
Inside `ORKDateTimePicker` the `_pickerView.calendar` is set with the calendar passed in the init method. But that is not enough, the `_pickerView.timeZone` property needs to be set too if we want to use a particular time zone. Sounds weird but that seems to be the way `UIPickerView` works.

Both of the following changes do the work for me:
1. Set the time zone in the method that creates the picker view.

``` Objective-C
- (UIDatePicker *)pickerView {
    if (_pickerView == nil) {
        _pickerView = [[UIDatePicker alloc] init];

        // mirlhaq ----
        _pickerView.timeZone = _calendar.timeZone;
        // mirlhaq ----

        [_pickerView addTarget:self action:@selector(valueChanged:) forControlEvents:UIControlEventValueChanged];
        self.answerFormat = _answerFormat;
        self.answer = _answer;
    }
    return _pickerView;
}
```
1. Set the time zone in the method that sets the answer format.

``` Objective-C
- (void)setAnswerFormat:(ORKAnswerFormat *)answerFormat {
...
    if ([self isTimeOfDay]) {
        [self setDate:[(ORKTimeOfDayAnswerFormat *)answerFormat pickerDefaultDate]];
    } else {
        ORKDateAnswerFormat *dateAnswerFormat = (ORKDateAnswerFormat *)answerFormat;
        [self setDate:[dateAnswerFormat pickerDefaultDate]];
        _pickerView.calendar = [dateAnswerFormat currentCalendar];

        // mirlhaq -----
        _pickerView.timeZone = _pickerView.calendar.timeZone;
        // mirlhaq -----

        _calendar = [dateAnswerFormat currentCalendar];     
...
}
```

**Comment by umerkhan-apple** [comment]
@mirlhaq Would you be able to provide a PR with the fix in which you set the timezone when the answer format is set?

**Comment by mirlhaq** [comment]
@umerkhan-apple Sure! [here it is](https://github.com/ResearchKit/ResearchKit/pull/965).
