### ISSUE TITLE
Continuous Scale Step - UI value and result value mismatch when using fraction digits

### ISSUE THREAD

**Issue by mirlhaq** [ResearchKit/ResearchKit#834]
When using fraction digits, the value displayed by the UI is not the same as the one from the results. For example if `maximumFractionDigits` is `2`, the user slides the slider to, let's say, `7`, the UI shows `7` but the result is something near `7` but not `7` (i.e. `6.9884...`).

This becomes important when using _navigation rules_, if we create a navigation rule and provide a `7` in our `NSPredicate` it **will always be false**.

Doing this fixes the issue:

`@ ORKAnserFormat`

``` Objective-C
- (ORKQuestionResult *)resultWithIdentifier:(NSString *)identifier answer:(id)answer {
    ORKQuestionResult *questionResult = [[[self questionResultClass] alloc] initWithIdentifier:identifier];

    // mirlhaq --- ContinuousScale navigation rules always evaluate to false because the result is different from what is displayed in the UI. The fraction digits have to be taken into account in self.answer as well.
    if ([self isKindOfClass:[ORKContinuousScaleAnswerFormat class]])
    {
        NSNumberFormatter* formatter = [(ORKContinuousScaleAnswerFormat*)self numberFormatter];
        answer = [formatter numberFromString:[formatter stringFromNumber:answer]];
    }
    // mirlhaq ---

    questionResult.answer = answer;
    questionResult.questionType = self.questionType;
    return questionResult;
}
```

**OR** perhaps, a more elegant way to do this would be to add an overriding method in `ORKContinuousScaleAnswerFormat` so the code is cleaner.

**Comment by umerkhan-apple** [comment]
@mirlhaq Could you provide the change in a PR?

**Comment by mirlhaq** [comment]
@umerkhan-apple sure! [here](https://github.com/ResearchKit/ResearchKit/pull/899) it is.
