### ISSUE TITLE
issue after updating to iOS 10 SDK

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#835]
Hello, I am having issues with ORKTextAnswerFormat after updating to iOS 10 SDK and new version of Xcode. The user interface is odd, and entered text does not show. Entered text is capture, just not shown to the user. Please see attached file. Is anyone else having this issue?

ORKAnswerFormat *format = [ORKTextAnswerFormat textAnswerFormat];

ORKQuestionStep *step = [ORKQuestionStep questionStepWithIdentifier:theInteractionEntity.field_name title:theInteractionEntity.field_label answer:format];

![simulator screen shot oct 4 2016 9 41 34 am](https://cloud.githubusercontent.com/assets/125992/19076451/d2cb4656-8a16-11e6-84eb-6a77c72981fb.png)

**Comment by cmetts** [comment]
Pull Request #806 fixed the issue with a ORKQuestionStep with textAnswerFormat, but the issue remains when using emailAnswerFormat. See attached screenshot.

![simulator screen shot oct 4 2016 11 01 57 am](https://cloud.githubusercontent.com/assets/125992/19079648/533ca04a-8a22-11e6-8f0c-d80fccd9f43c.png)

**Comment by cmetts** [comment]
Also, issues remain when using redex. The below was working before updating to iOS 10. This should limit to digits only, 10 characters. Currently, after update, it accepts anything. 

ORKTextAnswerFormat *theTextAnswerFormat= [ORKTextAnswerFormat textAnswerFormatWithValidationRegex:@"^[0-9]{1,10}$" invalidMessage:@"The number is invalid"];
                    theTextAnswerFormat.keyboardType = UIKeyboardTypeNumberPad;
                    ORKAnswerFormat *format = theTextAnswerFormat;
                    
                    ORKQuestionStep *step = [ORKQuestionStep questionStepWithIdentifier:theInteractionEntity.field_name title:theInteractionEntity.field_label answer:format];

**Comment by ninoguba** [comment]
Grab the latest version (1.4) and use PR #831 to completely fixed the UI issues with iOS 10

**Comment by umerkhan-apple** [comment]
Issue resolved in the RK 1.4.
