### ISSUE TITLE
ResearchKit on The Changelog!

### ISSUE THREAD

**Issue by adamstac** [ResearchKit/ResearchKit#84]
Howdy from The Changelog!

We'd love to have y'all on the show sometime to talk about ResearchKit.

You may have heard of our podcast, but if not -- The Changelog is a podcast covering what's fresh and new in open source. Listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to y'all!

Adam, EIC

**Comment by DanKeen** [comment]
Thanks for the invite, Adam - closing this as it isn't really an Issue. Please reach out to researchkit@apple.com instead.

**Comment by adamstac** [comment]
Awesome. Thanks Dan. Emailed.

**Comment by adamstac** [comment]
@DanKeen I emailed a while back but haven't heard from anyone. Is there someone in particular I should reach out to?
