### ISSUE TITLE
"Cannot find protocol declaration for 'CAAnimationDelegate'; did you mean 'UIApplicationDelegate'?" 

### ISSUE THREAD

**Issue by mhollis1980** [ResearchKit/ResearchKit#843]
I've opened the sample apps and followed the instructions to get a project up and running but I keep getting an compile error"
Cannot find protocol declaration for 'CAAnimationDelegate'; did you mean 'UIApplicationDelegate'?

I'm running this on xcode 7.3.1?

Any thoughts?
Thanks,
Mike.

**Comment by rsanchezsaez** [comment]
Hey Mike,

The latest version of *ResearchKit* is only compatible with *Xcode 8.0* and up. :-)

**Comment by mhollis1980** [comment]
That's what i thought once I started poking around a little more. Thanks for the reply. 

Mike.
