### ISSUE TITLE
ORKPasscodeViewController Bug

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#844]
This seems to be an iOS 10 issue.
When one decides to cancel the touch ID, when prompted to use touch ID for logging in, the keyboard that used to display for people to enter the 4 digit pincode instead is not showing up anymore. It just shows white screen, and even though its receiving the input as the keyboard is there, its not showing up on the screen.
![img_0070](https://cloud.githubusercontent.com/assets/17889409/19543942/f1d41436-962f-11e6-9aff-cf9d178c7d29.PNG)

**Comment by kothapas** [comment]
This seems to be an iOS 10.0 issue as other people have faced this issue. 

Here is a link http://stackoverflow.com/questions/39045675/ios-keyboard-inside-uiremotekeyboardwindow-is-not-shown-when-uitextfield-becom

**Comment by Garrettv11** [comment]
The hack to work around this problem follows:

In ORKPasscodeStepViewController, you need to delay the call to makePasscodeViewBecomeFirstResponder like so:

```
else if (error.code == LAErrorUserCancel) {
                    [strongSelf  performSelector:@selector(makePasscodeViewBecomeFirstResponder) withObject:self afterDelay:1];
                }
```
