### ISSUE TITLE
Survey version

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#852]
Hi,

Very simple suggestion/proposal.

As I'm developing my app, I am modifying my survey. I tend to store survey results in Core Data.

It would be logical to permit a 'survey version ID' created with the ORKTask, which is simply passed into the ORKTaskResult, so that the application can work out which particular version of a survey the result was created from.

**Comment by ninoguba** [comment]
Possible workaround is to suffix your task identifier with the version, i.e:  <taskid>_<version>.  What do you think?

**Comment by umerkhan-apple** [comment]
@md0u80c9 Any thoughts?

**Comment by md0u80c9** [comment]
I was wondering whether adding a property to ORKTask in a PR to carry the version number on input might be more appropriate. On task completion, when we create ORKTaskResult, we pass on the same version number. Having a numerical int would make most sense.

The problem with using the task identifier to denote the version is then that you have to have logic in every area that you might use the task identifier (which may not be in a single place). Adding the property to ORKTask, which is automatically added as a property to ORKTaskResult on task completion would allow that to be avoided and would maintain backwards compatibility (if it was set as 1 by default for example). It's also a string - so doesn't denote a linear change which may make the decoding logic messier.


The sort of use case I was thinking was that you create a survey to ask a patient 10 questions. Later, in a new version, you now ask an 11th question. The first 10 questions are equally valid in both surveys; so therefore you only need to know the version number if it is the 11th you are interested in.

In your result handling, all you would have is:

// Process results for questions 1-10

if (taskResult.version > 1) {
// Process 11th question results
}

**Comment by umerkhan-apple** [comment]
@md0u80c9 Good discussion and explanation for the use-case. I think @ninoguba has brought up a good solution to append suffixes. But I also see how that is not sufficient for your particular use-case. From an API perspective, we might not want to modify the current survey structure for RK for this use-case, but instead you can pursue it by creating 2 separate survey tasks and presenting either one when appropriate, or use navigable ordered task, but whenever you don't want to present the 11th questions, you just skip it to the end. This way the results will always contain 11 result objects, but the last one will just be empty.

**Comment by md0u80c9** [comment]
Thanks @umerkhan-apple.  The project is being significantly expanded and voids this particular problem for me anyway (we will be using HL7 FIHR to store and retrieve the results, so my surveys will have to be unpacked on completion, and draft surveys won't be persisted).
