### ISSUE TITLE
Score / Total / Sum Survey Steps

### ISSUE THREAD

**Issue by jamiedaniel** [ResearchKit/ResearchKit#855]
When progressing though a survey and values are numeric, or of expected type; I would like to have the steps scored as the survey is being taken. This would allow navigation to occur based on either current answer or progressive sum/total/score.

ORKResults should also be able to provide a JSON response for score.

For example:
**taskViewController.result.scoreValue**
- This would return a double value
  ex: 36

**taskViewController.result.scoreSummary**
- This would return a Dictionary or JSON of similar values
  ex: 
  Not at all : 3
  Somewhat : 5
  Disagree : 4

**Comment by ninoguba** [comment]
Since there is no built-in way to score results yet in ResearchKit, I suggest you implement your own scoring algorithm on this delegate method:

http://researchkit.org/docs/Protocols/ORKTaskViewControllerDelegate.html#//api/name/taskViewController:didChangeResult:

**Comment by umerkhan-apple** [comment]
Agree with @ninoguba . Tracking this feature request in #873 .
