### ISSUE TITLE
ORKTextChoiceAnswerFormat on singleChoice style when it's not optional doesn't have Next or Done button

### ISSUE THREAD

**Issue by milifili** [ResearchKit/ResearchKit#858]
I just created a single text choice task with the following code (copied of ORKCatalog but its not optional) : 

        let textChoiceOneText = NSLocalizedString("Choice 1", comment: "")
        let textChoiceTwoText = NSLocalizedString("Choice 2", comment: "")
        let textChoiceThreeText = NSLocalizedString("Choice 3", comment: "")
        
        // The text to display can be separate from the value coded for each choice:
        let textChoices = [
            ORKTextChoice(text: textChoiceOneText, value: "choice_1" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: textChoiceTwoText, value: "choice_2" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: textChoiceThreeText, value: "choice_3" as NSCoding & NSCopying & NSObjectProtocol)
        ]
        
        let answerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: textChoices)
        
        let questionStep = ORKQuestionStep(identifier: String(describing:Identifier.textChoiceQuestionStep), title: exampleQuestionText, answer: answerFormat)
        
        questionStep.text = exampleDetailText
        questionStep.isOptional = false

       ORKOrderedTask(identifier: String(describing:Identifier.textChoiceQuestionTask), steps: [questionStep])

And I'm wondering why there is not **Next** or **Done** button. Is it a bug or this is how ORK works. The same happens whenever Boolean answer format is not optional.
![test](https://cloud.githubusercontent.com/assets/5347193/19931195/82eef746-a103-11e6-9389-8432f00a24e3.png)

**Comment by ninoguba** [comment]
I think this was by design so that you complete the step with one tap only for single-choice or boolean questions.

**Comment by kelseydedoshka-apple** [comment]
@milifili This is by designed as @ninoguba mentioned. Since there is only a single action required to complete the step there is no need for a Next or a Done button.

However if you want a Done button you could use an ORKFormStep as the step in your ORKOrderedTask. You can add your questionStep above as an ORKFormItem and add that to the ORKFormStep. More information on ORKFormSteps can be found in the ResearchKit documentation.
