### ISSUE TITLE
Extend ORKOrderedTask to include navigation rules

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#86]
Either subclass `ORKOrderedTask`, or extend it, to include navigation rules.

A navigation rule would be something which can be asked if it matches the current step. If it matches the current step, then if provided with the results of the task to date, it should provide the step identifier for the next step. A concrete navigation rule class might be one checks if the result is equal to a particular question result. Although a block might be nicer, it would not be possible to serialize, so we prefer direct equality checks for now. A future generalization might be the use of predicates.

Any navigation rule classes should be serializable with `NSSecureCoding`, and serialization support in `ORKESerialization` in the ORKTest project would also be appropriate.

This task is to propose suitable API, implement, and ideally write unit tests.

**Comment by rsanchezsaez** [comment]
I'm working on this while the *iPad margins pull request* is reviewed.

**Comment by jwe-apple** [comment]
Sounds good. Please email me a draft of API for review as soon as you have something to look at. Can likely save you implementation time if we get the API close to right the first time.

**Comment by jwe-apple** [comment]
(and also I can circulate it more widely here)

**Comment by rsanchezsaez** [comment]
Some ideas for the API:

    @interface ORKStepNavigationRule : NSObject

    - (instancetype)initWithSourceStepIdentifier:(NSString *)sourceStepIdentifier;
    - (NSString *)nextStepIdentifierWithTaskResult:(ORKTaskResult *)taskResult;

    @property (nonatomic, copy, readonly) NSString *sourceStepIdentifier;


    @end


    @interface ORKStepResultEvaluator : NSObject

    - (instancetype)initWithStepResultIdentifier:(NSString *)stepResultIdentifier;
    - (BOOL)evaluateWithTaskResult:(ORKTaskResult *)taskResult;

    @end


    @interface ORKStepBooleanResultEvaluator : ORKStepResultEvaluator

    - (instancetype)initWithStepResultIdentifier:(NSString *)stepResultIdentifier expectedAnswer:(BOOL)expectedAnswer;

    @end


    @interface ORKResultEvaluatorStepNavigationRule : ORKStepNavigationRule

    - (instancetype)initWithSourceStepIdentifier:(NSString *)sourceStepIdentifier
                           successStepIdentifier:(NSString *)successStepIdentifier
                           failureStepIdentifier:(NSString *)failureStepIdentifier
                                      evaluators:(NSArray *)evaluators;

    @end

The idea here is that you build an `ORKResultEvaluatorStepNavigationRule ` with the *source step identifier*, the two possible *target step identifiers*, and one or more *evaluators*. We'd need to provide evaluator subclasses for all step question types.

Then `ORKOrderedTask` would have the following new property:

    @property (nonatomic, readonly) NSArray *stepNavigationRules 

If `stepNavigationRules` is empty, or doesn't have a suitable navigation rule for the current step, `ORKOrderedTask` uses the current approach of returning the next step in sequential order.

If it has a suitable result comparison step navigation rule for the current step, it calls `nextStepIdentifierWithTaskResult:` on it, which in turn queries its evaluators with the current `ORKTaskResult`. If all the evaluators pass, it returns the *success step*; if any of them doesn't it returns the *failure step*.

Other types of "custom" navigation rule subclasses would be possible as well.

---

Is this going in the right direction?

**Comment by p2** [comment]
The way this works in surveys I usually see is that a question (or group of questions, sorely missing from ResearchKit) knows whether it should be displayed based on an answer on a **previous** question. Your proposal turns this around by letting the question decide, based on its answer, which step to show **next**. Given the limitation of not having groups (which can be skipped entirely based on a previous answer) this might actually be the way to go.

**Comment by jwe-apple** [comment]
@p2 We've discussed doing it the other way round, and adding groups. We may end up adding groups at some point anyway, in order to be more interoperable with (e.g.) FHIR, but in principle a group-structured task could be a different implementation of the ORKTask protocol, and have nothing to do with ORKOrderedTask.

**Comment by jwe-apple** [comment]
In particular I don't think we'd ever attach rules to steps. Instead we'd attach rules to groups, which could potentially contain only a single step.

**Comment by p2** [comment]
@jwe-apple Sounds good. We're actually creating a FHIR bridge, so that would make for an easier mapping down the road. FHIR can have rules at both group AND question level, but limiting to groups should be perfectly fine; and cleaner, for that matter.

**Comment by jwe-apple** [comment]
@p2 It would be great if you could contribute your FHIR bridge back to ResearchKit. Starting sooner rather than later. I know there are several other parties out there also thinking about this, and having something concrete would be great.

**Comment by jwe-apple** [comment]
@p2 ... and if that happened to include an alternative to or an extension to ordered tasks that supported group structure, that would be worth looking at.

**Comment by p2** [comment]
@jwe-apple I have this working with subclasses of `ORKQuestionStep` and `ORKOrderedTask` against sufficiently complex FHIR questionnaires. Groups would be nice but this works for now. Will be difficult to contribute the bridging back to ResearchKit though since I'm using our [Swift FHIR](https://github.com/smart-on-fhir/Swift-FHIR) framework.

**Comment by jwe-apple** [comment]
@p2 Ah, that's ok. Could you share with me so I can have a look? Want to judge if there's some framework support we can add.

**Comment by p2** [comment]
@jwe-apple Sure, shared and sent a quick overview email.

**Comment by rsanchezsaez** [comment]
By the way, for anybody looking into give this a try: `ORKTest` has a new example called *Step Navigation Task*. Looking at the corresponding code in `MainViewController` is a quick way to see the API in use.

**Comment by jwe-apple** [comment]
Completed.
