### ISSUE TITLE
Where best to extend to add view controller to take Bluetooth reading

### ISSUE THREAD

**Issue by dmelgar** [ResearchKit/ResearchKit#866]
I work on a library that's able to take Bluetooth readings from medical devices such as glucometers. I’d like to extend ResearchKit to allow the user to retrieve their glucose readings. It is not clear to me where the ideal extension point is.

In particular, I’m considering the following:
- Subclass ORKQuestionStep.
- Create a new ORKAnswerFormat subclass. However, there a good bit of special purpose handling of answer formats in the ORKQuestionStepViewController so I don’t see how that can reasonably be extended without modifying the ORKQuestionStepViewController.

Any guidance on the intended ResearchKit extension points would be a big help.

Thanks

**Comment by umerkhan-apple** [comment]
If the glucometer writes into HealthKit, then you can use a HKAnswerFormat to populate the glucose readings. Otherwise, a simple solution is to override the taskViewController delegate and retrieve the data via bluetooth before the step is presented.

**Comment by kelseydedoshka-apple** [comment]
@dmelgar - just checking in here to see if Umer's suggestion above helped you resolve your issue?

**Comment by dmelgar** [comment]
The glucometer does not write into HealthKit. 
I implemented taking a Bluetooth reading by creating a ORKStep subclass and  ORKQuestionStepViewController subclass with its own nib. I needed to present a UI helping the user through the process to collect the Bluetooth reading.
Seemed to work reasonably well although had to imitate the style of controls to get to the next step etc.

**Comment by kelseydedoshka-apple** [comment]
@dmelgar - I am glad you were able to find a solution. Is it ok to close this issue since you have move forward with this?

**Comment by dmelgar** [comment]
Yes, can close the issue.
