### ISSUE TITLE
Not able to Subclass by all classes

### ISSUE THREAD

**Issue by MahendraKumarSV** [ResearchKit/ResearchKit#869]
Hi All,

I am trying to extend some classes from research kit, I have got some requirement to customize the **Image choice answer format**, **Text choice answer format** when I try to create a class by subclassing the class **ORKTextChoiceCellGroup** xcode is throwing an error. 

One thing I want to know clearly why I can only subclass the specific classes but not all.

**Comment by umerkhan-apple** [comment]
Some files, such as ORKTextChoiceCellGroup, have Target Membership set as Project.
