### ISSUE TITLE
Audio predefined task: audio step should not show too loud if outputdir is nil and developer ignored the error

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#87]
[rdar://problem/20503028](rdar://problem/20503028)

Currently, if the output directory is nil, we report an error to the developer via the task view controller delegate. If the developer does not handle the error, the task continues, and the audio recorder setup fails, which results in the audio showing as "too loud".

Instead, the audio step view should display some kind of error state to indicate that there was an error setting up audio. This should be a useful prompt to the developer to do some error handling - though we hope users will never see it.

**Comment by coxy1989** [comment]
Something like

_audioRecorder.outputDirectory == nil ? [self functionWhichCallsSuspendAndShowsUIAlertView] : [self start];

in ORKAudioStepViewController's ViewDidAppear?

**Comment by jwe-apple** [comment]
Probably without the alert view, because if we have an alert view it needs copy which we need to localize and maintain. But yes, roughly that.
