### ISSUE TITLE
Track individual sections in visual consent steps

### ISSUE THREAD

**Issue by chrisortman** [ResearchKit/ResearchKit#870]
I'm trying to figure out a way to log each section in a VisualConsentStep so that we can determine if a user drops out of consent at a certain point.

I can't find any suitable way to do this. I've tried subclassing ORKOrderedTask and overriding step after, as well as implementing the ORKTaskControllerDelegate step will appear.

Any ideas?

**Comment by umerkhan-apple** [comment]
ORKTaskViewControllerDelegate `stepWillAppear` method should allow you to see what the currentStep is and from that you can determine when the user stopped.

**Comment by kelseydedoshka-apple** [comment]
@chrisinsfo - just checking in to see if Umer's solution above helped you with your issue?

**Comment by kelseydedoshka-apple** [comment]
@chrisortman - just checking in here to see if Umer's suggestion above helped you resolve your issue?

**Comment by chrisortman** [comment]
@kelseydedoshka-apple No, I think I wound up adding a callback to ORKVisualConsentStepViewController for didShowSection

I think I had tried stepWillAppear but that was not sufficient because I wanted to know which *section* and all sections display under the same VisualConsentStep

I didn't submit a pull request with those changes though because I had already submitted a prior (different) pull request and it sat unreviewed in github for so long that it felt like it would have been wasted time.

**Comment by kelseydedoshka-apple** [comment]
@chrisortman - apologies for your frustrations with prior pull requests.

Did the addition of your callback function provide you with the functionality that you needed? If so is it ok to close this issue?

**Comment by kelseydedoshka-apple** [comment]
@chrisortman - closing this issue as you found a solution, but please feel free to reach back out if you are experiencing other issues.

**Comment by penacristian** [comment]
@chrisortman do you have the didShowSection code in hand? I'm facing the same problem as you.

**Comment by chrisortman** [comment]
@penacristian I don't sorry. I wound up not implementing it so that it recorded each consent section and instead only audited when the task finished.
