### ISSUE TITLE
ORKCompletionStep bug

### ISSUE THREAD

**Issue by dadixon** [ResearchKit/ResearchKit#871]
How can I fix this?
<img width="487" alt="screen shot 2016-12-01 at 1 22 12 pm" src="https://cloud.githubusercontent.com/assets/1591018/20806558/60bde3e4-b7c9-11e6-8fd3-28a4c03e5a5c.png">

**Comment by ninoguba** [comment]
This is a duplicate of #820 and #864.

**Comment by kelseydedoshka-apple** [comment]
@dadixon This issue has been resolved. Please pull the latest ResearchKit to get the fix.
