### ISSUE TITLE
Custom ORKAudioStep

### ISSUE THREAD

**Issue by dadixon** [ResearchKit/ResearchKit#875]
Is there an easy way to create an ORKAudioStep with extra buttons that start the recorder over? Whenever I do anything with the customView, the ORKAudioGraphView goes away so I'm assuming it overrides the default.

**Comment by umerkhan-apple** [comment]
Could you provide some code for reference?

**Comment by kelseydedoshka-apple** [comment]
@dadixon - friendly ping here to see if you could provide some code for reference

**Comment by dadixon** [comment]
Hey. I was able to create buttons inside the customView but when I click the buttons, nothing happens.

I've added this in:

`func taskViewController(_ taskViewController: ORKTaskViewController, viewControllerFor step: ORKStep) -> ORKStepViewController? {
        
        if step.identifier == "pitch" {
            return PitchStepViewController(step: step)
        } else {
            return nil
        }
    }`

**Comment by kelseydedoshka-apple** [comment]
@dadixon - is your selectionChanged handler being executed and the label text is not changing, or is that action function never being called at all?

**Comment by dadixon** [comment]
Action is never called

**Comment by kelseydedoshka-apple** [comment]
@dadixon - how do you link the selectionChanged handler to the UI element?

**Comment by dadixon** [comment]
I created an nib file.

**Comment by kelseydedoshka-apple** [comment]
@dadixon - From the snippets you provided I don't see any glaring issues that would be causing this problem. Would you be able to upload a sample project with the issue isolated if you are still experiencing this?

**Comment by dadixon** [comment]
I will try to create one for you tomorrow

**Comment by dadixon** [comment]
https://github.com/dadixon/testResearchKit

**Comment by kelseydedoshka-apple** [comment]
@dadixon - thanks for sharing the code, I'll take a look at this.

**Comment by umerkhan-apple** [comment]
Tracking the repo and issue in #909

**Comment by majeedyaseen** [comment]
@dadixon  I can't see your sample project here [https://github.com/dadixon/testResearchKit](https://github.com/dadixon/testResearchKit) can you again share it so I can have a look how to implement the same. I also want to implement a custom ORKAudioStep
