### ISSUE TITLE
HealthStore not set

### ISSUE THREAD

**Issue by safiyyahmohammed** [ResearchKit/ResearchKit#876]
Hi, I'm quite new to xcode and Researchkit, and I'm having an issue. When the profile tab is clicked, it shows fatal error: healthStore not set. How do I fix this please?

**Comment by akshay-yadav-apple** [comment]
Hey @safiyyahmohammed,
In line 44, the variable healthStore of type HKHealthStore is created but never initialized. So when it's being used in line 53, it shows the fatal error. This bug will be fixed in next RK update. 
For now, if you initialize healthStore in line 44, the profile tab will work.

**Comment by biblelogosthegame** [comment]
Has RK been updated yet to fix this bug?  I've tried to change line 44, but every change that I make following the HealthKit docs or tutorial docs results in errors that prevent the application from building.  I have checked my Privacy settings on my device and it shows that my test app is authorized to access my health data, but it crashes whenever I push the button and I checked the stable and master branches and ProfileViewController has no recent changes in this area.  Thank you for any help you can provide.
