### ISSUE TITLE
Where can more information be found for the new "Data Collection Module?"

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#879]

**Comment by kelseydedoshka-apple** [comment]
@cmetts Thanks for the question about the Data Collection Module! Currently the documentation that we provide for this is in the data collection module header files for the code. We will be updating the ResearchKit documentation with more info soon.

**Comment by cmetts** [comment]
ok, but not finding documentation in the header to be very helpful for me. 

Are there any example apps? code?

Thanks
