### ISSUE TITLE
Data Collection Unit Tests Failing

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#881]
The data collection unit tests are currently failing.

**Comment by rsanchezsaez** [comment]
All the data collection unit tests pass for me on the latest `master`.

I experienced test failures in the past due to *HealthKit* permissions. Make sure `ORKTest` has full *HealthKit* access. :-)

**Comment by umerkhan-apple** [comment]
@rsanchezsaez Sounds great!
