### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by safiyyahmohammed** [ResearchKit/ResearchKit#882]
Hello, please how do I get the results from the survey and the active tasks?

**Comment by dannyiss** [comment]
Easiest way to decode how your results are stored, in the taskviewcontroller function after it has been submitted

print(taskViewController.result)

Use that and it should come up with results like below:

<ORKStepResult: 0x600000a71440; identifier: "formSleepDisorder"; enabledAssistiveTechnology: None; results: (
        <ORKChoiceQuestionResult: 0x600000a71d40; identifier: "formSleepDisorder"; answer:
            (
                " 3"
            )>
    )>,

Within the result, you are able to access methods such as result(forIdentifier: "whatever you have called your identifier for the question")

Results are stored via which step they are apart of and then in steps you could have an ORKFormStep which includes multiple elements such as multiple ORKChoiceQuestionResult.

**Comment by akshay-yadav-apple** [comment]
Hey @safiyyahmohammed ,
You can always view the results by following @dannyiss suggestion. This will work for most survey questions. Also, if you are looking for sensor data from the recorders saved in a separate file, you can access the URL with 'fileURL' key, and read thru the file on that location for the sensor data.
