### ISSUE TITLE
Latest Release is Not Available on CocoaPods

### ISSUE THREAD

**Issue by apbendi** [ResearchKit/ResearchKit#885]
Any chance you'd be able to push the latest release (1.4.1) to CocoaPods? This would be especially useful as the author of a framework that depends on ResearchKit, since there is no way to specify an alternative source as a transitive dependency in a podspec file. I'd love for our customers to be able to easily pull in the iOS 10 render bugs corrected in the latest version. Thanks!!

**Comment by kelseydedoshka-apple** [comment]
@apbendi - Thank you for your patience with this. CocoaPods has been updated to 1.4.1. Please let me know if you have any issues getting the latest release.

**Comment by apbendi** [comment]
Thanks @kelseydedoshka-apple
