### ISSUE TITLE
ORKGraphChartView.m: Use of undeclared identifier 'ORKRangedPoint' with TARGET_INTERFACE_BUILDER

### ISSUE THREAD

**Issue by denisbohm** [ResearchKit/ResearchKit#886]
When compiling for interface builder ORKGraphChartView references an undeclared identifier ORKRangedPoint which causes the build to fail.  So no custom views are shown in interface builder.

Should ORKRangedPoint be ORKValueRange?

**Comment by akshay-yadav-apple** [comment]
Hey @denisbohm!
Thank you for bringing this to our attention.
This bug has been reported.

**Comment by akshay-yadav-apple** [comment]
Hey @denisbohm,
Thank you very much for bringing this to our attention. 
I am reporting this as a bug, and closing the issue. 

Please use ORKValueRange instead of ORKRangedPoint until the fix.
Checkout PR #620 for more information.

**Comment by akshay-yadav-apple** [comment]
Hey @denisbohm,

We'd love to have you create a new PR to fix this issue.  can you do that?
The only place ORKRangedPoint exist is in the ORKGraphChartView.m 

-thanks

**Comment by rsanchezsaez** [comment]
I've fixed this as part of [PR #890](https://github.com/ResearchKit/ResearchKit/pull/890).
