### ISSUE TITLE
ORKVideoCaptureStep

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#887]
Is there any documentation on adding a video capture step?

I have done the following:

ORKVideoCaptureStep *step = [[ORKVideoCaptureStep alloc] initWithIdentifier:theInteractionEntity.field_name];
[stepArray addObject:step];

But the app crashes here in ORKvideoCaptureStepViewController.m:

 [_movieFileOutput startRecordingToOutputFileURL:_fileURL
                                      recordingDelegate:self];

I do not see a way to specify the URL, if that is what is needed.

**Comment by ninoguba** [comment]
I believe you need to set the outputDirectory property of your task view controller.

http://researchkit.org/docs/Classes/ORKTaskViewController.html#//api/name/outputDirectory

**Comment by cmetts** [comment]
precisely - thanks so much!

**Comment by ninoguba** [comment]
Great! You can now close this then.
