### ISSUE TITLE
[Review step] API design

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#89]
<rdar://problem/19220394>

Participants should be able to review the data they've entered into ResearchKit apps. This issue is for designing an API for supporting this in ResearchKit.

We'd like to have a review step that could be placed at the end of a survey task, which would allow the user to review their answers. This would take the form of a table view, with roughly one row per answer. It might make sense to make each step a section, so that all the answers in a form come together in a single section.

Tapping on an answer should allow the user to jump to that answer. Supporting this jump will require modifications to `ORKTaskViewController`, and may also require changes to the `ORKTask` protocol. We're open to suggestions on how exactly the "jump" should work, but a secondary modal presentation is unlikely to be the right answer.

The review step should also be usable stand-alone. For instance, an app might store both the task the user completed, and the results of that task. By restoring those, and attaching them to the review step, it should be possible to allow review of their data in a new, entirely separate task.

See also #90 and #91 for follow-on tasks.

**Comment by oliverschaefer** [comment]
An `ORKReviewStep` could be a subclass of a `ORKFormStep`, with one `ORKFormItem` for every answer that was actually given. In order to properly display the form items, this would also require a custom `ORKReviewAnswerFormat` and `ORKReviewQuestionType`, to let the view controller know how to display the corresponding cells correctly.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Are you suggesting we should use `ORKFormStepViewController` to present the results? Since `ORKFormItem` supports all the types of `ORKAnswerFormat`? 

And allow user to modify the results without leaving `ORKReviewStep`, then `jumping` from review step to original step is not necessary?

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Yes, presenting results via `ORKFormStepViewController`should be convenient, especially since it eliminates the need for boilerplate code. However, I think jumping is still necessary. One possible way to do the jump would be: Define a `ORKReviewAnswerFormat` with a 'targetStepIdentifier' property. Once an `ORKFormItem` has been selected, get the `targetStepIdentifier`and use `ORKTaskViewController`'s `showViewController:(ORKStepViewController *)viewController goForward:(BOOL)goForward animated:(BOOL)animated` method to display the corresponding view controller. I've already implemented part of this and will happily share the code with you if you'd like?

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Thanks for starting working on this!

Let me know if we are on the same page. For the UI flow, user is able to tap to go to the next step to see the "original" step with result, and make editing there. Probably need to hide **Continue** button on "original" step but keep **Skip** button on this step. After finish editing, user tap top left corner **Back** button (or kill the result by tapping **Skip**) to go back to review step. 

For the API side, I image `ORKReviewStep` need to take an array of `ORKStep` and another array of `ORKStepResult` as input(If a `ORKStep` is present, then no need have `targetStepIdentifier` ).   

I'm not totally convinced by reusing `ORKFormStepViewController` to present `ORKReviewStep`. The UI could looks similar to the form step, but there are some key differences:
  - Only accept tapping to move to editing view
  - not fetch data from HealthKit
  - text choices only display selected row
  - ...

Maybe worth to create a new `ORKReviewStepViewController` but reuse some of the `ORKFormItemCell` cells. I'm open to discussion.

**Comment by oliverschaefer** [comment]
@YuanZhu-apple UIFlow: I'd like to think of a review step as a task's table of contents. Tapping a cell brings the user back to the original step. From there navigation works as usual: tapping back will call `stepBeforeStep`, while tapping continue will call `stepAfterStep` respectively. What about a separate "go back to review step" option?

API: The review step collects the data from an `ORKTaskResult`. It looks up the `steps` from it's task property. I think the `targetStepIdentifier` will be needed anyway. It might be helpful if you take a look at what I've implemented so far? I've forked the ResearchKit project and committed my changes

**Comment by YuanZhu-apple** [comment]
From encapsulation perspective, I like ORKReviewStepViewController to contain two view controllers:
 - ORKReviewListViewController
 - ORKQuestionViewController/ORKFormStepViewController (Editing)

You can find this type of implementation in `ORKConsentReviewStepViewController`, which is a single step but has two VCs embedded in a child `UIPageViewController`.

The encapsulation prevents `taskViewController` from involving step navigation for reviewing. It will also support review step standalone use case.

Off course, make a pull request, we can discuss there:D

**Comment by oliverschaefer** [comment]
@YuanZhu-apple I've looked at the implementation of `ORKConsentReviewStepViewController`. That really seems to be a better (clearer) approach compared to what I first suggested. I tried things out and realized the following: `ORKStepViewController` and its subclasses are designed to be presented inside an `ORKTaskViewController` (take the scroll view observation for instance). So why not subclassing `ORKTaskViewController` (especially since reviewing includes the presence of steps and step results)? I start thinking that a review step should rather be a review task, what about you?

**Comment by YuanZhu-apple** [comment]
Are you suggesting use `ORKTaskViewController`'s subclass as `ORKReviewStepViewController`?

**Comment by oliverschaefer** [comment]
Maybe a subclass is too much... We could implement an `includeReviewStep` property in `ORKTaskViewController`. If that property is `true` the view controller shows a list of its' managed steps and their current results. Once a user selects an item from that list, the view controller jumps to the corresponding step.

**Comment by YuanZhu-apple** [comment]
I think this the UI flow we both agreed:
````
[Step1] - [Step2] - [Step3] - [ReviewStep] <-> [Step1r] (No done button, only has back button)
                                     |<------> [Step2r] (No done button, only has back button)
                                     |<------> [Step3r] (No done button, only has back button)
```
 After I reviewed the following questions:
```
The review step should also be usable stand-alone. 
For instance, an app might store both the task the user completed, and the results of that task.
```
```
How to push changed result back to ORKTaskVC?
```
```
How to get correct step view controller for `[Step1r]`? (Now all stepVC are from ORKTaskVC) 
```
Make me think most of the responsibility should be put on `ORKTask`.

**Comment by oliverschaefer** [comment]
I totally agree in terms of UI flow. But if we put responsibilities on `ORKTaskViewController` things become a lot easier:
* Stand-alone: If an app stores both tasks and their results, a new `ORKTaskViewController` can be instantiated, with a its' `defaultResultSource` set
* No need to push result changes back to `ORKTaskViewController`
* No need of separate [StepXrVC]. The task view controller simply returns a modified [StepXVC] without the back button
* Universal API for all classes that implement `ORKTask`, not just `ORKOrderedTask`

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Did you get a chance to look at this? Would like to know your opinion before I start implementing...

**Comment by YuanZhu-apple** [comment]
Hey @oliverschaefer I am drafting a more detailed spec for this. Will share it with you by tomorrow.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer  This a drafted plan, open to discussion.

-----------
### Two Scenarios
 - In survey: Display review step at the end(or in the middle) of a survey
  * Accept answer changes
  * Only works with ORKOrderedTask (changing answer could affect the questions set)

- Outside a survey: Display review step **standalone**
  * Not allow answer to be changed (Unless there is good use case)

### ORKReviewStep
- Introduce ORKReviewStep, which has two attributes: 
  * NSArray *steps; 
  * id<ORKTaskResultSource> resultSource;

- `steps`, `resultSource` carry a list of steps with results to be displayed in standalone use case. Leave them empty for in survey use case.

### ORKReviewStepViewControler
 - ORKReviewStepViewControler has two inputs:
  * `steps` (Come from ORKReviewStep or ORKTaskVC)
  * `ORKTaskResultSource` (from reviewStep.resultSource or taskVC.result)

![mockup2](https://cloud.githubusercontent.com/assets/11466704/9002255/7a985284-3716-11e5-85ac-b8ce29b95929.png)

### Modifications to ORKTaskVC

- Be able provides to a pasted steps array (generated from stepIdentifiers in `ORKTaskResult`).
- Configure a reviewStepVC properly:
  * Provide its steps array when the steps on `ORKReviewStep` is nil
  * Set its result object on reviewStepVC when the `resultSource` on `ORKReviewStep` is nil
  * Intercept `(stepAfterStep:)` and `(stepBeforeStep:)` for transitions between reviewStepVC and stepVC. Don’t forward `(stepAfterStep:)` and `(stepBeforeStep:)` to ORKTask during review.

### How to include a review step in survey
```
ORKReviewStep *reviewStep = [[ORKReviewStep alloc] initWithIdentifer:@“reviewStep.identifier”];
ORKOrderedTask *task = [[ORKOrderedTask alloc] initWithIdentifier:@“task.identifier” steps:@[step1, step2, step3, reviewStep]];
ORKTaskViewController *taskVC = [[ORKTaskViewController alloc] initWithTask:task taskRunUUID:[NSUUID UUID]];

(Then present this taskVC)
```

### How to show review step standslone (Outside a survey)
```
ORKReviewStep *reviewStep = [[ORKReviewStep alloc] initWithIdentifer:@“reviewStep.identifier” steps:@[step1, step2, step3]];
reviewStep.resultSource = taskResult;
ORKOrderedTask *task = [[ORKOrderedTask alloc] initWithIdentifier:@“task.identifier” steps:@[reviewStep]];

ORKTaskViewController *taskVC = [[ORKTaskViewController alloc] initWithTask:task taskRunUUID:[NSUUID UUID]];

(Then present this taskVC)
```

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Nice. Will look over it in detail tomorrow.

**Comment by oliverschaefer** [comment]
Hey @YuanZhu-apple, I’ve extended your draft using some pseudo-code below:
<h2>Introduce</h2>
- `ORKReviewStep`
- `ORKReviewStepViewController`
- `ORKReviewStepViewControllerDelegate`
- `ORKReviewStepReviewDirection`

<h2>Change</h2>
- `ORKTaskViewController`

<h2>ORKReviewStep</h2>
<h3>properties</h3>
    NSArray *steps
    ORKTaskResultSource *resultSource
    ORKReviewStepReviewDirection *reviewDirection
<h3>use cases</h3>
- __outside of a survey = standalone__
  - steps array is provided upon initialization
  - review step is at the beginning
  - step results may not be changed
  - review direction defaults to forward
		
- __within a survey__
  - steps array is nil
  - review step is at the end or in the middle
  - step results can be changed
  - review direction defaults to reverse			

<h2>ORKReviewStepViewControllerDelegate</h2>
<h3>methods</h3>
    reviewStepViewController: shouldIncludeStep: 
        called to determine if a step should be included in the review
    
    reviewStepViewController: canChangeAnswerForStep: 
        called to determine if an answer can be changed during review
    
    reviewStepViewController: willReviewStep: 
        called when a step is selected for review

<h2>ORKReviewStepViewController</h2>
<h3>properties</h3>
    NSArray *steps
    ORKTaskResultSource *resultSource
    ORKReviewStepViewControllerDelegate *reviewDelegate
<h3>methods</h3>
    discoverSteps:
        copy steps array from review step
        if steps array is nil
            repeatedly call stepAfterStep: (reviewDirection forward) or stepBeforeStep: (reviewDirection reverse) until upcoming step is nil or another review step is reached
            for every step in steps array
                call reviewStepViewController: shouldIncludeStep:
            reload tableView data			

    viewDidLoad:
        discoverSteps

    tableView: didSelectRowAtIndexPath:
        if reviewStepViewController: canChangeAnswerForStep: returns true, call reviewStepViewController: willReviewStep:

<h2>ORKTaskViewController</h2>
<h3>properties</h3>
    NSArray *navigationStack
    
<h3>methods</h3>
    pushStepOnNavigationStack:

    popStepFromNavigationStack:

    reviewStepViewController: shouldIncludeStep: 
        returns YES if the given step should be included in the review, otherwise NO

    reviewStepViewController: canChangeAnswerForStep: 
        returns YES if the given step can be edited during review, otherwise NO

    reviewStepViewController: shouldIncludeStep:
        return YES

    reviewStepViewController: canReviewStep:
        within a survey return YES, otherwise NO

    reviewStepViewController: willReviewStep:
        call viewControllerForStep:
        push reviewStep and step on navigationStack
        call flipToNextPageFrom:

    viewControllerForStep:
        initialize ORKReviewStepViewController
        set resultSource
        set self as reviewDelegate

    nextStep:
        if navigationStack is not empty, pop last element from stack and return it			

    prevStep:
        if navigationStack is not empty, pop last element from stack and return it

**Comment by YuanZhu-apple** [comment]
@oliverschaefer Do you mind to create a PR **only** include your extended draft in markdown format?
It is easier for us to share comments. Thanks!

**Comment by oliverschaefer** [comment]
@YuanZhu-apple Close this one?

**Comment by SarahUCD** [comment]
Is anyone willing to share the code for a standalone Review Step in Swift language? I am new to github and swift programming.
