### ISSUE TITLE
Website has placeholders for feed and favicon in <head>

### ISSUE THREAD

**Issue by akoeplinger** [ResearchKit/ResearchKit#9]
The [website](http://researchkit.github.io/) has some placeholders for the feed+favicons in `<head>`, those should be filled in I guess:

![image](https://cloud.githubusercontent.com/assets/1376924/7143154/1d2f34a0-e2de-11e4-9b99-bbbf4778604b.png)

**Comment by jwe-apple** [comment]
Yep, thanks!

**Comment by YuanZhu-apple** [comment]
Now the website has been updated.
