### ISSUE TITLE
[Review step] Implementation of review step

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#90]
<rdar://problem/19220394>

Participants should be able to review the data they've entered into RK apps. This issues is for implementing the review step, following on from #89 (API design)

We'd like to have a review step that could be placed at the end of a survey task, which would allow the user to review their answers. This would take the form of a table view, with roughly one row per answer. It might make sense to make each step a section, so that all the answers in a form come together in a single section.

Tapping on an answer should allow the user to jump to that answer. Supporting this jump will require modifications to ORKTaskViewController, and may also require changes to the ORKTask protocol. We're open to suggestions on how exactly the "jump" should work, but a secondary modal presentation is unlikely to be the right answer.

The review step should also be usable stand-alone. For instance, an app might store both the task the user completed, and the results of that task. By restoring those, and attaching them to the review step, it should be possible to allow review of their data in a new, entirely separate task.

**Comment by KaiCode2** [comment]
Is there any progress or plans this task? If not I'd like to try to take this one on. It would most likely be at a pretty slow pace so if this one is non-urgent I'd like to take it on.

**Comment by YuanZhu-apple** [comment]
@oliverschaefer is working on this one.

**Comment by oliverschaefer** [comment]
@KaiCode2 Thanks for your commitment. @YuanZhu-apple and I are actively working on this one. See PR #463 for more information on the progress we make.

**Comment by KaiCode2** [comment]
👍🏼

**Comment by rsanchezsaez** [comment]
I think this issue can now be closed as the aforementioned PR was merged.
