### ISSUE TITLE
ResearchKit 1.3.1 Cocoapod missing ORKValueRange

### ISSUE THREAD

**Issue by patrickcze** [ResearchKit/ResearchKit#906]
This is not currently present within the cocoa pods version and is preventing users from being able to use ORKLineGraphView from working.

This appears to be a reoccurring issue that was previously closed.

 https://github.com/ResearchKit/ResearchKit/issues/796

**Comment by kelseydedoshka-apple** [comment]
@patrickcze - CocoaPods has been updated to 1.4.1 - this may resolve your issue. Please try the latest and let me know if this helps you out.
