### ISSUE TITLE
Image Capture Step's title or text not working

### ISSUE THREAD

**Issue by gitspider** [ResearchKit/ResearchKit#911]
I want to set the title or comment of ORKImageCaptureStep.
```
let imageStep = ORKImageCaptureStep(identifier: kStepAllPicture)
imageStep.title = "Title"
imageStep.text = "capture"
```

But none of these work. How could I do that?

**Comment by kelseydedoshka-apple** [comment]
@gitspider - ORKImageCaptureStep does not currently support title and text options. You could include an instruction step before the image capture step which displays the title and text you want.
