### ISSUE TITLE
Is there a reason why ORKWaitStep forbids backward navigation?

### ISSUE THREAD

**Issue by Sonictherocketman** [ResearchKit/ResearchKit#914]
Running into this issue. I have a wait step that manages some processing based on user input that could fail. I'd like to return the user to the previous step to try different input if an error occurs, but `ORKWaitStep` expressly forbids this; not sure why.

```obj-c
- (BOOL)allowsBackNavigation {
    return NO;
}
```

[Source &#8594;](https://github.com/ResearchKit/ResearchKit/blob/4f3d0f33df3ca96764ccac72a2dda729a567ac33/ResearchKit/Common/ORKWaitStep.m#L79)

Can this be addressed, or at least some addition made to the documentation to explain that it isn't possible?

Spent too long trying to debug why I was getting a nil view.

**Comment by ninoguba** [comment]
It is possible to "go back" from ORKWaitStep.   Here's a snippet of code that lets you go back in the event of an error, for example:

`func taskViewController(_ taskViewController: ORKTaskViewController, stepViewControllerWillAppear stepViewController: ORKStepViewController) {
        if (stepViewController.step?.identifier == "Wait") {
            
            // Get answers from login step
            let loginStepResult = taskViewController.result.stepResult(forStepIdentifier: "Login")
            let loginStepResultUsernameQuestion = loginStepResult?.result(forIdentifier: "ORKLoginFormItemEmail") as! ORKQuestionResult
            let loginStepResultUsernameAnswer = loginStepResultUsernameQuestion.answer as! String
            let loginStepResultPasswordQuestion = loginStepResult?.result(forIdentifier: "ORKLoginFormItemPassword") as! ORKQuestionResult
            let loginStepResultPasswordAnswer = loginStepResultPasswordQuestion.answer as! String
            
            // Verify login credentials
            if let stepViewController = stepViewController as? ORKWaitStepViewController {
                BackendHelper.login(username: loginStepResultUsernameAnswer, password: loginStepResultPasswordAnswer) { (status, json) in
                    if (status) {
                        // Success
                        stepViewController.goForward()
                    } else {
                        // Error
                        self.showAlert(message: NSLocalizedString("Problem validating user credentials.", comment: ""), title: "Login Error", controller: taskViewController)
                        stepViewController.goBackward()
                    }
                }
            }
            
        }
    }`

This is a code I use for validating log in credentials during the wait step.  If success proceed to next step, otherwise go back the previous step.  Hope this gives you an idea for your use case.

**Comment by umerkhan-apple** [comment]
@Sonictherocketman +1 for @ninoguba response. Did that help resolve your issue?
