### ISSUE TITLE
ORKVideoCaptureStep's 'duration' property has an automatic maximum value of 120 in seconds

### ISSUE THREAD

**Issue by sunkistmehta** [ResearchKit/ResearchKit#917]
According to the description of this property, the maximum that this can be set to is 20.0 minutes (60*20 seconds i.e **1200 seconds**). However, any value that is greater than 120 is automatically defaulted to **120 seconds**. This means that the video can only be recorded for a maximum of 120 seconds.

If anyone has come across this problem and has corrected it or found a different solution, please guide me too.

Thanks in advance.

**Comment by umerkhan-apple** [comment]
@sunkistmehta You are correct in your findings. This a bug. Would you be able to provide a PR with the fix? The default duration would still be 120 seconds, while the max duration should be 1200 seconds. Thanks!

**Comment by rochoSC** [comment]
I know where is the problem. I'll submit a PR in a couple of hours (need to figure out the process)

**Comment by rochoSC** [comment]
Solved in PR #954

**Comment by sunkistmehta** [comment]
@rochoSC Thank you for solving this in your PR.

**Comment by umerkhan-apple** [comment]
PR has been merged. Thanks @rochoSC
