### ISSUE TITLE
Jump to the next question when answering  ORKAnswerFormat.booleanAnswerFormat()

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#918]
Is it possible make the survey jump to the next question as soon as the user taps either Yes or No?? 

Currently, after tapping yes or no, user needs to tap "Next" button to go to the next question.

**Comment by ninoguba** [comment]
Use the BooleanAnswerFormat and that will go to the next step right away.

**Comment by iaarpit** [comment]
Your step should not be skippable. If you set the isOptional property to false, it should work the way you want.

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez - the suggestions above should solve your issue. Were you able to get the functionality working as desired?

**Comment by JorgeAGomez** [comment]
@kelseydedoshka-apple I am currently working on it. I will let you know if I can make the functionality working as I want to. 

Thanks everyone for the help!

**Comment by JorgeAGomez** [comment]
UPDATE: Thanks @iaarpit !! Is working just the way I wanted it. @kelseydedoshka-apple  I got it working. Thanks again!!

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez great thanks for letting us know you got it working! Closing this issue.
