### ISSUE TITLE
Help with getting results from ORKStep

### ISSUE THREAD

**Issue by jayp27** [ResearchKit/ResearchKit#919]
Hi, I am learning to use ResearchKit. I am new to coding in Swift. I do know programming in Java and C. 

Below is sample of what I have.

   public var SurveyTask: ORKOrderedTask {
 
    var steps = [ORKStep]()
    
    //Intructions step
    let instructionStep = ORKInstructionStep(identifier: "IntroStep")
    instructionStep.title = "Instructions"
    instructionStep.text = "Please answer these questions to the best of your ability. By beginning, you understand that data will be shared with authorized hospital personnel."
    steps += [instructionStep]

    
    //Question name
    let nameAnswerFormat = ORKTextAnswerFormat(maximumLength: 20)
    nameAnswerFormat.multipleLines = false
    //    nameAnswerFormat.isOptional = false
    let nameQuestionStepTitle = "What is the name of the patient?"
    let nameQuestionStep = ORKQuestionStep(identifier: "NameStep", title: nameQuestionStepTitle, answer: nameAnswerFormat)
    nameQuestionStep.isOptional = false
    steps += [nameQuestionStep]
    
    
    //Breathing
    let breathingStepTitle1 = "What of the following apply to your child's current breathing condition? (check all that apply)"
    let breathingChoices = [
        ORKTextChoice(text: "Home oxygen use", value: "Home oxygen use" as NSString),
        ORKTextChoice(text: "Cystic fibrosis", value: "Cystic fibrosis" as NSString),
        ORKTextChoice(text: "Chronic lung disease", value: "Chronic lung disease" as NSString),
        ORKTextChoice(text: "Asthma", value: "Asthma" as NSString),
        ORKTextChoice(text: "Chronic cough", value: "Chronic cought" as NSString),
        ORKTextChoice(text: "Use of an inhaler", value: "Use of an inhaler" as NSString),
        ORKTextChoice(text: "Difficulty swallowing", value: "Difficulty swallowing" as NSString),
        ORKTextChoice(text: "None", value: "None" as NSString)
    ]
    let breathingAnswerFormat =  ORKAnswerFormat.choiceAnswerFormat(with: .multipleChoice, textChoices: breathingChoices)
    let breathingStep = ORKQuestionStep(identifier: "Breathing", title: breathingStepTitle1, answer: breathingAnswerFormat)
    breathingStep.isOptional = false
    steps += [breathingStep]
    
   
    //Completion
    let summaryStep = ORKCompletionStep(identifier: "SummaryStep")
    summaryStep.title = "Information Recorded"
    summaryStep.text = "Please finish the remaining steps"
    steps += [summaryStep]
    
    //-----------------------------------------------------------------------
    
    return ORKOrderedTask(identifier: "Questions", steps: steps)

I am looking for help to get answer the user has input or selected from the given choices.

I tried the code:

func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?){
    
        switch (reason) {
        case .completed:
                let taskResult = taskViewController.result.results
                
                for stepResults in taskResult! as! [ORKStepResult]
                {
                    print("---")
                    for result in stepResults.results!
                    {
                        if result.identifier == "NameStep"
                        {
                            print(result)
    
                        }
                        if result.identifier == "Breathing"
                        {
                           print(result)
                        }
                    }
                }
            }
      }

This printed results show after running what I have on simulator:

`---
<ORKTextQuestionResult: 0x61000026a280; identifier: "NameStep"; answer: Jay>
---
<ORKChoiceQuestionResult: 0x61800026fc00; identifier: "Breathing"; answer:
    (
        "Chronic cought",
        "Use of an inhaler",
        "Difficulty swallowing"
    )>
---

`

I want to be able to make a 

var name = Jay
and
var breathing = 456 (because they are in the position 4,5,6 according to the index of available text choices to choose from)

My goal is to send the data in some form over the web maybe have a PHP script (which I will also learn once i get results to work)

I have googled and tried to follow some many threads but I have not had any success other than being able to print what I have above.

I am open to ideas to how to send my results from the questionnaire in a readable format over the internet.

Thank you in advance!

**Comment by dannyiss** [comment]
Can you not just change the value on each of the ORKTextChoice within Breathing to the numbers 1-5?

**Comment by kelseydedoshka-apple** [comment]
@jayp27 - You are almost there to getting the answer values. In each of your if statements in your stepResults.results for loop instead of printing the result, you can cast the result as the type of the question result and from there you can access the answer property.

For the name you can do something like:

// Please remember to check for nil and type before forcing the type cast and unwrapping the answer value.
let nameAnswerResult = result as! ORKTextQuestionResult
let name = nameAnswerResult.answer!

You can do the same for each of your answers.

**Comment by jayp27** [comment]
@dannyiss  I will be doing it later to make it easier when putting data together

@kelseydedoshka-apple 

Thank for helping me.

So did as you suggested.
`for stepResults in taskResult! as! [ORKStepResult]
                {
                    print("---")
                    for result in stepResults.results!
                    {
                        if result.identifier == "NameStep"
                        {
                            let nameResult = result as! ORKTextQuestionResult
                            let name = nameResult.answer!
                            print(name)
                            
                        }
                        if result.identifier == "Breathing"
                        {
                            let breathingResult = result as! ORKChoiceQuestionResult
                            let breathing = breathingResult.answer!
                            print(breathing)
                           // print(taskResults.stepResult(forStepIdentifier: "Breathing"))
                        }
                    }
                }
`

`---
Jay
---
(
    "Home oxygen use",
    "Cystic fibrosis",
    "Chronic lung disease",
    Asthma,
    "Chronic cought"
)
---`

It worked that you very much!

I have a follow up question however.
As you see the result of Breathing, Asthma is without quotes while all the other options are within quotes. Any idea why that would be happening?

Another question is I am trying to individually check what answers have been selected.
`if result.identifier == "Breathing"
                        {
                            let breathingResult = result as! ORKChoiceQuestionResult
                            let breathing = breathingResult.answer!
                            print(breathing)
                            let bsize = (breathing as AnyObject).count
                            print(bsize)
                            
                            for index in 0 ..< bsize!
                            {
                                print(breathing[index])
                            }
                            
                           // print(taskResults.stepResult(forStepIdentifier: "Breathing"))
                        }
`
the above code print(bsize) prints: Optional(5) since I selected 5 of the options available.

for example: I want to to see breathing at index: 0, breathing[0] = Home Oxygen use. Next breathing[1] = Cystic Fibrosis. 
How can i do that? The above code gives error where i have print(breathing[index])

Thank you in advance!

**Comment by kelseydedoshka-apple** [comment]
@jayp27 you can use navigable ordered tasks to set predicate rules on steps in your task. Create predicate rules for your height > 3 and determine proper navigation based on the result. More info on navigable order tasks can be found in the ResearchKit documentation. 

I don't know that you need to change the units being stored to resolve your first issue - can you just convert the units at the time that you need to display them or compute the calculation?

**Comment by jayp27** [comment]
@kelseydedoshka-apple
Thanks for the tip. I actually solved most of what I mentioned. However I still don't know how to use  navigable ordered tasks. Could please give me example in swift 3. 
Follow up question: As you see I have already added all the questions to my ORKsteps but will it update automatically by using the answer for previous question to determine if the question(the step) should be skipped in my ORKsteps ? 

Thank you in advance.

**Comment by kelseydedoshka-apple** [comment]
@jayp27 - you can find more information on the navigable ordered tasks here: http://researchkit.org/docs/Classes/ORKNavigableOrderedTask.html

To get the behavior you are looking for you need to set predicate rules that will determine which steps to automatically go to depending on the responses to previous questions. By creating these rules and attaching them to the task the navigation you desire should happen automatically.

**Comment by kelseydedoshka-apple** [comment]
@jayp27 - Checking in here to see if you had success using the NavigableOrderedTask or if you are still having issues with this?

**Comment by jayp27** [comment]
@kelseydedoshka-apple thank you for checking back. Since the project I am working on is just to showcase an idea and not for releasing. My team decided not to worry about adding navigableOrderedTask for now. But I did look into the NavigavleOrderedTask and I was learning but team needs me to finish some other things so I are skipping that for now. 

Thank you again for the help!
