### ISSUE TITLE
Graphs for viewing historical HealthKit and ResearchKit data

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#92]
AppCore has a graphing component that the initial apps use to present ResearchKit and HealthKit data (see `APCGraph`). We think it might make sense to import that code in some form into ResearchKit. Some of the requirements for HealthKit data display in research apps are very specific, so it might make sense to include some limited charting capabilities in ResearchKit.

This task is to review the `APCGraph` code and propose an appropriate API for ResearchKit graphing, and then import, document, and write appropriate demos.

#178

**Comment by coxy1989** [comment]
Something like that?

**Comment by jwe-apple** [comment]
A commendable effort. A few more `APC`'s to get rid of there, but yes, please get a PR in.

**Comment by rsanchezsaez** [comment]
Probably we can close this as the *Charts module* has been merged.

Any charts improvement should be reported as a separate issue.
