### ISSUE TITLE
How to set navigable rules for ORKPageStep in a task?

### ISSUE THREAD

**Issue by iaarpit** [ResearchKit/ResearchKit#921]
I tried different ways to implement but it's not working. Please, can someone give me an example code?

This is one of the way I implemented it.
```
//quiz 1
let quiz1Question = "What is the purpose of this Study?"
let quiz1TextChoices = [
            ORKTextChoice(text: "0", value: 0 as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: "1", value: 1 as NSCoding & NSCopying & NSObjectProtocol)
        ]
let quiz1AnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: quiz1TextChoices)
let quiz1step = ORKQuestionStep(identifier: "quiz1step", title: quiz1Question, answer: quiz1AnswerFormat)
        
// Failure step
let failureStep = ORKInstructionStep(identifier: "failureStep")
failureStep.title = "Try again"
        
// Success step
let successStep = ORKCompletionStep(identifier: "successStep")
successStep.title = "Great Job!"

let pageStep = ORKNavigablePageStep(identifier: "pageStep", steps: [quiz1step, failureStep, successStep])
      
let pageSampleTask = ORKNavigableOrderedTask(identifier: "pageSampleTask", steps: [pageStep])

let resultSelector = ORKResultSelector(stepIdentifier: "pageStep", resultIdentifier: "quiz1step")

let predicateQuiz1 = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: 0 as NSCoding & NSCopying & NSObjectProtocol)

let quizPredicateRule = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateQuiz1, "successStep")])

pageSampleTask.setNavigationRule(quizPredicateRule, forTriggerStepIdentifier: "pageStep")
```

**Comment by syoung-smallwisdom** [comment]
You need to setup your task first and then instantiate the pageStep using it.

````
let pageTask =  ORKNavigableOrderedTask(identifier: "pageStep", steps: [quiz1step, failureStep, successStep])
// Setup navigation
let pageStep = ORKNavigablePageStep(identifier: "pageStep", pageTask: pageTask)
````

**Comment by iaarpit** [comment]
@syoung-smallwisdom It worked. Thanks.

But, In the main task, 
`let mainTask = ORKNavigableOrderedTask(identifier: "mainTask", steps: [pageStep, followUpStep])`

- There is no way to go to `followUpStep` if the last step in the `pageStep` is `ORKCompletionStep`
- `pageStep` doesn't allow to navigate back if its first in the steps array of the `mainTask`.

<img width="337" alt="screen shot 2017-02-16 at 11 05 37 am" src="https://cloud.githubusercontent.com/assets/20975999/23029272/f5c7ca72-f437-11e6-8ba9-1c8259b3fa4b.png">

**Comment by syoung-smallwisdom** [comment]
@iaarpit 
Sorry, I don't entirely understand your issue. Which direction are you trying to navigate, and why? 

If you are including an `ORKCompletionStep` as a substep of the `ORKPageStep` then no, the base ResearchKit implementation does not allow navigating away from the completion step b/c it is intended as an endpoint and hides the next button.  I have implemented a work-around to this which is to set the `shouldShowContinueButton` property on the `ORKCompletionStepViewController` to `true`, but this is *not* the default behavior.

The `ORKPageStep` was designed to allow modeling a set of steps that would be grouped into a single `ORKStepResult`.

Some example uses:
https://github.com/Sage-Bionetworks/BridgeAppSDK/blob/master/BridgeAppSDK/SBAConsentReviewStep.swift
https://github.com/Sage-Bionetworks/BridgeAppSDK/blob/master/BridgeAppSDK/SBAExternalIDStep.swift
https://github.com/Sage-Bionetworks/ResearchUXFactory-iOS/blob/master/ResearchUXFactory/SBATrackedSelectionStep.swift

All of these use an older implementation that is not backed by an `ORKOrderedTask` but they can still serve as a reference point. They all return a consolidated result that is created from the individual steps in the collection.

**Comment by iaarpit** [comment]
@syoung-smallwisdom Thank you examples. 

`ORKCompletionStep` if used as a subStep anywhere in the array in `ORKNavigableOrderedTask` allows navigating away. So I was assuming the same behavior if I instantiate `ORKPageStep` with a task having `ORKCompletionStep`.

- `pageStep` doesn't allow to navigate back if it is first in the steps array of the `mainTask`.
In the above point, I am trying to ask why I cannot see a back button in the Navigation bar?

**Comment by syoung-smallwisdom** [comment]
@iaarpit 
Default "navigate away" from a completion step is to change the `leftBarButtonItem` to next instead of cancel. For `ORKPageStep`, all the sub-steps are wrapped within a `UIPageViewController` that shows the `ORKStepViewController` for the current sub-step. The `leftBarButtonItem` points at whatever is the expected item for the page step and *not* for the sub-step.  Therefore, to display a navigation element (next button) to navigate away from the `ORKCompletionStep` you will need to set the `shouldShowContinueButton` on the instantiated `ORKCompletionStepViewController` to `true`.

**Comment by iaarpit** [comment]
@syoung-smallwisdom Thank you for the response. 

One last question, 
There is no `backButtonItem` in the `navigationBar` when it is `ORKPageStep`? Was there a reason to do that or am I missing anything?

<img width="337" alt="screen shot 2017-02-16 at 11 05 37 am" src="https://cloud.githubusercontent.com/assets/20975999/23029272/f5c7ca72-f437-11e6-8ba9-1c8259b3fa4b.png">

**Comment by syoung-smallwisdom** [comment]
If you look at the example in `ORKTest` there is a back button. Because the `ORKPageStep` is the first step in your scenario there is no where to go back to (so the back button is hidden).

**Comment by iaarpit** [comment]
@syoung-smallwisdom 
Thank you for the help. So it means there is no way to navigate back in `ORKPageStep` itself. Thanks again
