### ISSUE TITLE
Changing colours of UIButtons, UILabels, UITableViewCell. 

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#924]
For the first screenshot (ORKInstruction), I want to change the text "Tell us how you feel" to color White. As well as the color of "Self Assessment". In addition, how can I change the background of the button? I want the border to be green (Like the navigation bar), and the background blue as the view background. 

For the second screenshot, how can I modify the color of "Yes" and "No"?? 
And how can I change the background color of the cell to match the view background color ?? (blue)

![simulator screen shot feb 18 2017 10 39 58 am](https://cloud.githubusercontent.com/assets/6026875/23095401/a6ace248-f5c6-11e6-97fd-6ae62b3bfbc3.png)
![simulator screen shot feb 18 2017 10 40 04 am](https://cloud.githubusercontent.com/assets/6026875/23095404/a798dd88-f5c6-11e6-8413-9f21c25ce361.png)

**Comment by JorgeAGomez** [comment]
I already figured out how to change colours for everything except for the Labels "Self assessment" and "Tell us how you feel".

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez - the "Get Started" UIButton should inherit the tintColor from the applications window tint color. If you set your window tintColor in your AppDelegate - all buttons will inherit that color. Or you can just set your container tintColor where necessary to have the children views pick it up.

If you are using ResearchKit steps, the "Tell us how you feel" and "Self assessment" text labels don't currently have an API to change their color. This is something you would have to build out in the ResearchKit framework.

**Comment by umerkhan-apple** [comment]
@JorgeAGomez You could also use UIAppearance to update the color of UILabel throughout the app and that should get adopted by RK labels as well.
