### ISSUE TITLE
Displaying information only as ORKFormItem

### ISSUE THREAD

**Issue by tobiasjungnickel** [ResearchKit/ResearchKit#925]
Are there form items to only display information - of text and of images - in an ORKFormStep without the ability to input or select data by the user?

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel -  In general you can use an InstructionStep to just display information to the user without allowing them to interact with the step. Let me know if this works for your use case.

**Comment by tobiasjungnickel** [comment]
@kelseydedoshka-apple i was searching for a more tabular way. ORKFormItems with choiceAnswerFormatWithStyle:textChoices and choiceAnswerFormatWithImageChoices would have been perfect but without the need/possibility to select any item by the user.

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel - Thanks for the clarification, I now understand what you are looking for.

At the moment choiceAnswerFormatWithStyle only supports single and multiple choice selections. This is something that could potentially be extended to support no selection, or an additional form type could be added that looks similar to choiceAnswerFormatWith style but does not allow user interaction.

If you happen to go down one of these routes we would love to have it contributed back!

**Comment by tobiasjungnickel** [comment]
@kelseydedoshka-apple i was considering that too, but it looks as to much overhead to use form items just for displaying information in table views. A better solution, which i already started, might be to extend ORKTableStep with convenient functionality to also configure sections instead of just items and also different types of cells not only for text but also images and so on.

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel - I like your proposed solution as well. Please feel free to reach out with any questions as you finish developing the feature!

**Comment by kelseydedoshka-apple** [comment]
@tobiasjungnickel - closing this issue. Please feel free to reach back out if you need assistance developing this.
