### ISSUE TITLE
Unable to navigate back to previous subclassed ORKActiveStep

### ISSUE THREAD

**Issue by rmquapp** [ResearchKit/ResearchKit#927]
New to ResearchKit and having trouble implementing a custom ORKActiveStep. I subclassed ORKActiveStepViewController exactly as described in #711 and it's showing up fine, but when Next is clicked and it goes to the next (non-custom) step, there is no back button to return to the custom step.
Am I missing something obvious or can this not be done?

**Comment by kelseydedoshka-apple** [comment]
@rmquapp - do you mind sharing a code snippet of how you have this setup? You should be able to accomplish the functionality you are looking for, but I would need to see what you have so far to try and narrow down the issue.

**Comment by umerkhan-apple** [comment]
@rmquapp In `ORKStep_Private.h`, there is a boolean property `allowsBackNavigation`. If that is set to `YES` on the step after your custom active step, then you will not be able to go backwards. This is a setting on that non-custom step and is not a side-effect from your active step.

**Comment by rmquapp** [comment]
We had decided to make do without the custom screen because we were blocked by this issue at the time, but thank you anyway for your replies, we'll keep that in mind for the future!
