### ISSUE TITLE
Passcode screen doesn't show number pad when Touch ID is enabled

### ISSUE THREAD

**Issue by emersonf** [ResearchKit/ResearchKit#931]
I'm working on a ResearchKit 1.4 app that has been set up for Passcode and Touch ID. When opening the app, the modal is shown asking for Touch ID to be used. But it's possible to press Cancel on the modal. If that happens, the modal goes away, but the number pad isn't shown (see the screenshot). 

I can actually tap the blank space where the numbers *should* be rendered to enter the passcode, but the number pad isn't rendered.

[
![img_0048](https://cloud.githubusercontent.com/assets/834831/23580593/48c52fda-010d-11e7-8f4e-10966c5d0b02.PNG)
](url)

**Comment by stevemoser** [comment]
I see this screen all the time in the simulator when I have 'Connect Hardware Keyboard' turned on. Do you see this on device without a Bluetooth keyboard attached?

**Comment by emersonf** [comment]
Yep, the screenshot's from an iPhone 7. Bluetooth isn't even enabled.

**Comment by umerkhan-apple** [comment]
@emersonf Using RK 1.4, I was able to get the keyboard to show on the Simulator if the `Connect Hardware Keyboard` option is turned off. Even when it is turned on, I was able to get the keyboard to show by clicking the `Toggle Software Keyboard` option.

**Comment by syoung-smallwisdom** [comment]
@umerkhan-apple @joshbruhin 
I believe this is the issue addressed by https://github.com/ResearchKit/ResearchKit/pull/915

**Comment by umerkhan-apple** [comment]
@syoung-smallwisdom Great! Merged that change in to facilitate that edge case! Thank you! 👍
