### ISSUE TITLE
Setting vertical to false in ORKAnswerFormat.scale does not work. 

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#932]
Any suggestions?

<img width="373" alt="screen shot 2017-03-06 at 10 43 17 am" src="https://cloud.githubusercontent.com/assets/6026875/23621919/cecad8da-0259-11e7-9451-fcbada2cc3ce.png">

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez - would you be willing to share the code snippet where you are setting this up?

**Comment by umerkhan-apple** [comment]
@JorgeAGomez What version of RK and iOS are you using? There were some layout issues introduced with iOS 10. However, they should have been fixed in the latest RK. If you can check with the latest master and let me know if the issue still exists.

**Comment by JorgeAGomez** [comment]
@umerkhan-apple Thank you very much. I updated the pod and it fixed the problem. It was indeed a problem with iOS 10. You can close this issue now.

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez - glad you were able to resolve your problem.

**Comment by JorgeAGomez** [comment]
<img width="376" alt="screen shot 2017-03-21 at 12 08 16 am" src="https://cloud.githubusercontent.com/assets/6026875/24134535/98033348-0dca-11e7-938f-d9fee05ae4a8.png">


Well apparently the problem is now on this screen. Any solutions for this?
