### ISSUE TITLE
Duplicate interface definition for class 'ORKLineGraphChartView'

### ISSUE THREAD

**Issue by stealthsyco** [ResearchKit/ResearchKit#933]
After updating my ResearchKit from 1.3.1 -> 1.4.1 I've come into this issue. I used cocoapods to update. I also tried installing ResearchKit manually with the same issue. I can't seem to figure out what is causing this issue. Any help would be greatly appreciated.

**Comment by umerkhan-apple** [comment]
@stealthsyco Did you try doing a clean build? If so, would it be possible to provide a sample project with the issue isolated for the team to debug?

**Comment by umerkhan-apple** [comment]
@stealthsyco Are you still experiencing this issue or is it okay to close this one?

**Comment by kelseydedoshka-apple** [comment]
@stealthsyco - have you tried doing a full project clean and rebuild? Sometimes there can be build issues when updating the version if old data is still cached for the build.
