### ISSUE TITLE
[README] Examples should be updaated to reflect new syntax

### ISSUE THREAD

**Issue by johnsaigle** [ResearchKit/ResearchKit#939]
In trying out the demo in the README, I ran into errors with the [Present the Task](https://github.com/ResearchKit/ResearchKit#4-present-the-task) section as the function signature for `ORKTaskViewControllerDelegate` has changed. 

`didFinishWithReason` should be changed to `didFinishWith`, and `NSError?` should be changed to `Error?` for this introductory example.

**Comment by johnsaigle** [comment]
Addressed in this PR https://github.com/ResearchKit/ResearchKit/pull/940

**Comment by umerkhan-apple** [comment]
@johnsaigle PR tracking this change has been merged! Thanks for the contribution! 👍
