### ISSUE TITLE
Answers from survey.

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#943]
Can I get an example on how to print to the console the boolean answer of each question?

I want to check the answer every time a question is answered. As soon as the user answer "yes" or "no" I will check what the answer is. 

Basically, I want to show extra questions, depending on the answers. If a user scores 3pts, then 3 extra questions will appear. 

I am using Swift 3. 

Any help would be great thanks.!

**Comment by dannyiss** [comment]
What are you trying to achieve? Are you trying to create a survey that has
branching logic? Or are you wanting to store the data?

**Comment by JorgeAGomez** [comment]
I am trying to create a survey with branching logic. My survey at the beginning will always have 12 questions. Based on the answers on these 12 questions the user will get 3 more questions. Questions are mostly "Yes" or "No", so if user answers "Yes", they get 1 point. If at the end of question 12, the user has 3 or more points, then 3 more questions will popup automatically. 

Any suggestions to implement this? 

Thanks!

**Comment by dannyiss** [comment]
I am going to assume you have separated your View Controller and the Survey into different classes. I would create a function in the Survey Class: 
```
func getResults( taskResult: ORKTaskResult) -> Int {
  let results = taskResult.result.results
        var aCounter: Int = 0
        for result in results!
        {
           //Modify the if statement to include other types of questions that will add to the aCounter
          //e.g (result as! ORKTextQuestionResult).textAnswer == 'Sick'
            if (result as! ORKBooleanQuestionResult).booleanAnswer == 1
            {
                aCounter += 1
            }
            
        }
    return aCounter
}
```
I would then check what the returned variable is and from there present the extra questions. This does sound like a "workaround". However, the other option is if you are already familiar with predicates and using them with an ORKNavigableTask. You would have to setup a predicate that checked all of the questions and your final `ORKPredicateStepNavigationRule` would be hideously long! `let predicateLightHeadache: NSCompoundPredicate = NSCompoundPredicate(andPredicateWithSubpredicates: [predicateHeadache, predicateSevereNo])` Something like this would be required and it would be quite hard to implement considering you do not know the combination in which they will select the questions in.

**Comment by ninoguba** [comment]
This is exactly what ORKNavigableOrderedTask is for.

http://researchkit.org/docs/Classes/ORKNavigableOrderedTask.html

Based on answers it will or will not present your "extra" steps depending on how you set up your predicates.

Refer to this in the documentation:

http://researchkit.org/docs/docs/Survey/CreatingSurveys.html

**Comment by umerkhan-apple** [comment]
@JorgeAGomez I recommend @ninoguba suggestion of using a navigable ordered task. A navigable ordered task allows you to create branching logic for a survey based on responses provided in the survey.

`ORKCatalog` has an example survey that you can use a reference.

Let me know if you have any other questions, or if we can close this issue.
