### ISSUE TITLE
Trying to Implement didChange Result: ORKTaskResult

### ISSUE THREAD

**Issue by dannyiss** [ResearchKit/ResearchKit#945]
```
 func taskViewController(_ taskViewController: ORKTaskViewController, didChange result: ORKTaskResult) {
        self.result = result
        print(self.result?.results)
    }
```
Why does this only get called when the consent form is "submitted/changed" when I use a NavigableOrderedTask,  is this delegate is not available? or am I implementing the wrong delegate?

**Comment by kelseydedoshka-apple** [comment]
@dannyiss - what are you trying to accomplish with the delegate method? Access to the result before the consent is submitted?

**Comment by dannyiss** [comment]
I got that delegate working, trying to find if there is a method to grab the results in a survey as the user progresses. Not just the consent form.

**Comment by umerkhan-apple** [comment]
@dannyiss That delegate gets called anytime the result object for a step has been modified. If you would like to retrieve the result every time the step is done presenting, you can use the `stepViewControllerWillDisappear`.

**Comment by dannyiss** [comment]
I just found that method will scrolling through the resources! Thank you! Got it implemented as needed.
