### ISSUE TITLE
Cast ORKChoiceQuestionResult to string

### ISSUE THREAD

**Issue by ecstaticax** [ResearchKit/ResearchKit#946]
I have extracted results from survey from a ORKChoiceQuestionResult. When I print it on console I see the result is:

(
0
)

I would like to convert that value to a string (or a int if it is a number). Whatever I do I receive as error that:

Could not cast value of type '__NSSingleObjectArrayI' (0x108470d60) to 'NSString' (0x104bc9c40).

What can I do? Regards

**Comment by ninoguba** [comment]
Try this:

```
let stepResult = taskResult.firstResult as? ORKStepResult
let choiceResult = stepResult.firstResult as? ORKChoiceQuestionResult
let answer = choiceResult.choiceAnswers?.first as? String
print("Answer: \(answer)")
```

**Comment by ecstaticax** [comment]
I cannot make it work.

This is my code:

`extension ViewController : ORKTaskViewControllerDelegate {
    
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason:
    
    
        ORKTaskViewControllerFinishReason, error: Error?){
        
        
        
        switch (reason) {
        case .completed:
            let taskResult = taskViewController.result.results
            
            for stepResults in taskResult! as! [ORKStepResult]
            {
                print("---------------------------------------------------------")
                for result in stepResults.results!
                {
                    if result.identifier == "CHIEDO_NOME"
                    {
                      
                        let nameAnswerResult = result as! ORKTextQuestionResult
                        let name = nameAnswerResult.answer!
                        print(name)
                        
                    }
                    if result.identifier == "CHIEDO_OBIETTIVO"
                    {
                        let nameAnswerResult2 = result as! ORKChoiceQuestionResult
                        let name2 = nameAnswerResult2.answer!
                        print("il risultato è pari a: ", name2)
                        
                    }
                    if result.identifier == "CHIEDO_COLORE"
                    {
                        let nameAnswerResult3 = result as! ORKChoiceQuestionResult
                        let name3 = nameAnswerResult3.answer!
                        print(name3)
                        
                    }

                    
                }
            }
        default:break
            
        }
        
        taskViewController.dismiss(animated: true, completion: nil)
        
    }
`

I would like to get a string or a int from name2 variable.

**Comment by ninoguba** [comment]
You need to do this instead:

```
if result.identifier == "CHIEDO_OBIETTIVO"
                    {
                        let nameAnswerResult2 = result as! ORKChoiceQuestionResult
                        let name2 = nameAnswerResult2.choiceAnswers?.first 
                        print("il risultato è pari a: ", name2)
                        
                    }
```

**Comment by ninoguba** [comment]
Basically ORKChoiceQuestionResult produces an array.  You simply just get the elements of the array and cast to String or Int depending on the value you expect.   If your choice questions allows multiple selection then your array will contain the selected element values, otherwise it will just be one element in the choiceAnswers array.

**Comment by ecstaticax** [comment]
Thanks a lot. It did the trick (even if I had to change a line code)

`print("il risultato è pari a: ", name2!)`

**Comment by kelseydedoshka-apple** [comment]
@ecstaticax - Looks like @ninoguba's response did the trick for you. Ok to close or is this still being worked through?

**Comment by ecstaticax** [comment]
It can be closed. Thanks again to Nino.
