### ISSUE TITLE
Update Bundle Version/Build

### ISSUE THREAD

**Issue by craylward** [ResearchKit/ResearchKit#949]
Cloned the ResearchKit project and opened in Xcode. Noticed that the Bundle version and build numbers are still listed as 1.3 when release notes indicate 1.4.

**Comment by umerkhan-apple** [comment]
@craylward Would you be able to provide a PR with the change?

**Comment by kelseydedoshka-apple** [comment]
@craylward - thanks for the update. A fix for this has been merged, therefore closing this issue.
