### ISSUE TITLE
ORKCompletionStep checkMark animation stretched.

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#955]
After updating the ResearchKit framework, the ORKCompletionStep screen does not work as expected.
The check mark animation is stretched. 

Any comments or solutions for this?

<img width="376" alt="screen shot 2017-03-21 at 12 08 16 am" src="https://cloud.githubusercontent.com/assets/6026875/24166282/5e5855ce-0e38-11e7-9df9-52f7b7f5c365.png">

**Comment by MacroYau** [comment]
Use the `master` branch instead of the `stable` branch.

**Comment by kelseydedoshka-apple** [comment]
@JorgeAGomez - Are you still seeing this issue when using master?

**Comment by JorgeAGomez** [comment]
@kelseydedoshka-apple  Yeah. I am still getting the same stretched image for the checkmark.

**Comment by JorgeAGomez** [comment]
@MacroYau what do you by stable branch? 

I am using cocoapods to install this framework and I ran pod update and pod install. Is there an extra step I need to do to get the master branch?

**Comment by MacroYau** [comment]
@JorgeAGomez CocoaPods fetches only the latest `stable` release. You need to either use Carthage or manually get the `master` branch of this repo (as instructed in the "Getting Started" section of the README).

**Comment by umerkhan-apple** [comment]
@JorgeAGomez Agree with @MacroYau, the latest `master` branch fixes a lot of UI issues introduced with iOS 10. We will have a `stable` release available in the near future with these fixes.

**Comment by JorgeAGomez** [comment]
Thanks @MacroYau you are the man!
