### ISSUE TITLE
The Create Passcode View Controller is not fully laid out when presented

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#960]
The Create Passcode View Controller is not fully laid out when presented. Run the `Create Passcode` item in `ORKTest` and observe how the view controller is being laid out at the same time as it presents.

**Comment by kelseydedoshka-apple** [comment]
@rsanchezsaez - thanks for bringing this up. Closing this as I have merged @benjamin-42 's PR to resolve this.
