### ISSUE TITLE
Value picker is presented off-center on iPhone 6/7 in standard zoom mode.

### ISSUE THREAD

**Issue by SusanKern** [ResearchKit/ResearchKit#962]
Value pickers appear to be presented as left-justified instead of centered.  This is not noticeable when presented on iPhone 5 or iPhone 6/7 in zoomed mode.

This is running ResearchKit 1.4.1.

![screen shot 2017-03-23 at 9 29 53 am](https://cloud.githubusercontent.com/assets/4137984/24250031/d6d12d18-0fab-11e7-95d2-f2f73aaa32f5.png)

**Comment by jefferythewind** [comment]
I'm not an expert but did you try pulling the latest from the `master` branch.  Apparently there were some UI issues introduced in the `stable` branch that have been fixed in the `master`.

**Comment by umerkhan-apple** [comment]
@SusanKern As @jefferythewind suggested, try to use the `master` branch. It includes a lot of UI fixes introduced with iOS 10. We will have a `stable` release with those changes in the near future.

**Comment by kelseydedoshka-apple** [comment]
@SusanKern - were you able to see the issue resolved when using the master branch?

**Comment by SusanKern** [comment]
Yes, I apologize for not updating the thread.  The issue and a few other small UI problems were resolved when using the master branch.  My only suggestion would be to make sure to include some relevant, searchable text when pushing changes to the repo.  If I had been able to search on "picker" in the repo changes, it would have saved me several hours of work.
