### ISSUE TITLE
Presenting a custom UIAlertController during survey

### ISSUE THREAD

**Issue by dannyiss** [ResearchKit/ResearchKit#967]
I am currently trying to implement a way to grab which selections the user is making and then alert them when it is not correct

```
if let getResult = result.stepResult(forStepIdentifier: "xxxx"){
            let result = getResult.results?.first as? ORKChoiceQuestionResult
            let answers = result?.choiceAnswers?.count
            if(answers! > 1 )
            {
                if let temp = getResult.results?.first as? ORKChoiceQuestionResult{
                    if temp.choiceAnswers?.first as! String == "1"
                    {
                        let alertController = UIAlertController(title: "Error", message: "Cannot select Not being treated & others", preferredStyle: .alert)
                        
                        let OKAction = UIAlertAction(title: "OK", style: .default) { (action:UIAlertAction) in
                            print("You've pressed OK button");
                        }
                        
                        alertController.addAction(OKAction)
                        self.present(alertController, animated: true, completion:nil)
                    }
                }
            }
        }
```
Adding that UIAlertController throws a `Warning: Attempt to present UIAlertController: XXXX on XXXX: XXXX whose view is not in the window hierarchy! ` Does anyone know how to present it properly over the survey? Bonus question, how do I then modify what is selected? i.e just reset the question as if no selections were made.

**Comment by ninoguba** [comment]
Keep an instance of your task's view controller before you present the task then present the alert controller via this instance of the task view controller.  See sample code below:

Class Declaration:

`fileprivate var taskViewController : ORKTaskViewController!`

On your delegate:

```
    func symptomTrackerViewController(_ viewController: OCKSymptomTrackerViewController, didSelectRowWithAssessmentEvent assessmentEvent: OCKCarePlanEvent) {

        guard let activityType = ActivityType(rawValue: assessmentEvent.activity.groupIdentifier!),
            let assessmentActivity = storeManager.activityWithType(type: activityType) as Activity? else { return }
        
        // Show an `ORKTaskViewController` for the assessment's task.
        taskViewController = ORKTaskViewController(task: assessmentActivity.task(activity: assessmentEvent.activity), taskRun: nil)
        taskViewController.delegate = self
        present(taskViewController, animated: true, completion: nil)
    }
```

To present your alert:

`taskViewController.present(alertController, animated: true, completion:nil)`

**Comment by dannyiss** [comment]
Fixed it! Thank you! 👍 Now how do I change the currently selected ORKMultipleChoice answers? Hmmmm.....

**Comment by ninoguba** [comment]
You can provide default values to your question before it gets presented.  Once user makes their selections, you can do your validation and add logic to show them an alert or let them go through the next step.

**Comment by dannyiss** [comment]
Ended up using a combination between `func taskViewController(_ taskViewController: ORKTaskViewController, shouldPresent step: ORKStep) -> Bool {` and `func taskViewController(_ taskViewController: ORKTaskViewController, didChange result: ORKTaskResult) {` to achieve exactly that! Thank you! I will close the issue now.
