### ISSUE TITLE
Removing methods without deprecation breaks things

### ISSUE THREAD

**Issue by syoung-smallwisdom** [ResearchKit/ResearchKit#968]
I cannot pin to master and pull in the work-around for Xcode 8.3 (https://github.com/ResearchKit/ResearchKit/pull/963) into our fork b/c https://github.com/ResearchKit/ResearchKit/pull/952 will break everything.

For the future, please consider a change of policy to use deprecation to warn people that a method signature is changing. It really hurts our efforts to create an open source community of researchers who are all able to contribute to a common code base. Additionally, deprecation is standard practice for evolving an SDK.

**Comment by rsanchezsaez** [comment]
I didn't want to cause that much hassle. I'll soon submit a PR re-adding the removed methods and marking them as deprecated. :)

**Comment by syoung-smallwisdom** [comment]
Thank you! 

I was going to create a category to add the method (until I had time to go through and find/fix it) but felt it warranted opening an issue. We are finding that often the researchers that we partner with who are using ResearchKit aren't experienced developers; instead they are MD/phD folks who "code a bit". While we have a framework to help insulate our partners from having to use ResearchKit directly, I worry that anyone coming directly to the source would find these kinds of breaking changes really frustrating.

**Comment by umerkhan-apple** [comment]
Thanks @rsanchezsaez ! Really appreciate your continued feedback @syoung-smallwisdom !
