### ISSUE TITLE
Issue in presenting Passcode view from a landscape app

### ISSUE THREAD

**Issue by hasiniran** [ResearchKit/ResearchKit#973]
When a ORKTaskViewController with a ORKOrderedTask of ORKPasscodeStep is presented from a landscape app, following runtime error is resulted. 

'Supported orientations has no common orientation with the application, and [ORKTaskViewController shouldAutorotate] is returning YES'

**Comment by kelseydedoshka-apple** [comment]
@hasiniran - Thanks for bringing this up! Generally we like to limit passcode implementations to portrait mode as that provides the best screen real estate and dimensions for this kind of UI. I am curios about the specifics of your use case where you want to be using the passcode step in landscape?

**Comment by hasiniran** [comment]
@kelseydedoshka-apple Thanks for the reply. I'm using the ResearchKit modules in a data collection app running on an iPad. The app is constrained to be run in the landscape mode due to the nature of functions specific for the app. Passcode step is used when the user consent and register for the app. To maintain consistency across the app I would like to have all the views of the app in the landscape mode, hence the issue.

**Comment by kelseydedoshka-apple** [comment]
@hasiniran - Thanks for the explanation on this. We think this is valuable to support but since the currently limitation only supports portrait I would like to do some extensive testing on the feature before including it the framework. Has there been any testing on your side for enabling this mode?

**Comment by hasiniran** [comment]
@kelseydedoshka-apple I did test the passcode view after the fix, particularly within the scope of my app and things work fine for me. However, I agree that some more testing is required to check the feature before adding it to the framework.

**Comment by kelseydedoshka-apple** [comment]
@hasiniran great thanks for the additional information. Let's work on the additional testing in parallel.

**Comment by Pariecemckinney-apple** [comment]
@hasiniran, PR for this issue has been merged. Closing issue
