### ISSUE TITLE
ORKESerialization + Swift 3?

### ISSUE THREAD

**Issue by dasoga** [ResearchKit/ResearchKit#977]
Hi everyone, is **ORKESerialization** working with Swift 3?
I want to have my results task in a JSON file to send it to a server.
I attached 2 images with the errors that I have.

Anyone knows how can I solve them? Thank you!

![screen shot 2017-05-06 at 8 52 04 am](https://cloud.githubusercontent.com/assets/11412369/25772869/71be91ee-3239-11e7-9fd7-c31ef308136e.png)
![screen shot 2017-05-06 at 8 52 09 am](https://cloud.githubusercontent.com/assets/11412369/25772871/71d9b55a-3239-11e7-899d-bc48615baec4.png)

**Comment by kelseydedoshka-apple** [comment]
@dasoga - updates to this were made in the latest release to master. Can you confirm that has been resolved on your end with the latest or are you still seeing this issue?

**Comment by dasoga** [comment]
Hi @kelseydedoshka-apple I'm using ResearchKit with CocoaPods...(version 1.4.0)
I'll clone the repo and add it to my project to use this feature, I'll let you know ASAP.

Thanks for your response!

**Comment by kelseydedoshka-apple** [comment]
@dasoga - understood, thanks for keeping me updated on this. Stayed tuned for the updated CocoaPod soon!

**Comment by dasoga** [comment]
Hi @kelseydedoshka-apple I just tested it and is working now, I appreciate your time! Thank you so much.

I just want to say what I did, maybe this can be helpful for someone else.

I dragged and drop ORKESerialization.h and .m files into my proyecto, create a bridge header and import:

#import "ORKESerialization.h"

Then I can call the functions:

```
extension ViewController: ORKTaskViewControllerDelegate{
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        
        let taskResult = taskViewController.result
        
        let jsonData = try! ORKESerializer.jsonData(for: taskResult)
        if let jsonString = NSString(data: jsonData, encoding: String.Encoding.utf8.rawValue) {
            print(jsonString)
        }
        
        taskViewController.dismiss(animated: true, completion: nil)
    }
}
```

**Comment by kelseydedoshka-apple** [comment]
@dasoga - great thanks for keeping us updated on this, and thanks for sharing your solution as well!
