### ISSUE TITLE
Deselect choices when another choice is selected

### ISSUE THREAD

**Issue by RimasRekasius** [ResearchKit/ResearchKit#978]
In a text choice question where multiple choices are allowed, is it possible to deselect choices when another choice is selected?  If so, how would this be done?  Here is the scenario... the question is something like "How was your breathing during the night? Check all that apply" and the choices are as follows: "Regular", "Heavy", "Snoring", "Snorts or gasps", "I don't know".  Let's say that the user selects "Heavy" and "Snoring", but then upon further thought changes his/her mind and selects "I don't know".  It would be nice to have the other choices automatically deselected for the user.

**Comment by ninoguba** [comment]
This one is easy, all you have to do is set the "exclusive" property of the ORKTextChoice that correspond to "I don't know" to true and it take care of what you need for you.

**Comment by ninoguba** [comment]
http://researchkit.org/docs/Classes/ORKTextChoice.html#//api/name/exclusive

**Comment by RimasRekasius** [comment]
Awesome...!!!  Thanks for the hint... works great...!!!

**Comment by jlandyr** [comment]
Hi, is this feature available in Swift in the new Researchkit 1.4?
I can't find that property using ORKTextChoice(text: ", value:)

<img width="754" alt="captura de pantalla 2017-08-08 a la s 17 57 35" src="https://user-images.githubusercontent.com/10555951/29081524-160fa2ec-7c63-11e7-93a5-652892a6aae4.png">
