### ISSUE TITLE
Adding extra questions or skipping questions while survey is running.

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#979]
I have three questions that should be asked if the user answered 2 or more "Yes". The survey currently have 12 questions, if the user answer yes to two or more questions, then I want to add 3 extra questions. (OR I will always add the 3 extra questions to my ORKOrderedTask, and then I would skip the last 3 questions is the user did not answer "Yes" to 2 or more questions).

I have been playing around with "taskViewController didChange" that lets me check if the current answer for the current question is "yes" or "no". I have a counter that keeps incrementing if the answer is "yes". 

Now, I just need to either add 3 new questions if the counter reaches to 2. (OR skip the last 3 questions if counter never reaches to 2.)

Any comments or suggestions to implement this?

Thanks!!!

**Comment by ninoguba** [comment]
You need to add all your step questions to the task and since you want branching logic, you'll need to use ORKNavigableOrderedTask.  Refer to the following guide (at the end) to see how you can implement what you need.

http://researchkit.org/docs/docs/Survey/CreatingSurveys.html

**Comment by JorgeAGomez** [comment]
Thanks for the response @ninoguba . I read the example. However, when I set the rules using ORKResultSelector, this will only work if I am expecting an specific answer for a question.

For example: 
        // Ineligible step
        let ineligibleStep = ORKInstructionStep(identifier: String(describing:Identifier.eligibilityIneligibleStep))
        ineligibleStep.title = NSLocalizedString("You are ineligible to join the study", comment: "")
        
        // Eligible step
        let eligibleStep = ORKCompletionStep(identifier: String(describing:Identifier.eligibilityEligibleStep))
        eligibleStep.title = NSLocalizedString("You are eligible to join the study", comment: "")
        
        // Create the task
        let eligibilityTask = ORKNavigableOrderedTask(identifier: String(describing:Identifier.eligibilityTask), steps: [
            introStep,
            formStep,
            ineligibleStep,
            eligibleStep
            ])

        // Build navigation rules.
        var resultSelector = ORKResultSelector(stepIdentifier: String(describing:Identifier.eligibilityFormStep), resultIdentifier: String(describing:Identifier.eligibilityFormItem01))
        let predicateFormItem01 = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "Yes" as NSCoding & NSCopying & NSObjectProtocol)
        
        resultSelector = ORKResultSelector(stepIdentifier: String(describing:Identifier.eligibilityFormStep), resultIdentifier: String(describing:Identifier.eligibilityFormItem02))
        let predicateFormItem02 = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "Yes" as NSCoding & NSCopying & NSObjectProtocol)
        
        resultSelector = ORKResultSelector(stepIdentifier: String(describing:Identifier.eligibilityFormStep), resultIdentifier: String(describing:Identifier.eligibilityFormItem03))
        let predicateFormItem03 = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelector, expectedAnswerValue: "No" as NSCoding & NSCopying & NSObjectProtocol)

        let predicateEligible = NSCompoundPredicate(andPredicateWithSubpredicates: [predicateFormItem01, predicateFormItem02, predicateFormItem03])
        let predicateRule = ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [ (predicateEligible, String(describing:Identifier.eligibilityEligibleStep)) ])



This will only match if the first two answers are "Yes" and the last one is "No". In my case, the order of the answers does not matter, as long as 2 of the answers are "Yes". 

My rule only needs to check if 2 answers are "Yes" without caring what question was answered "Yes". 

How can I check if 2 of the answers are "Yes" using these rules?

**Comment by ninoguba** [comment]
You may want to look into the EligibilityTask example included in the ORKCatalog app.

**Comment by ninoguba** [comment]
I think you will need to create one NSCompoundPredicate for each permutation of YES/NO combinations to your set of questions.

**Comment by kelseydedoshka-apple** [comment]
@ninoguba thanks for the solutions here - @JorgeAGomez - were you able to resolve this with the above suggestions?

**Comment by JorgeAGomez** [comment]
@kelseydedoshka-apple Yes. You can close this issue. Thanks!
