### ISSUE TITLE
Print the current answer for current question

### ISSUE THREAD

**Issue by JorgeAGomez** [ResearchKit/ResearchKit#980]
I am trying to use didChange function to check the answer selected by the user. Every question is set with Boolean Answers (Yes or No). Right now I have this code, which prints EVERY answer, every time the user answer one question. The first question, prints answer1. Then in the second question, prints answer1 and answer2. 

I want to be able to print just the current answer, for the current question. Since didChange is called when user answer the question, I was trying to do it inside this function. 

Any ideas or suggestions to print JUST the current answer?

Here is what I have right now: 

         public func taskViewController(_ taskViewController: ORKTaskViewController, didChange result: ORKTaskResult) {
    
          if let results = taskViewController.result.results as? [ORKStepResult] {
              for stepResult: ORKStepResult in results {
                  for result in ([ORKResult]?(stepResult.results!))!{
                      if let questionResult = result as? ORKQuestionResult {
                          print("\(questionResult.identifier), \(questionResult.answer!)")
                      }
                  }
              }
          }
  }

**Comment by ninoguba** [comment]
Assuming the "current" answer is always the last, then you can just print the value of the last element of the results array.

If this assumption can't be true then I would do some logic on the taskViewController:stepViewControllerWillAppear delegate instead.

**Comment by JorgeAGomez** [comment]
You can close this issue. I figured it out. Thanks for your help @ninoguba
