### ISSUE TITLE
ReseachKit tint color

### ISSUE THREAD

**Issue by HEIDEMAN** [ResearchKit/ResearchKit#982]
Is there somewhere globally where I can set the tint color from the default blue to a custom color?

**Comment by ninoguba** [comment]
Yes you can do that in your AppDelegate's didFinishLaunchingWithOptions function and set window.tintColor to your liking.

**Comment by kelseydedoshka-apple** [comment]
@ninoguba thanks for solution here. @HEIDEMAN - did this help resolve your issue?

**Comment by kelseydedoshka-apple** [comment]
@HEIDEMAN - friendly ping here to see if you were able to resolve this?

**Comment by kelseydedoshka-apple** [comment]
@HEIDEMAN - closing this as @ninoguba has a great suggestion. Feel free to reopen if you are still having issues with this.
