### ISSUE TITLE
Update pod spec to v1.5

### ISSUE THREAD

**Issue by stevemoser** [ResearchKit/ResearchKit#983]

**Comment by kelseydedoshka-apple** [comment]
@stevemoser - we are working to get the pod spec updated. Stay tuned!

**Comment by EliaCereda** [comment]
I second this request. I am in need of a few fixes that have been merged in master long ago, but are not yet available in the released versions.

**Comment by akshay-yadav-apple** [comment]
@stevemoser @EliaCereda 
We have updated the pods for Researchkit. 
Please let us know if you run into any issue while updating your project.
pod 'ResearchKit', '~> 1.5'

**Comment by SNagra** [comment]
I was able to update without any issues in one of my projects. Actually fixed some UI issues too!

**Comment by akshay-yadav-apple** [comment]
@SNagra,
Great to hear!
