### ISSUE TITLE
How to auto populate local db parameters(either text or number) into Researchkit CRF text or number field Questions?

### ISSUE THREAD

**Issue by savanil** [ResearchKit/ResearchKit#984]
As per my requirement I need to get user health parameter from physical health devices such as apple watch or Fitbit devices and need to populate in crf in my app.

Could you please suggest how could we achieve(values auto selection) in Research kit CRFs.

Thanks in advance

**Comment by kelseydedoshka-apple** [comment]
@savanil - can you provide a little more context as to where you are at with this? Are you able to read values from HealthKit from the apple watch? Is there some place you are stuck getting those values populated in? Any sample code pertaining to your issue would be helpful as well.

**Comment by savanil** [comment]
First of all I would like to thank "kelseydedoshka" for responding my query.

Currently we are working on Research & Analysis based iPhone app, in that we used research kit for surveys implementation.

As per my requirement, user will assign surveys day wise and each survey will have dynamic questions on each day, recently we integrated fit bit device with our app. Using fit bit device we are able to receive users activities information into our app.

Here are my question -

1. If survey will have question related to fit bit - let us assume there is one question - 
“How many steps have you climbed yesterday ..?” - 
how could I auto populate(instead of user entry) fit bit device information which is saved on our local db to surveys answer field of Text/Number kind of  research kit question?

2. Is there any way to add one button(to fetch and show value on answer field instead of user entry) in those kind of questions, if user taps on that button we will pass information and that will populated in answer field. (Since we have dynamic type of questions.)

Could you please confirm on this.

Thank you,

**Comment by kelseydedoshka-apple** [comment]
@savanil - a few follow up questions to yours and some answers.

1. If you are grabbing data from the fitbit, can you just collect that data behind the scenes and store it as necessary? Is there even a need to present a researchKit step here? If it is, consider the 
answer below regarding the delegate  methods.

2. All of the researchKit steps are extendable via the framework and therefore you could add functionality into the steps to accomplish this if you need to. I would also look into the idea or ORKNavigableOrdered tasks to determine steps based on previous answers if that is necessary. You can also look at the taskViewController delegate methods and intercept the view controller before it is displayed to add custom functionality to it.

**Comment by savanil** [comment]
yes, here we are maintaining all fit bit information in local db as day wise(which we already collected and saved in to local db, its not collecting while user accessing survey).

And could you please suggest text or number text field reference in survey, so when we are creating  survey form generation we will pass value to the answer field of that particular Fit bit question.

Can we handle like this.. Could you please confirm if I am in wrong path

Thank you

**Comment by kelseydedoshka-apple** [comment]
@savanil - if you will be displaying numbers I would recommend the number text field option, otherwise it is best to use the generic text field.

I believe you are on the right track with this. Please reference my earlier comment regarding the taskViewControllerDelegate for performing your customizations.

**Comment by savanil** [comment]
I will follow and consider your suggestion to customise our UI(currently busy with other priorities) and will update soon.

Thanks kelseydedoshka

**Comment by kelseydedoshka-apple** [comment]
@savanil - great, please don't hesitate to reach back out with questions as you continue to work on this.

**Comment by Pariecemckinney-apple** [comment]
@savanil - Just wanted to check in to see if there has been any progress with your issue?

**Comment by savanil** [comment]
Hi Pariecemckinney-apple,

As per the Client priorities, we postponed this requirement for time being...
Most probably we will move very soon, and I will update here my feedback and progress on issue.

thank you

**Comment by Pariecemckinney-apple** [comment]
@savanil, Sounds great. I will close the issue for now but please feel free to reopen when the discussion continues.
