### ISSUE TITLE
ORKVideoCaptureStep stops recording audio for videos > 10 seconds

### ISSUE THREAD

**Issue by unknownunknown** [ResearchKit/ResearchKit#989]
I'm having issues with audio not recording for videos over 10 seconds long. Shorter clips work just fine though. I tried different video capture durations, letting it default; tried setting isAudioMute to false -- but all of this made no difference.

I am using an iPad 12.9 pro, running ios 10.3.2.

Any advice? thanks so much!

**Comment by Pariecemckinney-apple** [comment]
Hello @unknownunknown,

We really appreciate you pointing out this issue. We will begin investigating, and get back to you soon. In the meantime, if you happen to find a solution please feel free to share it here or create a PR. 

Thanks again!

Pariece

**Comment by unknownunknown** [comment]
Thanks so much! Im using researchkit a bit unconventionally, for an art installation in the recently opened museum in oakland, to collect video interviews of people to build a public archive. It's open to public now and I guess I didn't thoroughly test it with longer videos, only discovering the problem when it opened! So for now the installation has an out for order sign :-( but Thanks so much, and appreciate any solutions or work around as soon as you can get round to it.

Cheers
Tara

**Comment by Pariecemckinney-apple** [comment]
@unknownunknown Sorry to hear about the road block the issue has caused. Fortunately, there is a quick work around to get the audio working.

 Navigate to and open the ORKVideoCaptureStepViewController.m file within the ResearchKit framework. Once there, around line 181 you will find a line of code reading "movieFileOutput.maxRecordedDuration = CMTimeMakeWithSeconds(_videoCaptureStep.duration.floatValue, 30.0);". Directly below this line add the following line of code "movieFileOutput.movieFragmentInterval = kCMTimeInvalid;". This should be all you need to fix your problem. If for some reason, this doesn't work please feel free to let me know. 

Hope this helps, and we're very excited that ResearchKit has been able to help you with your project. 

Best Regards
Pariece

**Comment by unknownunknown** [comment]
Amazing! thanks so much for getting back so quickly. ill try this and do some more thorough testing and get back to you! :-)

**Comment by unknownunknown** [comment]
with first couple of tests, it def works! thanks!! let you know if i run into anything else.
