### ISSUE TITLE
Revise all 'updateConstraints' implementations

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#99]
Some `updateConstraints` implementations may be accumulating duplicate constraints. They also need to call `[super updateConstraints]` last, but some of them call it early. Revise this.

See comments [here](https://github.com/ResearchKit/ResearchKit/pull/98) for more details.

**Comment by jwe-apple** [comment]
Yep.

**Comment by jwe-apple** [comment]
While revising some of these for other issues, I remembered why so many of them have been set up dynamic. We thought developers might want to present our view controllers in frames of their own devising, for instance on iPad. So in that case the margins should depend on the presenting frame, rather than the screen size.

**Comment by rsanchezsaez** [comment]
I think that presenting the view controllers on custom sized frames would continue to work with static constraints (as long as the containing frame doesn't change in the middle of a task). So I feel we can try to make the constraints static as much as we can (as long as the constraints correctly support a device orientation change).

The only thing is that all *ork metrics* are now generally gotten based on the *view's window*, which prevents it getting proper metrics for a custom frame. For metric extraction, we should be able to replace the *view's window* by the *task controller root view* without much trouble. Right?

**Comment by jwe-apple** [comment]
@rsanchezsaez That's the point. The size of the task controller's root view is not necessarily known at the time of view instantiation - as we won't be in the view hierarchy at that point. Consider for example instantiation during UI state restoration.

**Comment by rsanchezsaez** [comment]
Ah, I see.

**Comment by rsanchezsaez** [comment]
In progress: I'll homogenize all `updateConstraints` methods and make sure `super` is called last. I'll also try to move constraints to `init` when they don't need to dynamically recreated (as in `ORKActiveStepQuantityView`, [PR #125](https://github.com/ResearchKit/ResearchKit/pull/125)).

I think we can make this work properly when using RK view controllers in custom frames even if we have some static constraints. But let's cross that bridge when we come to it.

**Comment by jwe-apple** [comment]
Yep, go for it.

**Comment by jwe-apple** [comment]
Actually can you keep the `super` move separate from the ->`init` change, and do separate PRs?

**Comment by rsanchezsaez** [comment]
Will do.

Should I do the homogenization for truly dynamic constraints in a third PR? I plan to consistently use `activateConstraints:`/`deactivateConstraints:` instead of `addConstraints:`/`removeConstraints:`, as the former seems more automatic and less error prone.

**Comment by jwe-apple** [comment]
Definitely as a separate, third PR.

And *please* try to keep the whitespace changes to a minimum so this is easier to review.

**Comment by jwe-apple** [comment]
It's ok to do the first PR now, but TBH I'd rather we got the iPad bugs fixed and did some of this homogenization later. Autolayout is pretty sensitive and I'd rather do it after we branch for 1.1.

**Comment by rsanchezsaez** [comment]
Understood.

I'll look into the iPad bugs first.

**Comment by YuanZhu-apple** [comment]
@jwe-apple Can we close this issue?

**Comment by rsanchezsaez** [comment]
I believe this can be closed, all `[super updateConstraints]` calls are the last item now.

**Comment by rsanchezsaez** [comment]
Closing.
