### ISSUE TITLE
Question: how can I skip or hide a step in a survey?

### ISSUE THREAD

**Issue by dasoga** [ResearchKit/ResearchKit#990]
Hi,

I just have a question, how can I skip or hide a step?
Example:

Steps array:
[QuestionBool, QuestionOne, QuestionTwo , QuestionThree]

I have a rule for this:
_QuestionBool -> Yes - Question One -> Question Two -> Question Three_

But I want to hide the Step("Question one") if the user choose No
_QuestionBool -> No -> Question Two -> Question Three_

**Note**: I don't know the next step identifier ("Question two") because this comes from an API.
The API just return:
- Actual Step identifier
- Dependency: 
     - Step to jump identifier 
     - Expected Answer 

I hope be clear
Thank you!

**Comment by Pariecemckinney-apple** [comment]
Hello @dasoga, 

I would be happy to point you in the right direction. If I am understanding your issue correctly. You wish to set up conditions where certain steps in your survey can be skipped based the user's previous answers? If this is correct, I would recommend reading through our documentation on the ORKNavigableOrderedTask object. This object will give you the functionality that you seem to be seeking. Hope this helps.

**Comment by dasoga** [comment]
Hello @Pariecemckinney-apple, 

Thanks for your replay, I'm already using ORKNavigableOrderedTask...I'll try to explain my problem:

Example
I got this JSON from the API...
```
{
                        "uuid": "28554c7a-3403-4306-9977-71e0dfbe1b2e",
                        "text": "Are you taking medicine?",
                        "answers": [
                            {
                                "uuid": "54acf9df-b5dc-4f69-8b9f-9e8f9704e87a",
                                "text": "Yes"
                            },
                            {
                                "uuid": "a91a14b2-331a-489e-aa43-fdcb52eda43b",
                                "text": "No"
                            }
                        ],
                        },

                        {
                        "uuid": "7848935a-cf4b-4a71-ae58-3ec0cf2cbd04",
                        "answers": [
                            {
                                "uuid": "f8c19c6c-e179-414f-8e41-110da4f95114",
                                "text": "String",
                                "type": "string"
                            }
                        ],
                        "dependency": {
                            "rule": "A",
                            "conditions": [
                                {
                                    "rule_key": "A",
                                    "operator": "==",
                                    "question": "28554c7a-3403-4306-9977-71e0dfbe1b2e",
                                    "answer": "54acf9df-b5dc-4f69-8b9f-9e8f9704e87a",
                                    "condition_value": null
                                }
                            ]
                        },
                        "text": "Please describe when you get chest pain or discomfort.",
                        "answer_type": "string"
                    },

...
```

This is an array of questions with answers, the problem is I created an array of steps with this JSON, in this example, if the user press "Yes" the next step (**"uuid": "7848935a-cf4b-4a71-ae58-3ec0cf2cbd04"**) is going to show, that is correct, but if the user press "No" I need to skip that step (**"uuid": "7848935a-cf4b-4a71-ae58-3ec0cf2cbd04"**). Do you know how can I do that?.

Thanks!

**Comment by dasoga** [comment]
Hi again!...

I saw that the better way to get this custom task is create a subclass of ORKOrderedTask, I'll try with that. I'll let you know as soon as I finish.

**Comment by Pariecemckinney-apple** [comment]
@dasoga , Sounds great! Please keep me updated on your progress.

**Comment by swaffoja** [comment]
@dasoga Look at the `BranchingOrderedTask` class in the attached zip file. I subclassed `ORKOrderedTask` to show and hide questions based on the answer of a previous question. The TestTasks.swift file illustrates usage.

[Archive.zip](https://github.com/ResearchKit/ResearchKit/files/1126508/Archive.zip)

**Comment by dasoga** [comment]
@swaffoja awesome!
I replicated the implementation in my app and is working really good. I had to add some subclasses of ORKStep (like ORKInstructionsStep, ORKQuestionStep, ORKFormStep), I added my own properties for each and everything is going well.
I really apreciate your answers and time! 
Thanks so much!...I'll close this issue
