### ISSUE TITLE
Restoring task changes Continue button titles to default values "Next" or "Get Started"

### ISSUE THREAD

**Issue by iaarpit** [ResearchKit/ResearchKit#991]
Follow these steps to generate issue:
1. I set `continueButtonTitle` property of a stepVC as `"exit"`, suppose stepIdentifier is `"Final"`.
2. I start a task, after going through some steps I land at `Final` step. I save my task here.
3. I restore my saved task, `continueButtonTitle` property of a Final step is `"Next"` but actually it should be `"exit"`.

**Comment by Pariecemckinney-apple** [comment]
@iaarpit, Thank you for opening this issue. Would you be able to give a little more context on exactly whats happening?

**Comment by iaarpit** [comment]
@Pariecemckinney-apple I have edited my comment. Please review and let me know if you still don't understand what I am trying to convey.

**Comment by Pariecemckinney-apple** [comment]
@iaarpit, I really appreciate the edits. Makes complete sense now. We will begin investigating the issue and get back with you soon. Apologies for the confusion at the beginning.

**Comment by Pariecemckinney-apple** [comment]
@iaarpit, Where exactly are you modifying the `continueButtonTitle`? When you save a task the only data that is stored are the step results up until the current step that you are on. When you restore the task this data is used to navigate the user to the step where they left off.

However, attributes such as `continueButtonTitle` are not saved and should be handled using provided delegate methods such as `stepViewControllerWillAppear`. If you utilize these delegate methods to modify a stepViewController before it appears, your button should always remain the same even if the task was restored from a previous date or time.

Hope this helps and please feel free to reach back out if you are still having trouble.

**Comment by iaarpit** [comment]
@Pariecemckinney-apple,

Thanks for the response. I found the issue. So the `taskViewController(_ taskViewController: ORKTaskViewController, stepViewControllerWillAppear stepViewController: ORKStepViewController)` doesn't get called if the delegate is passed nil in `self.init(task: task, restorationData: restore, delegate: nil)` and then set the task.delegate = self.

**Comment by Pariecemckinney-apple** [comment]
Great! Glad to hear you were able to get the issue resolved. Closing now.
