### ISSUE TITLE
MVC implementation of surveytasks

### ISSUE THREAD

**Issue by nasim-ahmed** [ResearchKit/ResearchKit#993]
I want a model for the survey tasks of Researchkit  ORKOrderedTasks, to create an array of the questions which will be parsed from json. Currently it is displaying questions from static data like below
`static let balancedDiet:ORKOrderedTask = {
       var steps = [ORKStep]()
        
        // Instruction step
        let instructionStep = ORKInstructionStep(identifier: "IntroStep")
        instructionStep.title = "Balanced Diet"
        instructionStep.text = "Please answer these 4 questions to the best of your ability. It's okay to skip a question if you don't know the answer."
        
        steps += [instructionStep]
        //Breathing
        let breathingStepTitle1 = "What of the following apply to your child's current breathing condition? (check all that apply)"
        let breathingChoices = [
            ORKTextChoice(text: "Home oxygen use", value: "Home oxygen use" as NSString),
            ORKTextChoice(text: "Cystic fibrosis", value: "Cystic fibrosis" as NSString),
            ORKTextChoice(text: "Chronic lung disease", value: "Chronic lung disease" as NSString),
            ORKTextChoice(text: "Asthma", value: "Asthma" as NSString),
            ORKTextChoice(text: "Chronic cough", value: "Chronic cought" as NSString),
            ORKTextChoice(text: "Use of an inhaler", value: "Use of an inhaler" as NSString),
            ORKTextChoice(text: "Difficulty swallowing", value: "Difficulty swallowing" as NSString),
            ORKTextChoice(text: "None", value: "None" as NSString)
        ]
        let breathingAnswerFormat =  ORKAnswerFormat.choiceAnswerFormat(with: .multipleChoice, textChoices: breathingChoices)
        let breathingStep = ORKQuestionStep(identifier: "Breathing", title: breathingStepTitle1, answer: breathingAnswerFormat)
        breathingStep.isOptional = false
        steps += [breathingStep]}()`

I want my model to include any type of question, so that when the json is parsed for different questions it can map to the appropriate question in the model and can create an array of questions. I am doing this in swift 3. Please help.

**Comment by ninoguba** [comment]
What you're looking to implement is very easy actually.  Your model will simply have an array of JSON objects with properties that correspond to ORKQuestionStep and ORKAnswerFormat properties.  Then you will implement some DynamicTaskBuilder class that will take in your model JSON, iterate on the array question objects, depending on the question type you instantiate the corresponding ORKQuestionStep/ORKAnswerFormat combination, add them to your ORKStep step array and present your dynamically built ORKTask. Hope this helps. :)

**Comment by nasim-ahmed** [comment]
Thanks, Mr.Ninoguba. I tried implementing your solution.This is my model 
`public class Question: NSObject {
    public let identifier:String
    public let questionStepTitle:String
    public let questionStep:ORKQuestionStep
    public let answerFormat:ORKAnswerFormat
    
    init(identifier:String,questionStepTitle:String, answerFormat:ORKAnswerFormat){
        self.identifier = identifier
        self.questionStepTitle = questionStepTitle
        self.answerFormat = answerFormat
        
        self.questionStep = ORKQuestionStep(identifier: self.identifier, title: self.questionStepTitle, answer: self.answerFormat)
    }
}`

And I am parsing using the following code `if let questionsDictionaries = data["questions"] as? [[String: Any]] {
            for questionsDictionary in questionsDictionaries {
                if let identifier = questionsDictionary["identifier"] as? String {
                    if let questionStepTitle = questionsDictionary["questionStepTitle"] as? String{
                        if let answerFormat = questionsDictionary["answerFormat"] as? String{

                            let questionStp = HDQuestion(identifier: identifier, questionStepTitle: questionStepTitle, answerFormat: (answerFormat as? ORKAnswerFormat)!)
                        
                               surveyQuestions.append(questionStp)
                            
                        }
                    }
                }
            }
        }`

The problem is with the answer format. For the sake of simplicityI am trying to show just one Boolean type question. So, answerFormat  would be ORKBooleanAnswerFormat(). But JSON returns  it as a string  rather than a class. How to solve this ?

**Comment by ninoguba** [comment]
You will need to do some mapping of course.  In your JSON model your type can be "boolean" and in your builder, preferably using a switch, if type = "boolean" then you instantiate ORKBooleanAnswerFormat().   You will need a mapping for each ORKQuestionStep/ORKAnswerFormat.
