### ISSUE TITLE
Possible Bug: ORKPasscodeViewController.isPasscodeStoredInKeychain() is unexpectedly returning NO

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#995]
I recently noticed this strangely happening in my app.  I'm pretty certain I've stored the passcode already before but somehow on subsequent launches of the app, this unexpectedly returns NO and thus directs my app users back to the onboarding flow.

My app has exactly ORKSample's lock/onboarding flow.  There must be some bug that is clearing the passcode in the keychain for some reason.  Still investigating...

Anybody else experience this?

**Comment by Pariecemckinney-apple** [comment]
@ninoguba, Thanks for posting this issue. Is this happening randomly or is the password no being saved at all? Also, what version are you using?

**Comment by ninoguba** [comment]
The passcode is saved in the keychain by ORKPasscodeViewController but strangely at random subsequent launches of the app the passcode disappears in the keychain.  I'm using the latest version of RK and iOS.  Happens in the Simulator and I think in the actual device as well.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba, I've tried recreating the problem but it hasn't popped up yet. I will keep opening the app randomly over the next couple of days on both the simulator and iPhone. Will keep you posted.

**Comment by ninoguba** [comment]
I find it mostly happening when building and running the app from Xcode to launch in the Simulator.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba - Still haven't been able to reproduce the bug. Will leave this issue open with the hopes that someone else has run into the issue.

**Comment by dukemike** [comment]
I get this all the time in the simulator and believe it's caused by killing the app. For what it's worth, I've seen it happen outside of CareKit apps as well. To prevent it, put the app in the background before stopping the app in Xcode.

**Comment by ninoguba** [comment]
Thanks @dukemike and you're right I only see this happening when launching the app through xcode onto the simulator or my connected device.

@Pariecemckinney-apple thanks for looking into this.  I think we can close this now as it is only happening during development.
